export default defineEventHandler(() => {
  return [
    {
      day: 'Freitag, 21. Juni 2024',
      inPast: false,
      entries: [
        {
          date: '2024-06-21',
          timeFrom: '17.30 Uhr',
          timeTo: null,
          description: 'Öffnung Festzelt, Festwirtschaft und Food Meile',
          location: 'Festgelände und Festzelt Urdorf',
          important: false,
        },
        {
          date: '2024-06-21',
          timeFrom: '17.45 Uhr',
          timeTo: null,
          description: 'Warm-up mit Rosalia Golden Hits',
          location: 'Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-21',
          timeFrom: '19.00 Uhr',
          timeTo: null,
          description: 'Festeröffnung ZKMF 2024',
          location: 'Festzelt Urdorf',
          important: false,
        },
        {
          date: '2024-06-21',
          timeFrom: '19.30 Uhr',
          timeTo: null,
          description: 'Galakonzert mit der SWISS Band',
          location: 'Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-21',
          timeFrom: '21.00 Uhr',
          timeTo: null,
          description: 'Feiern mit der Stubete Gäng',
          location: 'Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-21',
          timeFrom: '22.40 Uhr',
          timeTo: null,
          description: 'Ausklang  mit DJ Outside',
          location: 'Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-21',
          timeFrom: 'bis 02.00 Uhr',
          timeTo: null,
          description: 'Barbetrieb',
          location: 'Festzelt Urdorf',
          important: false,
        },
      ],
    },
    {
      day: 'Samstag, 22. Juni 2024',
      inPast: false,
      entries: [
        {
          date: '2024-06-22',
          timeFrom: '08.00 Uhr',
          timeTo: null,
          description: 'Öffnung Festgelände',
          location: 'Urdorf und Schlieren',
          important: false,
        },
        {
          date: '2024-06-22',
          timeFrom: '09.00 Uhr',
          timeTo: null,
          description: 'Start Wettspiele ZKMF 2024',
          location: 'Urdorf und Schlieren',
          important: true,
        },
        {
          date: '2024-06-22',
          timeFrom: '09.00 Uhr',
          timeTo: null,
          description: 'Jugend und Blasmusik\nVorstellung Bläserklasse',
          location: 'Singsaal Moosmatt Urdorf',
          important: true,
        },
        {
          date: '2024-06-22',
          timeFrom: '10.50 - ',
          timeTo: '16.00 Uhr',
          description: 'Unterhaltungskonzerte\nmit Holz, Blech und Schwyzerörgeli',
          location: 'Festzelt Schlieren',
          important: true,
        },
        {
          date: '2024-06-22',
          timeFrom: '12.00 Uhr',
          timeTo: null,
          description: 'Zmittag und Musig mit Brässkalation',
          location: 'Festzelt Urdorf',
          important: false,
        },
        {
          date: '2024-06-22',
          timeFrom: '13.30 Uhr',
          timeTo: null,
          description: 'Start Parademusik',
          location: 'Im Moos Urdorf',
          important: true,
        },
        {
          date: '2024-06-22',
          timeFrom: '17.30 Uhr',
          timeTo: null,
          description: 'Rangverkündigung',
          location: 'Zentrumshalle Urdorf',
          important: false,
        },
        {
          date: '2024-06-22',
          timeFrom: '19.15 Uhr',
          timeTo: null,
          description: 'Wettspiel Höchstklasse',
          location: 'Zentrumshalle Urdorf',
          important: true,
        },
        {
          date: '2024-06-22',
          timeFrom: '20.30 Uhr',
          timeTo: null,
          description: 'Rocken mit dem Saint City Orchestra',
          location: 'Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-22',
          timeFrom: '22.30 Uhr',
          timeTo: null,
          description: 'Feiern mit der Compass Party Band',
          location: 'Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-22',
          timeFrom: '01.00 Uhr',
          timeTo: null,
          description: 'Ausklang  mit DJ Outside',
          location: 'Festzelt Urdorf',
          important: false,
        },
        {
          date: '2024-06-22',
          timeFrom: 'bis 04.00 Uhr',
          timeTo: null,
          description: 'Barbetrieb',
          location: 'Festzelt Urdorf',
          important: false,
        },
      ],
    },
    {
      day: 'Sonntag, 23. Juni 2024',
      inPast: false,
      entries: [
        {
          date: '2024-06-23',
          timeFrom: '08.00 Uhr',
          timeTo: null,
          description: 'Öffnung Festgelände',
          location: 'Urdorf und Schlieren',
          important: false,
        },
        {
          date: '2024-06-23',
          timeFrom: '09.00 Uhr',
          timeTo: null,
          description: 'Start Wettspiele ZKMF 2024',
          location: 'Urdorf und Schlieren',
          important: true,
        },
        {
          date: '2024-06-23',
          timeFrom: '09.00 - ',
          timeTo: '16.00 Uhr',
          description: 'Unterhaltungskonzerte',
          location: 'Festzelt Schlieren',
          important: true,
        },
        {
          date: '2024-06-23',
          timeFrom: '10.00 Uhr',
          timeTo: null,
          description: 'Ökumenischer Gottesdienst',
          location: 'Festzelt Schlieren',
          important: true,
        },
        {
          date: '2024-06-23',
          timeFrom: '12.00 Uhr',
          timeTo: null,
          description: 'Zmittag und Musig mit Schäbyschigg\nIm Anschluss Blaskapelle aus Altheim und Sigmaringendorf',
          location: 'Festzelt Urdorf',
          important: false,
        },
        {
          date: '2024-06-23',
          timeFrom: '13.30 Uhr',
          timeTo: null,
          description: 'Start Parademusik',
          location: 'Im Moos Urdorf',
          important: true,
        },
        {
          date: '2024-06-23',
          timeFrom: '17.00 Uhr',
          timeTo: null,
          description: 'Gesamtchor ZKMF 2024',
          location: 'Kiesplatz beim Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-23',
          timeFrom: '18.00 Uhr',
          timeTo: null,
          description: 'Rangverkündigung, Fahnenübergabe',
          location: 'Festzelt Urdorf',
          important: true,
        },
        {
          date: '2024-06-23',
          timeFrom: 'bis 20.00 Uhr',
          timeTo: null,
          description: 'Ausklang Zürcher Kantonalmusikfest 2024',
          location: 'Festzelt Urdorf',
          important: false,
        },
      ],
    },
  ]
})
