export default defineEventHandler(() => {
  return [
    {
      id: 19,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'HOECHSTKLASSE',
      klasseDescription: 'Höchstklasse',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 15,
        identifier: 'zentrumshalle-urdorf',
        name: 'Zentrumshalle Urdorf',
        address: 'Birmensdorferstrasse 77, 8902 Urdorf',
        latitude: 47.385636902376,
        longitude: 8.422329961061,
        googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
        type: 'WETTSPIELLOKAL',
        capacity: '80 Personen',
        modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
        sortOrder: 5,
        mapId: '4W',
        cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
        kuulaId: '5Msg1',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.385636902376,
          longitude: 8.422329961061,
        },
      },
      description: 'A - Konzertmusik, Höchstklasse, Harmonie (Zentrumshalle Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 18,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_1',
      klasseDescription: '1. Klasse',
      besetzung: 'BRASS_BAND',
      besetzungDescription: 'Brass Band',
      category: null,
      categoryDescription: null,
      location: {
        id: 15,
        identifier: 'zentrumshalle-urdorf',
        name: 'Zentrumshalle Urdorf',
        address: 'Birmensdorferstrasse 77, 8902 Urdorf',
        latitude: 47.385636902376,
        longitude: 8.422329961061,
        googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
        type: 'WETTSPIELLOKAL',
        capacity: '80 Personen',
        modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
        sortOrder: 5,
        mapId: '4W',
        cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
        kuulaId: '5Msg1',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.385636902376,
          longitude: 8.422329961061,
        },
      },
      description: 'A - Konzertmusik, 1. Klasse, Brass Band (Zentrumshalle Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 13,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_1',
      klasseDescription: '1. Klasse',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 15,
        identifier: 'zentrumshalle-urdorf',
        name: 'Zentrumshalle Urdorf',
        address: 'Birmensdorferstrasse 77, 8902 Urdorf',
        latitude: 47.385636902376,
        longitude: 8.422329961061,
        googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
        type: 'WETTSPIELLOKAL',
        capacity: '80 Personen',
        modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
        sortOrder: 5,
        mapId: '4W',
        cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
        kuulaId: '5Msg1',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.385636902376,
          longitude: 8.422329961061,
        },
      },
      description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 4,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_2',
      klasseDescription: '2. Klasse',
      besetzung: 'BRASS_BAND',
      besetzungDescription: 'Brass Band',
      category: null,
      categoryDescription: null,
      location: {
        id: 18,
        identifier: 'salmensaal-schlieren',
        name: 'Salmensaal Schlieren',
        address: 'Uitikonerstrasse 17, 8952 Schlieren',
        latitude: 47.396055051974,
        longitude: 8.448625196597,
        googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
        type: 'WETTSPIELLOKAL',
        capacity: '70 Personen',
        modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
        sortOrder: 2,
        mapId: '1W',
        cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
        kuulaId: '5ZfQq',
        einspiellokal: null,
        instrumentendepotId: 8,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.396055051974,
          longitude: 8.448625196597,
        },
      },
      description: 'A - Konzertmusik, 2. Klasse, Brass Band (Salmensaal Schlieren)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 3,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_2',
      klasseDescription: '2. Klasse',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 18,
        identifier: 'salmensaal-schlieren',
        name: 'Salmensaal Schlieren',
        address: 'Uitikonerstrasse 17, 8952 Schlieren',
        latitude: 47.396055051974,
        longitude: 8.448625196597,
        googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
        type: 'WETTSPIELLOKAL',
        capacity: '70 Personen',
        modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
        sortOrder: 2,
        mapId: '1W',
        cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
        kuulaId: '5ZfQq',
        einspiellokal: null,
        instrumentendepotId: 8,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.396055051974,
          longitude: 8.448625196597,
        },
      },
      description: 'A - Konzertmusik, 2. Klasse, Harmonie (Salmensaal Schlieren)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 20,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_3',
      klasseDescription: '3. Klasse',
      besetzung: 'BRASS_BAND',
      besetzungDescription: 'Brass Band',
      category: null,
      categoryDescription: null,
      location: {
        id: 19,
        identifier: 'grosse-ref-kirche-schlieren',
        name: 'Grosse Ref. Kirche Schlieren',
        address: 'Kirchgasse 7, 8952 Schlieren',
        latitude: 47.396801014533,
        longitude: 8.44573297815,
        googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
        type: 'WETTSPIELLOKAL',
        capacity: '50 Personen',
        modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
        sortOrder: 1,
        mapId: '2W',
        cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
        kuulaId: '5c8Mp',
        einspiellokal: null,
        instrumentendepotId: 8,
        instrumentendepotParademusikId: 7,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'STANDARD',
        coordinates: {
          latitude: 47.396801014533,
          longitude: 8.44573297815,
        },
      },
      description: 'A - Konzertmusik, 3. Klasse, Brass Band (Grosse Ref. Kirche Schlieren)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 17,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_3',
      klasseDescription: '3. Klasse',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 19,
        identifier: 'grosse-ref-kirche-schlieren',
        name: 'Grosse Ref. Kirche Schlieren',
        address: 'Kirchgasse 7, 8952 Schlieren',
        latitude: 47.396801014533,
        longitude: 8.44573297815,
        googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
        type: 'WETTSPIELLOKAL',
        capacity: '50 Personen',
        modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
        sortOrder: 1,
        mapId: '2W',
        cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
        kuulaId: '5c8Mp',
        einspiellokal: null,
        instrumentendepotId: 8,
        instrumentendepotParademusikId: 7,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'STANDARD',
        coordinates: {
          latitude: 47.396801014533,
          longitude: 8.44573297815,
        },
      },
      description: 'A - Konzertmusik, 3. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 2,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_3',
      klasseDescription: '3. Klasse',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 16,
        identifier: 'reformierte-kirche-urdorf',
        name: 'Reformierte Kirche Urdorf',
        address: 'Weihermattstrasse 40, 8902 Urdorf',
        latitude: 47.381879850735,
        longitude: 8.424846238635,
        googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
        type: 'WETTSPIELLOKAL',
        capacity: '50 Personen',
        modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
        sortOrder: 3,
        mapId: '5W',
        cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
        kuulaId: '5gJVm',
        einspiellokal: null,
        instrumentendepotId: 7,
        instrumentendepotParademusikId: 7,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'STANDARD',
        coordinates: {
          latitude: 47.381879850735,
          longitude: 8.424846238635,
        },
      },
      description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 5,
      modul: 'A',
      modulDescription: 'A - Konzertmusik',
      klasse: 'KLASSE_4',
      klasseDescription: '4. Klasse',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 19,
        identifier: 'grosse-ref-kirche-schlieren',
        name: 'Grosse Ref. Kirche Schlieren',
        address: 'Kirchgasse 7, 8952 Schlieren',
        latitude: 47.396801014533,
        longitude: 8.44573297815,
        googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
        type: 'WETTSPIELLOKAL',
        capacity: '50 Personen',
        modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
        sortOrder: 1,
        mapId: '2W',
        cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
        kuulaId: '5c8Mp',
        einspiellokal: null,
        instrumentendepotId: 8,
        instrumentendepotParademusikId: 7,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'STANDARD',
        coordinates: {
          latitude: 47.396801014533,
          longitude: 8.44573297815,
        },
      },
      description: 'A - Konzertmusik, 4. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 9,
      modul: 'B',
      modulDescription: 'B - Unterhaltungsmusik',
      klasse: 'MITTELSTUFE',
      klasseDescription: 'Mittelstufe',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 17,
        identifier: 'turnhalle-weihermatt-urdorf',
        name: 'Turnhalle Weihermatt Urdorf',
        address: 'Weihermattstrasse 50, 8902 Urdorf',
        latitude: 47.379936044763,
        longitude: 8.427330468337,
        googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
        type: 'WETTSPIELLOKAL',
        capacity: '70 Personen',
        modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
        sortOrder: 4,
        mapId: '6W',
        cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
        kuulaId: '5ZfzW',
        einspiellokal: null,
        instrumentendepotId: 7,
        instrumentendepotParademusikId: 7,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'STANDARD',
        coordinates: {
          latitude: 47.379936044763,
          longitude: 8.427330468337,
        },
      },
      description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 16,
      modul: 'B',
      modulDescription: 'B - Unterhaltungsmusik',
      klasse: 'OBERSTUFE',
      klasseDescription: 'Oberstufe',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 18,
        identifier: 'salmensaal-schlieren',
        name: 'Salmensaal Schlieren',
        address: 'Uitikonerstrasse 17, 8952 Schlieren',
        latitude: 47.396055051974,
        longitude: 8.448625196597,
        googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
        type: 'WETTSPIELLOKAL',
        capacity: '70 Personen',
        modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
        sortOrder: 2,
        mapId: '1W',
        cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
        kuulaId: '5ZfQq',
        einspiellokal: null,
        instrumentendepotId: 8,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.396055051974,
          longitude: 8.448625196597,
        },
      },
      description: 'B - Unterhaltungsmusik, Oberstufe, Harmonie (Salmensaal Schlieren)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 15,
      modul: 'B',
      modulDescription: 'B - Unterhaltungsmusik',
      klasse: 'UNTERSTUFE',
      klasseDescription: 'Unterstufe',
      besetzung: 'HARMONIE',
      besetzungDescription: 'Harmonie',
      category: null,
      categoryDescription: null,
      location: {
        id: 17,
        identifier: 'turnhalle-weihermatt-urdorf',
        name: 'Turnhalle Weihermatt Urdorf',
        address: 'Weihermattstrasse 50, 8902 Urdorf',
        latitude: 47.379936044763,
        longitude: 8.427330468337,
        googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
        type: 'WETTSPIELLOKAL',
        capacity: '70 Personen',
        modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
        sortOrder: 4,
        mapId: '6W',
        cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
        kuulaId: '5ZfzW',
        einspiellokal: null,
        instrumentendepotId: 7,
        instrumentendepotParademusikId: 7,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'STANDARD',
        coordinates: {
          latitude: 47.379936044763,
          longitude: 8.427330468337,
        },
      },
      description: 'B - Unterhaltungsmusik, Unterstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 14,
      modul: 'D',
      modulDescription: 'D - Parademusik traditionell',
      klasse: null,
      klasseDescription: null,
      besetzung: null,
      besetzungDescription: null,
      category: null,
      categoryDescription: null,
      location: {
        id: 20,
        identifier: 'marschmusikstrecke-urdorf',
        name: 'Parademusikstrecke Urdorf',
        address: 'Im Moos 3, 8902 Urdorf',
        latitude: 47.390412605741,
        longitude: 8.427050647289,
        googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
        type: 'PARADEMUSIK',
        capacity: null,
        modules: null,
        sortOrder: 7,
        mapId: '7W',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: {
          latitude: 47.390412605741,
          longitude: 8.427050647289,
        },
      },
      description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 6,
      modul: 'G',
      modulDescription: 'G - Tambouren',
      klasse: null,
      klasseDescription: null,
      besetzung: 'TAMBOUREN',
      besetzungDescription: 'Tambouren',
      category: 'MODUL_G_KAT_A',
      categoryDescription: 'Kat. A',
      location: {
        id: 14,
        identifier: 'embrisaal-urdorf',
        name: 'Embrisaal Urdorf',
        address: 'Im Embri 8, 8902 Urdorf',
        latitude: 47.387068997702,
        longitude: 8.425614397929,
        googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
        type: 'WETTSPIELLOKAL',
        capacity: '10 Personen',
        modules: 'G (Tambouren) und H (Perkussionsensembles)',
        sortOrder: 6,
        mapId: '3W',
        cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
        kuulaId: '5ZfQh',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.387068997702,
          longitude: 8.425614397929,
        },
      },
      description: 'G - Tambouren (Kat. A), Tambouren (Embrisaal Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 7,
      modul: 'G',
      modulDescription: 'G - Tambouren',
      klasse: null,
      klasseDescription: null,
      besetzung: 'TAMBOUREN',
      besetzungDescription: 'Tambouren',
      category: 'MODUL_G_KAT_B',
      categoryDescription: 'Kat. B',
      location: {
        id: 14,
        identifier: 'embrisaal-urdorf',
        name: 'Embrisaal Urdorf',
        address: 'Im Embri 8, 8902 Urdorf',
        latitude: 47.387068997702,
        longitude: 8.425614397929,
        googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
        type: 'WETTSPIELLOKAL',
        capacity: '10 Personen',
        modules: 'G (Tambouren) und H (Perkussionsensembles)',
        sortOrder: 6,
        mapId: '3W',
        cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
        kuulaId: '5ZfQh',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.387068997702,
          longitude: 8.425614397929,
        },
      },
      description: 'G - Tambouren (Kat. B), Tambouren (Embrisaal Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 8,
      modul: 'G',
      modulDescription: 'G - Tambouren',
      klasse: null,
      klasseDescription: null,
      besetzung: 'TAMBOUREN',
      besetzungDescription: 'Tambouren',
      category: 'MODUL_G_KAT_C',
      categoryDescription: 'Kat. C',
      location: {
        id: 14,
        identifier: 'embrisaal-urdorf',
        name: 'Embrisaal Urdorf',
        address: 'Im Embri 8, 8902 Urdorf',
        latitude: 47.387068997702,
        longitude: 8.425614397929,
        googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
        type: 'WETTSPIELLOKAL',
        capacity: '10 Personen',
        modules: 'G (Tambouren) und H (Perkussionsensembles)',
        sortOrder: 6,
        mapId: '3W',
        cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
        kuulaId: '5ZfQh',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.387068997702,
          longitude: 8.425614397929,
        },
      },
      description: 'G - Tambouren (Kat. C), Tambouren (Embrisaal Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 11,
      modul: 'H',
      modulDescription: 'H - Perkussionsensembles',
      klasse: 'MITTELSTUFE',
      klasseDescription: 'Mittelstufe',
      besetzung: 'PERKUSSIONSENSEMBLE',
      besetzungDescription: 'Perkussionsensemble',
      category: null,
      categoryDescription: null,
      location: {
        id: 14,
        identifier: 'embrisaal-urdorf',
        name: 'Embrisaal Urdorf',
        address: 'Im Embri 8, 8902 Urdorf',
        latitude: 47.387068997702,
        longitude: 8.425614397929,
        googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
        type: 'WETTSPIELLOKAL',
        capacity: '10 Personen',
        modules: 'G (Tambouren) und H (Perkussionsensembles)',
        sortOrder: 6,
        mapId: '3W',
        cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
        kuulaId: '5ZfQh',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.387068997702,
          longitude: 8.425614397929,
        },
      },
      description: 'H - Perkussionsensembles, Mittelstufe, Perkussionsensemble (Embrisaal Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 12,
      modul: 'H',
      modulDescription: 'H - Perkussionsensembles',
      klasse: 'OBERSTUFE',
      klasseDescription: 'Oberstufe',
      besetzung: 'PERKUSSIONSENSEMBLE',
      besetzungDescription: 'Perkussionsensemble',
      category: null,
      categoryDescription: null,
      location: {
        id: 14,
        identifier: 'embrisaal-urdorf',
        name: 'Embrisaal Urdorf',
        address: 'Im Embri 8, 8902 Urdorf',
        latitude: 47.387068997702,
        longitude: 8.425614397929,
        googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
        type: 'WETTSPIELLOKAL',
        capacity: '10 Personen',
        modules: 'G (Tambouren) und H (Perkussionsensembles)',
        sortOrder: 6,
        mapId: '3W',
        cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
        kuulaId: '5ZfQh',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.387068997702,
          longitude: 8.425614397929,
        },
      },
      description: 'H - Perkussionsensembles, Oberstufe, Perkussionsensemble (Embrisaal Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
    {
      id: 10,
      modul: 'H',
      modulDescription: 'H - Perkussionsensembles',
      klasse: 'UNTERSTUFE',
      klasseDescription: 'Unterstufe',
      besetzung: 'PERKUSSIONSENSEMBLE',
      besetzungDescription: 'Perkussionsensemble',
      category: null,
      categoryDescription: null,
      location: {
        id: 14,
        identifier: 'embrisaal-urdorf',
        name: 'Embrisaal Urdorf',
        address: 'Im Embri 8, 8902 Urdorf',
        latitude: 47.387068997702,
        longitude: 8.425614397929,
        googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
        type: 'WETTSPIELLOKAL',
        capacity: '10 Personen',
        modules: 'G (Tambouren) und H (Perkussionsensembles)',
        sortOrder: 6,
        mapId: '3W',
        cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
        kuulaId: '5ZfQh',
        einspiellokal: null,
        instrumentendepotId: 6,
        instrumentendepotParademusikId: 6,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: 'FULL',
        coordinates: {
          latitude: 47.387068997702,
          longitude: 8.425614397929,
        },
      },
      description: 'H - Perkussionsensembles, Unterstufe, Perkussionsensemble (Embrisaal Urdorf)',
      status: 'FINAL',
      entries: [],
      final: true,
      notPending: true,
    },
  ]
})
