export default defineEventHandler(() => {
  return {
    hauptsponsor: [
      {
        name: 'Zürcher Kantonalbank',
        cloudflareId: '1f12d549-3af0-4d91-d5b0-6dd9bb3e4e00',
        url: 'https://www.zkb.ch/de/ueber-uns/unser-engagement/kultur-szene/zuercher-kantonalmusikfest.html',
      },
    ],
    premium: [
      { name: 'Haldengut Bier', cloudflareId: '5e16ed1e-39ce-4e38-53f3-e86a338c1300', url: 'https://haldengut.ch' },
      {
        name: 'Mobiliar Versicherung',
        cloudflareId: '5402e6d6-16f4-4825-69d8-4c1e4e6f4000',
        url: 'https://www.mobiliar.ch',
      },
      { name: 'Gemeinde Urdorf', cloudflareId: 'ab1c5640-ed22-4e00-850a-1b132c1fe000', url: 'https://www.urdorf.ch' },
      {
        name: 'Franz AG',
        cloudflareId: 'fb7cb0e4-dcec-46d4-d108-4287acecd300',
        url: 'https://www.franz.ch',
      },
      { name: 'Otto Rohrunterhalt GmbH', cloudflareId: 'e8bbaacf-2f2c-4fff-df4f-56ec9377a900', url: 'https://www.otto-rohrunterhalt.ch' },
      {
        name: 'Stadt Schlieren',
        cloudflareId: '052e0928-2c2c-4919-31d4-3cc8ba9fd100',
        url: 'https://www.schlieren.ch',
      },
    ],
    deluxe: [
      { name: 'Landolt Weine', cloudflareId: '65df5e8f-bc6b-4d89-d374-4babafb26300', url: 'https://www.landolt-weine.ch' },
      {
        name: 'Hauseigentümerverband',
        cloudflareId: '5165dff6-ce1e-44fb-64bc-c66050623900',
        url: 'https://www.hev-schlieren.ch',
      },
      { name: 'Aregger', cloudflareId: 'e072a022-b7a1-47ad-1fbc-80f7f072b300', url: 'https://aregger-elektro.swiss' },
      {
        name: 'Murbach Musik AG',
        cloudflareId: '69d9824a-a095-4074-b226-4573d58ae600',
        url: 'https://murbach-musik.ch',
      },
      { name: 'effekte.ch AG', cloudflareId: '9822ed45-2e4b-4ff2-bf43-ed2c3713f600', url: 'https://effekte.ch' },
      {
        name: 'heer Musik AG',
        cloudflareId: '3df8e173-ba16-4e55-e109-3051b6433100',
        url: 'https://www.heermusic.com',
      },
      { name: 'Fest-Service Schmidinger', cloudflareId: 'ec2089ac-477a-469e-7011-860c0e9e4500', url: 'https://www.feste-schmidinger.ch' },
      {
        name: 'Bridgestone',
        cloudflareId: '558dcfe3-81d9-44b4-a2be-241f71976500',
        url: 'https://www.bridgestone.ch',
      },
    ],
    sponsor: [
      {
        name: 'TCS Zürcher Limmattal',
        cloudflareId: '1756c1b2-876d-41ce-15c3-37294b134e00',
        url: 'https://www.tcs.ch/de/der-tcs/sektionen/zuerich/untersektionen/limmattal',
      },
      { name: 'Stadt Dietikon', cloudflareId: '98a5d0b7-56bc-4aff-8c66-1dce826ed800', url: 'https://www.dietikon.ch' },
      {
        name: 'Musikhaus Bucher AG',
        cloudflareId: 'a335c07e-6201-49dc-64f9-8edced287800',
        url: 'https://musikbucher.ch',
      },
      { name: 'F. Goetschmann GmbH', cloudflareId: 'df055867-c12b-464d-e127-e12b8e6d4b00', url: 'https://www.goetschmann-maler.ch' },
      {
        name: 'Landis AG',
        cloudflareId: 'a782812c-0503-4116-b9f8-f250d5e60600',
        url: 'https://landis-ing.ch',
      },
    ],
    musikfan: [
      { name: 'Hotel Tivoli', cloudflareId: '1707ade1-2f95-4d17-06ba-d4694cf7fd00', url: 'https://www.hotel-tivoli.ch' },
      {
        name: 'Gelateria Leonardo',
        cloudflareId: '40dde5ba-2569-4fc2-c153-969e13523800',
        url: 'https://www.gelaterialeonardo.ch',
      },
      { name: 'Gemeinde Unterengstringen', cloudflareId: '52d0a499-914e-48f9-3bba-f2af46ec5400', url: 'https://www.unterengstringen.ch' },
      {
        name: 'Walter Bochsler AG',
        cloudflareId: 'f166e362-9ef2-4410-a4b5-200108723c00',
        url: 'https://bochsler-ag.ch',
      },
      { name: 'J. Wiederkehr AG', cloudflareId: '63293f52-60f8-40b7-bfb1-3f167040db00', url: 'https://www.wiederkehr-dietikon.ch' },
      {
        name: 'Gewerbe- und Handelszentrum Schlieren AG',
        cloudflareId: '41fab597-a69d-469f-9878-aec70b39fd00',
        url: 'https://ghzschlieren.ch',
      },
      { name: 'Meier Tobler AG', cloudflareId: '4f8e989d-6080-4238-dcc5-549472255c00', url: 'https://www.meiertobler.ch' },
      {
        name: 'mp technology',
        cloudflareId: '6bc8f2ea-c4f9-49be-2098-1fbdcdb0cf00',
        url: 'https://www.mptechnology.ch',
      },
      { name: 'Mosterei Möhl AG', cloudflareId: '01218a7a-d741-417a-a452-fabe2fcc3c00', url: 'https://www.moehl.ch' },
      {
        name: 'Gemeinde Oberengstringen',
        cloudflareId: 'd2dd7761-ac88-4675-01a0-a43f24502600',
        url: 'https://www.oberengstringen.ch',
      },
      { name: 'Büsser Informatik GmbH', cloudflareId: '260ed535-22ce-4660-14c1-907b62065800', url: 'https://www.buesser.ch' },
      {
        name: 'Kath. Pfarramt St. Josef',
        cloudflareId: 'f0ca3c0a-4396-4d4f-c64e-e419d893bc00',
        url: 'https://www.pfarrei-schlieren.ch',
      },
      { name: 'CS-Reinigung GmbH', cloudflareId: 'a8e7cc99-e88f-4d6f-34a1-1480d9a58e00', url: 'https://www.cs-reinigung.ch' },
      {
        name: 'DBU Facility Services AG',
        cloudflareId: 'fff61c9b-f22e-459f-4786-b9f1e25e8e00',
        url: 'https://www.dbu.ch',
      },
      { name: 'Schneider Metallbau AG', cloudflareId: 'c3fae87a-3e80-4252-ed91-0b73f2a97300', url: 'https://schneider-metall.ch' },
      {
        name: 'Zunft zur Zimmerleuten',
        cloudflareId: '9ccbc846-35d3-4f49-3eac-881c120dcd00',
        url: 'https://zimmerleuten.ch',
      },
      { name: 'Friedrich Gebäudetechnik GmbH', cloudflareId: 'fcf3de9c-7070-4483-34e6-cc3fa8d4bb00', url: 'https://www.friedrich-gebaeudetechnik.ch' },
      {
        name: 'Brandfix AG',
        cloudflareId: '1b540cbb-2c32-4b3b-db82-a9d19e74e400',
        url: 'https://brandfix.ch',
      },
      { name: 'Downstairs Studio', cloudflareId: 'ee8e8811-6800-4efb-115d-032645909200', url: 'https://downstairs-studio.ch' },
      {
        name: 'dolce far niente',
        cloudflareId: 'ef5a2360-aab9-4ee7-5047-30effc3f0b00',
        url: 'https://www.dolcefarniente.ch',
      },
      { name: 'Elektro Weber AG', cloudflareId: '50a6342a-8f1e-48be-10af-201b5e547300', url: 'https://elektroweberag.ch' },
      {
        name: 'Dräksak',
        cloudflareId: 'b07b6bac-968f-4de3-daa6-0de1ac816e00',
        url: 'https://draeksak.ch',
      },
      { name: 'Garage Brogli AG', cloudflareId: '146c1111-ba5a-4499-b425-b966b4a51000', url: 'https://www.brogliag.ch' },
      {
        name: 'Ref. Kirche Schlieren',
        cloudflareId: '2edee03a-8a2d-44de-e094-0056440d0800',
        url: 'https://www.ref-schlieren.ch',
      },
      { name: 'Hampel AG', cloudflareId: 'b9640f75-6966-48cd-f155-20109dcda000', url: 'https://hampelgruppe.ch' },
      {
        name: 'Gemeinde Geroldswil',
        cloudflareId: '1e90f91e-9c75-4ddc-08e5-8ec233678000',
        url: 'https://www.geroldswil.ch',
      },
      {
        name: 'Migros-Kulturprozent',
        cloudflareId: '9f5525a0-4052-4c66-5228-7ad7510b3c00',
        url: 'https://engagement.migros.ch/de/organisation/migros-zuerich',
      },
      { name: 'Zurich Versicherung', cloudflareId: 'faf1f592-cbb7-410e-a323-50262a246900', url: 'https://www.zurich.ch' },
      {
        name: 'Ref. Kirche Urdorf',
        cloudflareId: '0874efa0-1964-410f-7b26-44bf0ebd6b00',
        url: 'https://www.ref-urdorf.ch',
      },
      { name: 'Blutspende Zürich', cloudflareId: '8bafbba3-b2a2-46fa-0dba-4e365f7fad00', url: 'https://www.blutspendezurich.ch' },
      {
        name: 'Metzgerei Steiner',
        cloudflareId: '36615ef5-2638-409e-db8f-a99380728100',
        url: 'https://www.steiner-metzgerei.ch',
      },
      { name: 'K. Greb & Sohn Haustechnik AG', cloudflareId: 'd019bfc4-0e22-42e4-91a4-1ea116e97c00', url: 'https://www.greb.ch' },
      {
        name: 'Fubotech AG',
        cloudflareId: 'fbf5f00c-43b6-467b-6e61-bd586c4f1a00',
        url: 'https://www.fubotech.ch',
      },
      { name: 'Maler Mettler', cloudflareId: 'c1ff00ec-d924-469b-aa10-f0c7a5b61a00', url: 'https://maler-mettler.ch' },
      {
        name: 'Bolliger AG Gartenbau',
        cloudflareId: '0f2136e7-080f-44f0-1634-f72960385400',
        url: 'https://bolliger-gartenbau.ch',
      },
      { name: 'Herzog Küchen', cloudflareId: 'b8d41478-52e6-4570-7358-a4f5ef70eb00', url: 'https://www.herzog-kuechen.ch' },
      {
        name: 'Gemeinde Uitikon',
        cloudflareId: '26f67855-795d-4c35-7d4f-fffce199af00',
        url: 'https://www.uitikon.ch',
      },
      { name: 'n c ag', cloudflareId: 'e96a1e19-b30d-428d-ce80-e8fe84689e00', url: 'https://ncag.ch' },
    ],
    goenner: [
      { name: 'Musikhaus Kubli', cloudflareId: null, url: 'https://www.dasmusikhaus.ch' },
      {
        name: 'Edile Gips GmbH',
        cloudflareId: null,
        url: null,
      },
      { name: 'SEQUOIA Legal & Advisory GmbH', cloudflareId: null, url: null },
      { name: 'Stucky Holzprofilleisten AG', cloudflareId: null, url: null },
      {
        name: 'AGILITA',
        cloudflareId: null,
        url: 'https://www.agilita.ch',
      },
      { name: 'Pneushop Sergio Pallaoro GmbH', cloudflareId: null, url: null },
      { name: 'Garage Schweizer', cloudflareId: null, url: null },
      {
        name: 'Helvetic Tours',
        cloudflareId: null,
        url: 'https://www.helvetictours.ch',
      },
      { name: 'Betschart AG Spenglerei', cloudflareId: null, url: 'https://www.spenglereibetschart.ch' },
      {
        name: 'Gemeinde Weiningen',
        cloudflareId: null,
        url: null,
      },
      { name: 'Kohler Zäune AG', cloudflareId: null, url: 'https://zaun-kohler.ch' },
      { name: 'AGIR AG', cloudflareId: null, url: 'https://www.agir.biz' },
      {
        name: 'Höhn Monika privat',
        cloudflareId: null,
        url: null,
      },
      { name: 'Seifriz AG Gipsergeschäft', cloudflareId: null, url: null },
      {
        name: 'Zahnarzt Bertschinger',
        cloudflareId: null,
        url: 'https://www.zahnarztschlieren.ch',
      },
      { name: 'Pestalozzi AG', cloudflareId: null, url: 'https://www.pestalozzi.com' },
      { name: 'Vicentini Transporte AG', cloudflareId: null, url: null },
      {
        name: 'SikaBau AG',
        cloudflareId: null,
        url: 'https://bau.sika.com',
      },
      { name: 'Gemeinde Oetwil a.d.L.', cloudflareId: null, url: 'https://www.oetwiladl.ch' },
      {
        name: 'Brüwe Bau AG',
        cloudflareId: null,
        url: 'https://bruewe.ch',
      },
      { name: 'Tierarzt Praxis Bachmann', cloudflareId: null, url: null },
      { name: 'Gemeinde Birmensdorf', cloudflareId: null, url: null },
      {
        name: 'SmartYES Energy Solutions',
        cloudflareId: null,
        url: 'https://smart-y.ch',
      },
      { name: 'Limeco', cloudflareId: null, url: null },
      { name: 'Wirtschaftskammer Schlieren', cloudflareId: null, url: null },
      {
        name: 'Watt Peak GmbH',
        cloudflareId: null,
        url: null,
      },
      { name: 'Brem + Schwarz AG', cloudflareId: null, url: 'https://brem-schwarz.ch' },
      {
        name: "Rolli's Steakhouse",
        cloudflareId: null,
        url: null,
      },
      { name: 'PKZ Burger-Kehl & Co. AG', cloudflareId: null, url: 'https://www.pkz.ch' },
      {
        name: 'A. Baltensperger AG',
        cloudflareId: null,
        url: 'https://baltensperger.ch',
      },
      { name: 'Swiss Transport', cloudflareId: null, url: 'https://swisstransport.ch' },
      {
        name: 'Smart Efficient AG',
        cloudflareId: null,
        url: 'https://www.smartefficient.ch',
      },
      { name: 'All for One Switzerland AG', cloudflareId: null, url: null },
      {
        name: 'Paul Dill Plattenbeläge AG',
        cloudflareId: null,
        url: 'https://paul-dill-plattenbelage-ag.business.site',
      },
      { name: 'Geistlich Immobilia AG', cloudflareId: null, url: 'https://www.geistlich-immobilia.ch' },
      {
        name: 'Auer Brillen und Kontaktlinsen',
        cloudflareId: null,
        url: null,
      },
      { name: 'Restaurant Salmen', cloudflareId: null, url: 'https://salmen.ch' },
      { name: 'Planzer Transporte AG', cloudflareId: null, url: null },
      {
        name: 'Audika AG',
        cloudflareId: null,
        url: 'https://www.audika.ch',
      },
      { name: 'Höhn AG Malerunternehmen', cloudflareId: null, url: null },
    ],
  }
})
