export default defineEventHandler(() => {
  return [
    {
      type: 'SAMSTAG_ABEND',
      inPast: false,
      entries: [
        {
          type: 'SAMSTAG_ABEND',
          date: '2024-06-22',
          start: '17:30:00',
          end: '18:00:00',
          title: 'Rangverkündigung',
          subtitle: null,
          text: null,
          location: {
            id: 15,
            identifier: 'zentrumshalle-urdorf',
            name: 'Zentrumshalle Urdorf',
            address: 'Birmensdorferstrasse 77, 8902 Urdorf',
            latitude: 47.385636902376,
            longitude: 8.422329961061,
            googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
            type: 'WETTSPIELLOKAL',
            capacity: '80 Personen',
            modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
            sortOrder: 5,
            mapId: '4W',
            cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
            kuulaId: '5Msg1',
            einspiellokal: {
              id: 1,
              identifier: 'singsaal-moosmatt',
              name: 'Singsaal Moosmatt',
              address: 'Im Moos 24, 8902 Urdorf',
              latitude: 47.388554561192,
              longitude: 8.425192408359,
              googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+24%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.388554561192,8.425192408359',
              type: 'EINSPIELLOKAL',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '4E',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.388554561192, longitude: 8.425192408359 },
            },
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: {
              id: 6,
              identifier: 'turnhalle-embri',
              name: 'Turnhalle Embri',
              address: 'Im Embri 8, 8902 Urdorf',
              latitude: 47.387036241257,
              longitude: 8.425649260081,
              googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.387036241257,8.425649260081',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '3/4D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.387036241257, longitude: 8.425649260081 },
            },
            juryfeedback: {
              id: 23,
              identifier: 'zivilschutzanlage',
              name: 'Zivilschutzanlage',
              address: 'Birmensdorferstrasse 77, 8902 Urdorf',
              latitude: 47.385708178028,
              longitude: 8.422369510897,
              googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.385708178028,8.422369510897',
              type: 'JURYFEEDBACK',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '4J',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.385708178028, longitude: 8.422369510897 },
            },
            percussionEquipmentType: 'FULL',
            coordinates: { latitude: 47.385636902376, longitude: 8.422329961061 },
          },
          cloudflareId: null,
          vereinIdentifier: null,
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SAMSTAG_ABEND',
          date: '2024-06-22',
          start: '19:15:00',
          end: '20:00:00',
          title: 'Brass Band Eglisau',
          subtitle: 'Wettspiel 1. Klasse, Brass Band',
          text: null,
          location: {
            id: 15,
            identifier: 'zentrumshalle-urdorf',
            name: 'Zentrumshalle Urdorf',
            address: 'Birmensdorferstrasse 77, 8902 Urdorf',
            latitude: 47.385636902376,
            longitude: 8.422329961061,
            googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
            type: 'WETTSPIELLOKAL',
            capacity: '80 Personen',
            modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
            sortOrder: 5,
            mapId: '4W',
            cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
            kuulaId: '5Msg1',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: { latitude: 47.385636902376, longitude: 8.422329961061 },
          },
          cloudflareId: null,
          vereinIdentifier: 'brass-band-eglisau',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SAMSTAG_ABEND',
          date: '2024-06-22',
          start: '20:30:00',
          end: '21:30:00',
          title: 'Stadtharmonie Zürich Oerlikon-Seebach',
          subtitle: 'Wettspiel Höchstklasse, Harmonie',
          text: null,
          location: {
            id: 15,
            identifier: 'zentrumshalle-urdorf',
            name: 'Zentrumshalle Urdorf',
            address: 'Birmensdorferstrasse 77, 8902 Urdorf',
            latitude: 47.385636902376,
            longitude: 8.422329961061,
            googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
            type: 'WETTSPIELLOKAL',
            capacity: '80 Personen',
            modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
            sortOrder: 5,
            mapId: '4W',
            cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
            kuulaId: '5Msg1',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: { latitude: 47.385636902376, longitude: 8.422329961061 },
          },
          cloudflareId: null,
          vereinIdentifier: 'stadtharmonie-zuerich-oerlikon-seebach',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SAMSTAG_ABEND',
          date: '2024-06-22',
          start: '20:30:00',
          end: '22:00:00',
          title: 'Rocken mit dem Saint City Orchestra',
          subtitle: null,
          text: 'Entstanden aus einer spontanen Bierlaune, haben die sechs Musiker ihren Weg in die Welt des Irish Punk Rock gefunden. Was das Saint City Orchestra wirklich auszeichnet, sind nicht nur seine Songs, sondern vielmehr die mitreissenden Auftritte und die überschwängliche Partystimmung, die sie bei jedem Gig entfachen.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: 'f4f06a1a-0753-462b-eea3-98283a4b6900',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'saint-city-orchestra',
          inPast: false,
        },
        {
          type: 'SAMSTAG_ABEND',
          date: '2024-06-22',
          start: '22:30:00',
          end: '23:59:00',
          title: 'Feiern mit der Compass Party Band',
          subtitle: null,
          text: 'Compass ist die neue Partyband der Schweiz. Als perfekt eingespieltes Team treten die sechs Musiker bei verschiedensten Events in der Schweiz und im benachbarten Ausland auf. Sie wissen genau, was es für eine richtige Party braucht, und können auf eine langjährige Bühnenerfahrung in verschiedenen Stilrichtungen zurückblicken.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: 'ea75cb30-69c0-4a19-6ee7-0e79ab4cf900',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'compass',
          inPast: false,
        },
        {
          type: 'SAMSTAG_ABEND',
          date: '2024-06-23',
          start: '01:00:00',
          end: '04:00:00',
          title: 'Ausklang mit DJ Outside',
          subtitle: null,
          text: 'DJ Outside ist «Diskjockey, Moderator und Veranstalter von musikalischen Mega-Events – ein aufgestellter und auf dem Boden gebliebener Schweizer Bub». Das musikalische Menü wird mit viel Schwung serviert. Durch jahrelange Erfahrung hat DJ Outside immer die richtige Musik parat, so dass sich alle wohlfühlen können.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: '96b8667c-d26d-43da-6b02-9305e1284300',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'dj-outside',
          inPast: false,
        },
      ],
    },
    {
      type: 'FREITAG_ABEND',
      inPast: false,
      entries: [
        {
          type: 'FREITAG_ABEND',
          date: '2024-06-21',
          start: '17:45:00',
          end: '18:45:00',
          title: 'Warm-up mit Rosalia Golden Hits',
          subtitle: null,
          text: 'Sängerin Rosalia, während rund 20 Jahren charismatische Frontfrau der «Nonstop R&J Country Band», bereichert jeden Anlass mit Golden Hits von Country bis Pop mit ihrer sympathischen Bühnenpräsenz. Neben vielen bekannten Hits zum Mitsingen und Tanzen runden verschiedene Eigenkompositionen das vielfältige musikalische Programm ab.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: '85c1dd92-5728-46b7-834d-ad4393bcdc00',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'rosalia-golden-hits',
          inPast: false,
        },
        {
          type: 'FREITAG_ABEND',
          date: '2024-06-21',
          start: '19:30:00',
          end: '20:30:00',
          title: 'Galakonzert mit der SWISS Band',
          subtitle: null,
          text: 'Das im Jahr 1958 durch Angestellte der damaligen «Swissair» gegründete Orchester hat sich auf Unterhaltungsmusik mit einer breiten Palette von Musikrichtungen spezialisiert. Es spielt Musik aus der Swing-Ära, Rock-, Pop- Soul und Funk-Titel sowie bekannte Film- und Musical-Melodien und tritt immer wieder mit bekannten und prominenten Gästen auf.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: '9ced0d94-baec-443f-f070-34398d142f00',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'swiss-band',
          inPast: false,
        },
        {
          type: 'FREITAG_ABEND',
          date: '2024-06-21',
          start: '21:00:00',
          end: '22:30:00',
          title: 'Feiern mit der Stubete Gäng',
          subtitle: null,
          text: 'Aurel und Moritz Hassler, die beiden sympathischen Brüder aus dem Zugerland, haben mit ihrer Stubete Gäng 2019 mal ebenso einen völlig neuen Musikstil erfunden. Ihr «ÖrbnLändlr» eroberte die Schweiz im Sturm. Der Megahit «Petra Sturzenegger» ist längst anerkanntes Schweizer Kulturgut, das landauf, landab von Göschenen bis Airolo mitgesungen wird.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: '687817b1-01a6-42b5-6bfa-8c8e559dda00',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'stubete-gaeng',
          inPast: false,
        },
        {
          type: 'FREITAG_ABEND',
          date: '2024-06-21',
          start: '22:40:00',
          end: '23:59:00',
          title: 'Ausklang mit DJ Outside',
          subtitle: null,
          text: 'DJ Outside ist «Diskjockey, Moderator und Veranstalter von musikalischen Mega-Events – ein aufgestellter und auf dem Boden gebliebener Schweizer Bub». Das musikalische Menü wird mit viel Schwung serviert. Durch jahrelange Erfahrung hat DJ Outside immer die richtige Musik parat, so dass sich alle wohlfühlen können.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: '96b8667c-d26d-43da-6b02-9305e1284300',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'dj-outside',
          inPast: false,
        },
      ],
    },
    {
      type: 'SONNTAG',
      inPast: false,
      entries: [
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '09:05:00',
          end: '09:45:00',
          title: 'Musikverein Hedingen',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-hedingen',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '10:00:00',
          end: '11:00:00',
          title: 'Ökumenischer Gottesdienst',
          subtitle: null,
          text: 'Sei dabei an einem festlichen ökumenischen Gottesdienst mit musikalischer Begleitung durch den Musikverein Hedingen! Alle sind herzlich eingeladen, den Sonntag gemeinsam zu feiern. Die Predigt wird von Pfarrer Ivan Walther und Pastoraltheologin Séverine Piazza im Rahmen des Zürcher Kantonalmusikfests gestaltet. Wir freuen uns auf eine rege Teilnahme!',
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: {
              id: 8,
              identifier: 'schulhaus-hofacker-turnhalle',
              name: 'Schulhaus Hofacker Turnhalle',
              address: 'Hofackerstrasse 2, 8952 Schlieren',
              latitude: 47.39453952852,
              longitude: 8.444151354002,
              googleMapsAddress: 'https://www.google.ch/maps/place/Hofackerstrasse+2%2C+8952+Schlieren',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.394539528520,8.444151354002',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '1/2D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.39453952852, longitude: 8.444151354002 },
            },
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: null,
          unterhaltungIdentifier: 'gottesdienst',
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '11:15:00',
          end: '11:55:00',
          title: 'Brass Band Musig Hittnau',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'brass-band-musig-hittnau',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '12:00:00',
          end: '13:45:00',
          title: 'Zmittag mit Schäbyschigg',
          subtitle: null,
          text: 'Schäbyschigg sind fünf weltoffene und unerschrockene Musiker: Mit Klarinette, Trompeten, Tuba und Akkordeon sowie Käse, Brot und «Tiggets» im Gepäck sind sie unterwegs, um mit ihrer Musik die Herzen von Nah und Fern zu erfreuen. Mal groovig, mal lüpfig, mal melancholisch, mal urchig – immer authentisch und frisch tragen sie ihre Melodien in die Welt hinaus.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: '537e6324-ebdd-46ee-759c-059cceceaf00',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'schaebyschigg',
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '12:15:00',
          end: '13:00:00',
          title: 'Musikverein Harmonie Adliswil',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-harmonie-adliswil',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '13:30:00',
          end: '14:10:00',
          title: 'Musikverein Helvetia Marthalen',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-helvetia-marthalen',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '14:00:00',
          end: '14:45:00',
          title: 'Blaskapelle aus Altheim und Sigmaringendorf (DE)',
          subtitle: null,
          text: 'Ehrwürdiger Besuch von den Nachbarn aus Süddeutschland! Der Musikverein Altheim und der Musikverein Sigmaringendorf planten eine Reise nach Zürich. Nachdem sie erfahren hatten, dass das Kantonalmusikfest just am vorgesehenen Wochenende stattfindet, beschlossen sie sogleich, den Event im Rahmen ihres Aufenthalts mit einer musikalischen Darbietung zu bereichern. Herzlichen Dank und willkommen im Limmattal!',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: null,
          vereinIdentifier: null,
          unterhaltungIdentifier: 'altheim-und-sigmaringendorf',
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '14:25:00',
          end: '15:05:00',
          title: 'Musikverein Harmonie Bauma',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-harmonie-bauma',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '15:00:00',
          end: '15:45:00',
          title: 'Stadtmusik Dietikon',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: null,
          vereinIdentifier: 'stadtmusik-dietikon',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '15:20:00',
          end: '16:00:00',
          title: 'Musikverein Buchs ZH',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-buchs-zh',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '16:00:00',
          end: '16:45:00',
          title: 'Musikverein Harmonie Adliswil',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-harmonie-adliswil',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '17:00:00',
          end: '17:30:00',
          title: 'Gesamtchor',
          subtitle: null,
          text: null,
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: null,
          vereinIdentifier: null,
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SONNTAG',
          date: '2024-06-23',
          start: '18:00:00',
          end: '19:00:00',
          title: 'Rangverkündigung und Fahnenübergabe',
          subtitle: 'Musikverein Harmonie Schlieren und Musikverein Harmonie Urdorf',
          text: null,
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: null,
          vereinIdentifier: null,
          unterhaltungIdentifier: null,
          inPast: false,
        },
      ],
    },
    {
      type: 'SAMSTAG_TAG',
      inPast: false,
      entries: [
        {
          type: 'SAMSTAG_TAG',
          date: '2024-06-22',
          start: '09:00:00',
          end: '10:00:00',
          title: 'Jugend und Blasmusik',
          subtitle: null,
          text: 'Mitmachen in einer Bläserklasse – etwas für Dich? Das Erlernen eines Instruments macht Spass und lässt Dich in die wunderbare Welt der Musik eintauchen. Die Schule Urdorf hat vor einigen Monaten ein Pilotprojekt gestartet. Jan Wyss, musikalischer Leiter, zeigt, was die Schülerinnen und Schüler in dieser Zeit erreicht haben und wie Du mitmachen kannst.',
          location: {
            id: 1,
            identifier: 'singsaal-moosmatt',
            name: 'Singsaal Moosmatt',
            address: 'Im Moos 24, 8902 Urdorf',
            latitude: 47.388554561192,
            longitude: 8.425192408359,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+24%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.388554561192,8.425192408359',
            type: 'EINSPIELLOKAL',
            capacity: null,
            modules: null,
            sortOrder: 0,
            mapId: '4E',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: null,
            instrumentendepotParademusikId: null,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.388554561192, longitude: 8.425192408359 },
          },
          cloudflareId: '8757a3f7-653d-44e5-6b5a-7a8b1a151800',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'jugend-und-blasmusik',
          inPast: false,
        },
        {
          type: 'SAMSTAG_TAG',
          date: '2024-06-22',
          start: '10:50:00',
          end: '11:30:00',
          title: 'Musikverein Harmonie Birmensdorf',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-harmonie-birmensdorf',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SAMSTAG_TAG',
          date: '2024-06-22',
          start: '11:45:00',
          end: '13:00:00',
          title: 'Swiss Jungle Drummers Steelband',
          subtitle: null,
          text: 'Die 14-köpfige popige Steelband stammt aus dem Musik-und Showunternehmen Art of Rhythm von Roger Küng.\nDie Band wurde 2007 gegründet und begeistert das Publikum mit ihrem karibischen Holiday-Sound. Im repertoir finden sich sowohl typische karibische titel im calypso oder Samba Stil aber auch moderne Unterhaltung aus der Popszene. Lassen sie sich mit diesem einzigartigen Stil verzaubern und geniessen sie dieses Holiday-Feeling!',
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: {
              id: 8,
              identifier: 'schulhaus-hofacker-turnhalle',
              name: 'Schulhaus Hofacker Turnhalle',
              address: 'Hofackerstrasse 2, 8952 Schlieren',
              latitude: 47.39453952852,
              longitude: 8.444151354002,
              googleMapsAddress: 'https://www.google.ch/maps/place/Hofackerstrasse+2%2C+8952+Schlieren',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.394539528520,8.444151354002',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '1/2D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.39453952852, longitude: 8.444151354002 },
            },
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: 'eb2d6b58-fe53-4532-23df-ba32f9c6db00',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'swiss-jungle-drummers-steelband',
          inPast: false,
        },
        {
          type: 'SAMSTAG_TAG',
          date: '2024-06-22',
          start: '12:00:00',
          end: '14:00:00',
          title: 'Zmittag mit Brässkalation',
          subtitle: null,
          text: 'Fette Brass-Power ohne Kompromisse! Nach diesem Motto gründeten zehn Jungs vor neun Jahren eine Band, um auf eigene Faust die weite Welt der Blasmusik zu erkunden. Mit ihrem einzigartigen Sound, der quer durch Pop, Hip-Hop und Funk geht, reizt die Band die Grenzen dessen aus, was Blasmusik heute sein kann.',
          location: {
            id: 22,
            identifier: 'festzelt-urdorf',
            name: 'Festzelt Urdorf',
            address: 'Bahnhofstrasse 52, 8902 Urdorf',
            latitude: 47.386092494172,
            longitude: 8.424727317603,
            googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 8,
            mapId: 'FU',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 7,
            instrumentendepotParademusikId: 8,
            instrumentendepot: {
              id: 7,
              identifier: 'turnhalle-bahnhofstrasse',
              name: 'Turnhalle Bahnhofstrasse',
              address: 'Bahnhofstrasse 50, 8902 Urdorf',
              latitude: 47.3865713534,
              longitude: 8.425189176428,
              googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '5/6D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
            },
            juryfeedback: null,
            percussionEquipmentType: null,
            coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
          },
          cloudflareId: '996f1c4f-5cdc-470b-e212-61221748fd00',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'braesskalation',
          inPast: false,
        },
        {
          type: 'SAMSTAG_TAG',
          date: '2024-06-22',
          start: '13:30:00',
          end: '14:10:00',
          title: 'Musikverein Oberrieden',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-oberrieden',
          unterhaltungIdentifier: null,
          inPast: false,
        },
        {
          type: 'SAMSTAG_TAG',
          date: '2024-06-22',
          start: '14:25:00',
          end: '15:00:00',
          title: 'Schwyzerörgeli Gruppe Schlieren',
          subtitle: null,
          text: 'Die 1990 gegründete Schwyzerörgeli-Gruppe besteht heute aus 21 Musizierenden und spielt unter der Leitung von Dominik Heller vorwiegend traditionelle schweizerische Volkmusik, wie Länder, Marsch, Schottisch und Walzer.',
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: {
              id: 8,
              identifier: 'schulhaus-hofacker-turnhalle',
              name: 'Schulhaus Hofacker Turnhalle',
              address: 'Hofackerstrasse 2, 8952 Schlieren',
              latitude: 47.39453952852,
              longitude: 8.444151354002,
              googleMapsAddress: 'https://www.google.ch/maps/place/Hofackerstrasse+2%2C+8952+Schlieren',
              googleMapsCoordinates: 'https://www.google.com/maps?q=47.394539528520,8.444151354002',
              type: 'INSTRUMENTENDEPOT',
              capacity: null,
              modules: null,
              sortOrder: 0,
              mapId: '1/2D',
              cloudflareId: null,
              kuulaId: null,
              einspiellokal: null,
              instrumentendepotId: null,
              instrumentendepotParademusikId: null,
              instrumentendepot: null,
              juryfeedback: null,
              percussionEquipmentType: null,
              coordinates: { latitude: 47.39453952852, longitude: 8.444151354002 },
            },
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: 'c13c0cf1-638d-4160-8f76-aaee65fefd00',
          vereinIdentifier: null,
          unterhaltungIdentifier: 'schwyzeroergeli-gruppe-schlieren',
          inPast: false,
        },
        {
          type: 'SAMSTAG_TAG',
          date: '2024-06-22',
          start: '15:20:00',
          end: '16:00:00',
          title: 'Musikverein Zürich-Seebach',
          subtitle: 'Unterhaltungskonzert',
          text: null,
          location: {
            id: 21,
            identifier: 'festzelt-schlieren',
            name: 'Festzelt Schlieren',
            address: 'Badenerstrasse 12, 8952 Schlieren',
            latitude: 47.397439543225,
            longitude: 8.446011061969,
            googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
            type: 'FESTZELT',
            capacity: null,
            modules: null,
            sortOrder: 9,
            mapId: 'FS',
            cloudflareId: null,
            kuulaId: null,
            einspiellokal: null,
            instrumentendepotId: 8,
            instrumentendepotParademusikId: 7,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'STANDARD',
            coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
          },
          cloudflareId: null,
          vereinIdentifier: 'musikverein-zuerich-seebach',
          unterhaltungIdentifier: null,
          inPast: false,
        },
      ],
    },
  ]
})
