export default defineEventHandler(() => {
  return [
    {
      id: 34,
      identifier: 'brass-band-eglisau',
      name: 'Brass Band Eglisau',
      logoImgId: '285ed9ef-3054-4412-a828-b6f06162b300',
      bildImgId: 'ee3b96b0-30b5-45b5-88c8-8ce3a0a1c800',
      homepage: 'https://www.bbeglisau.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Brass Band Eglisau\n1938 wurde die Brass Band Eglisau als damalige «Musikgesellschaft Eglisau» gegründet. Seit den Fünfzigerjahren spielt die BBE als einziger Verein im Musikverband Zürcher Unterland in dieser Besetzungsform.\nDie Freude am gemeinsamen Musizieren auf hohem Niveau steht nebst der Pflege der Kameradschaft im Vordergrund für die Aktivmitglieder der BBE. Wir üben fleissig zuhause und proben wöchentlich gemeinsam. Wir konzertieren gerne und oft und nehmen regelmässig an regionalen und nationalen Wettbewerben teil, um wertvolle Standortbestimmungen zu erhalten, welche uns motivieren und in der musikalischen Entwicklung weiterbringen.\nDies fordert den Musikanten, dem Dirigenten und der Vereinsleitung Jahr für Jahr einiges ab. Doch dadurch sind wir in der Lage, auch mit anderen Musikern mannigfaltigster Couleur gemeinsam Konzerte aufzuführen und mit attraktiven Konzertprogrammen das Publikum immer wieder von neuem zu begeistern.\n',
    },
    {
      id: 44,
      identifier: 'brass-band-maur',
      name: 'Brass Band Maur',
      logoImgId: '65169502-6172-409d-2aba-f65e67083f00',
      bildImgId: '31aadff8-96f5-4b0c-491c-518c18aa3a00',
      homepage: 'https://www.bbmaur.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Brass Band Maur ist ein am Greifensee beheimateter Musikverein mit ca. 20 aktiven Mitgliedern. Diese sind zwischen 13 und 80 Jahre alt und stammen aus der näheren Umgebung. Wir dürfen zudem auf treue MitspielerInnen aus anderen Vereinen zählen, die uns auf verschiedenen Positionen bei Bedarf verstärken.',
    },
    {
      id: 100,
      identifier: 'brass-band-musig-hittnau',
      name: 'Brass Band Musig Hittnau',
      logoImgId: 'c287f02d-40ca-4ede-8814-312acf77a600',
      bildImgId: '9c088f1a-af9e-4212-e557-bb9a31259300',
      homepage: 'https://www.musig-hittnau.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Brass Band Hittnau wurde 1935 gegründet. Wir spielen seit der Gründung in Brass Band Besetzung in der 3. Stärkeklasse. Aktuell zählt unsere Verein 27 Musikantinnen und Musikanten. Im August 2023 hat Dieter Bischof neu die musikalische Leitung übernommen.\n\nWir bieten Jung und Alt eine anspruchsvolle Freizeitbeschäftigung in einem Umfeld, wo Kameradschaft und Geselligkeit noch gross geschrieben werden. Unsere Schwerpunkte legen wir auf eine stetige Weiterentwicklung des Vereins, die gezielte Jugendförderung, sowie darauf, anspruchsvolle Brass Band Musik zu präsentieren.\n\nDie konzertanten Höhepunkte bilden unser Jahreskonzert im Frühling und das Konzert in der Kirche oder eine Abendunterhaltung zum Jahresende. Unser Augenmerk gilt auch den übers ganze Jahr verstreuten Darbietungen in Form von Ständchen und Platzkonzerten zu den verschiedensten Anlässen. Die Brass Band Musig Hittnau ist ein typischer Dorfverein, der im kulturellen Leben der Gemeinde Hittnau einen wichtigen Platz einnimmt.',
    },
    {
      id: 65,
      identifier: 'fusion-mallets',
      name: 'Fusion Mallets',
      logoImgId: 'afebfb03-2bb3-49e4-e176-3d40d3807300',
      bildImgId: null,
      homepage: null,
      facebook: null,
      instagram: null,
      websiteText: 'Die Fusion Mallets sind das Perkussionsensemble der Musikschule Weinfelden TG.',
    },
    {
      id: 90,
      identifier: 'harmonie-am-bachtel',
      name: 'Harmonie am Bachtel',
      logoImgId: '9cb91f45-2a66-47be-e83e-37d87356e900',
      bildImgId: '2ae1bb39-4a66-4246-c4be-b2fd82dbd400',
      homepage: 'https://www.harmonieambachtel.ch',
      facebook: 'https://www.facebook.com/harmonieambachtel',
      instagram: 'https://www.instagram.com/harmonie_am_bachtel/',
      websiteText:
        'Mit 35 bis 40 Musikantinnen und Musikanten konzertieren wir begeistert mit vielfältiger Literatur konzertante, traditionelle und moderne Blasmusik. Wir nehmen regelmässig an Wettbewerben teil und spielen in der 2. Stärkeklasse mit Harmoniebesetzung.\n\nJährliche Höhepunkte sind die Winterkonzerte in den Kirchen Hinwil und Tann im Januar/Februar, das Frühlingskonzert im Mai/Juni und das Weihnachtskonzert im Dezember. In der Bevölkerung sehr beliebt sind unsere Platzkonzerte im Sommer/Herbst, das Anführen des Räbeliechtli-Umzuges im November oder die eigene Festwirtschaft an der Chilbi Hinwil mit Auftritten von Gastformationen.\n\nDie Freude an der Musik bringt uns zusammen, die generationenübergreifende Kameradschaft formt uns zur Einheit. Gemütlichkeit und Freundschaften pflegen wir an Skiweekends, Grillabenden, Chlausfeieren, Vereinsreisen und natürlich der "Beiz nach der Probe".',
    },
    {
      id: 96,
      identifier: 'harmonie-eintracht-kuesnacht',
      name: 'Harmonie Eintracht Küsnacht',
      logoImgId: '14fd9dfe-5a8e-47ac-df27-4a0b8ea3f300',
      bildImgId: '671f325b-e7cb-4054-1c76-56453a140200',
      homepage: 'https://www.harmonie-kuesnacht.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die HEK ist trotz ihrer langen Vereinsgeschichte ein dynamischer und jung gebliebener Verein. Im Frühling sowie im Herbst erfreuen wir das Publikum mit einem Konzert, dazwischen sind wir auch an diversen Dorfanlässen anzutreffen.\nSelbstverständlich gibt es auch bei uns Gelegenheiten, bei denen wir die Instrumente zu Hause lassen. Ski-Weekend, Grillabende, Musikreise und andere Anlässe, die unsere "Vereins-Chemie" im positiven Sinne beeinflussen.',
    },
    {
      id: 61,
      identifier: 'harmonie-eintracht-maennedorf',
      name: 'Harmonie Eintracht Männedorf',
      logoImgId: '0bfb0a5c-dcdb-4d73-cfab-c2e4beb1a600',
      bildImgId: 'd0a0cf0f-78d4-4822-134c-b3b220eb3700',
      homepage: 'https://www.musikverein-maennedorf.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Harmonie Eintracht Männedorf, kurz HEM, ist DER Musikverein am rechten Zürichseeufer!\n• DER mit knapp 50 Mitgliedern und einer ausgewogenen Besetzung;\n• DER mit vielen jungen und motivierten Musikern/-innen;\n• DER mit einem riesigen Zusammenhalt und einem ausgesprochenen Sinn fürs Gemeinsame;\n• DER, welcher abwechslungsreiche und mitreissende Literatur spielt – eine Jahreshälfte ist bei uns jeweils der konzertanten, eine der unterhaltenden Blasmusik gewidmet;\n• DER, welcher erstklassige Literatur der 2. und 3. Stärkeklasse spielt;\n• DER mit lokaler Verankerung, welcher kontinuierlich im Austausch mit der Musikschule, der Jugendmusik und der Bevölkerung steht;',
    },
    {
      id: 109,
      identifier: 'harmonie-freienbach',
      name: 'Harmonie Freienbach',
      logoImgId: '079d5084-1e31-4f0e-0d6f-d2f5fb27d600',
      bildImgId: 'fff5b327-2dbf-482d-6c17-86667771a000',
      homepage: 'http://www.harmonie-freienbach.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Harmonie Freienbach ist der Musikverein der Gemeinde Freienbach, zu der die fünf Dörfer Pfäffikon, Wilen, Bäch, Hurden und Freienbach gehören. Sie besteht aus rund 45 Mitgliedern und spielt neu in der U-Musik Oberstufe. Die Harmonie Freienbach pflegt die traditionelle und zeitgemässe Blasmusik, ist aber auch offen für andere Stile und Richtungen. Sie bemüht sich um ein attraktives musikalisches Angebot mit einem breiten Spektrum und setzt hohe Qualitätsansprüche an sich selber.',
    },
    {
      id: 84,
      identifier: 'harmoniemusik-helvetia-horgen',
      name: 'Harmoniemusik Helvetia Horgen',
      logoImgId: '8a1fce0d-9a00-49b4-55b2-24ef81092d00',
      bildImgId: '121c917e-b3fc-4015-9b09-7290e3065600',
      homepage: 'https://www.harmonie-horgen.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Als Blasmusikverein aus Horgen am Zürichsee spielen wir in klassischer Harmoniebesetzung und fokussieren unsere Konzerte und Auftritte hauptsächlich auf Horgen und die nähere Umgebung.\n\nUnsere Vision: Wir sind das Blasorchester für unvergessliche musikalische Höhenflüge für alle. Um dieses Ziel zu erreichen, umfasst unser Repertoire verschiedenste Literatur für Konzerte und Ständchen und wir suchen aktiv die Zusammenarbeit mit anderen Vereinen, Musikern und Künstlern, um unserem Publikum und auch unseren Mitgliedern immer wieder neue musikalische Erlebnisse und ein abwechslungsreiches Programm bieten zu können.\n\nIm Sinne einer nachhaltigen Nachwuchsförderung und mit dem Ziel Jugendlichen eine sinnvolle Freizeitbeschäftigung zu ermöglichen, arbeiten wir eng mit der Kadettenmusik Horgen zusammen und unterstützen diese aktiv in ihren Bestrebungen zur Ausbildung junger Musikantinnen und Musikanten.',
    },
    {
      id: 54,
      identifier: 'harmoniemusik-wald',
      name: 'Harmoniemusik-Wald',
      logoImgId: '8db647ea-f0a2-4ea7-a19c-15522e4ba700',
      bildImgId: 'd0b5f708-8ddf-4c2e-8a89-2a82e927ab00',
      homepage: 'https://www.harmoniemusik-wald.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'www.harmoniemusik-wald.ch\n1875 gegründet, sind wir heute eine aktive, dynamische und motivierte Harmoniemusik aus dem ZH - Oberland. Unterhaltungsmusik ist die Leidenschaft unserer gut 30 Musikantinnen und Musikanten aller Altersstufen. Wir unterhalten unser Publikum mit musikalischen Leckerbissen verschiedenster Genres und scheuen uns auch nicht, unkonventionelle Gastkünstler zu Konzerten einzuladen.',
    },
    {
      id: 95,
      identifier: 'harmonie-pfaeffikon',
      name: 'Harmonie Pfäffikon',
      logoImgId: 'fc28f45d-99c5-493b-9b97-906dd5110c00',
      bildImgId: 'fb4c3515-bbbb-483c-b13c-af8173d7ff00',
      homepage: 'https://www.harmonie-pfaeffikon.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Harmonie Pfäffikon ist 3. Klass-Verein in Harmoniebesetzung und zählt 30 junge und junggebliebene Mitglieder. Seit Mitte Mai 2023 wird die Harmonie Pfäffikon von Marco Liechti dirigiert. Das Repertoire reicht von traditioneller Blasmusik über bunt gemischte Unterhaltungsmusik bis hin zur klassischen Musik. Die musikalischen Schwerpunkte im Vereinsjahr bilden das Frühlingskonzert im April und das Kirchenkonzert im November. Der Musigplausch, das Muttertagskonzert, die Fiirabigkonzerte und der Musikantensonntag sind weitere von der Harmonie organisierte Anlässe. Zusätzlich ist die Harmonie an zahlreichen Anlässen von der Gemeinde, der Kirchgemeinde sowie von Pfäffiker- oder anderen Vereinen zu hören. ',
    },
    {
      id: 27,
      identifier: 'harmonie-wetzikon',
      name: 'Harmonie Wetzikon',
      logoImgId: '7bbad14d-427b-43a1-1f00-314c7f2c0700',
      bildImgId: '1a48cb98-e56c-478b-6fb9-45e729a5d100',
      homepage: 'https://www.harmonie-wetzikon.ch',
      facebook: 'https://www.facebook.com/harmoniewetzikon',
      instagram: 'https://www.instagram.com/harmoniewetzikon',
      websiteText:
        'Die "Harmonie Wetzikon" ist ein Verein mit einer beeindruckenden Geschichte. Im Jahr 1875 gegründet, ist sie seitdem ein fester Bestandteil der musikalischen Kultur in Wetzikon. Mit rund 45 engagierten Mitgliedern zeigt sich die Harmonie als starke und vielfältige Musikgemeinschaft.\nWas die Harmonie Wetzikon besonders auszeichnet, ist ihr breit gefächertes musikalisches Repertoire. Von der klassischen konzertanten Blasmusik bis hin zu modernsten Unterhaltungsshows beherrscht der Verein eine enorme Diversität an musikalischen Genres. Die Mitglieder sind stolz darauf, ein breites Spektrum an musikalischen Erlebnissen bieten zu können, das für jeden Geschmack etwas bereithält. Ob bei den Hauptkonzerten, lokalen Veranstaltungen oder bei Platzkonzerten, die Harmonie Wetzikon weiss das Publikum zu begeistern und in eine Welt der Klänge und Emotionen zu entführen. Bei der Darbietung von Unterhaltungsmusik blickt die Harmonie Wetzikon auf rund zehn spezielle Jahre zurück, in welchen sie sich getreu nach dem Motto «GANZ ANDERSCH» zu einer modernen Unterhaltungs-Band entwickelt hat. So werden regelmässig Konzerte mit Gastkünstlern und jeder Menge Unterhaltungstechnik durchgeführt.\nTrotz ihrer langen Tradition ist die Harmonie Wetzikon stets offen für neue Ideen und Innovationen. Der Verein bietet jungen Talenten die Möglichkeit, ihre musikalischen Fähigkeiten weiterzuentwickeln und Teil einer lebendigen musikalischen Gemeinschaft zu sein. Lassen Sie sich überzeugen und geniessen Sie modernste Blasmusik.\n',
    },
    {
      id: 110,
      identifier: 'harmonie-zumikon',
      name: 'Harmonie Zumikon',
      logoImgId: '2bffb8d6-a146-4343-31c8-6fc2b42dc000',
      bildImgId: 'ac650a53-6186-4d20-2752-3d8b8df85200',
      homepage: 'https://harmonie-zumikon.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind ein Verein mit motivierten Musikantinnen und Musikanten.\nUnsere Hauptziele sind das gemeinsame Musizieren und die Höhepunkte im Musikjahr: das Jahreskonzert im Frühsommer, das Jubilarenkonzert im Oktober, sowie das Adventskonzert vor Weihnachten in der Kirche.\nNatürlich engagieren wir uns darüber hinaus überall dort, wo in Zumikon etwas läuft - oder zum Laufen gebracht werden soll.\nUnsere Konzerte und Auftritte sollen einem breiten Publikum einen abwechslungsreichen und gehörfälligen Musikgenuss bieten - dann macht es auch uns Spass!',
    },
    {
      id: 36,
      identifier: 'jugendmusik-bezirk-affoltern',
      name: 'Jugendmusik Bezirk Affoltern',
      logoImgId: null,
      bildImgId: '71eb68aa-dfee-417a-32cf-1a160422f300',
      homepage: 'https://www.jumba.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Jumba wurde im Jahre 1967 durch die Musikvereine im Amt gegründet. Im Jahre 2020 wurde eine Partnerschaft mit der Musikschule Knonaueramt aufgenommen, so werden die jungen Musikschüler und Schülerinnen vom Instumentalunterricht über 2 Ensemble bis zur Jumba geführt. Mit dieser Lösung soll der Nachwuchs langfristig gesichert werden.',
    },
    {
      id: 106,
      identifier: 'kreismusik-limmattal',
      name: 'Kreismusik Limmattal',
      logoImgId: '869fefe3-ff74-471e-1405-b39721f8b500',
      bildImgId: '6a5e181b-421c-4717-4756-e29383aa7f00',
      homepage: 'https://kmlimmattal.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind im rechten Limmattal zuhause und spielen Unterhaltungsmusik für die Bevölkerung.\n\nDas Bläserkorps probt Mittwochs von 20:00 bis 22:00 im Vereinssaal im Zentrum Oberengstringen. Besuchen Sie uns in einer Probe und wecken Sie Ihr musikalisches Talent!\n\nDie Tambourengruppe (Erwachsene) probt Mittwochs von 19:00 - 21:00 Uhr im Schulhaus Kalktarren Schlieren, die Jungtambouren proben Dienstags/Mittwochs/Donnerstags in kleinen Gruppen. Kinder und Erwachsene sind jederzeit willkommen vorbeizuschauen!',
    },
    {
      id: 24,
      identifier: 'musikgesellschaft-andelfingen',
      name: 'Musikgesellschaft Andelfingen',
      logoImgId: '7d303e0c-e7ea-4651-f49e-e78cdeb65200',
      bildImgId: '4161350d-019c-4d90-9df9-cd29f692c900',
      homepage: 'https://www.mgandelfingen.ch',
      facebook: null,
      instagram: null,
      websiteText:
        '\nwww.mgandelfingen.ch\nMG Andelfingen | Facebook\nMusikgesellschaft Andelfingen (@mgandelfingen) • Instagram-Fotos und -Videos\n\n\nDie Musikgesellschaft Andelfingen ist ein Verein mit 34 motivierten Musikantinnen und Musikanten, die durch die Liebe zur Blasmusik miteinander verbunden sind. Unsere Leidenschaft für die Musik schafft eine einzigartige Verbindung zwischen den Mitgliedern. Wir teilen nicht nur Noten, sondern auch Emotionen, Ziele und Erinnerungen. \nWir proben engagiert und fleissig um unsere musikalischen Fähigkeiten zu verbessern und als Ensemble zu wachsen. \nAuf unsere Erfolge bei Wettbewerben und die vielen positiven Rückmeldungen unseres Publikums sind wir stolz. Auftritte sind Chancen unsere Freude zu teilen.\nWir spielen in Harmoniebesetzung und sind glücklich darüber, dass wir eine solide Besetzung haben, die es uns ermöglicht, konstante musikalische Leistungen zu erbringen. Selbstverständlich träumen wir von der Erweiterung unserer Register und würden uns über Zuwachs freuen. Mit viel Engagement und Durchhaltewillen ist es uns glücklicherweise in den letzten Jahren gelungen, unsere Nachwuchsförderung solide zu gestalten und junge Talente zu fördern. \nHilfsbereitschaft, Teamwork und Pünktlichkeit sind weitere Grundpfeiler unserer Gemeinschaft. Wir unterstützen uns gegenseitig und achten darauf, dass jede und jeder seinen Platz im Orchester findet. Gemeinsam geniessen wir auch das gesellige Zusammensein an Vereinsabenden, Ausflügen und Feiern. Es sind auch Freundschaften, die über die Bühne hinausgehen. \nWenn wir unsere Instrumente in die Hand nehmen, entstehen Klänge, die uns und hoffentlich alle unsere Zuhörerinnen und Zuhörer im Herzen berühren, inspirieren und verbinden. \n',
    },
    {
      id: 38,
      identifier: 'musikgesellschaft-faellanden',
      name: 'Musikgesellschaft Fällanden',
      logoImgId: 'd9e920a9-845e-439e-8f22-3f9e1df37000',
      bildImgId: 'f3e98277-78fc-4060-41fc-94a0cfceec00',
      homepage: 'https://mgfaellanden.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Uns gibt es schon seit über 110 Jahren. 1907 wurde die Musikgesellschaft Fällanden gegründet – und sie hat seither einiges erlebt. Als konfessionell und politisch unabhängiger Musikverein spielen wir sowohl aktuelle wie auch traditionelle Blasmusik. Neben dem Erreichen der musikalischen Zielsetzung ist uns auch der gesellschaftliche Kontakt untereinander wichtig.',
    },
    {
      id: 30,
      identifier: 'musikgesellschaft-fehraltorf',
      name: 'Musikgesellschaft Fehraltorf',
      logoImgId: '0be6f7bb-057b-4620-d3d8-543956726d00',
      bildImgId: 'e86e8d51-aede-4772-0e2a-93c13cb47b00',
      homepage: 'https://mg-fehraltorf.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Musikgesellschaft Fehraltorf ist seit ihrer Gründung im Jahre 1892 ein Blasorchester in Harmoniebesetzung, in welchem Holz- und Blechblasinstrumente gleichermaßen vertreten sind. Das Orchester umfasst ca. 35-40 Aktivmitglieder, die zwischen 16 und 65 Jahre alt sind.\n\nUnser vielseitiges Repertoire, welches von moderner Unterhaltungsmusik (Film, Musical, Swing, Rock, Pop etc.) über konzertante Klassik bis hin zur traditionellen Blasmusik reicht, begeistert nebst unserem Publikum vor allem auch unsere große Zahl von jungen Musikantinnen und Musikanten.\n\nWir treffen uns wöchentlich am Donnerstagabend zur Probe und falls notwendig, vor anspruchsvollen Auftritten, auch zu Gesamt- oder Registerproben am Montag - stets bestrebt, unser musikalisches Niveau innerhalb der zweiten Stärkeklasse Harmonie weiter zu steigern. Wir beteiligen uns u. a. an Gemeindeanlässen, geben Quartierständchen im Dorf und nehmen regelmäßig an musikalischen Wettspielen wie kantonale oder eidgenössische Musikfeste oder an Kreismusiktagen teil. Als Höhepunkt jedes Jahres findet jeweils am letzten Wochenende im Januar unsere Abendunterhaltung in der Mehrzweckhalle Heiget statt. Das inzwischen zur Tradition gewordene Konzert in der Kirche, welches ca. jedes zweite Jahr im Herbst aufgeführt wird, ist ebenfalls kaum mehr aus unserem Spielprogramm wegzudenken. Selbstverständlich kommt dabei die Kameradschaft nicht zu kurz: Sommernachtsfeste, Minigolf- oder Kegelabende, Go-Kart Rennen, Skitage oder Musikreisen sind nur einige der Aktivitäten, die wir dank der ausgezeichneten Stimmung im Verein immer wieder miteinander unternehmen.',
    },
    {
      id: 53,
      identifier: 'musikgesellschaft-glattfelden',
      name: 'Musikgesellschaft Glattfelden',
      logoImgId: '5bdcef6a-5fe1-4546-51bd-c095a4172b00',
      bildImgId: 'cce0b539-c89f-4b9e-e5c2-7ee806189b00',
      homepage: 'https://musik-glattfelden.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir, die Musikgesellschaft Glattfelden, sind ein über 100 Jahre alter Traditionsverein. Derzeit bestehen wir aus 28 aktiven MitgliederInnen. Über das ganze Jahr verteilt finden diverse Akti-vitäten statt. Wir spielen an öffentlichen Anlässen in Glattfelden und Umgebung, gestalten eigene Unterhaltungskonzerte und nehmen regelmässig an Musiktagen teil.\nBeim Musizieren steht die Freude am Zusammenspiel, Teamgeist und das Abtauchen in eine andere Welt an erster Stelle. Das wollen wir MusikantInnen nicht nur selber erleben, sondern auch unserer Jugend vermitteln. Wir bieten Kindern die Möglichkeit, Blasinstrumente und Schlagwerke kennen zu lernen und in Zusammenarbeit mit der Musikschule Zürcher Unterland ein Instrument zu erlernen. Wir freuen uns sehr über jedes Kind, welches diese sinnvolle Frei-zeitbeschäftigung wählt und so bald als möglich bei uns im Verein mitspielen kann! Zurzeit zählt unsere Junior-Rock-Band 10 Mitglieder im Alter zwischen 10 und 15 Jahren.\nWir möchten generationenübergreifend die Freude am Musizieren vermitteln und fördern. In unserer offenen, kameradschaftlichen Vereinskultur ist uns jedes Mitglied wichtig.\n',
    },
    {
      id: 48,
      identifier: 'musikgesellschaft-haeggenschwil',
      name: 'Musikgesellschaft Häggenschwil',
      logoImgId: '233ddb4a-6f04-4edd-d311-279b53e14a00',
      bildImgId: 'bfde1c4b-bb67-43d7-656a-2a1e27777100',
      homepage: 'https://mg-haeggenschwil.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Musikgesellschaft Häggenschwil ist ein dynamischer Verein, der sich gerne von neuen und kreativen Ideen begeistern lässt und offen für Neues ist. Unsere Musig-Show mit diversen läuferischen Einlagen auf der Bühne ist bereits zur Tradition geworden. Wir verbringen aber auch gerne gemütliche Stunden miteinander, was unseren Zusammenhalt ebenso stärkt.',
    },
    {
      id: 58,
      identifier: 'musikgesellschaft-harmonie-turbenthal',
      name: 'Musikgesellschaft Harmonie Turbenthal',
      logoImgId: '8b82e30a-4d49-4981-af7d-e0c0d76e2200',
      bildImgId: '73cab507-4cc6-44ec-0445-b8c8a89c3800',
      homepage: 'https://www.mght.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind ein bunt gemischter Dorfverein, dem es am Herzen liegt, gemeinsam zu musizieren und dabei Spass zu haben. Wir sind auch gewillt, uns neuen Herausforderungen zu stellen und wollen uns musikalisch weiterentwickeln.',
    },
    {
      id: 57,
      identifier: 'musikgesellschaft-niederhasli',
      name: 'Musikgesellschaft Niederhasli',
      logoImgId: 'cb2cfe8c-38c0-4576-968f-3fcd40e02a00',
      bildImgId: 'ae587a82-7d12-436c-ad34-31d123952800',
      homepage: 'https://mgniederhasli.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Musikgesellschaft Niederhasli gibt es schon seit über 100 Jahren, gegründet wurde sie im Jahr 1913. Wir sind ein junger\nund engagierter, im Dorf sehr gut verankerter, Verein. Wir widmen uns vor allem der modernen Unterhaltungsmusik sowie der\nklassischen Blasorchesterliteratur. Und natürlich kommt bei uns auch das Vereinsleben nicht\nzu kurz. ',
    },
    {
      id: 98,
      identifier: 'musikgesellschaft-rafz',
      name: 'Musikgesellschaft Rafz',
      logoImgId: 'e98c3f25-51e7-43d4-729c-d66ee824fe00',
      bildImgId: 'f1b9ba28-8e2f-439a-85cc-aa5415dbdf00',
      homepage: 'https://www.mg-rafz.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der 1917 gegründete Verein zählt immer gute 35 Aktivmitglieder.\n \nDer Verein hat eine gute Mischung von "Alt und Jung".\n \nWir spielen in der 3. Stärkeklasse, Harmonie.\n \nUnser Repetoir hat Stücke von leichter klassischer Musik über traditionelle Märsche bis zur modernen Unterhaltungsmusik.\n \nEine Hautpaufgabe ist das Umrahmen von Dorfanlässen. Wir spielen zu goldenen und diamantenen Hochzeiten, sowie bei 80, 90 und ab 95 Jahren jährlich unseren Mitbürgern.\n \nDer Verein fördert auch das kameradschaftliche Miteinander und unternimmt dazu Vereinsreisen oder andere Freizeitaktivitäten.',
    },
    {
      id: 102,
      identifier: 'musikgesellschaft-seuzach',
      name: 'Musikgesellschaft Seuzach',
      logoImgId: 'd504aad3-0e99-479c-a69b-f01130389400',
      bildImgId: 'ab5e94ed-f0d2-41ff-0c07-4d3f2e7d0000',
      homepage: 'https://www.mgseuzach.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Anfang März 1897 fanden sich gleichgesinnte Musikfreunde zusammen und gründeten die Musikgesellschaft Seuzach. Unser Verein zählt rund 40 Aktivmitglieder und besteht aus dem Musikkorps, dem Drumkorps und unserem Nachwuchs. Unser Leitsatz seit der Gründung des Vereins heisst: "Sich selber und anderen Menschen mit Musik Freude bereiten".',
    },
    {
      id: 79,
      identifier: 'musikverein-baeretswil',
      name: 'Musikverein Bäretswil',
      logoImgId: '378b7532-006f-4033-2687-2220fdb85f00',
      bildImgId: '36abcce6-a465-45f9-a025-8c72934df300',
      homepage: 'https://www.mvbaeretswil.ch',
      facebook: 'https://www.facebook.com/mvbaeretswil',
      instagram: null,
      websiteText:
        'Gegründet wurde der Musikverein Bäretswil 1935, damals noch unter dem Namen "Musikgesellschaft Adetswil". Wir spielen heute in Harmoniebesetzung in der 4. Klasse und bestehen aus 17 Mitgliedern. Die Pflege des kulturellen Lebens in unserem Dorf liegt uns dabei besonders am Herzen. Unser Probetag ist der Donnerstag. ',
    },
    {
      id: 93,
      identifier: 'musikverein-bonstetten',
      name: 'Musikverein Bonstetten',
      logoImgId: '22ee5593-c18c-4047-7193-e03eca56ca00',
      bildImgId: 'bc859fd8-cbb0-4b95-b7e7-26547b0ea000',
      homepage: 'https://www.mv-bonstetten.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Bonstetten wurde im Jahr 1888 gegründet, im 2013 durften wir unser 125-jähriges Bestehen feiern. Unter der Leitung von Rhea Paschen spielen 29 motivierte Aktivmitglieder im Verein mit. Wir treffen uns wöchentlich am Mittwochabend im Gemeindesaal Bonstetten zur Probe. In unserem Repertoire findet man klassische Konzertstücke, Märsche, Polkas und Evergreens - aber auch moderne, poppige Stücke sind vorhanden.\n\nUnsere Zuhörer erfreuen wir das ganze Jahr hindurch bei Auftritten im Dorf, ob an verschiedenen kirchlichen Anlässen oder der 1.Augustfeier  - es gibt immer eine guten Grund, Musik zu machen.\n\nAls Höhepunkt findet das traditionelle Jahreskonzert im März statt:\n\nBei bis anhin immer vollem Haus spielen wir am Samstagabend mit Nachtessen, Tombola und Bar und am Sonntagnachmittag bei Kaffee und selbstgemachtem Kuchen.\n\nAuch die Geselligkeit kommt bei uns nicht zu kurz: Beim gemütlichen Zusammensein nach der Probe, dem Grillabend oder der Musikreise\n\nVielleicht wohnen Sie in der Nähe, spielen ein Blas- oder Schlaginstrument, dann zögern Sie nicht, schauen Sie vorbei, wir würden uns freuen !',
    },
    {
      id: 103,
      identifier: 'musikverein-brass-band-henggart',
      name: 'Musikverein Brass Band Henggart',
      logoImgId: '99af1fc4-b5b5-4288-1ef1-fdb60adbc600',
      bildImgId: '55f46e6f-315b-4c22-6ec4-368fe2bc4700',
      homepage: 'https://www.mvbbh.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Brass Band Henggart spielt in der 2. Stärkeklasse und ist im schönen zürcher Weinland daheim. Wir begeistern unser Publikum mit einem zeitgemässen Repertoire an unseren Unterhaltungskonzeren im Januar oder an unserer sommerlichen Serenade. Weiter nehmen wir auch regelmässig an Wettbewerben teil.',
    },
    {
      id: 77,
      identifier: 'musikverein-buchs-zh',
      name: 'Musikverein Buchs ZH',
      logoImgId: '1258bfc5-fd8c-4f23-9a85-186648899c00',
      bildImgId: '6dc06fdc-9842-4256-8e78-11e7b7058700',
      homepage: 'https://mvbuchs.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind ein kleiner, aber motivierter Verein aus dem Zürcher Furttal mit zurzeit 27 Mitgliedern und spielen in der 3. Stärkeklasse.\nWir haben ein breites Konzertrepertoire, mit welchem wir immer wieder unser Publikum überraschen und begeistern können.\nUnser Verein ist offen für Jung bis Alt, von Klein bis Gross - also alle, die Freude haben in einem tollen Verein zu musizieren und auch das Gesellschaftliche zu pflegen.',
    },
    {
      id: 50,
      identifier: 'musikverein-dietlikon',
      name: 'Musikverein Dietlikon',
      logoImgId: '002352a8-9312-4d14-f512-942a2ade0400',
      bildImgId: '0d349708-65f9-482a-ac4d-f505c91b3600',
      homepage: 'https://www.mvd.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der 1970 gegründete Musikverein Dietlikon ist eine Gruppe von mittlerweile über 50 Musikbegeisterten aus Dietlikon und Umgebung. Wir haben nicht nur die grossen Konzerte, das Sommerkonzert oder Frühlingskonzert. und die beiden Jahreskonzerte, im Blick, sondern auch das gediegene und friedliche Zusammenleben im Verein.  ',
    },
    {
      id: 29,
      identifier: 'musikverein-eintracht-wallisellen',
      name: 'Musikverein Eintracht Wallisellen',
      logoImgId: '2c95999a-86a4-41a5-bf39-9281f6007300',
      bildImgId: 'a9f53bb8-d383-448a-de4c-efd74cf57700',
      homepage: 'https://www.musik-wallisellen.ch',
      facebook: null,
      instagram: null,
      websiteText: 'www.musik-wallisellen.ch',
    },
    {
      id: 75,
      identifier: 'musikverein-gossau-zh',
      name: 'Musikverein Gossau ZH',
      logoImgId: '88ed499c-9f65-4624-fc28-11de7e77f400',
      bildImgId: '1e8be700-d98a-4b64-d0e7-06ba0d284800',
      homepage: 'http://www.mv-gossau.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Gossau ist ein typischer Dorfverein, der im kulturellen Leben der Gemeinde Gossau einen wichtigen Platz einnimmt. Unser musikalisches Spektrum reicht von Märschen und Polkas über Unterhaltungsmusik bis zu klassischen Kompositionen und Originalblasmusik.',
    },
    {
      id: 70,
      identifier: 'musikverein-grueningen',
      name: 'Musikverein Grüningen',
      logoImgId: '4a6a9670-b536-41c6-86d2-b09e9c48b000',
      bildImgId: 'f9fcaebb-037c-4f7e-e72d-836de7aa6e00',
      homepage: 'https://www.mvgrueningen.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Herzlich willkommen beim Musikverein Grüningen im Zürcher Oberland.\n \nWir spielen in der 3. Klasse Harmoniebesetzung und treffen uns jeden Mittwochabend von 20.00 Uhr bis 22.00 Uhr im Werkhof Grüningen zu unseren Gesamtproben. Unser Repertoire umfasst die ganze Palette der heutigen Blasmusik. Diese reicht von konzertanter bis hin zur modernen Unterhaltungsliteratur. Fehlen dürfen jedoch auch die traditionellen Märsche, Polkas und Walzer nicht.',
    },
    {
      id: 81,
      identifier: 'musikverein-harmonie-adliswil',
      name: 'Musikverein Harmonie Adliswil',
      logoImgId: '5fd2817d-2d40-47e2-95ac-715a206d0200',
      bildImgId: 'f4099c42-3afe-4e38-bec1-d4ad1c6cf300',
      homepage: 'https://www.harmonie-adliswil.ch',
      facebook: 'https://www.facebook.com/mvhadliswil',
      instagram: 'https://www.instagram.com/mvhadliswil/',
      websiteText:
        'Obwohl wir den Jahrgang 1891 haben, spielen wir keineswegs nur altbewährte Blasmusik, sondern fühlen uns fast wohler in der modernen Unterhaltungsmusik. Neben unserer alljährlichen Abendunterhaltung im Februar spielen wir jeweils im April als Zunftmusik der Schmiden am Sechseläuten mit oder unterhalten die Menschen in und um Adliswil.',
    },
    {
      id: 32,
      identifier: 'musikverein-harmonie-affoltern-am-albis',
      name: 'Musikverein Harmonie Affoltern am Albis',
      logoImgId: '8065e576-8de1-4a92-6e4a-4dc4be557d00',
      bildImgId: 'd149d391-4553-4615-ff22-094ae785df00',
      homepage: 'https://www.harmonie-affoltern.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Harmonie Affoltern a/A ist eine gesellige Gruppe von Frauen und Männern, die eine gemeinsame Leidenschaft haben: Sie musizieren alle unheimlich gerne. \n1920 wurde die Harmonie Affoltern a/A gegründet. Zurzeit treffen sich ca. 40 junge und jung gebliebene Mitglieder jeden Dienstag zur Probe. Die Harmonie nimmt auch gerne an Musikfesten teil. Zu den jährlichen musikalischen Höhepunkten zählen das Frühlingskonzert sowie auch die Jahreskonzerte im November. Auch das gemütliche Beisammensein (Skitag, Grillabend, Familientag, Musikreise, Jahresschlusshöck, etc.) darf nicht fehlen.\n\nDie Harmonie Affoltern a/A freut sich auf das Zürcher Kantonalmusikfest in Urdorf + Schlieren und bedankt sich ganz herzlich für die Gastfreundschaft!',
    },
    {
      id: 78,
      identifier: 'musikverein-harmonie-altstetten',
      name: 'Musikverein Harmonie Altstetten',
      logoImgId: null,
      bildImgId: '933a79c4-d1e1-445d-f400-46d5cde9c600',
      homepage: 'https://www.mha.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Verein mit seinen bald 125 Jahren Vereinsgeschichte weist gut 50 Mitglieder auf. Fixpunkte im Jahresprogramm sind das Frühlingskonzert im Mai mit eher populärer Ausrichtung und die Kirchenkonzerte im Advent, bei denen symphonisch-konzertante Werke zur Aufführung gelangen. Daneben tritt der Verein am Sechseläuten sowie an Sommer- und Platzkonzerten in der Innenstadt und im Quartier auf.',
    },
    {
      id: 67,
      identifier: 'musikverein-harmonie-bauma',
      name: 'Musikverein Harmonie Bauma',
      logoImgId: '4de6c50e-1c0e-41e9-1404-76bba6cb3700',
      bildImgId: 'b1e67385-b4f6-4f1a-fd35-c0b22fe3b700',
      homepage: 'http://www.harmoniebauma.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind ein aktiver Verein mit ca. 20 Mitgliedern und spielen in der 3. Stärkeklasse. Wir proben 1x pro Woche am Donnerstag. Gemeinsam zu Musizieren, die Gesellschaft und den Zuhörer*Innen mit Musik Freude zu verbreiten, steht an oberster Stelle.  ',
    },
    {
      id: 25,
      identifier: 'musikverein-harmonie-birmensdorf',
      name: 'Musikverein Harmonie Birmensdorf',
      logoImgId: '68114baf-a26c-4b46-f04b-7e256ebb4c00',
      bildImgId: 'ac903a33-a6a5-426a-f2e7-a2ec9c84ce00',
      homepage: 'https://mhbirmensdorf.ch',
      facebook: 'https://www.facebook.com/profile.php?id=100063672812286',
      instagram: null,
      websiteText:
        'Der Musikverein Harmonie Birmensdorf wurde bereits im Jahr 1904 gegründet. Trotz seines hohen Alters strahlt er mit seinen gut 40 Aktivmitgliedern in jugendlicher Frische. \nWir sind ein Dorfverein, welcher die Gemeinden Birmensdorf, Aesch und Uitikon an diversen Auftritten repräsentiert. So sind uns Ständli im Dorf genauso wichtig wie die Teilnahme an Musikfesten.\n\nJeweils am letzten Novembersamstag und am ersten Dezembersamstag finden unsere traditionellen Jahreskonzerte statt. Wir bieten ein abwechslungsreiches Programm mit Unterhaltungsmusik vom Marsch über Dixie, Pop, Rock bis zu Klassik, Musicals und Filmmusik.\n\nDas alljährlich Kirchenkonzert in der reformierten Kirche in Birmensdorf fordert uns in klassischer und konzertanter Blasmusikliteratur.\n\nAls Zunftspiel der Zunft zur Meisen sind wir schon viele Jahre am traditionsreichen Zürcher Sechseläuten mitten in der Innenstadt mit dabei.\n\nWir wagen uns immer wieder an spezielle Musikprojekte wie zum Beispiel das Konzert mit den vereinigten Chören von Birmensdorf oder das Gemeinschaftskonzert mit dem Musikverein Harmonie Wollishofen.\n\nAuch die Geselligkeit kommt bei uns nicht zu kurz. Wir legen viel Wert auf gute Kameradschaft und eine gesellige Vereinskultur.\n\nWir proben jeweils am Montag im Gemeindezentrum Brüelmatt von 20:00-22:00 Uhr (Zusatzproben sind am Donnerstag) und freuen uns über jeden Besuch.\n',
    },
    {
      id: 22,
      identifier: 'musikverein-harmonie-hausen-am-albis',
      name: 'Musikverein Harmonie Hausen am Albis',
      logoImgId: 'f3bc8548-e124-4e76-101d-3d3b46439400',
      bildImgId: '3cd422a5-a893-4c58-f7c5-3fa0bc618f00',
      homepage: 'https://mvhausen.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Harmonie Hausen am Albis wurde am 18. Juli 1894 gegründet und ist somit schon über 125 Jahre alt. Zurzeit zählt unser Verein ca. 50 Aktivmitglieder zwischen 20 und 80 Jahren. So verschieden unsere Mitglieder sind, so vielseitig ist auch unser musikalisches Repertoire. Es reicht von Klassik über Märsche bis hin zu Musical-, Film- und Popmusik. Neben der musikalischen Weiterentwicklung und neuen musikalischen Projekten und Herausforderungen wird auch die Kameradschaft sehr gross geschrieben. Weitere Informationen finden Sie auf unserer Homepage unter www.mvhausen.ch.',
    },
    {
      id: 89,
      identifier: 'musikverein-harmonie-thalwil',
      name: 'Musikverein Harmonie Thalwil',
      logoImgId: null,
      bildImgId: '543c099b-cdc0-4217-76af-f53c50df0f00',
      homepage: 'https://www.harmonie-thalwil.ch',
      facebook: 'https://www.facebook.com/harmoniethalwil',
      instagram: null,
      websiteText:
        'Der Musikverein Harmonie Thalwil ist die Adresse für Blasmusik in Thalwil. Mit gegenwärtig etwa 30 Aktivmitgliedern führen wir zweimal jährlich ein grösseres Konzertprogramm durch, die Abendunterhaltung im Mai sowie das konzertante Blasmusikkonzert im Dezember. Das musikalische Jahresprogramm ergänzt sich durch Auftritte an Anlässen der Gemeinde sowie durch kleinere Konzerte in Quartieren des Dorfes und auswärts.\n\nNeben all der Musik darf natürlich das Gesellschaftliche nicht zu kurz kommen. Angefangen beim gemütlichen Zusammensein nach der Probe in der Beiz über Ausflüge, Samichlausabend hin zu Musikreise und Skiweekend gibt es Anlässe, an denen wir Mitglieder und nicht die Musiknoten im Mittelpunkt stehen.',
    },
    {
      id: 97,
      identifier: 'musikverein-harmonie-waedenswil',
      name: 'Musikverein Harmonie Wädenswil',
      logoImgId: 'b7747d47-a48e-4c67-697d-df9e05f09200',
      bildImgId: 'fee6e586-708f-4319-3ed9-888e01605a00',
      homepage: 'http://www.harmonie-waedenswil.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Harmonie Wädenswil wurde 1883 aus einer Initiative des Männergesangvereins heraus gegründet. Heute umfasst das Orchester ca. 55 MusikerInnen aller Altersklassen. Als Stadtmusik der grössten Gemeinde am Zürichsee sind wir fester Bestandteil des kulturellen Lebens in Wädenswil. Darüber hinaus sind wir mit Stolz seit über 50 Jahren die Zunftmusik der "Zunft zu den drei Königen" aus Zürich.',
    },
    {
      id: 64,
      identifier: 'musikverein-harmonie-zuerich-oberstrass',
      name: 'Musikverein Harmonie Zürich-Oberstrass',
      logoImgId: 'd9f16fd2-3395-43cf-1f9a-e63c75e09200',
      bildImgId: 'a62bffbf-92b7-46c9-92e9-115eda7e2800',
      homepage: 'https://www.mhz-oberstrass.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind ein im Zürcher Oberstrass Quartier beheimateter Musikverein, welcher auf eine 124 jährige Geschichte zurückblicken kann. Nebst traditioneller Blasmusik, findet sich in unserem Repertoire vor allem zeitgemässe Unterhaltungsmusik. So erfreuen wir unser Publikum an unserem Unterhaltungskonzert, unserem Konzert in der Kirche oder Sommerkonzerten in und ausserhalb von unserem Quartier mit Rock-, Filmmusik bis hin zu modernen Pop Songs. \n',
    },
    {
      id: 21,
      identifier: 'musikverein-harmonie-zuerich-schwamendingen',
      name: 'Musikverein Harmonie Zürich Schwamendingen',
      logoImgId: '9a60f7af-fc0e-4a27-d4cd-6f2ed6d81300',
      bildImgId: '60f9cc22-a346-4edb-d915-770b24effd00',
      homepage: 'https://www.mvschwamendingen.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der MVS ist ein lebhafter und engagierter Verein im Quartier Schwamendingen mit rund 30 Musizierenden.\nWir heissen Neulinge und Wiedereinsteigende genauso herzlich willkommen wie Fortgeschrittene. Mit offenen Armen empfangen wir alle Interessierten und sind stets auf der Suche nach musikalischer Verstärkung. Egal welches Niveau alle haben die Möglichkeit, sich dem Verein anzuschliessen und gemeinsam mit Gleichgesinnten Musik zu machen. Die Gemeinschaft steht im Mittelpunkt, und alle tragen zum klangvollen Zusammenspiel bei.\nWir proben jeden Mittwoch und begeistern an unseren Konzerten mit Stücken der 4. Stärkeklasse aus einem breiten Spektrum an musikalischen Genres. Darüber hinaus ist der Verein stolz darauf, als Zunftmusik der Zunft Schwamendingen jedes Jahr beim Zürcher Sechseläuten mitzulaufen.\nWir danken für die Organisation und freuen uns auf das kantonale Musikfest.\n',
    },
    {
      id: 41,
      identifier: 'musikverein-hedingen',
      name: 'Musikverein Hedingen',
      logoImgId: '77c92194-8d34-46a0-4c96-b1f729775600',
      bildImgId: 'ebcfe3ae-07e0-4551-bb34-0e3213908000',
      homepage: 'https://mv-hedingen.jimdofree.com',
      facebook: null,
      instagram: null,
      websiteText:
        'Der 1937 gegründete Musikverein Hedingen ist ein Harmonie-Blasorchester und umfasst heute etwa 30 Musikerinnen und Musiker.\n\nSeither fördert der Verein das Musizieren als aktive Freizeitgestaltung und kulturelle Betätigung. Er gestaltet aktiv das Dorfleben mit, indem er jährlich verschiedene Konzerte organisiert oder an anderen Anlässen im Dorf teilnimmt. In unserem Repertoire finden sich fast alle Stilrichtungen, von der klassischen Musik über traditionelle Märsche bis zu moderner Unterhaltungsmusik.\n\nMit Freude und Spass wollen wir Musik für uns und unser Publikum machen. Der Schwierigkeitsgrad der Musikstücke wird unseren Fähigkeiten und unseren Möglichkeiten angepasst und bewegt sich zwischen der 2. und der 3. Stärkeklasse. Einmal im Jahr spielen wir ein zweiteiliges grosses Konzert. Dieses beinhaltet einen konzertanten Teil sowie einen Teil mit Unterhaltungsmusik. Mit unterhaltsamer und zielgerichteter Literatur wollen wir die Herzen des Publikums gewinnen.',
    },
    {
      id: 55,
      identifier: 'musikverein-helvetia-marthalen',
      name: 'Musikverein Helvetia Marthalen',
      logoImgId: '1111f051-b0a2-4789-4062-b0090fa99700',
      bildImgId: 'd8796110-0ac2-4271-bb3f-8be11ebcfc00',
      homepage: 'https://www.musikverein-marthalen.ch',
      facebook: 'https://www.facebook.com/MusikvereinHelvetiaMarthalen',
      instagram: 'https://instagram.com/musikverein_marthalen?igshid=MXNkeHI1aXBiOXVudg%3D%3D&utm_source=qr',
      websiteText:
        '\nWillkommen in Marthalen, dem Dorf mit einem intakten Vereinsleben. Unser Verein ist Teil der Vielfalt und trägt aktiv und mit Freude zu einem lebendigen Dorf bei. Wir sind in Marthalen und der näheren Umgebung bestens verankert und mit diversen Anlässen das ganze Jahr unterwegs. Nähere Informationen findest du auf unserer Homepage.\n\nHaben wir dein Interesse als Zuhörer oder Musikant geweckt? Dann besuche uns am nächsten Anlass oder komme doch einfach bei der nächsten Probe am Dienstag vorbei.',
    },
    {
      id: 88,
      identifier: 'musikverein-kempttal',
      name: 'Musikverein Kempttal',
      logoImgId: '62792df7-089c-4c10-5f94-0750a81a3600',
      bildImgId: 'c72ff89e-39ca-46ad-c32a-4a73e58f4d00',
      homepage: 'https://www.mv-kempttal.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Gegründet wurde unser Verein 1897, damals noch unter dem Namen Musikgesellschaft Winterberg-Grafstal und als reine Blech-Formation. Stark geprägt von den Arbeitern der Firma Maggi in Kemptthal, nahm der Verein 1907 dann seinen jetzigen Namen an. Unter der Leitung von Stephan Burkhalter unterhält das 27 Mitglieder umfassende Orchester sein Publikum regelmässig am Frühlingskonzert, an der Abendunterhaltung und mit diversen Platzkonzerten in der Gemeinde Lindau.',
    },
    {
      id: 37,
      identifier: 'musikverein-langnau-am-albis',
      name: 'Musikverein Langnau am Albis',
      logoImgId: '0960619b-3726-47aa-57a3-fc5f5f369b00',
      bildImgId: '67d48d84-f624-4993-1574-70524258f100',
      homepage: 'https://www.musikverein-langnau.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der im Jahre 2009 gegründete Musikverein Langnau am Albis setzt sich mit Hingabe dafür ein, gute Musik zu pflegen und das öffentliche, kulturelle sowie gesellschaftliche Leben in Langnau am Albis zu bereichern. Durch regelmäßige Proben und öffentliche Auftritte tragen wir aktiv zum Dorfleben bei und hoffen, viele Menschen zu begeistern.\nUnser Repertoire ist vielfältig und umfasst sowohl Originalwerke für Blasorchester als auch zeitgenössische Arrangements. Wir möchten ein breites Publikum ansprechen und wagen uns gerne an verschiedene musikalische Stilrichtungen heran. \nBesonders wichtig ist uns die enge Zusammenarbeit mit der Jugendmusik Sihltal (ehemals Jugendspiel Langnau am Albis). Viele unserer Mitglieder haben bereits in der Jugendmusik Sihltal musiziert oder tun dies immer noch. Wir unterstützen mit Registerproben und helfen beim Jahreskonzert mit. \nWir freuen uns auf musikalische Stunden im Rahmen des ZKMF 2024 !',
    },
    {
      id: 52,
      identifier: 'musikverein-meilen',
      name: 'Musikverein Meilen',
      logoImgId: 'bb838ec7-5833-467c-fb4b-284c1bc78600',
      bildImgId: '6dd8b58b-05a8-4592-dede-32f176c5df00',
      homepage: 'https://www.mv-meilen.com',
      facebook: 'https://www.facebook.com/mvmeilen',
      instagram: 'https://instagram.com/mvmeilen',
      websiteText:
        'Der Musikverein Meilen ist ein dynamisches und modernes Blasorchester der 1. Stärkeklasse, welches sich aus einer guten Mischung aus jungen sowie erfahreneren Mitgliedern zusammensetzt. Aktuell dürfen wir auf rund 35 Mitglieder zählen, mit deren Puste wir unsere Musik an den verschiedensten Anlässen im Jahr präsentieren. Unser breites und anspruchsvolles Repertoire umfasst für die Jahreskonzerte Ende Januar ein eher sinfonisches Programm, sowohl mit Originalwerken für Blasorchester, wie auch mit Transkriptionen aus der klassischen Musik. Für die meisten Anlässe unter dem Jahr präsentieren wir ein breites Spektrum von bekannten Film- und Popklassikern über mitreissende Arrangements aus verschiedenen Volksmusikformen und traditionellen Blasmusikmärschen.',
    },
    {
      id: 51,
      identifier: 'musikverein-neerach',
      name: 'Musikverein Neerach',
      logoImgId: 'e3e17443-8cb3-4d55-3e47-a734206b7100',
      bildImgId: '6574eac4-f4b7-4a63-2b5d-8830cdd4aa00',
      homepage: 'https://www.mvneerach.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Neerach zählt aktuell 45 Aktivmitglieder und ein paar weitere Musikfreunde, die tatkräftig und regelmässig bei uns mitwirken. Von jung bis jung geblieben sind Frauen und Männer sehr ausgeglichen vertreten.\nUnser abwechslungsreiches Repertoire hat nicht nur für unser Publikum einiges zu bieten, sondern begeistert die Musikantinnen und Musikanten von 12 bis 73 Jahren gleichermassen. ',
    },
    {
      id: 69,
      identifier: 'musikverein-neftenbach',
      name: 'Musikverein Neftenbach',
      logoImgId: 'f1b1a155-1db7-4622-7e8d-e963970abd00',
      bildImgId: 'd1c2c1db-6b48-463d-82dd-63677a26b700',
      homepage: 'https://mv-neftenbach.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der MV Neftenbach existiert seit 1897 – ursprünglich unter dem Namen Musikgesellschaft «Alpenrösli» Neftenbach. Nach mehr als einem Jahrhundert Vereinsgeschichte sind wir etwa 40 Musikerinnen und Musiker vom Teenager bis zur Rentnerin, die vor allem eines verbindet. Die Liebe zur Musik.\n\nWir treffen uns jeweils Donnerstags (wenn nötig auch Dienstags) um 19:45 Uhr in der alten Turnhalle Drei Linden zur Probe und bestreiten das ganze Jahr hindurch grössere und kleinere Auftritte. Wir verstehen uns als typischen Dorfverein, haben aber den Anspruch, innerhalb der 3. Stärkeklasse Harmonie auf hohem Niveau zu spielen. Dementsprechend nehmen wir auch regelmässig an regionalen, kantonalen und eidgenössischen Musikfesten teil.\n\nDa nicht alle dieselben musikalischen Vorlieben haben, spielen wir auch ganz verschiedene Programme: an der Abendunterhaltung ist vor allem anspruchsvolle Unterhaltungsmusik gefragt, an Wettspielen klassische Blasmusikkompositionen und bei Ständchen auch traditionelle Märsche und Walzer. So kommen alle zum Zug.',
    },
    {
      id: 85,
      identifier: 'musikverein-oberrieden',
      name: 'Musikverein Oberrieden',
      logoImgId: null,
      bildImgId: 'ab32d40d-897e-4f70-b958-a3fa7a018a00',
      homepage: 'https://musikverein-oberrieden.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Musikanten des Musikvereins Oberrieden verstehen sich als «Unterhaltungsmusikanten», die durch gemeinsames Musizieren sowohl sich als auch die Bevölkerung von Oberrieden und Umgebung mit einem breiten musikalischen Spektrum unterhalten wollen.\n\nBereits seit dem Jahr 1937 ist die Blasmusik ein fester Bestandteil der Oberriedner Dorfkultur. Früher noch unter den Namen «Jugendmusik» und «Harmonie» bekannt, schlossen sich die beiden Vereine Anfang 2011 zum «Musikvereins Oberrieden» (MVO)» zusammen.\n\nDie Abendunterhaltung im Frühling und das Adventskonzert im Dezember zählen zu den wichtigsten musikalischen Anlässen im Jahresprogramm. Ein Highlight ist die Teilnahme am Zürcher Sechseläuten. Seit 1968 gebührt dem MVO die Ehre, als Zunftspiel die Zunft Wollishofen am Sechseläuten begleiten zu dürfen.',
    },
    {
      id: 86,
      identifier: 'musikverein-richterswil-samstagern',
      name: 'Musikverein Richterswil Samstagern',
      logoImgId: 'ac993059-ec50-4498-74b7-5395f996f500',
      bildImgId: '15b26f2a-51cc-4e39-b40f-02f617a00000',
      homepage: 'https://www.mrs-online.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind ein Dorfverein in der 3. Stärkeklasse in Harmoniebesetzung. Unser Repertoire umfasst Musikstücke verschiedener Musikstile, um bei jedem Anlass etwas Passendes dabei zu haben. Wenn Sie Freude an moderner und tradtioneller Blasmusik haben, sind Sie bei uns an der richtigen Adresse. Von jungen bis erfahrenen Musikanten ist bei uns alles vertreten. Wir geniessen das gemeinsame Musizieren und freuen uns auf das kantonale Musikfest. ',
    },
    {
      id: 66,
      identifier: 'musikverein-ruemlang',
      name: 'Musikverein Rümlang',
      logoImgId: 'e9f3fd95-7e2e-4795-d1fc-589ae2c52200',
      bildImgId: '500f5ebb-44db-4865-bc93-485d00427100',
      homepage: 'https://www.mvruemlang.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Der Musikverein Rümlang besteht seit 1959. Die Vereinsgeschichte ist also schon alt, sicherlich bewegt aber keinesfalls verstaubt. Im Gegenteil, dank aktiven Mitgliedern hat der Verein allen Strömungen Stand gehalten und wir sind stolz darauf, dass wir als Dorfverein mit unseren engagierten Aktivmitgliedern das ganze Jahr hindurch  musizieren und an lokalen Veranstaltungen teilnehmen. \nNicht nur musikalisch sind wir aktiv, auch das gemütliche Beisammensein bei einem Grillend oder Fondueplausch sowie diverse Ausflüge gehören bei uns zum Programm.',
    },
    {
      id: 39,
      identifier: 'musikverein-schoenenberg',
      name: 'Musikverein Schönenberg',
      logoImgId: null,
      bildImgId: '02e9d339-e495-428d-f0d9-3e54a6bcf800',
      homepage: 'https://www.mvschonenberg.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Wir sind ein aktiver Dorfverein mit aufgestellten Mitgliedern, welche die Liebe zur Blasmusik und die Kameradschaft verbindet.\nMit unseren rund 35 Mitglieder im Alter von 17 bis 89 Jahren proben wir einmal die Woche.\nDas Jahreshighlight ist unser Chränzli. Auch unter dem Jahr sind wir an diversen Auftritten anzutreffen.',
    },
    {
      id: 31,
      identifier: 'musikverein-stammheim',
      name: 'Musikverein Stammheim',
      logoImgId: '7b225547-2353-4ae8-a2c9-9cf7d3b21c00',
      bildImgId: '22fab279-45a3-40ab-211c-a9a62980b800',
      homepage: 'https://www.musikverein-stammheim.ch',
      facebook: 'https://www.facebook.com/mvstammheim',
      instagram: 'https://www.instagram.com/musikverein_stammheim',
      websiteText: null,
    },
    {
      id: 80,
      identifier: 'musikverein-uetikon-am-see',
      name: 'Musikverein Uetikon am See',
      logoImgId: 'fe5639a2-0b1e-4a2f-5dc9-150cb8e67300',
      bildImgId: '48c51cdc-632c-457d-01a4-eb2b3d00d900',
      homepage: 'https://www.mv-uetikon.ch',
      facebook: null,
      instagram: null,
      websiteText: 'Mit viel Hingabe unterstützen wir seit 1965 aktiv das Dorfleben in Uetikon am See mit vielfältiger Musik. ',
    },
    {
      id: 91,
      identifier: 'musikverein-weisslingen',
      name: 'Musikverein Weisslingen',
      logoImgId: 'fb20463e-8481-44d4-1da4-10e7c10c6300',
      bildImgId: '7247147d-5f1e-47b7-7cba-46d93a7d8100',
      homepage: 'https://www.mv-weisslingen.ch',
      facebook: 'https://www.facebook.com/profile.php?id=100085123252190',
      instagram: null,
      websiteText: 'mv-weisslingen.ch',
    },
    {
      id: 108,
      identifier: 'musikverein-wil-zh',
      name: 'Musikverein Wil ZH',
      logoImgId: null,
      bildImgId: 'd1a76b6d-c560-4aad-b6ee-9ee34c06db00',
      homepage: 'https://www.mvwil.ch',
      facebook: null,
      instagram: null,
      websiteText: null,
    },
    {
      id: 42,
      identifier: 'musikverein-zuerich-hoengg',
      name: 'Musikverein Zürich-Höngg',
      logoImgId: '1cd63cd1-ea11-4668-df63-5c0102a24e00',
      bildImgId: '012cdbe2-506c-4799-c4a1-f07de322df00',
      homepage: 'https://hoenggermusik.ch',
      facebook: 'https://www.facebook.com/Hoenggermusik',
      instagram: 'https://www.instagram.com/mv_hoengg/',
      websiteText:
        'Der Musikverein Zürich-Höngg, ein voll ausgebautes symphonisches Blasorchester der Stadt Zürich, steht seit Januar 2023 unter der Leitung von Enrico Calzaferri. Zu den Höhepunkten im Jahresprogramm gehören das Konzert im Toni-Areal im Frühling, die Konzerte in der Kirche im Dezember sowie die Openair-Sommerkonzerte an den schönsten Plätzen in der Stadt Zürich. Die rund 80 Musiker*innen erarbeiten unter der professionellen Leitung ihres Dirigenten Blasorchesterliteratur aus verschiedensten Sparten und bereiten dem Publikum eine vielfältiges Konzerterlebnis.',
    },
    {
      id: 112,
      identifier: 'musikverein-zuerich-seebach',
      name: 'Musikverein Zürich-Seebach',
      logoImgId: 'f799031d-85a5-4a47-cc8b-b19ed6333500',
      bildImgId: '2be81a71-5768-475d-69a9-a8a8f4ae0600',
      homepage: 'https://www.mzseebach.ch',
      facebook: null,
      instagram: 'https://www.instagram.com/mzseebach',
      websiteText:
        'Der Musikverein Zürich-Seebach ist eine Blasmusik mit Harmoniebesetzung und wurde 1929 als "Arbeiter-Musik Oerlikon und Umgebung" gegründet. Heute überzeugt der MZS mit seinen 32  Mitgliedern durch beschwingte Unterhaltungsmusik, konzertanter Blasmusik sowie Stücken  aus den Bereichen Latin und Funk. Diverse Mitglieder sind über Jahrzehnte dabei und schätzen die kollegiale Stimmung.',
    },
    {
      id: 111,
      identifier: 'perkussionsensemble-winterthur',
      name: 'Perkussionsensemble Winterthur',
      logoImgId: '3cf839ab-545e-47ce-d79c-1b28bc424200',
      bildImgId: null,
      homepage: null,
      facebook: null,
      instagram: null,
      websiteText:
        'Die Formation setzt sich vor allem aus jetzigen und ehemaligen Schülerinnen und Schülern der Musikschule „Eulach-Perkussion“ Winterthur und Gästen zusammen. Wir wollen den Anlass des ZKMF 24 in Urdorf nutzen, um um das Werk von David Maslanka aufzuführen.',
    },
    {
      id: 72,
      identifier: 'schlagzeugensemble-florhof',
      name: 'Schlagzeugensemble Florhof',
      logoImgId: '01bea775-073f-4e7d-6c99-2ee97506f500',
      bildImgId: null,
      homepage: null,
      facebook: null,
      instagram: null,
      websiteText:
        'Das Ensemble Florhof ist eine bunte ZUsammenstellung von Anfänger und fortgeschrittene Schüler. Gemeinsam haben sie die Neugier neue Instrumente auszuprobieren, und die Freude am Zusammenspiel.',
    },
    {
      id: 59,
      identifier: 'sjmuz-percussion-ensemble',
      name: 'SJMUZ Percussion Ensemble',
      logoImgId: 'f88352ed-f2e4-4f39-6192-12c04632eb00',
      bildImgId: '71147c24-4d4b-435c-1725-987a13f5ca00',
      homepage: 'https://www.sjmuz.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Das SJMUZ Percussion Ensemble bietet den Aspi- und Blasorchester-Schlagzeugern die Möglichkeit, als Ergänzung zu ihrer Formation zusätzlich in einem Schlagzeugensemble zu spielen. Je nach Projekt bestehen wir aus 6 - 12 Schlagzeugerinnen und Schlagzeugern.\nDer Höhepunkt des Jahres ist jeweils der Auftritt am Jahresschlusskonzert am ersten Wochenende im Dezember. Aber wir nehmen auch regelmässig an Wettbewerben teil. So konnten wir am Eidgenössischen Jugendmusikfest in Zug 2013 den Schweizermeister Titel in der Kategorie Schlagzeugensembles gewinnen. Ausserdem dürfen wir jeweils das Blasorchester auf seinen Auslandreisen begleiten.\nWir decken die ganze Bandbreite der Perkussionsliteratur ab: neben anspruchsvollen Wettbewerbsstücken spielen wir viel Grooviges, aber auch effektvolle Show-Stücke fehlen nicht in unserem Repertoire. Bei Umzügen führt das SJMUZ Percussion Ensemble als Drumline das Blasorchester an und bildet so die akustische Visitenkarte der SJMUZ.',
    },
    {
      id: 94,
      identifier: 'sjmuz-schlagzeugensemble',
      name: 'SJMUZ Schlagzeugensemble',
      logoImgId: '74515138-d025-4cc0-774e-9cad2dcbe000',
      bildImgId: 'ca0cafe8-a83b-40dc-6ec9-ad217905f500',
      homepage: 'https://www.sjmuz.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Das SJMUZ-Schlagzeugensemble bietet jungen Schlagzeugerinnen und Schlagzeugern ab ca. einem Jahr Unterricht eine erste Möglichkeit für das Zusammenspiel. Die Gruppe besteht aus 4 – 8 Kindern. Zweimal im Jahr präsentieren wir die geübten Stücke an einem Konzert.\nDas Spielen in der Gruppe mit Gleichaltrigen macht grossen Spass, ist ein enormer Motivationsfaktor und eine unverzichtbare Ergänzung zur Einzelstunde. Im Ensemble lernen wir wichtige musikalische Grundlagen wie das Zusammenspiel und das Spielen unter einem Dirigenten. Zusätzlich lernen wir die vielen verschiedenen Instrumente aus der Welt der Perkussion kennen, was grosse Abwechslung bietet.',
    },
    {
      id: 83,
      identifier: 'spielgemeinschaft-mettmenstetten-ottenbach',
      name: 'Spielgemeinschaft Mettmenstetten/Ottenbach',
      logoImgId: null,
      bildImgId: '9079dba1-5bd1-444c-6c50-f66eed4dcc00',
      homepage: 'https://www.mvmettmenstetten.ch',
      facebook: null,
      instagram: null,
      websiteText: 'Siehe: mvmettmenstetten.ch',
    },
    {
      id: 76,
      identifier: 'stadtharmonie-winterthur-toess',
      name: 'Stadtharmonie Winterthur-Töss',
      logoImgId: '7f7a52c3-5df6-4b8e-facc-a197bea02200',
      bildImgId: 'e49126ae-28f2-45d1-2553-c6e05e1de600',
      homepage: 'https://www.stadtharmonie-winterthur.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Stadtharmonie Winterthur-Töss wurde 1879 , vor beinahe 150-Jahren gegründet. Im Jahr 2005 übernahm Helmut Hubov die musikalische Leitung und prägt und fördert seither unsere musikalischen Fähigkeiten.\nDas Vereinsjahr ist geprägt vom Familienkonzert im Frühling (Familienprogramm, Märchen und Einbezug der Jugendensembles) dem Winterkonzert mit konzertanter Blasorchesterliteratur und im Dezember ein Adventskonzert in der Kirche. Sommerkonzerte mit Unterhaltungsmusik in und um Winterthur vervollständigen das abwechslungsreiche Jahresprogramm. Zur Standortbestimmung gehören auch die Teilnahme an Kantonalen, Nationalen oder Europäischen Musikwettbewerben. Immer wieder sind auch vielbeachtete Grossprojekte wie  "The Queen Symphony" von Tolga Kashif (2010), "Stabat Mater" von Karl Jenkins (2014) oder "Carmina Burana" von Carl Orff (2018) mit jeweils total über 200 Mitwirkenden Teil der Vereinsaktivitäten. \nDer nächste Grossanlass ist bereits programmiert. Im Herbst 2024 möchten wir nochmals das beeindruckende Werk «Stabat Mater» von Karl Jenkins zusammen mit der Stadtmusik Stockach (D) und einem grossen Chor aus Winterthur aufführen. \nwww.stadtharmonie-winterthur.ch \n',
    },
    {
      id: 23,
      identifier: 'stadtharmonie-zuerich-oerlikon-seebach',
      name: 'Stadtharmonie Zürich Oerlikon-Seebach',
      logoImgId: '069bfa0e-b6e6-475c-3e85-2d9fdeb2a400',
      bildImgId: 'd2b215f4-7255-4b23-4a2a-37a0aeed7500',
      homepage: 'https://stadtharmonie.ch',
      facebook: 'https://www.facebook.com/stadtharmonie.ch',
      instagram: 'https://www.instagram.com/stadtharmonie.ch',
      websiteText:
        'Die Stadtharmonie Zürich Oerlikon-Seebach ist ein ausgebautes sinfonisches Blasorchester der Höchstklasse mit rund 80 Amateurmusikerinnen und -musikern. Sie steht seit 2005 unter der Leitung des Tessiner Dirigenten Carlo Balmelli. Bekannt ist die Stadtharmonie für ihren warmen, ausgewogenen Klang und ihren musikalischen Ausdruck. Die Stadtharmonie hat es sich zum Ziel gesetzt, möglichst alle Instrumente mit eigenen Musikanten zu besetzen, so z.B. auch Spezialinstrumente wie Englischhorn oder Bassflöte. Auch die Solisten stammen bei Konzerten der Stadtharmonie regelmässig aus den eigenen Reihen. Nur wenn die Instrumentierung über den Bestand des Orchesters hinausgeht, werden externe Musiker hinzugezogen.',
    },
    {
      id: 71,
      identifier: 'stadtmusik-buelach',
      name: 'Stadtmusik Bülach',
      logoImgId: '05b451a9-da62-48db-f512-ef11999e1900',
      bildImgId: '87942338-02e4-4b6d-098c-38f47e021200',
      homepage: 'https://smbuelach.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Stadtmusik, über 100jährig, bringt beim Musizieren Jung und Alt zusammen. Zwei Konzerte pro Jahr sind unsere Highlights. Das Repertoire umfasst von Traditionell über Film, Pop, Rock, Musicalmelodien und klassischer Musik bis zu originaler Blasmusik-Literatur. Neben der Musik pflegen wir auch ein fröhliches Miteinander.',
    },
    {
      id: 47,
      identifier: 'stadtmusik-dietikon',
      name: 'Stadtmusik Dietikon',
      logoImgId: '1ab7755b-70f2-4c9a-16ff-503d2bc25600',
      bildImgId: 'f9417e39-4dec-4e50-b4db-c665175dbd00',
      homepage: 'https://www.stadtmusik-dietikon.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die Stadtmusik Dietikon...\n- ist ein Blasorchester mit rund 70 Mitgliedern.\n- musiziert unter der Leitung von Marco Nussbaumer.\n- gibt es bereits seit 1891. Damals hiess der Verein noch Eintracht.\n- ist bereits seit 60 Jahren Zunftmusik der Zunft zum Kämbel.\n- ist durchschnittlich 44 Jahre alt. Das jüngste Mitglied ist 22, das älteste 80.\n- probt im Schnitt etwa 100 Stunden pro Jahr.\n- besteht zu mehr als 60% aus Mitgliedern, die auch in Dietikon wohnen.\n- probt immer Mittwochs von 20 - 22 Uhr im eigenen Probelokal.\n- nimmt an Wettbewerben in der ersten Stärkeklasse teil.\n- bestreitet rund 14 musikalische Auftritte pro Jahr.',
    },
    {
      id: 74,
      identifier: 'stadtmusik-duebendorf',
      name: 'Stadtmusik Dübendorf',
      logoImgId: 'd8d78f86-a0a7-4479-53a3-29ad9e136600',
      bildImgId: 'ba5b168d-7e0e-4759-904d-f9ad7ffcf000',
      homepage: 'http://www.stadtmusik-duebendorf.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Willkommen bei der Stadtmusik Dübendorf!\nWir sind ein aufgestelltes und dynamisches Blasorchester und haben uns für den Vortrag in der zweiten Stärkeklasse angemeldet. Dreiundvierzig Bläser:innen und Schlagzeuger:innen treffen sich ein- bis zweimal pro Woche zur Probe. Neben einem weiten Spektrum an Musikstilen pflegen wir die Geselligkeit. Wir freuen uns darauf, wenn Ihr an unserem Vortrag am ZKMF vorbei schaut.',
    },
    {
      id: 28,
      identifier: 'stadtmusik-illnau-effretikon',
      name: 'Stadtmusik Illnau-Effretikon',
      logoImgId: '8af16efa-e81e-4570-da68-10f30e823600',
      bildImgId: '77db9dfd-80bd-4876-abed-fff6c74cd300',
      homepage: 'https://smie.ch',
      facebook: 'https://www.facebook.com/StadtmusikIllnauEffretikon',
      instagram: 'https://www.instagram.com/stadtmusikillnaueffretikon',
      websiteText:
        'Die SMIE ist ein Amateur-Orchester der 1. Stärkeklasse, unter professioneller musikalischer Leitung. Rund 50 Aktivmitglieder aus Stadt und Region zwischen 18 und 85 Jahren pflegen vielfältige Blasorchesterliteratur.\n\nHauptanlässe sind das Konzert in der Kirche im Januar und das Unterhaltungskonzert im September.\n\nDer Verein trägt zur kulturellen Vielfalt in der Region bei und wird von der Stadt und von seiner Gönnervereinigung unterstützt. Mit der Stadtjugendmusik besteht eine enge Zusammenarbeit.',
    },
    {
      id: 46,
      identifier: 'stadtmusik-winterthur',
      name: 'Stadtmusik Winterthur',
      logoImgId: 'a4cf3a9b-8ab3-4cd2-4377-d5270e511300',
      bildImgId: '3dbecf25-eac8-4019-8b6e-33492afa7500',
      homepage: 'https://www.stadtmusik-winterthur.ch',
      facebook: 'https://www.facebook.com/StadtmusikWinterthur',
      instagram: 'https://www.instagram.com/stadtmusikwinterthur',
      websiteText:
        'Die Stadtmusik Winterthur besteht aus zirka 60 Aktivmitgliedern von durchschnittlich 37 Jahren. Das breite Repertoire des Erstklass-Vereins umfasst neben Bearbeitungen eine grosse Anzahl zeitgenössischer Originalwerke.  \n\nDie Wurzel der Stadtmusik Winterthur reichen über viele Generationen zurück bis ins Jahr 1872. Damals trafen sich 20 engagierte Bläser und gründeten einen Verein, der mittlerweile seit über 140 Jahren erfolgreich musiziert. Dabei hat sich in den letzten 40 Jahren die Geschlechterverteilung stark verändert: Während noch am Anfang der siebziger Jahre des letzten Jahrhunderts nur eine einzige Frau im Verein mitspielte, ist heute die Hälfte der Musizierenden weiblichen Geschlechts.\n\nWenn die Stadtmusik heute den Heinrich-Menet-Marsch vorträgt, gedenkt sie damit auch ihres ehemaligen Dirigenten und ausgebildeten Trompeters Heinrich Menet, der von 1960-1988 den Stab führte. Er wurde 1986 am Eidgenössischen Musikfest mit dem Stephan-Jaeggi-Preis für seine Verdienste um die Blasmusik in der Schweiz ausgezeichnet. Langjährige Dirigenten waren auch Solo-Oboist Gunhard Mattes und der Klarinettist Urs Bamert. Von 2006 bis 2020 stand der Verein unter der musikalischen Leitung des ausgebildeten Dirigenten und Perkussionisten Fredi Olbrecht. Im Sommer 2006 erreichte die Stadtmusik unter seiner Leitung am Eidgenössischen Musikfest in Luzern den 10. Rang in der ersten Stärkeklasse.\n\nDie wichtigsten musikalischen Anlässe sind das Jahreskonzert Ende März und das Herbstkonzert im November. Das Jahreskonzert steht jedes Jahr unter einem anderen Motto, zu welchem Transkriptionen und Originalwerken gespielt werden. Das Herbstkonzert stellt einen musikalischen Gegensatz zum Jahreskonzert dar, wobei Musikstücke aus anderen Stilrichtungen gespielt werden.\n\nDie Stadtmusik nimmt regelmässig an nationalen und internationalen Wettbewerben teil und tritt an diesen in der ersten Klasse an. Erfolge sind der 7. Platz am Eidgenössischen Musikfest in St. Gallen 2011, sowie 2012 die Titelverteidigung des Wallbergcontests in Volketswil und der Sieg am Musikwettbewerb in Malgart de Mar (Spanien) 2014.\n\nAls Verein organisierten wir das Eidgenössische Musikfest 1986 und das Zürcher Kantonalmusikfest 2013.',
    },
    {
      id: 49,
      identifier: 'stadtmusik-zuerich',
      name: 'Stadtmusik Zürich',
      logoImgId: 'e09b204b-ce21-4444-78a0-ab497c6f9200',
      bildImgId: '722f6c10-6e92-4e36-5a0c-7208fa9ec200',
      homepage: 'https://www.stadtmusik.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die 1846 gegründete Stadtmusik Zürich, repräsentatives Musikkorps der grössten Schweizer Stadt, ist ein voll ausgebautes Harmonie-Blasorchester und umfasst heute rund 80 Musikerinnen und Musiker. Gemäss ihren Weisungen bezweckt sie die Pflege guter Blasmusik und ist bestrebt, das kulturelle Leben der Stadt Zürich und deren Ansehen im In- und Ausland zu fördern.',
    },
    {
      id: 99,
      identifier: 'tambouren-polizeimusik-zuerich-stadt',
      name: 'Tambouren der Polizeimusik Zürich-Stadt',
      logoImgId: 'bc632145-a664-4f43-d056-99681a6d5d00',
      bildImgId: 'b306b21c-d2af-4a79-12a0-2be63de7cf00',
      homepage: 'https://www.polizeimusik.ch',
      facebook: 'https://www.facebook.com/polizeimusik',
      instagram: 'https://www.instagram.com/polizeimusikzurichstadt/',
      websiteText:
        'Am 31. Kantonalmusikfest in Urdorf und Schlieren sind wir mit unserer Tambourengruppe zu Gast.\nDie Polizeimusik Zürich-Stadt wurde 1902, analog der ältesten Korpsmusik der Schweiz, der Korpsmusik der Kantonspolizei Zürich, gegründet. Wir sind ein wichtiges Bindeglied zwischen Polizei und Bevölkerung und musikalische Botschafterin für die Stadtpolizei Zürich, die Stadt Zürich und die Schweiz mit Auftritten im In- und Ausland. Musikalisch sind wir auf konzertante Unterhaltungsmusik, Hallen- und Rasenshows ausgerichtet.\nAls reine Amateurband mit aktuell 74 Mitgliedern, davon 52 Musikern, 9 Tambouren und 13 Funktionären wollen wir mit unserer Musik unseren Mitmenschen Freude bereiten.',
    },
    {
      id: 68,
      identifier: 'kreismusik-limmattal-tambouren',
      name: 'Tambourengruppe der Kreismusik Limmattal',
      logoImgId: null,
      bildImgId: '9da9a900-8699-4292-029a-f22fe3184000',
      homepage: 'http://www.kmlimmattal.ch',
      facebook: null,
      instagram: null,
      websiteText: 'Tambourengruppe der Kreismusik Limmattal',
    },
    {
      id: 56,
      identifier: 'tambourenverein-stadt-winterthur',
      name: 'Tambourenverein der Stadt Winterthur',
      logoImgId: 'f7574c11-9038-4861-6a19-a0a0ac443200',
      bildImgId: '7e09f898-3541-4e01-82b4-82f59a743800',
      homepage: 'https://www.tambourenwinterthur.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Mit Freude stellen wir uns als grössten Tambourenverein der Umgebung Winterthur vor. Neuzeit paart sich nirgends so gut mit Tradition wie bei uns!\nAn verschiedenartigen Engagements dürfen wir unser Können unter Beweis stellen. Grosse Saalkonzerte im Theater Winterthur, das Begleiten von feierlichen Festakten und private Anlässe gehören dazu. Erlebnisse wie Räbeliechtli-Umzüge in der kalten Jahreszeit, Wettspiele in der ganzen Schweiz, Geburtstage und Hochzeiten runden das Vereinsjahr auf abwechslungsreiche Weise ab. \nTolle Erfolge zieren unsere Vereinsgeschichte. Wir sind amtierender Vize-Schweizermeister in der Kategorie Percussion. \n\nWeitere Infos zu uns findet ihr hier: https://www.tambourenwinterthur.ch/ueber-uns',
    },
    {
      id: 73,
      identifier: 'tambourenverein-weinland-andelfingen',
      name: 'Tambourenverein Weinland Andelfingen',
      logoImgId: null,
      bildImgId: 'ffa5efd7-5d96-44e4-c044-8e37d06d0900',
      homepage: 'https://tvwa.ch',
      facebook: null,
      instagram: null,
      websiteText: 'Tambourenverein Weinland Andelfingen www.tvwa.ch',
    },
    {
      id: 101,
      identifier: 'vbz-musik',
      name: 'VBZ Musik',
      logoImgId: '6a4264d3-2feb-48de-6f1e-eb5ab7ac0300',
      bildImgId: '2da917b9-8a68-4c29-a337-748174a15d00',
      homepage: 'https://vbz-musik.ch',
      facebook: null,
      instagram: null,
      websiteText:
        'Die VBZ-Musik ist ein Blasmusikverein mit einer stattlichen Anzahl Mitglieder und hat sich in erster Linie der Unterhaltungsmusik verschrieben. Wir wollen mit unserer Musik die Zuhörer unterhalten und Lebensfreude vermitteln. Und was genauso wichtig ist, wir wollen Spass haben an dem, was wir machen!\n\nEs ist kein Geheimnis, dass wir in unserem Verein die Geselligkeit genauso pflegen wie unsere musikalische Ausrichtung. Wir haben das grosse Glück, unseren Sitz im Musikzentrum Albisgütli zu haben, fernab des städtischen Rummels und mit traumhafter Sicht auf Uetliberg und Zürichsee.\n\nBei uns ist jeder willkommen, der unsere Freude an gepflegter Unterhaltungsmusik teilen will, eine musikalische Grundausbildung hat und bereit ist, mit einem Blasmusikverein der etwas anderen Art selbst die Probearbeit zu geniessen.',
    },
  ]
})
