// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  ssr: true,
  devtools: { enabled: true },
  css: ['~/assets/css/main.css'],

  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
      // https://answers.netlify.com/t/javascript-heap-out-of-memory-when-trying-to-build-a-nuxt-app/93138/14
      cssnano: process.env.NODE_ENV === 'production' ? { preset: ['default', { discardComments: { removeAll: true } }] } : false,
    },
  },

  googleFonts: {
    families: {
      Poppins: {
        wght: [100, 200, 300, 400, 500, 600, 700, 800, 900],
      },
    },
    display: 'swap',
    preconnect: true,
    useStylesheet: true,
  },

  modules: ['@nuxt/image', '@nuxtjs/google-fonts', '@nuxtseo/module', 'nuxt-gtag', '@vueuse/nuxt'],

  runtimeConfig: {
    public: {
      // do not use process.env.NODE_ENV as it is overwritten (always production) when running 'generate'
      apiBase: process.env.API_BASE ?? 'http://localhost:8080',
    },
  },

  site: {
    url: 'https://www.zkmf2024.ch',
    name: 'ZKMF2024',
    defaultLocale: 'de',
  },

  gtag: {
    id: 'NUXT_PUBLIC_GTAG_ID',
    initialConsent: false,
  },

  image: {
    cloudflare: {
      baseURL: 'https://imagedelivery.net/b5PKQi-eHYmFXihh4Gjd5g/',
    },
  },

  nitro: {
    prerender: {
      routes: [
        '/lokal/embrisaal-urdorf',
        '/lokal/turnhalle-weihermatt-urdorf',
        '/lokal/salmensaal-schlieren',
        '/lokal/grosse-ref-kirche-schlieren',
        '/lokal/zentrumshalle-urdorf',
        '/lokal/reformierte-kirche-urdorf',
        '/verein/musikverein-harmonie-birmensdorf',
        '/verein/musikverein-langnau-am-albis',
        '/verein/stadtmusik-zuerich',
        '/verein/musikgesellschaft-andelfingen',
        '/verein/musikgesellschaft-faellanden',
        '/verein/harmoniemusik-wald',
        '/verein/musikverein-stammheim',
        '/verein/stadtmusik-duebendorf',
        '/verein/harmonie-wetzikon',
        '/verein/musikverein-schoenenberg',
        '/verein/musikverein-harmonie-affoltern-am-albis',
        '/verein/musikverein-eintracht-wallisellen',
        '/verein/musikverein-harmonie-waedenswil',
        '/verein/stadtmusik-buelach',
        '/verein/musikverein-harmonie-altstetten',
        '/verein/musikgesellschaft-niederhasli',
        '/verein/harmonie-volketswil',
        '/verein/kreismusik-limmattal-tambouren',
        '/verein/musikverein-wil-zh',
        '/verein/harmonie-zumikon',
        '/verein/schlagzeugensemble-florhof',
        '/verein/musikverein-buchs-zh',
        '/verein/musikverein-oberrieden',
        '/verein/harmoniemusik-helvetia-horgen',
        '/verein/musikgesellschaft-harmonie-turbenthal',
        '/verein/musikverein-kempttal',
        '/verein/stadtjugendmusik-zuerich-unterstufe',
        '/verein/harmonie-am-bachtel',
        '/verein/musikverein-weisslingen',
        '/verein/musikverein-uetikon-am-see',
        '/verein/musikverein-brass-band-henggart',
        '/verein/musikverein-harmonie-adliswil',
        '/verein/musikverein-richterswil-samstagern',
        '/verein/vbz-musik',
        '/verein/perkussionsensemble-winterthur',
        '/verein/musikverein-harmonie-bauma',
        '/verein/musikgesellschaft-fehraltorf',
        '/verein/musikverein-meilen-',
        '/verein/musikverein-helvetia-marthalen',
        '/verein/musikverein-gossau-zh',
        '/verein/musikverein-zuerich-hoengg',
        '/verein/fusion-mallets',
        '/verein/musikverein-harmonie-zuerich-schwamendingen',
        '/verein/jugendmusik-bezirk-affoltern',
        '/verein/musikgesellschaft-haeggenschwil',
        '/verein/musikverein-neftenbach',
        '/verein/musikverein-neerach',
        '/verein/stadtmusik-dietikon',
        '/verein/spielgemeinschaft-mettmenstetten-ottenbach',
        '/verein/musikverein-bonstetten',
        '/verein/stadtmusik-illnau-effretikon',
        '/verein/musikverein-ruemlang',
        '/verein/harmonie-pfaeffikon',
        '/verein/musikgesellschaft-glattfelden',
        '/verein/musikverein-harmonie-thalwil',
        '/verein/stadtmusik-winterthur',
        '/verein/stadtharmonie-winterthur-toess',
        '/verein/harmonie-eintracht-maennedorf',
        '/verein/musikverein-hedingen',
        '/verein/musikverein-zuerich-seebach',
        '/verein/musikverein-harmonie-hausen-am-albis',
        '/verein/stadtharmonie-zuerich-oerlikon-seebach',
        '/verein/musikgesellschaft-rafz',
        '/verein/harmonie-freienbach',
        '/verein/brass-band-eglisau',
        '/verein/tambourenverein-stadt-winterthur',
        '/verein/musikgesellschaft-seuzach',
        '/verein/tambourenverein-weinland-andelfingen',
        '/verein/harmonie-eintracht-kuesnacht',
        '/verein/kreismusik-limmattal',
        '/verein/tambouren-polizeimusik-zuerich-stadt',
        '/verein/musikverein-dietlikon',
        '/verein/musikverein-harmonie-zuerich-oberstrass',
        '/verein/stadtjugendmusik-zuerich-oberstufe',
        '/verein/musikverein-grueningen',
        '/verein/brass-band-musig-hittnau',
        '/verein/musikverein-baeretswil',
        '/verein/brass-band-maur',
      ],
    },
  },
})
