export default defineEventHandler(() => {
  return [
    {
      day: 'Sa., 22.06.2024',
      inPast: false,
      entries: [
        {
          vereinId: 68,
          vereinIdentifier: 'kreismusik-limmattal-tambouren',
          vereinsname: 'Tambourengruppe der Kreismusik Limmattal',
          modul: 'Tambouren',
          klasse: null,
          besetzung: 'Tambouren',
          competition: 'Tambouren',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '09:35:00',
          end: '09:55:00',
          time: '09:35 - 09:55',
          inPast: false,
        },
        {
          vereinId: 99,
          vereinIdentifier: 'tambouren-polizeimusik-zuerich-stadt',
          vereinsname: 'Tambouren der Polizeimusik Zürich-Stadt',
          modul: 'Tambouren',
          klasse: null,
          besetzung: 'Tambouren',
          competition: 'Tambouren',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '10:10:00',
          end: '10:30:00',
          time: '10:10 - 10:30',
          inPast: false,
        },
        {
          vereinId: 56,
          vereinIdentifier: 'tambourenverein-stadt-winterthur',
          vereinsname: 'Tambourenverein der Stadt Winterthur',
          modul: 'Tambouren',
          klasse: null,
          besetzung: 'Tambouren',
          competition: 'Tambouren',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '10:45:00',
          end: '11:05:00',
          time: '10:45 - 11:05',
          inPast: false,
        },
        {
          vereinId: 73,
          vereinIdentifier: 'tambourenverein-weinland-andelfingen',
          vereinsname: 'Tambourenverein Weinland Andelfingen',
          modul: 'Tambouren',
          klasse: null,
          besetzung: 'Tambouren',
          competition: 'Tambouren',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '11:20:00',
          end: '11:40:00',
          time: '11:20 - 11:40',
          inPast: false,
        },
        {
          vereinId: 94,
          vereinIdentifier: 'sjmuz-schlagzeugensemble',
          vereinsname: 'SJMUZ Schlagzeugensemble',
          modul: 'Perkussionsensembles',
          klasse: 'Unterstufe',
          besetzung: 'Perkussionsensemble',
          competition: 'Perkussionsensembles, Unterstufe',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '13:35:00',
          end: '13:55:00',
          time: '13:35 - 13:55',
          inPast: false,
        },
        {
          vereinId: 72,
          vereinIdentifier: 'schlagzeugensemble-florhof',
          vereinsname: 'Schlagzeugensemble Florhof',
          modul: 'Perkussionsensembles',
          klasse: 'Mittelstufe',
          besetzung: 'Perkussionsensemble',
          competition: 'Perkussionsensembles, Mittelstufe',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '14:10:00',
          end: '14:30:00',
          time: '14:10 - 14:30',
          inPast: false,
        },
        {
          vereinId: 65,
          vereinIdentifier: 'fusion-mallets',
          vereinsname: 'Fusion Mallets',
          modul: 'Perkussionsensembles',
          klasse: 'Mittelstufe',
          besetzung: 'Perkussionsensemble',
          competition: 'Perkussionsensembles, Mittelstufe',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '14:45:00',
          end: '15:05:00',
          time: '14:45 - 15:05',
          inPast: false,
        },
        {
          vereinId: 59,
          vereinIdentifier: 'sjmuz-percussion-ensemble',
          vereinsname: 'SJMUZ Percussion Ensemble',
          modul: 'Perkussionsensembles',
          klasse: 'Oberstufe',
          besetzung: 'Perkussionsensemble',
          competition: 'Perkussionsensembles, Oberstufe',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '15:20:00',
          end: '15:40:00',
          time: '15:20 - 15:40',
          inPast: false,
        },
        {
          vereinId: 111,
          vereinIdentifier: 'perkussionsensemble-winterthur',
          vereinsname: 'Perkussionsensemble Winterthur',
          modul: 'Perkussionsensembles',
          klasse: 'Oberstufe',
          besetzung: 'Perkussionsensemble',
          competition: 'Perkussionsensembles, Oberstufe',
          type: 'WETTSPIEL',
          typeDescription: 'Wettspiel',
          location: {
            id: 14,
            identifier: 'embrisaal-urdorf',
            name: 'Embrisaal Urdorf',
            address: 'Im Embri 8, 8902 Urdorf',
            latitude: 47.387068997702,
            longitude: 8.425614397929,
            googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
            googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
            type: 'WETTSPIELLOKAL',
            capacity: '10 Personen',
            modules: 'G (Tambouren) und H (Perkussionsensembles)',
            sortOrder: 6,
            mapId: '3W',
            cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
            kuulaId: '5ZfQh',
            einspiellokal: null,
            instrumentendepotId: 6,
            instrumentendepotParademusikId: 6,
            instrumentendepot: null,
            juryfeedback: null,
            percussionEquipmentType: 'FULL',
            coordinates: {
              latitude: 47.387068997702,
              longitude: 8.425614397929,
            },
          },
          date: '2024-06-22',
          start: '15:55:00',
          end: '16:15:00',
          time: '15:55 - 16:15',
          inPast: false,
        },
      ],
    },
  ]
})
