export default defineEventHandler(() => {
  return {
    id: 100,
    name: 'Brass Band Musig Hittnau',
    direktionName: 'Dieter Bischof',
    logoImgId: 'c287f02d-40ca-4ede-8814-312acf77a600',
    bildImgId: '9c088f1a-af9e-4212-e557-bb9a31259300',
    homepage: 'https://www.musig-hittnau.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Brass Band Hittnau wurde 1935 gegründet. Wir spielen seit der Gründung in Brass Band Besetzung in der 3. Stärkeklasse. Aktuell zählt unsere Verein 27 Musikantinnen und Musikanten. Im August 2023 hat Dieter Bischof neu die musikalische Leitung übernommen.\n\nWir bieten Jung und Alt eine anspruchsvolle Freizeitbeschäftigung in einem Umfeld, wo Kameradschaft und Geselligkeit noch gross geschrieben werden. Unsere Schwerpunkte legen wir auf eine stetige Weiterentwicklung des Vereins, die gezielte Jugendförderung, sowie darauf, anspruchsvolle Brass Band Musik zu präsentieren.\n\nDie konzertanten Höhepunkte bilden unser Jahreskonzert im Frühling und das Konzert in der Kirche oder eine Abendunterhaltung zum Jahresende. Unser Augenmerk gilt auch den übers ganze Jahr verstreuten Darbietungen in Form von Ständchen und Platzkonzerten zu den verschiedensten Anlässen. Die Brass Band Musig Hittnau ist ein typischer Dorfverein, der im kulturellen Leben der Gemeinde Hittnau einen wichtigen Platz einnimmt.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Brass Band',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'So., 23.06.2024, 09:00 - 09:25',
        titel: 'Auf dem Weg zum Ziel',
        description:
          'Wir eröffnen unseren Vortrag mit dem feierlichen Stück «Pioneers von Philip Sparke», welches die Expedition der zwei Heldenfiguren Meriwether Lewis und William Clark beschreibt. Ihnen gelang es trotz der Durchquerung feindlichen Gebietes, das Quellgebiet des Missouri zu erforschen und eine Route zum Pazifik zu finden. Wir präsentieren hier abenteuerliche Klänge.\n\nEin einflussreiches musiktheoretisches Lehrwerk trägt den Titel Gradus ad Parnassum („Stufen zum Parnass“ oder „Weg zum Gipfel“). Das Lehrwerk bedeutet im übertragenen Sinn einen bedeutenden künstlerischen Fortschritt bzw. den Schritt des Komponisten hin zur Perfektion.\n\nMit dem Stück «Parnassus von Jan van der Roost» werden wir Stufe um Stufe die musikalischen Themen mit all seinen Herausforderungen bestreiten. Der Start zeigt sich zuerst gut machbar. Je länger jedoch der Anstieg dauert, desto herausfordernder wird er, was sich auch deutlich am ansteigenden Schwierigkeitsgrad des Stücks zeigt. Am Ende des Werkes angekommen, präsentiert es sich in einer malerischen und fantastischen Klangwelt. In einem hellen majestätischen Dur-Akkord haben wir den Gipfel erreicht.\n\nWieder vom «Parnass» herabgestiegen, zeigt uns das Stück «Starlight von Alan Fernie» mit seinen prächtigen und glanzvollen Klängen das Licht am Ende des Weges. Im Abschluss unseres Vortrages erreichen wir dann unser Ziel mit einem kräftigen Schlussakzent.\n',
        programm: [
          {
            id: 9,
            modul: 'A',
            titelName: 'The Pioneers',
            composer: 'Philip Sparke',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 252,
            modul: 'A',
            titelName: 'Parnassus',
            composer: 'Jan Van der Roost',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 740,
            pflichtStueck: false,
            infoModeration:
              'Wir eröffnen unseren Vortrag mit dem feierlichen Stück «Pioneers von Philip Sparke», welches die Expedition der zwei Heldenfiguren Meriwether Lewis und William Clark beschreibt. Ihnen gelang es trotz der Durchquerung feindlichen Gebietes, das Quellgebiet des Missouri zu erforschen und eine Route zum Pazifik zu finden. Wir präsentieren hier abenteuerliche Klänge.\n\nEin einflussreiches musiktheoretisches Lehrwerk trägt den Titel Gradus ad Parnassum („Stufen zum Parnass“ oder „Weg zum Gipfel“). Das Lehrwerk bedeutet im übertragenen Sinn einen bedeutenden künstlerischen Fortschritt bzw. den Schritt des Komponisten hin zur Perfektion.\n\nMit dem Stück «Parnassus von Jan van der Roost» werden wir Stufe um Stufe die musikalischen Themen mit all seinen Herausforderungen bestreiten. Der Start zeigt sich zuerst gut machbar. Je länger jedoch der Anstieg dauert, desto herausfordernder wird er, was sich auch deutlich am ansteigenden Schwierigkeitsgrad des Stücks zeigt. Am Ende des Werkes angekommen, präsentiert es sich in einer malerischen und fantastischen Klangwelt. In einem hellen majestätischen Dur-Akkord haben wir den Gipfel erreicht.\n\nWieder vom «Parnass» herabgestiegen, zeigt uns das Stück «Starlight von Alan Fernie» mit seinen prächtigen und glanzvollen Klängen das Licht am Ende des Weges. Im Abschluss unseres Vortrages erreichen wir dann unser Ziel mit einem kräftigen Schlussakzent.\n',
            valid: true,
          },
          {
            id: 253,
            modul: 'A',
            titelName: 'Starlight',
            composer: 'Alan Fernie',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 129,
            pflichtStueck: false,
            infoModeration: 'Siehe unter Stück Parnassus',
            valid: true,
          },
        ],
      },
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 21,
          identifier: 'festzelt-schlieren',
          name: 'Festzelt Schlieren',
          address: 'Badenerstrasse 12, 8952 Schlieren',
          latitude: 47.397439543225,
          longitude: 8.446011061969,
          googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 9,
          mapId: 'FS',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.397439543225,
            longitude: 8.446011061969,
          },
        },
        dateTime: 'So., 23.06.2024, 11:15 - 11:55',
        titel: null,
        description: 'Die Reihenfolge der Stücke ist noch nicht festgelegt. Ebenfalls sind Programmänderungen noch vorbehalten.',
        programm: [],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 15:30 - 15:35',
        titel: null,
        description: null,
        programm: [
          {
            id: 254,
            modul: 'D',
            titelName: 'Arosa',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 173,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 255,
            modul: 'D',
            titelName: 'Slaidburn',
            composer: 'William Rimmer',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 210,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 20,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'BRASS_BAND',
        besetzungDescription: 'Brass Band',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Brass Band (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
