export default defineEventHandler(() => {
  return {
    id: 34,
    name: 'Brass Band Eglisau',
    direktionName: 'Andreas Buri',
    logoImgId: '285ed9ef-3054-4412-a828-b6f06162b300',
    bildImgId: 'ee3b96b0-30b5-45b5-88c8-8ce3a0a1c800',
    homepage: 'https://www.bbeglisau.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Brass Band Eglisau\n1938 wurde die Brass Band Eglisau als damalige «Musikgesellschaft Eglisau» gegründet. Seit den Fünfzigerjahren spielt die BBE als einziger Verein im Musikverband Zürcher Unterland in dieser Besetzungsform.\nDie Freude am gemeinsamen Musizieren auf hohem Niveau steht nebst der Pflege der Kameradschaft im Vordergrund für die Aktivmitglieder der BBE. Wir üben fleissig zuhause und proben wöchentlich gemeinsam. Wir konzertieren gerne und oft und nehmen regelmässig an regionalen und nationalen Wettbewerben teil, um wertvolle Standortbestimmungen zu erhalten, welche uns motivieren und in der musikalischen Entwicklung weiterbringen.\nDies fordert den Musikanten, dem Dirigenten und der Vereinsleitung Jahr für Jahr einiges ab. Doch dadurch sind wir in der Lage, auch mit anderen Musikern mannigfaltigster Couleur gemeinsam Konzerte aufzuführen und mit attraktiven Konzertprogrammen das Publikum immer wieder von neuem zu begeistern.\n',
    timetableEntries: [
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:40 - 13:45',
        titel: null,
        description: null,
        programm: [
          {
            id: 263,
            modul: 'D',
            titelName: 'Bundesrat Gnägi',
            composer: 'Albert Benz',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 265,
            modul: 'D',
            titelName: 'Triumph',
            composer: 'Hans Heusser',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Brass Band',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'Sa., 22.06.2024, 19:15 - 20:00',
        titel: 'Music from the North',
        description:
          'Rund um das Aufgabestück «Circius, Wind of the North» wurde ein Programm zusammengestellt, das der Herkunft und dem Charakter des Aufgabestück entspricht. Der langsame Teil von Circius basiert auf dem norwegischen Volkslied «Fiskarens tale til son sin», entsprechend sind auch bei den Selbstwahlstücken Volkslieder oder Volksmusik im Mittelpunkt. Alle Stücke stammen von Komponisten aus dem Norden Europas, deshalb unser Thema «Musik aus dem Norden».',
        programm: [
          {
            id: 258,
            modul: 'A',
            titelName: 'Ardross Castle aus Hymn of the Highlands',
            composer: 'Philippe Spark',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 390,
            pflichtStueck: false,
            infoModeration:
              'Wir beginnen und beenden das Selbstwahlprogramm mit je einem Satz aus «Hymn of the Highlands» von Philipp Sparke. Beiden Stücken liegt die bekannte Melodie «Higland Cathedral» zugrunde. Die beiden Sätze bilden quasi die Klammer um das ganze Programm. Ardross Castle beginnt mit entfernten Klängen des Horns und des Baritons bevor die Dudelsack-Melodie eingeführt wird. Nach einem schnellen Teil mit Material des Anfangs endet das Stück langsam',
            valid: true,
          },
          {
            id: 7,
            modul: 'A',
            titelName: 'Circius',
            composer: 'Torstein Aagard-Nilsen',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 542,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 259,
            modul: 'A',
            titelName: 'A Swedish Folk Song',
            composer: 'Traditionell',
            arrangeur: 'Peter Graham',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'An zweiter Stelle spielen wir das Aufgabestück Circius, gleichzeitig der musikalische Höhepunkt des Programms, anspruchsvoll zum Spielen und Zuhören, genial komponiert. Gemäss Ueberlieferungen aus dem 16. Jahrhundert soll der «Nordwind» grosse Zerstörung an Natur und Siedlungen verursacht haben. Der Mittelteil basiert auf einem einheimischen Volkslied.\nAls Beruhigung folgt das traditionelle «A Swedish Folk Song», welches vom Schotten Peter Graham für BB arrangiert wurde.\n',
            valid: true,
          },
          {
            id: 260,
            modul: 'A',
            titelName: 'Valdres, Norwegian Marsch',
            composer: 'Johannes Hanssen',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 210,
            pflichtStueck: false,
            infoModeration:
              'Valdres von Johannes Hanssen mit dem Untertitel «Norwegischer Marsch» stellt einen stilistischen Farbtupfer im Genre der Märsche dar: gesanglich-elegant, fast synfonisch und doch sehr marschtypisch und volkstümlich.',
            valid: true,
          },
          {
            id: 261,
            modul: 'A',
            titelName: 'Nordic Polka',
            composer: 'Andres Ebenroth/Matti Kallio',
            arrangeur: 'Philipp Harper',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Mit «Nordic Polka» von Andres Ebenroth/Matti Kallio und arrangiert von Philip Harper machen wir einen Abstecher in die unterhaltende Volksmusik. Ein raffiniertes Stück mit vielen solistischen Einlagen und technischen Finessen.',
            valid: true,
          },
          {
            id: 262,
            modul: 'A',
            titelName: 'Dundonnel aus Hymn of the Highlands',
            composer: 'Pilipp Sparke',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 360,
            pflichtStueck: false,
            infoModeration:
              'Mit dem aufregenden «Dundonnell» dem Schlusssatz aus «Hymn of the Highlands» schliessen wir unser Selbstwahlprogramm. Zuerst tönt es martialisch, anschliessend folgt ein wildes Presto bevor das Dudelsackthema von Ardross Castle wieder erscheint, diesmal in einem Grandioso, das den fulminanten Schluss einläutet. ',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 18,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'BRASS_BAND',
        besetzungDescription: 'Brass Band',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Brass Band (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
