export default defineEventHandler(() => {
  return {
    id: 44,
    name: 'Brass Band Maur',
    direktionName: 'Stefanie Gabathuler',
    logoImgId: '65169502-6172-409d-2aba-f65e67083f00',
    bildImgId: '31aadff8-96f5-4b0c-491c-518c18aa3a00',
    homepage: 'https://www.bbmaur.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Brass Band Maur ist ein am Greifensee beheimateter Musikverein mit ca. 20 aktiven Mitgliedern. Diese sind zwischen 13 und 80 Jahre alt und stammen aus der näheren Umgebung. Wir dürfen zudem auf treue MitspielerInnen aus anderen Vereinen zählen, die uns auf verschiedenen Positionen bei Bedarf verstärken.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Brass Band',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'So., 23.06.2024, 13:45 - 14:10',
        titel: 'Es werde Licht',
        description:
          'Unsere Gedanken zum Programm:\n\n«Es werde Licht» ist die Quintessenz aus den letzten ca. 10 Jahren unseres Vereins.\nDie ausgewählten Stücke beschreiben den Werdegang, unsere Botschaft, unsere\nWünsche und Ziele und unsere Funktion in der Gesellschaft.\n\nDie Brass Band Maur ist erst seit ein paar Jahren eine reine Brass Formation, zuvor\nwar sie über 100 Jahre lang eine Harmoniemusik. So sind wir quasi als Entdecker\nunterwegs, möchten Grenzen durchbrechen und neue Wege gehen! Unser Ziel ist\nes, einen klaren, kraftvollen Klang in die Weiten der Schöpfung zu senden und eine\nmitreissende Atmosphäre für unsere Konzertbesucher aber auch uns selbst schaffen\nzu können.\nWir sind neue Wege gegangen, haben uns auf die Suche nach neuen Mitgliedern\nmachen müssen und sind inzwischen zu einem Verein mit Charakter, Humor und viel\nEngagement zusammengewachsen. Jede/r ist willkommen mit allen Stärken und\nSchwächen- wir vereinen viele Geschichten und Charaktere.\n\nSo können wir uns wohl etwas wie Pioniere fühlen und dank einigen Urgesteinen und\nfast schon Dorforiginalen, wie es der Dällenbach Kari, eben der Stärn über Bärn war,\nist die Menschlichkeit und Anteilnahme in unserer Band gross. Zusammen Neues\nerreichen und Bewährtes kultivieren, manchmal majestätisch oder ernst, manchmal\nausgelassen und energiegeladen, wohl grad so, wie’s am Hof von König Henry dem\n8. zu und her ging, so geniessen wir unser Hobby, die Musik als Zeitvertreib in guter\nGesellschaft.\nUnser Programm soll ein Querschnitt durch unsere Literatur zeigen, es beinhaltet\nOriginalwerke, wie auch Arrangements, bei welchen wir jedoch stets Wert auf die\nQualität und nicht die Aktualität legen......\nLassen Sie sich von unserem Feuer und unserer Passion berühren und mitreissen,\nhören Sie, wie wir unsere Geschichte durch die Musik erzählen.',
        programm: [
          {
            id: 9,
            modul: 'A',
            titelName: 'The Pioneers',
            composer: 'Philip Sparke',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 64,
            modul: 'A',
            titelName: 'Es werde Licht',
            composer: 'Udo Jürgens',
            arrangeur: 'Jeremy Stone\t',
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 225,
            pflichtStueck: false,
            infoModeration:
              'Eigentlich ein Weihnachtslied von Udo Jürgens, wie er aber selbst darin singt, wünscht er sich eben Licht, Liebe und Menschlichkeit nicht nur zur Weihnachtszeit. Das berührende Arrangement stammt von Jeremy Stone.',
            valid: true,
          },
          {
            id: 65,
            modul: 'A',
            titelName: 'Stärn über Bärn',
            composer: 'Schneider/Hoffmann',
            arrangeur: 'Corsin Tuor',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration:
              'Aus dem Schweizer Musical «Dällenbach Kari», Kari ist ein Coiffeur Meister mit Lippenspalte und hat es darum besonders schwierig, Anerkennung und Liebe zu finden. In Annemarie, einer Tochter aus gutem Haus, findet er aber dennoch seine grosse Liebe. Deren Eltern aber sind gegen diese Beziehung, in der Folge verfällt Kari immer mehr dem Alkohol und wird dank seinen Geschichten und Anekdoten zum stadtbekannten Original. Schliesslich erkrankt er an Krebs und am 31. Juli 1931 stürzt er sich von der Kornhausbrücke in den Tod. Doch auch nach seinem Tod lebt er als Legende fort und gilt fortan als Stärn über Bärn. Corsin Tuor hat dieses kraftvolle, wunderbare Lied für Brass Band arrangiert.',
            valid: true,
          },
          {
            id: 66,
            modul: 'A',
            titelName: 'Past Time with good Company',
            composer: 'Henry VIII',
            arrangeur: 'T. Cheseaux',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 165,
            pflichtStueck: false,
            infoModeration:
              'Als junger Mann in den frühen Jahren des 16.\nJahrhunderts war der englische König Henry VIII ein begnadeter Sportler, Tänzer\nund Komponist. Seine bekannteste Komposition Pastime with good Company\nversprüht Eleganz und Lebhaftigkeit, sie erzählt von der königlichen Jagd und wurde\nals Hofunterhaltung oft gesungen und gespielt, wie es der Titel sagt, als Zeitvertrieb\nin bester Gesellschaft.',
            valid: true,
          },
          {
            id: 67,
            modul: 'A',
            titelName: 'Brass Ablaze',
            composer: 'Goff Richards',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 220,
            pflichtStueck: false,
            infoModeration:
              'Goff Richards schuf mit diesem Konzert Marsch ein Werk, welches den Klang der Brass Band darin als lichterloh brennendes Messing bezeichnet, mitreissend, energiegeladen mit klarem, kraftvollem Klang.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 20,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'BRASS_BAND',
        besetzungDescription: 'Brass Band',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Brass Band (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
