export default defineEventHandler(() => {
  return {
    id: 65,
    name: 'Fusion Mallets',
    direktionName: 'Simon Forster',
    logoImgId: 'afebfb03-2bb3-49e4-e176-3d40d3807300',
    bildImgId: null,
    homepage: null,
    facebook: null,
    instagram: null,
    websiteText: 'Die Fusion Mallets sind das Perkussionsensemble der Musikschule Weinfelden TG.',
    timetableEntries: [
      {
        modul: 'H',
        competition: 'Perkussionsensembles, Mittelstufe',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:45 - 15:05',
        titel: null,
        description: null,
        programm: [
          {
            id: 372,
            modul: 'H',
            titelName: 'Baya Baya',
            composer: 'Uffe Savery & Morten Friis',
            arrangeur: 'Benjamin Leuschner',
            grad: null,
            schwierigkeitsgrad: 'Mittelstufe',
            durationInSeconds: 360,
            pflichtStueck: false,
            infoModeration:
              'Das Safri-Duo setzt sich aus Uffe Savery und Morten Friis zusammen wobei Safri aus den beiden Nachnamen zusammengesetzt wurde. Beide sind Schulfreunde, die auch zusammen am Königlich Dänischen Konservatorium für Musik ihr Musikdiplom gemacht haben. Seit 1988 haben beide klassische Werke für ihre Perkussion-Musik umgeschrieben und sind damit weltweit aufgetreten. Der Durchbruch kam allerdings erst, als beide ihren Stil änderten und auf Dance-Music umstiegen. \nIhr grösster Erfolg war Played-A-Live (The Bongo Song). Das Lied erreichte 2001 Platz zwei in den deutschen Singlecharts sowie Platz eins der Schweizer Hitparade und der dänischen Charts. Baya Baya ist der dritte Dance-Hit, den Safri Duo veröffentlichte.',
            valid: true,
          },
          {
            id: 373,
            modul: 'H',
            titelName: "Tout l'univers",
            composer: 'Gjon Muharremaj, Nina Sampermans, Wouter Hardy, Xavier Michel',
            arrangeur: 'Bastian J. Purcell',
            grad: null,
            schwierigkeitsgrad: 'Mittelstufe',
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Tout l’univers ist ein Popsong, der vom Schweizer Sänger Gjon’s Tears beim Eurovision Song Contest 2021 in Rotterdam interpretiert wurde.  Er belegte den dritten Platz für die Schweiz.\nDas Lied handelt vom Auf und Ab des Lebenszyklus und der Hoffnung. Es gehe nicht darum, nur nach vorne zu schauen, sondern noch weiter, sprich, das ganze Universum zu betrachten. Weiterhin gehe es darum, dass die wichtigste und stärkste Person in einem Leben man selbst sei und dass es deshalb wichtig sei, sich selbst zu lieben. Wenn man sich nicht selbst respektiere, schlage sich dies in der Moral nieder.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 11,
        modul: 'H',
        modulDescription: 'H - Perkussionsensembles',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'PERKUSSIONSENSEMBLE',
        besetzungDescription: 'Perkussionsensemble',
        category: null,
        categoryDescription: null,
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'H - Perkussionsensembles, Mittelstufe, Perkussionsensemble (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
