export default defineEventHandler(() => {
  return {
    id: 109,
    name: 'Harmonie Freienbach',
    direktionName: 'Christian Bachmann',
    logoImgId: '079d5084-1e31-4f0e-0d6f-d2f5fb27d600',
    bildImgId: 'fff5b327-2dbf-482d-6c17-86667771a000',
    homepage: 'http://www.harmonie-freienbach.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Harmonie Freienbach ist der Musikverein der Gemeinde Freienbach, zu der die fünf Dörfer Pfäffikon, Wilen, Bäch, Hurden und Freienbach gehören. Sie besteht aus rund 45 Mitgliedern und spielt neu in der U-Musik Oberstufe. Die Harmonie Freienbach pflegt die traditionelle und zeitgemässe Blasmusik, ist aber auch offen für andere Stile und Richtungen. Sie bemüht sich um ein attraktives musikalisches Angebot mit einem breiten Spektrum und setzt hohe Qualitätsansprüche an sich selber.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Oberstufe, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'So., 23.06.2024, 11:15 - 11:40',
        titel: 'Vom amerikanischen Funk über den Norden bis zum Broadway',
        description: 'Amerikanischer Funk, nordische Unterhaltungsmusik und Norwegischer Funk im Kontrast zum Broadway. ',
        programm: [
          {
            id: 319,
            modul: 'B',
            titelName: 'In the stone',
            composer: 'Earth, Wind & Fire',
            arrangeur: 'Marcel Saurer',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 188,
            pflichtStueck: false,
            infoModeration:
              'In the stone, einer der ganz grossen Hits der amerikanischen Soul and Funk Band Earth, Wind & Fire in einem Arrngement von Marcel Saurer.',
            valid: true,
          },
          {
            id: 11,
            modul: 'B',
            titelName: 'Halvdan Sivertsen Medley',
            composer: 'Lars Erik Gudim',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 390,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 320,
            modul: 'B',
            titelName: 'Funky Hedde',
            composer: 'Torstein Aagaard-Nilsen ',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: 'Funky Hedde ist eine Funky Version der Norwegischen Melodie "Havard Hedde" die jeden zum Tanzen bringt.',
            valid: true,
          },
          {
            id: 222,
            modul: 'B',
            titelName: 'Wonderful Town',
            composer: 'Leonard Bernstein',
            arrangeur: 'Marcel Saurer',
            grad: 4.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 560,
            pflichtStueck: false,
            infoModeration:
              'Mit dem Musical "Wonderful Town" beschreiben Bernstein, Comden und Green ein musikalisches Portrait Ihrer Heimatstadt New York. Marcel Saurer schuf dieses wunderbare Arrangement dieses etwas weniger bekannten Werkes als die "West Side Story" des gleichen Komponisten.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 16,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'OBERSTUFE',
        klasseDescription: 'Oberstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'B - Unterhaltungsmusik, Oberstufe, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
