export default defineEventHandler(() => {
  return {
    id: 90,
    name: 'Harmonie am Bachtel',
    direktionName: 'Markus Steimen',
    logoImgId: '9cb91f45-2a66-47be-e83e-37d87356e900',
    bildImgId: '2ae1bb39-4a66-4246-c4be-b2fd82dbd400',
    homepage: 'https://www.harmonieambachtel.ch',
    facebook: 'https://www.facebook.com/harmonieambachtel',
    instagram: 'https://www.instagram.com/harmonie_am_bachtel/',
    websiteText:
      'Mit 35 bis 40 Musikantinnen und Musikanten konzertieren wir begeistert mit vielfältiger Literatur konzertante, traditionelle und moderne Blasmusik. Wir nehmen regelmässig an Wettbewerben teil und spielen in der 2. Stärkeklasse mit Harmoniebesetzung.\n\nJährliche Höhepunkte sind die Winterkonzerte in den Kirchen Hinwil und Tann im Januar/Februar, das Frühlingskonzert im Mai/Juni und das Weihnachtskonzert im Dezember. In der Bevölkerung sehr beliebt sind unsere Platzkonzerte im Sommer/Herbst, das Anführen des Räbeliechtli-Umzuges im November oder die eigene Festwirtschaft an der Chilbi Hinwil mit Auftritten von Gastformationen.\n\nDie Freude an der Musik bringt uns zusammen, die generationenübergreifende Kameradschaft formt uns zur Einheit. Gemütlichkeit und Freundschaften pflegen wir an Skiweekends, Grillabenden, Chlausfeieren, Vereinsreisen und natürlich der "Beiz nach der Probe".',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 2. Klasse, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:00 - 09:30',
        titel: 'Helden – gestern und heute',
        description:
          'Die Harmonie am Bachtel präsentiert ein heldenhaftes Konzertprogramm.\n\nEin Held oder eine Heldin ist eine Person, die eine Heldentat, also eine besondere, ausseralltägliche Leistung vollbracht hat. Die heroischen Fähigkeiten können von körperlicher Art zum Beispiel Kraft, Schnelligkeit oder Ausdauer sein, aber auch geistiger Natur, wie Mut, Aufopferungsbereitschaft, Kampf für Ideale oder Einsatzbereitschaft für Mitmenschen.\n\nBei Helden kann es sich um reale oder fiktive Personen handeln, um Gestalten der Geschichte aber auch aus Legenden, Sagen oder fiktiven Werken. \n\n\nUnser Konzert führt von Helden in nordischen Legenden und Sagen, zu Helden unserer Zeit in Form von ganzen Berufsgruppen bis zu einem realen Helden aus der Geschichte.\n\nAurora Borealis – oder auf Deutsch Nordlichter – inspirierten nicht nur die Komponisten wie Rossano Galante sondern auch die nordischen Völker, welche sich dieses unheimliche Geschehen am Himmel mit Legenden und Sagen zu erklären versuchten. Die mutigen Helden aus diesen Geschichten halfen ihnen gegen ihre Ängste.\n  \nQuaranTime wurde von Stephan Hodel während der Corona-Pandemie komponiert. In dieser Zeit wurden durch die Medien ganze Berufsgruppen zu Helden und Heldinnen gemacht.\n\nIn A Hero\'s Tale von Bert Appermont begegnen wir einer realen Person dem deutschen Reitergeneral Hans Michael Elias von Obentraut einem Helden aus der Vergangenheit mit einer dramatischen Geschichte.\n\n\nAurora Borealis oder auf Deutsch Nordlichter – wer kennt sie nicht – von Bildern, aus Filmen, aus Erzählungen oder hat sie gar schon selber erleben können. In Alaska, Kanada, Finnland, Island und Norwegen treten sie besonders häufig auf.\nHeute kann diese Erscheinung wissenschaftlich beschrieben werden. In früheren Zeiten jedoch suchten die Völker in Lappland, Sibirien und Alaska nach Erklärungen für dieses überwältigende Schauspiel am Himmel. Es entstanden verschiedene Legenden und Sagen. Die Menschen glaubten hier Zeichen ihrer Götter zu sehen, die auf diese Weise mit ihnen in Verbindung treten wollten. Die Zeichen galten oft als Vorboten für schlimme Zeiten wie Krieg, Pest, Hungersnot und lösten Ängste aus. \nDie Wikinger beispielsweise erklärten sich dieses Naturschauspiel mit folgender kleiner Geschichte: Sie sahen in den Polarlichtern das Zeichen, dass irgendwo auf der Welt eine große Schlacht geschlagen worden war. Nach ihrer Vorstellung ritten die Walküren – ein weibliches Geistwesen – zu Pferd nach jedem Gefecht über den Himmel und wählten die Helden aus. Diese erwählten Helden durften fortan an Odins Tafel speisen – Odin der Göttervater, Kriegs- und Totengott. Das Licht des Mondes spiegelt sich dabei auf den schimmernden Rüstungen der Helden und dadurch entstanden die bunten Nordlichter.\nNicht nur in der Mythologie, waren und sind die Nordlichter zur inspirierenden Quelle geworden. Auch Rossano Galantes Komposition Aurora Borealis vertont dieses Phänomen. Das üppig gesetzte Hauptthema stellt die glitzernden Nordlichter dar. Dieses Hauptthema ändert sich ständig, wie die Lichter selbst. Das Tongemälde verwandelt sich in eine spannende Vorwärtsbewegung. Es folgt ein romantischer, lyrischer Abschnitt, welcher die Schönheit und das Geheimnis der Nordlichter darstellt. Das Stück gipfelt in einer spannenden Reprise des Hauptthemas, das mit fesselnden Bläserfanfaren endet.\nDieses stimmungsvolle Werk lädt zum Träumen mit geschlossenen Augen ein.\n     \nQuaranTime von Stephan Hodel entstand während des Lockdowns anlässlich der Corona-Pandemie im Frühjahr 2020 – auf welche das Wortspiel im Titel QuaranTime anspielt. Gegen Ende des Werkes nach einem kurzen chaotischen Ausbruch erfolgt ein Stillstand.\nWir alle können uns noch gut an diese Zeit erinnern. Mit einem Mal stand alles still – Lockdown – Stillstand – auch das kulturelle und gesellschaftliche Leben in der Schweiz war von der Corona-Krise stark betroffen. Aber nicht alle Lebensbereiche standen still. Einige Berufsgruppen waren besonders gefordert. Einmal mehr zeigte sich, dass schlechte Zeiten gute Zeiten für Heldengeschichten sind. Sie boomen immer dann, wenn der Alltag ausser Kraft gesetzt ist und den Menschen besondere Zumutungen abverlangt werden. Hierzulande stand das medizinische Personal im Mittelpunkt, des sich rasch ausbreitenden Corona-Heldenkults. Ihr selbstloser Einsatz bestätigt den Ernst der Lage, verbürgt aber auch die Zuversicht, dass die Sache am Ende gut ausgehen wird. Gern wurden militärische Metaphern bemüht: Pflegekräfte und Ärztinnen standen an vorderster Front im Kampf gegen die Seuche. Solange sie die Stellung hielten, war die Schlacht nicht verloren. Weitere systemrelevant Berufsgruppen wurden in den Heldenstand erhoben: zum Beispiel die Supermarktmitarbeiterinnen, die Müllmänner, die Polizistinnen, die LKW-Fahrer, die Altenpflegerinnen. Diese Alltagsheldinnen und -helden verkörperten vor allem Einsatz- und Opferbereitschaft.\nDamit diese Heldinnen und Helden nicht so schnell wieder vergessen gehen, hat beispielsweise Malta im August 2021 eine 2-Euro-Gedenkmünze mit dem Thema "Helden der Pandemie" herausgegeben. Die 2-Euro-Münze stellt eine Hommage an Maltas Gesundheitssektor dar. Es ist ein Zeichen der nationalen Wertschätzung für die selbstlosen Anstrengungen und das Engagement vieler Menschen, die in solch globalen schwierigen Zeiten ihre eigene Gesundheit riskieren.\nTrotz der schwierigen Entstehungsgeschichte versucht das Werk von Stephan Hodel Optimismus zu versprühen, mit der Aussicht auf fröhlichere und unbeschwertere Zeiten.\n\nBert Appermont beschreibt in seinem Werk A Hero\'s Tale verschiedene Aspekte aus dem Leben des deutschen Reitergenerals Hans Michael Elias von Obentraut der von 1574 bis 1625 lebte. Er war für seine Nervenstärke, seine Loyalität und seinen Mut bekannt. General von Obentraut starb einen Heldentod in der Stadt Seelze unweit von Hannover. An der Stelle, an der er tödlich verwundet wurde, steht ihm zu Ehren ein Denkmal. \nDie Vier Sätze dieser Komposition führen uns durch sein Leben und Wirken. Eine majestätische Hymne entführt uns im ersten Satz (Opening & Hymn for a Hero) in die Vergangenheit. Seine Kindheit verbrachte er auf der Stromburg bei Stromberg. Dieser ist der zweite Satz (Stromburg Castle) gewidmet. Darin erklingt ein Tanzthema im Renaissancestil. Der dritte Satz (The Battle of Seelze) handelt von der dramatischen Geschichte seiner letzten Schlacht.\nVon Obentraut wollte die besetzte Festung Calenberg einnehmen. Jedoch kam es bei Seelze zwischen seiner Einheit mit 700 Reitern und Tillys Heer von 10.000 Mann zu einem Kampf. Als Obentraut davon erfuhr, soll er der Sage nach seiner Truppe so schnell zur Hilfe geeilt sein, dass er ohne Helm und nur mit einem Stiefel los ritt. Im Gefecht wurde er von einer Kugel tödlich getroffen. Er soll im Beisein von Tilly –seinem früheren Waffenbruder und aktuellen Anführer des feindlichen Heers –gestorben sein, der ihm die Augen geschlossen habe. Der Leichnam Obentrauts wurde in die Festung Calenberg gebracht und erst vier Monate später im Austausch gegen einen führenden Offizier herausgegeben. Alles in allem ein dramatischer heldenhafter Tod.\nDie geradezu mythische Verehrung, die Obentraut bereits zu Lebzeiten genoss, setzte sich über den Tod hinaus in verschiedenen Werken fort – auch in Appermonts Komposition speziell im vierten Satz (The Legend Continues) – hier mittels einer erweiterten Version der Hymne. Ein wahrer Held, der über seinen Tod hinaus verehrt wird.\n\nDieses Konzertprogramm zeigt eine breite musikalische Vielfalt und ein grosses Spektrum der Harmonie am Bachtel.',
        programm: [
          {
            id: 155,
            modul: 'A',
            titelName: 'Aurora Borealis',
            composer: 'Rossano Galante',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 390,
            pflichtStueck: false,
            infoModeration:
              'Aurora Borealis oder auf Deutsch Nordlichter – wer kennt sie nicht – von Bildern, aus Filmen, aus Erzählungen oder hat sie gar schon selber erleben können. In Alaska, Kanada, Finnland, Island und Norwegen treten sie besonders häufig auf.\nHeute kann diese Erscheinung wissenschaftlich beschrieben werden. In früheren Zeiten jedoch suchten die Völker in Lappland, Sibirien und Alaska nach Erklärungen für dieses überwältigende Schauspiel am Himmel. Es entstanden verschiedene Legenden und Sagen. Die Menschen glaubten hier Zeichen ihrer Götter zu sehen, die auf diese Weise mit ihnen in Verbindung treten wollten. Die Zeichen galten oft als Vorboten für schlimme Zeiten wie Krieg, Pest, Hungersnot und lösten Ängste aus. \nDie Wikinger beispielsweise erklärten sich dieses Naturschauspiel mit folgender kleiner Geschichte: Sie sahen in den Polarlichtern das Zeichen, dass irgendwo auf der Welt eine große Schlacht geschlagen worden war. Nach ihrer Vorstellung ritten die Walküren – ein weibliches Geistwesen – zu Pferd nach jedem Gefecht über den Himmel und wählten die Helden aus. Diese erwählten Helden durften fortan an Odins Tafel speisen – Odin der Göttervater, Kriegs- und Totengott. Das Licht des Mondes spiegelt sich dabei auf den schimmernden Rüstungen der Helden und dadurch entstanden die bunten Nordlichter.\nNicht nur in der Mythologie, waren und sind die Nordlichter zur inspirierenden Quelle geworden. Auch Rossano Galantes Komposition Aurora Borealis vertont dieses Phänomen. Das üppig gesetzte Hauptthema stellt die glitzernden Nordlichter dar. Dieses Hauptthema ändert sich ständig, wie die Lichter selbst. Das Tongemälde verwandelt sich in eine spannende Vorwärtsbewegung. Es folgt ein romantischer, lyrischer Abschnitt, welcher die Schönheit und das Geheimnis der Nordlichter darstellt. Das Stück gipfelt in einer spannenden Reprise des Hauptthemas, das mit fesselnden Bläserfanfaren endet.\nDieses stimmungsvolle Werk lädt zum Träumen mit geschlossenen Augen ein.',
            valid: true,
          },
          {
            id: 3,
            modul: 'A',
            titelName: 'QuaranTime',
            composer: 'Stephan Hodel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 459,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 156,
            modul: 'A',
            titelName: 'A Hero’s Tale',
            composer: 'Bert Appermont',
            arrangeur: null,
            grad: 4.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 660,
            pflichtStueck: false,
            infoModeration:
              "Bert Appermont beschreibt in seinem Werk A Hero's Tale verschiedene Aspekte aus dem Leben des deutschen Reitergenerals Hans Michael Elias von Obentraut der von 1574 bis 1625 lebte. Er war für seine Nervenstärke, seine Loyalität und seinen Mut bekannt. General von Obentraut starb einen Heldentod in der Stadt Seelze unweit von Hannover. An der Stelle, an der er tödlich verwundet wurde, steht ihm zu Ehren ein Denkmal. \nDie Vier Sätze dieser Komposition führen uns durch sein Leben und Wirken. Eine majestätische Hymne entführt uns im ersten Satz (Opening & Hymn for a Hero) in die Vergangenheit. Seine Kindheit verbrachte er auf der Stromburg bei Stromberg. Dieser ist der zweite Satz (Stromburg Castle) gewidmet. Darin erklingt ein Tanzthema im Renaissancestil. Der dritte Satz (The Battle of Seelze) handelt von der dramatischen Geschichte seiner letzten Schlacht.\nVon Obentraut wollte die besetzte Festung Calenberg einnehmen. Jedoch kam es bei Seelze zwischen seiner Einheit mit 700 Reitern und Tillys Heer von 10.000 Mann zu einem Kampf. Als Obentraut davon erfuhr, soll er der Sage nach seiner Truppe so schnell zur Hilfe geeilt sein, dass er ohne Helm und nur mit einem Stiefel los ritt. Im Gefecht wurde er von einer Kugel tödlich getroffen. Er soll im Beisein von Tilly –seinem früheren Waffenbruder und aktuellen Anführer des feindlichen Heers –gestorben sein, der ihm die Augen geschlossen habe. Der Leichnam Obentrauts wurde in die Festung Calenberg gebracht und erst vier Monate später im Austausch gegen einen führenden Offizier herausgegeben. Alles in allem ein dramatischer heldenhafter Tod.\nDie geradezu mythische Verehrung, die Obentraut bereits zu Lebzeiten genoss, setzte sich über den Tod hinaus in verschiedenen Werken fort – auch in Appermonts Komposition speziell im vierten Satz (The Legend Continues) – hier mittels einer erweiterten Version der Hymne. Ein wahrer Held, der über seinen Tod hinaus verehrt wird.",
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:50 - 14:55',
        titel: null,
        description: null,
        programm: [
          {
            id: 157,
            modul: 'D',
            titelName: 'Diavolezza',
            composer: 'Adolf Künzle',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 189,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 158,
            modul: 'D',
            titelName: 'Papstein Marsch',
            composer: 'Fritz Hanusch',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 3,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_2',
        klasseDescription: '2. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'A - Konzertmusik, 2. Klasse, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
