export default defineEventHandler(() => {
  return {
    id: 61,
    name: 'Harmonie Eintracht Männedorf',
    direktionName: 'Sebastian Rauchenstein',
    logoImgId: '0bfb0a5c-dcdb-4d73-cfab-c2e4beb1a600',
    bildImgId: 'd0a0cf0f-78d4-4822-134c-b3b220eb3700',
    homepage: 'https://www.musikverein-maennedorf.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Harmonie Eintracht Männedorf, kurz HEM, ist DER Musikverein am rechten Zürichseeufer!\n• DER mit knapp 50 Mitgliedern und einer ausgewogenen Besetzung;\n• DER mit vielen jungen und motivierten Musikern/-innen;\n• DER mit einem riesigen Zusammenhalt und einem ausgesprochenen Sinn fürs Gemeinsame;\n• DER, welcher abwechslungsreiche und mitreissende Literatur spielt – eine Jahreshälfte ist bei uns jeweils der konzertanten, eine der unterhaltenden Blasmusik gewidmet;\n• DER, welcher erstklassige Literatur der 2. und 3. Stärkeklasse spielt;\n• DER mit lokaler Verankerung, welcher kontinuierlich im Austausch mit der Musikschule, der Jugendmusik und der Bevölkerung steht;',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 11:00 - 11:25',
        titel: 'Die Natur und die Kraft des Lebens',
        description:
          'Der Musikverein Harmonie Eintracht Männedorf, kurz: HEM, ist DER Musikverein am rechten Zürichseeufer! In ihrem Konzertprogramm für das Zürcher Kantonalmusikfest beschäftigt sich die HEM mit einem der grössten Themen überhaupt: Mit der Natur und der Kraft des Lebens.\n\nIm ersten Vortragsstück "Blue Outer Space - Droplet of Life" drückt die HEM die Gedanken des japanischen Komponisten Satoshi Yagisawa zum Universum und zur Bedeutung des Lebens in der Form von sphärischen und chorischen Klängen aus. Sodann präsentiert die HEM ihre Interpretation des Aufgabenstücks "May the Forest Bloom Again" von Théo Schmitt, in welchem Waldbrände und deren verheerende Folgen Umwelt und Klima, aber auch die Regeneration und Resilienz der Natur geschildert werden. Mit dem Stück "Mountain Thyme" von Samuel Hazo rundet die HEM ihr Programm ab und lässt den Konzertsaal in hoffnungsvollem Glanz erstrahlen - kraftvoll und majestätisch, wild und unzähmbar wie die Natur.\n\nIn den präsentierten Werken wird den Zuhörenden und den Musiker:innen die unbändige Macht und Kraft der Natur über die Menschen bewusst. Zwar ist unser Planet Erde Teil des Universums - allerdings sind wir nur ein sehr kleiner Teil eines viel grösseren Ganzen. Und obwohl wir Menschen unseren eigenen Planeten beherrschen möchten, zeigt uns die Natur beispielsweise durch Stürme, Brände, Fluten, Vulkanausbrüche oder Erdbeben, dass sie mit ihrer brachialen Kraft den Menschen überlegen ist. Mit ihrem Konzertprogramm zeigt die HEM jedoch , dass die Kraft der Natur nicht immer zerstörerisch sein muss, sondern dass unsere resiliente und regenerative Umwelt für die Menschen auch eine Quelle der Inspiration und des Lebens darstellt.\n\nDie HEM wünscht viel Vergnügen mit ihrem Konzertprogramm "Die Natur und die Kraft des Lebens"!',
        programm: [
          {
            id: 86,
            modul: 'A',
            titelName: 'Blue Outer Space - Droplet of Life',
            composer: 'Satoshi Yagisawa',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 510,
            pflichtStueck: false,
            infoModeration:
              'Mit seiner Komposition "Blue Outer Space - Droplet Of Life" möchte der Komponist Satoshi Yagisawa dem Publikum die Möglichkeit geben, über die Bedeutung der Erde und des Lebens nachzudenken. \n\nDas Werk besteht aus fünf Sätzen: I. Der Beginn des Universums, II. Kollision von Asteroiden, III. Die Erschaffung der Erde, IV. Planet des Wassers: Die Erde, V. Dankbarkeit für alle Formen des Lebens. Die Musik ist im Chorstil geschrieben und bringt die Kostbarkeit des Lebens zum Ausdruck.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 87,
            modul: 'A',
            titelName: 'Mountain Thyme',
            composer: 'Samuel R. Hazo',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              'Samuel Hazo bearbeitete für dieses Werk das traditionelle Stück "The Braes o\' Balquhither", auch bekannt als "Wild Mountain Thyme", des Schottischen Dichters Robert Tannahill. Mit stetig wechselnden Texturen, farbiger Instrumentation und imposanter Dynamik verleiht der Komponist dem Volkslied einen wunderbaren Glanz und macht das Stück zu einem tollen Erlebnis für die Musizierenden und das Publikum zugleich.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:00 - 14:05',
        titel: null,
        description: null,
        programm: [
          {
            id: 234,
            modul: 'D',
            titelName: 'Marsch der Grenadiere',
            composer: 'Hans Honegger',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 235,
            modul: 'D',
            titelName: "That's the Way",
            composer: 'Harry Wayne Casey/Richard Finch',
            arrangeur: 'Victor Lopez',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 90,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
