export default defineEventHandler(() => {
  return {
    id: 54,
    name: 'Harmoniemusik-Wald',
    direktionName: 'Salvatore Cicero',
    logoImgId: '8db647ea-f0a2-4ea7-a19c-15522e4ba700',
    bildImgId: 'd0b5f708-8ddf-4c2e-8a89-2a82e927ab00',
    homepage: 'https://www.harmoniemusik-wald.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'www.harmoniemusik-wald.ch\n1875 gegründet, sind wir heute eine aktive, dynamische und motivierte Harmoniemusik aus dem ZH - Oberland. Unterhaltungsmusik ist die Leidenschaft unserer gut 30 Musikantinnen und Musikanten aller Altersstufen. Wir unterhalten unser Publikum mit musikalischen Leckerbissen verschiedenster Genres und scheuen uns auch nicht, unkonventionelle Gastkünstler zu Konzerten einzuladen.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:35 - 09:55',
        titel: 'Tanz durch die Jahrzehnte',
        description:
          "Wir nehmen mit unserem Selbstwahl Programm das Motto des ZKMF, 'Musik bewegt' auf und spielen 'tanzbare' Songs. Was gibt es Schöneres, als sich beim Tanzen von der Musik inspirieren zu lassen? \nDer rote Faden im Wettspielprogramm der Harmoniemusik Wald ZH bildet der \"Tanz durch die Jahrzehnte\". In der Musik von 'Earth, Wind and Fire', Gloria Gaynor, Bruno Mars sowie dem Pflichtstück 'We'll make it work' spürt man, dass in den 70er Jahren bis zur heutigen Zeit noch immer das selbe gilt: Tanzmusik tut nicht nur dem Körper gut, sondern dient ebenso als Erfrischungsquelle für den Geist und die Seele. \n\nDiese Gefühle möchte wir den ZuhörerInnen mit Unserm U-Musik Programm vermitteln. Gespielt wird....\n",
        programm: [
          {
            id: 184,
            modul: 'B',
            titelName: 'In the Stone',
            composer: 'M.White, D. Forster, A. Willis',
            arrangeur: 'G.Tinner',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 160,
            pflichtStueck: false,
            infoModeration: 'Prägnante Eröffnungsnummer von Earth Wind and Fire aus den 70er Jahren',
            valid: true,
          },
          {
            id: 185,
            modul: 'B',
            titelName: 'I Will survive',
            composer: 'D.Fekaris, F.Perren',
            arrangeur: 'J.G. Mortimer',
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 220,
            pflichtStueck: false,
            infoModeration: 'Tanznummer von Gloria Gaynour, ebenfalls aus den 70er Jahren',
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 186,
            modul: 'B',
            titelName: 'Uptown Funk',
            composer: 'B. Mars, M. Ronson',
            arrangeur: 'S. Cicero',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 255,
            pflichtStueck: false,
            infoModeration: 'Tanznummer von Bruno Mars aus dem Jahr 2014 (jüngere Vergangenheit)',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:20 - 14:25',
        titel: null,
        description: null,
        programm: [
          {
            id: 187,
            modul: 'D',
            titelName: 'Arosa',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 188,
            modul: 'D',
            titelName: "It's my Life",
            composer: 'J.B.Jovi, R.Sambora, M.Sandberg',
            arrangeur: 'M. Conaway',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 140,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
