export default defineEventHandler(() => {
  return {
    id: 96,
    name: 'Harmonie Eintracht Küsnacht',
    direktionName: 'Christian Meier',
    logoImgId: '14fd9dfe-5a8e-47ac-df27-4a0b8ea3f300',
    bildImgId: '671f325b-e7cb-4054-1c76-56453a140200',
    homepage: 'https://www.harmonie-kuesnacht.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die HEK ist trotz ihrer langen Vereinsgeschichte ein dynamischer und jung gebliebener Verein. Im Frühling sowie im Herbst erfreuen wir das Publikum mit einem Konzert, dazwischen sind wir auch an diversen Dorfanlässen anzutreffen.\nSelbstverständlich gibt es auch bei uns Gelegenheiten, bei denen wir die Instrumente zu Hause lassen. Ski-Weekend, Grillabende, Musikreise und andere Anlässe, die unsere "Vereins-Chemie" im positiven Sinne beeinflussen.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 13:45 - 14:10',
        titel: 'Mensch und Natur',
        description:
          'Das Konzert umfasst die Themen Naturgewalten, Seefahrt und menschliche Erfahrung.\n\nDas erste Stück "May the Forests Bloom Again" beschreibt einen Waldbrand und thematisiert die – hauptsächlich durch menschliche Aktivität verursachte - Zerstörung und die Hoffnung auf Wiederaufbau.\nEs verdeutlicht die Zerbrechlichkeit der Natur, aber auch deren fantastischen Fähigkeit zur Wiedergeburt.\n\nVom Land geht’s direkt aufs Wasser. \nDas zweite Stück symbolisiert die Verbindung zwischen Natur und dem menschlichen Handeln. \nDer Komponist Markus Götz thematisiert in "Waterkant!" die Seefahrt und das maritime Leben. \nDas schwankende Klima des Meeres kommt ebenso zur Geltung wie das spannende Matrosen-Dasein.\n\nZum Abschluss des Konzertes knüpfen drei Sätze aus "An English Sea Song Suite" von Philip Sparke dem Treiben auf dem Meer an. \nSie schildern die menschlichen Aktivitäten auf der See und bringen die Freude und den Stolz der Seefahrt passend zum Ausdruck.',
        programm: [
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 166,
            modul: 'A',
            titelName: 'Waterkant!',
            composer: 'Markus Götz',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 420,
            pflichtStueck: false,
            infoModeration: 'siehe bei Erläuterungen zum Selbstwahlprogramm',
            valid: true,
          },
          {
            id: 167,
            modul: 'A',
            titelName: 'An English Sea Song Suite - 1. Satz: The Saucy Arethusa',
            composer: 'Philip Sparke',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 120,
            pflichtStueck: false,
            infoModeration: 'siehe bei Erläuterungen zum Selbstwahlprogramm',
            valid: true,
          },
          {
            id: 168,
            modul: 'A',
            titelName: 'An English Sea Song Suite - 3. Satz: Tom Bowling',
            composer: 'Philip Sparke',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: 'siehe bei Erläuterungen zum Selbstwahlprogramm\n',
            valid: true,
          },
          {
            id: 169,
            modul: 'A',
            titelName: "An English Sea Song Suite - 4. Satz: Jack's the Lad",
            composer: 'Philip Sparke',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: 'siehe bei Erläuterungen zum Selbstwahlprogramm',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
