export default defineEventHandler(() => {
  return {
    id: 110,
    name: 'Harmonie Zumikon',
    direktionName: 'Sandro Pfister',
    logoImgId: '2bffb8d6-a146-4343-31c8-6fc2b42dc000',
    bildImgId: 'ac650a53-6186-4d20-2752-3d8b8df85200',
    homepage: 'https://harmonie-zumikon.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir sind ein Verein mit motivierten Musikantinnen und Musikanten.\nUnsere Hauptziele sind das gemeinsame Musizieren und die Höhepunkte im Musikjahr: das Jahreskonzert im Frühsommer, das Jubilarenkonzert im Oktober, sowie das Adventskonzert vor Weihnachten in der Kirche.\nNatürlich engagieren wir uns darüber hinaus überall dort, wo in Zumikon etwas läuft - oder zum Laufen gebracht werden soll.\nUnsere Konzerte und Auftritte sollen einem breiten Publikum einen abwechslungsreichen und gehörfälligen Musikgenuss bieten - dann macht es auch uns Spass!',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:20 - 15:40',
        titel: 'Harmonie in der Sommerbrise',
        description:
          'Das Konzertprogramm "Harmonie in der Sommerbrise" präsentiert eine vielfältige Auswahl an Stücken, die die Zuhörer auf eine musikalische Reise mitnehmen. Vom lebhaften "Watermelon Man" über die schwelgende Melodie von "Harmony" bis zur ansteckenden Energie von "You Can\'t Stop the Beat", werden die verschiedenen Facetten der Harmonie im Blasorchester hervorgehoben. Das Motto "Musik, die wie eine erfrischende Wassermelone an einem warmen Tag ist" symbolisiert die Freude, die diese Stücke verbreiten, und die Vorfreude auf den Sommer.',
        programm: [
          {
            id: 68,
            modul: 'B',
            titelName: 'Watermelon Man',
            composer: 'Herbie Hancock',
            arrangeur: 'Markus Götz',
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Der US-amerikanische Komponist und Jazz-Pianist Herbert Jeffrey "Herbie" Hancock wurde am 12. April 1940 in Chicago geboren. Viele seiner Kompositionen sind Klassiker geworden, so auch der der Watermelon Man, der 1962 erstmals auf dem Album "Takin\' Off" veröffentlicht wurde. Herbie Hancock erzählt selbst über die Entstehung des Watermelon Man, dass die Melodie aus dem Ausruf eines Wassermelonenverkäufers stamme, den er in seiner Jugend gehört habe. ',
            valid: true,
          },
          {
            id: 69,
            modul: 'B',
            titelName: 'Harmony',
            composer: 'Artie Kaplan',
            arrangeur: 'Don Campbell',
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 155,
            pflichtStueck: false,
            infoModeration:
              'Dieses optimistische Lied erschien 1973 auf einem Album von Artie Kaplan mit dem Titel Confessions of a Male Chauvinist (Bekenntnisse eines männlichen Chauvis). Harmony war ein unmittelbarer Erfolg, der bis heute nicht vergessen ist. Don Campbells Bearbeitung wird dem Original voll und ganz gerecht.',
            valid: true,
          },
          {
            id: 70,
            modul: 'B',
            titelName: 'Rock Fever',
            composer: 'Dominique Wyckhuys',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration:
              "Zu diesem Stück gibt es nicht viel zu sagen, denn der Titel sagt schon alles. Der starke Rockcharakter der Musik fängt die Energie des Rock'n'Roll ein und bringt die Bühne zum Beben. ",
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 71,
            modul: 'B',
            titelName: "You Can't Stop the Beat",
            composer: 'Marc Shaiman, Scott Wittman',
            arrangeur: 'Ted Ricketts',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 175,
            pflichtStueck: false,
            infoModeration:
              "Das Musical Hairspray wurde 2002 in New York am  Broadway uraufgeführt und lief dort mit mehr als 2500 Vorstellungen bis 2009. Es beruht auf dem 1988 entstandenen Film Hairspray von John Waters. Die deutschsprachige Uraufführung fand am 15. April 2008 im Theater St. Gallen statt. Der aus diesem Musical stammende Showstopper “You Can't Stop the Beat“ setzt den letzten Höhepunkt des Programms.",
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
