export default defineEventHandler(() => {
  return {
    id: 84,
    name: 'Harmoniemusik Helvetia Horgen',
    direktionName: 'Schmid Peter',
    logoImgId: '8a1fce0d-9a00-49b4-55b2-24ef81092d00',
    bildImgId: '121c917e-b3fc-4015-9b09-7290e3065600',
    homepage: 'https://www.harmonie-horgen.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Als Blasmusikverein aus Horgen am Zürichsee spielen wir in klassischer Harmoniebesetzung und fokussieren unsere Konzerte und Auftritte hauptsächlich auf Horgen und die nähere Umgebung.\n\nUnsere Vision: Wir sind das Blasorchester für unvergessliche musikalische Höhenflüge für alle. Um dieses Ziel zu erreichen, umfasst unser Repertoire verschiedenste Literatur für Konzerte und Ständchen und wir suchen aktiv die Zusammenarbeit mit anderen Vereinen, Musikern und Künstlern, um unserem Publikum und auch unseren Mitgliedern immer wieder neue musikalische Erlebnisse und ein abwechslungsreiches Programm bieten zu können.\n\nIm Sinne einer nachhaltigen Nachwuchsförderung und mit dem Ziel Jugendlichen eine sinnvolle Freizeitbeschäftigung zu ermöglichen, arbeiten wir eng mit der Kadettenmusik Horgen zusammen und unterstützen diese aktiv in ihren Bestrebungen zur Ausbildung junger Musikantinnen und Musikanten.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'Sa., 22.06.2024, 11:15 - 12:00',
        titel: 'Musica Espagnola – Eine Hommage an die Vielfalt der spanischen Musik',
        description:
          'Mit der Anmeldung der Harmoniemusik Helvetia Horgen ans 31. Zürcher Kantonalmusikfest 2024 in Urdorf & Schlieren, wurde uns das Werk\n«La Mesquita de Cordoba» der Amerikanerin Julie Giroux zugewiesen. Giroux widmet Ihre Komposition diesem einzigartigen Bauwerk und erzählt die Geschichte der Moschee (Bauzeit 40 Jahre) auf musikalische Weise. Es gelingt ihr die Musik der diversen Machthaber Cordobas (Römer, Mauren, Spanier) in ein fesselndes Werk zu packen.\nDie Harmoniemusik Helvetia integriert dieses grossartige Werk in Ihr Konzertprogramm und lässt die stilistische Vielfalt der spanischen Musik hochleben. Zur Aufführung gelangen Komponisten aus vergangener Zeit wie der Madrilene Géronimo Giménez (1854-1923), sowie zeitgenössische Blasorchester Komponisten wie Teo Aparicio Barberán (1967-), Saül Gómez Soler (1982-). Abgerundet wird das Programm mit dem Finale aus dem Werk "Trips" von Oscar Navarro (1981-).\n\nEs ist ein in sich stimmiges Programm entstanden, welches sowohl Publikum wie Musikerinnen und Musiker begeistert.\n ',
        programm: [
          {
            id: 203,
            modul: 'A',
            titelName: 'Portraits of Spain',
            composer: 'Teo Aparicio Barberán',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 578,
            pflichtStueck: false,
            infoModeration:
              'Dieses Werk vom spanischen Komponisten und Dirigenten Teo Aparicio Barberán ist eine musikalische Fantasie, die auf verschiedenen typisch spanischen Musikstilen basiert. Es beginnt mit einer Seguidilla im charakteristisch mitreißenden Rhythmus. Danach bringt eine wunderschöne, fast exotische andalusische Romance eine völlig andere musikalie ins Spiel. Schließlich darf auch der Fandango, einer der bekanntesten Tänze Spaniens, nicht fehlen. Zum Schluss erklingt eine mediterran angehauchte Copla.',
            valid: true,
          },
          {
            id: 2,
            modul: 'A',
            titelName: 'La Mezquita de Cordoba',
            composer: 'Julie Giroux',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 701,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 204,
            modul: 'A',
            titelName: 'Gioia',
            composer: 'Saül Gómez Soler',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 285,
            pflichtStueck: false,
            infoModeration:
              "Das neue Werk des jungen Spaniers Saul Gomez Soler, überzeugt durch eine neue, überraschende Klangsprache. \nDer musikalische Diskurs wurde aus einem kleinen Motiv entwickelt, das im gesamten Stück auftaucht, um große lyrische Linien zu schaffen und die Klangfülle und Eleganz des ganzen Blasorchesters zu nützen. Die Werk wurde von der 'Banda Municipal de Vitoria-Gasteiz' und ihrem Dirigenten Luis Orduña in Auftrag gegeben.",
            valid: true,
          },
          {
            id: 205,
            modul: 'A',
            titelName: 'Intermedio',
            composer: 'Gerónimo Giménez',
            arrangeur: 'Eduardo Suba',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 239,
            pflichtStueck: false,
            infoModeration:
              'Das vorliegende Werk für Solo-Gitarre, ist ein « Intermedio » (Zwischenspiel) aus dem bekannten Werk « Die Hochzeit des Louis Alonzo ». \nDer Komponist Gimenez, erlangte Weltruhm mit diesem Werk, welches in allen Möglichen Besetzungen gespielt wird. Gimenez lebte von 1854 bis 1923 in Sevilla (Spanien).\nGeniessen Sie diese äusserst spezielle Kombination – Gitarre und Blasorchester. Unsere Solistin ist : Deborah Mariotti',
            valid: true,
          },
          {
            id: 206,
            modul: 'A',
            titelName: 'Finale from « Trips »',
            composer: 'Oscar Navarro',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 330,
            pflichtStueck: false,
            infoModeration:
              'Oscar Navarro komponierte das Werk "Trips" (Reisen) in den Sommermonaten 2005, während er verschiedenen Städten in Spanien und Deutschland besuchte. Wir werden das Finale ab Takt 52 im zweiten Teil spielen, welches an die ständige Hektik und Aufregung des Reisens erinnert wie Autos, Gepäck, und Eile. Ein emotionaler und fulminanten Abschluss unserer Aufführung.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:50 - 15:55',
        titel: null,
        description: null,
        programm: [
          {
            id: 209,
            modul: 'D',
            titelName: 'Bundesrat Gnägi-Marsch',
            composer: 'Alfred Benz',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 210,
            modul: 'D',
            titelName: 'Marsch Des Geb Füs Bat 48',
            composer: 'Hans Flury',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 148,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 13,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
