export default defineEventHandler(() => {
  return {
    id: 27,
    name: 'Harmonie Wetzikon',
    direktionName: 'Roman Christoffel',
    logoImgId: '7bbad14d-427b-43a1-1f00-314c7f2c0700',
    bildImgId: '1a48cb98-e56c-478b-6fb9-45e729a5d100',
    homepage: 'https://www.harmonie-wetzikon.ch',
    facebook: 'https://www.facebook.com/harmoniewetzikon',
    instagram: 'https://www.instagram.com/harmoniewetzikon',
    websiteText:
      'Die "Harmonie Wetzikon" ist ein Verein mit einer beeindruckenden Geschichte. Im Jahr 1875 gegründet, ist sie seitdem ein fester Bestandteil der musikalischen Kultur in Wetzikon. Mit rund 45 engagierten Mitgliedern zeigt sich die Harmonie als starke und vielfältige Musikgemeinschaft.\nWas die Harmonie Wetzikon besonders auszeichnet, ist ihr breit gefächertes musikalisches Repertoire. Von der klassischen konzertanten Blasmusik bis hin zu modernsten Unterhaltungsshows beherrscht der Verein eine enorme Diversität an musikalischen Genres. Die Mitglieder sind stolz darauf, ein breites Spektrum an musikalischen Erlebnissen bieten zu können, das für jeden Geschmack etwas bereithält. Ob bei den Hauptkonzerten, lokalen Veranstaltungen oder bei Platzkonzerten, die Harmonie Wetzikon weiss das Publikum zu begeistern und in eine Welt der Klänge und Emotionen zu entführen. Bei der Darbietung von Unterhaltungsmusik blickt die Harmonie Wetzikon auf rund zehn spezielle Jahre zurück, in welchen sie sich getreu nach dem Motto «GANZ ANDERSCH» zu einer modernen Unterhaltungs-Band entwickelt hat. So werden regelmässig Konzerte mit Gastkünstlern und jeder Menge Unterhaltungstechnik durchgeführt.\nTrotz ihrer langen Tradition ist die Harmonie Wetzikon stets offen für neue Ideen und Innovationen. Der Verein bietet jungen Talenten die Möglichkeit, ihre musikalischen Fähigkeiten weiterzuentwickeln und Teil einer lebendigen musikalischen Gemeinschaft zu sein. Lassen Sie sich überzeugen und geniessen Sie modernste Blasmusik.\n',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:00 - 09:20',
        titel: 'Music Was My First Love',
        description:
          'Die Liebe zur Musik ist das, was wir leben und was wir dem Publikum mitgeben. Emotionen erleben ist unser Motto und mit diesem Programm spielen wir uns in die Herzen der Zuhörer. Lassen sie sich von der Harmonie mitreissen und erleben sie die Show in einem Block.',
        programm: [
          {
            id: 48,
            modul: 'B',
            titelName: 'Music was My First Love',
            composer: 'John Miles',
            arrangeur: 'Marcel Saurer',
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration:
              '"Music Was My First Love", Titelgeber unserer Show, bringt unser Motto zum Ausdruck. Das Trompetenregister spielt sich gleich zu Beginn der Show in eure Herzen und die ganze Harmonie reisst sie, liebes Publikum, in einen fulminanten Start der Show.',
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 49,
            modul: 'B',
            titelName: 'The Rose',
            composer: 'Amanda McBroom',
            arrangeur: 'Roman Christoffel',
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: false,
            infoModeration:
              'Etwas ruhiger geht es weiter mit «The Rose». Unsere Sängerin Eva Pearlman bringt mit dieser wunderbare Country-Ballade, gebettet in einem perfekt abgestimmten Arrangement, einmal mehr die Liebe zur Musik zum Ausdruck. ',
            valid: true,
          },
          {
            id: 50,
            modul: 'B',
            titelName: "Old Time Rock'n'Roll",
            composer: 'Bob Seger',
            arrangeur: 'Roman Christoffel',
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 195,
            pflichtStueck: false,
            infoModeration:
              "Mit «Old Time Rock’n Roll» bleibt niemand ruhig auf seinem Stuhl sitzen. Wie damals Bob Seger mit seiner Silver Bullet Band, reisst sie heute die Harmonie Wetzikon von den Hockern. Allen voran Eva Pearlman am Gesang sowie die Solisten Ralf Gübeli am Piano und Daniel Ziegler an der Trompete. Lasst euch von der Musik mitreissen und erleben sie Rock'n'Roll pur!",
            valid: true,
          },
          {
            id: 51,
            modul: 'B',
            titelName: 'On Fire',
            composer: 'Michael Geisler',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration:
              'Mit der feurigen Originalkomposition von Michael Geisler, bringt euch die Harmonie Wetzikon zum Höhepunkt und Abschluss der Show. Mit Solo-Passagen von Daniel Ziegler an der Trompete und Silvan Dietliker an den Drums wird nochmals mit den Emotionen gespielt und lässt Gänsehaut-Effekte erzeugen. Ein fulminantes musikalisches Feuerwerk findet hiermit seinen Abschluss: Music Was My First Love.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:10 - 14:15',
        titel: null,
        description: null,
        programm: [
          {
            id: 46,
            modul: 'D',
            titelName: "All's was bruchsch uf dr Welt",
            composer: 'Ernst Jakober',
            arrangeur: 'Christoph Walter',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 47,
            modul: 'D',
            titelName: 'Happy Marching Band',
            composer: 'Siegfried Rundel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
