export default defineEventHandler(() => {
  return {
    id: 95,
    name: 'Harmonie Pfäffikon',
    direktionName: 'Marco Liechti',
    logoImgId: 'fc28f45d-99c5-493b-9b97-906dd5110c00',
    bildImgId: 'fb4c3515-bbbb-483c-b13c-af8173d7ff00',
    homepage: 'https://www.harmonie-pfaeffikon.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Harmonie Pfäffikon ist 3. Klass-Verein in Harmoniebesetzung und zählt 30 junge und junggebliebene Mitglieder. Seit Mitte Mai 2023 wird die Harmonie Pfäffikon von Marco Liechti dirigiert. Das Repertoire reicht von traditioneller Blasmusik über bunt gemischte Unterhaltungsmusik bis hin zur klassischen Musik. Die musikalischen Schwerpunkte im Vereinsjahr bilden das Frühlingskonzert im April und das Kirchenkonzert im November. Der Musigplausch, das Muttertagskonzert, die Fiirabigkonzerte und der Musikantensonntag sind weitere von der Harmonie organisierte Anlässe. Zusätzlich ist die Harmonie an zahlreichen Anlässen von der Gemeinde, der Kirchgemeinde sowie von Pfäffiker- oder anderen Vereinen zu hören. ',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'So., 23.06.2024, 11:00 - 11:25',
        titel: 'Die vier Elemente',
        description:
          'Sehr geehrte Mitglieder der Musikkommission\n\nIm Namen der Harmonie Pfäffikon möchten wir Ihnen mit Freude unsere Auswahl für das Konzertprogramm des Zürcher Kantonalmusikfests im Modul A bekanntgeben. Gerne möchten wir Ihnen die Gründe für die Stückauswahl näherbringen.\n\nUnser Bestreben war es, ein abwechslungsreiches und anspruchsvolles Programm zu präsentieren, das die musikalische Bandbreite der Harmonie Pfäffikon hervorhebt und die Musikalität unserer Musikerinnen und Musiker zur Geltung bringt.\n\nDie Reihenfolge der Stücke wurde bewusst gewählt, um eine harmonische musikalische Erzählung zu schaffen, die das Publikum und die Jury auf eine Reise durch verschiedene Emotionen, Klangwelten und inhaltlich durch die 4 Elemente der Erde mitnimmt: \n\n1.) Luft \nBeim Thema Luft haben wir uns für "Blue Sky" entschieden, um das Konzert mit einem strahlenden und positiven Auftakt zu beginnen. Die luftigen Melodien und lebhaften Rhythmen dieses Stücks symbolisieren den Himmel, die Freiheit und die Weite. Diese Wahl soll nicht nur unsere musikalischen Fähigkeiten unter Beweis stellen, sondern auch die Freude und den Optimismus widerspiegeln, die unsere Musik vermitteln möchte.\n\n2.) Feuer\n"May the Forest Bloom Again" wurde uns als Pflichtstück für den Wettbewerb zugewiesen. Diese Auswahl eröffnet uns die Gelegenheit, technische Präzision und musikalische Erzählkraft zu demonstrieren. Die musikalische Reise von Wachstum, Feuer, Verlust und Wiederaufblühen verschmilzt sanft mit den Elementen der Erde und des Feuers, und betont zum einen die wilde Zerstörungskraft des Feuers, zum anderen aber auch die Robustheit und Wiedererstehungskraft der Natur.\n\n3.) Erde\nDie Wahl von "Return to the Indian Valley" basiert auf unserer Absicht, musikalische Tiefe zu vermitteln und somit unsere Verbindung zum Element Erde zu betonen. Dieses Stück eröffnet uns zudem die Möglichkeit, unsere musikalische Vielseitigkeit mit dem Spielen getragener, ruhigen Passagen zu zeigen. «Return to the Indian Valley» symbolisiert das Element der Erde, das die wunderbare Landschaft in diesem Tal formt.\n\n4.) Wasser\nDieses mitreissende Werk haben wir ausgewählt, um das Konzert mit kraftvollen und begeisternden Klängen abzuschliessen. "In Times of Triumph" repräsentiert das Element Wasser – der üppige und ausdrucksstarke langsame Abschnitt ist voll von fliessenden melodischen Linien, die das fliessende Nass musikalisch umschreiben. Auch symbolisiert «In Times of Triumph» den Sieg (oder Triumph) des Wassers über das Feuer und huldigt ganz generell das wichtigste aller Elemente, ohne das es weder Vegetation noch Leben gäbe.\n\nWir hoffen, dass unsere Begründung für die Stückauswahl Ihr Interesse geweckt hat. \n\nFreundliche Grüsse\nHarmonie Pfäffikon\n\n',
        programm: [
          {
            id: 150,
            modul: 'A',
            titelName: 'Blue Sky',
            composer: 'Hayato Hirose',
            arrangeur: '',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 280,
            pflichtStueck: false,
            infoModeration:
              'Wir haben uns für "Blue Sky" entschieden, um das Konzert mit einem strahlenden und positiven Auftakt zu beginnen. Die luftigen Melodien und lebhaften Rhythmen dieses Stücks symbolisieren den Himmel, die Freiheit und die Weite. Diese Wahl soll nicht nur unsere musikalischen Fähigkeiten unter Beweis stellen, sondern auch die Freude und den Optimismus widerspiegeln, die unsere Musik vermitteln möchte.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 151,
            modul: 'A',
            titelName: 'Return to the Indian Valley',
            composer: 'Ilari Hilkylä',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 210,
            pflichtStueck: false,
            infoModeration:
              'Die Wahl von "Return to the Indian Valley" basiert auf unserer Absicht, musikalische Tiefe zu vermitteln und somit unsere Verbindung zum Element Erde zu betonen. Dieses Stück eröffnet uns zudem die Möglichkeit, unsere musikalische Vielseitigkeit mit dem Spielen getragener, ruhigen Passagen zu zeigen. «Return to the Indian Valley» symbolisiert das Element der Erde, das die wunderbare Landschaft in diesem Tal formt',
            valid: true,
          },
          {
            id: 152,
            modul: 'A',
            titelName: 'In Times of Triumph',
            composer: 'James Swearingen',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 330,
            pflichtStueck: false,
            infoModeration:
              'Dieses mitreissende Werk haben wir ausgewählt, um das Konzert mit kraftvollen und begeisternden Klängen abzuschliessen. "In Times of Triumph" repräsentiert das Element Wasser – der üppige und ausdrucksstarke langsame Abschnitt ist voll von fliessenden melodischen Linien, die das fliessende Nass musikalisch umschreiben. Auch symbolisiert «In Times of Triumph» den Sieg (oder Triumph) des Wassers über das Feuer und huldigt ganz generell das wichtigste aller Elemente, ohne das es weder Vegetation noch Leben gäbe.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 14:10 - 14:15',
        titel: null,
        description: null,
        programm: [
          {
            id: 213,
            modul: 'D',
            titelName: 'Ravanello',
            composer: 'Walter JOSEPH',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 214,
            modul: 'D',
            titelName: 'Melodie und Harmonie',
            composer: 'Siegfried RUNDEL',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 17,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
