export default defineEventHandler(() => {
  return {
    id: 36,
    name: 'Jugendmusik Bezirk Affoltern',
    direktionName: 'Tobias Loew',
    logoImgId: null,
    bildImgId: '71eb68aa-dfee-417a-32cf-1a160422f300',
    homepage: 'https://www.jumba.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Jumba wurde im Jahre 1967 durch die Musikvereine im Amt gegründet. Im Jahre 2020 wurde eine Partnerschaft mit der Musikschule Knonaueramt aufgenommen, so werden die jungen Musikschüler und Schülerinnen vom Instumentalunterricht über 2 Ensemble bis zur Jumba geführt. Mit dieser Lösung soll der Nachwuchs langfristig gesichert werden.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 09:40 - 10:05',
        titel: 'Jumba voll in Fahrt',
        description:
          'Die Jumba ist im letzten September am EJMF in St Gallen das erste Mal in der 3. Klasse angetreten. Der Verein ist am wachsen und voll am Fahrt aufnehmen. Dieses Jahr treten wir hier und am WJMF in Zürich an und haben uns neue Ziele in der Punktzahl gesetzt. Die Jungen sind also gespannt, ob die gesteckten Zeile erreicht werden.',
        programm: [
          {
            id: 322,
            modul: 'A',
            titelName: 'Rockoverture',
            composer: 'Marcel Saurer',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: 'Heute spielen sie sich mit der Rockoverture in Fahrt, das gleich zu Beginn alle Spieler und Zuhörer in Fahrt gebracht werden.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 269,
            modul: 'A',
            titelName: 'Where the Elves lives',
            composer: 'Andreas Ludwig Schulte',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 400,
            pflichtStueck: false,
            infoModeration: 'Dann hören Sie das Pflichtstück des letztjährigen Eidg Jugendmusikfest in St Gallen.',
            valid: true,
          },
          {
            id: 270,
            modul: 'A',
            titelName: 'Spirit,Stallion of the Cimarron',
            composer: 'Hans Zimmer',
            arrangeur: 'Bertrand Moren',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 405,
            pflichtStueck: false,
            infoModeration:
              'Ein Lieblingsstück der Jumbaner. Ein rassiges Werk welches die Jumba fordert und zugleich die Spielfreude der jungen Musiker zeigt.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 13:50 - 13:55',
        titel: null,
        description: null,
        programm: [
          {
            id: 276,
            modul: 'D',
            titelName: 'Young Band Dixie',
            composer: 'Georg Stich',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 210,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 277,
            modul: 'D',
            titelName: 'San Carlo',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 190,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
