export default defineEventHandler(() => {
  return {
    id: 68,
    name: 'Tambourengruppe der Kreismusik Limmattal',
    direktionName: 'Cyril Fehr',
    logoImgId: null,
    bildImgId: '9da9a900-8699-4292-029a-f22fe3184000',
    homepage: 'http://www.kmlimmattal.ch',
    facebook: null,
    instagram: null,
    websiteText: 'Tambourengruppe der Kreismusik Limmattal',
    timetableEntries: [
      {
        modul: 'G',
        competition: 'Tambouren',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:35 - 09:55',
        titel: null,
        description: null,
        programm: [
          {
            id: 369,
            modul: 'G',
            titelName: 'Double Fantasy',
            composer: 'Roman Lombriser',
            arrangeur: null,
            grad: 6.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 8,
        modul: 'G',
        modulDescription: 'G - Tambouren',
        klasse: null,
        klasseDescription: null,
        besetzung: 'TAMBOUREN',
        besetzungDescription: 'Tambouren',
        category: 'MODUL_G_KAT_C',
        categoryDescription: 'Kat. C',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'G - Tambouren (Kat. C), Tambouren (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
