export default defineEventHandler(() => {
  return {
    id: 106,
    name: 'Kreismusik Limmattal',
    direktionName: 'Marcel Burch',
    logoImgId: '869fefe3-ff74-471e-1405-b39721f8b500',
    bildImgId: '6a5e181b-421c-4717-4756-e29383aa7f00',
    homepage: 'https://kmlimmattal.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir sind im rechten Limmattal zuhause und spielen Unterhaltungsmusik für die Bevölkerung.\n\nDas Bläserkorps probt Mittwochs von 20:00 bis 22:00 im Vereinssaal im Zentrum Oberengstringen. Besuchen Sie uns in einer Probe und wecken Sie Ihr musikalisches Talent!\n\nDie Tambourengruppe (Erwachsene) probt Mittwochs von 19:00 - 21:00 Uhr im Schulhaus Kalktarren Schlieren, die Jungtambouren proben Dienstags/Mittwochs/Donnerstags in kleinen Gruppen. Kinder und Erwachsene sind jederzeit willkommen vorbeizuschauen!',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 4. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:40 - 14:05',
        titel: 'Freude an der Musik',
        description:
          'In der Kreismusik ist jeder Musikant und jedes Niveau willkommen. Uns verbindet die Freude an der Musik, welche wir gerne mit anderen teilen. \nDie Zusammenstellung der Stücke und Schwierigkeiten entspricht in etwa der Vielfalt unserer Musikanten. So gestalten wir auch unsere Konzertprogramme mit unterhaltsamen und eingänglichen Stücken sowie mindestens einem Marsch. \nJubilee Spirit als fulminate Eröffnung passt gut zum Samurai. Mit Acclamations haben wir ein unterhaltsamaes, fägiges und konzertantes Stück gefunden, welches wir ebenfalls mit viel Freude einstudieren werden. Und zum Abschluss ein einfacher Marsch, welcher das Programm abrundet.\n',
        programm: [
          {
            id: 323,
            modul: 'A',
            titelName: 'Jubilee Spirit',
            composer: 'Mario Bürki',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration:
              'Ein kraftvolles und schönes Eröffnungswerk aus der Feder des schweizer Komponisten Mario Bürki. Perfekt als Ankündigung für die ehrenvollen Samurai.',
            valid: true,
          },
          {
            id: 5,
            modul: 'A',
            titelName: 'Samurai',
            composer: 'Mathias Wehr',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 324,
            modul: 'A',
            titelName: 'Acclamations',
            composer: 'Ed Huckeby',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 320,
            pflichtStueck: false,
            infoModeration: "Zur Anerkennung und Ehrung der Dienste der Samurai's wollen wir sie mit diesem abwechslungsreichen Stück verabschieden.",
            valid: true,
          },
          {
            id: 316,
            modul: 'A',
            titelName: 'Froh und Heiter',
            composer: 'Max Leemann',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration:
              'Zum Schluss gibts ein eingängiger und schöner schweizer Marsch von Max Leemann. Der Titel ist Programm: \n"Froh und Heiter" geht es weiter. \nDie Stimmung liegt uns am Herzen. deshalb wollen wir nicht scherzen. \nDrum nehmt dies Wort, und feiert noch lange an diesem Ort.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 5,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_4',
        klasseDescription: '4. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 4. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
