export default defineEventHandler(() => {
  return {
    id: 67,
    name: 'Musikverein Harmonie Bauma',
    direktionName: 'Karin Schütz',
    logoImgId: '4de6c50e-1c0e-41e9-1404-76bba6cb3700',
    bildImgId: 'b1e67385-b4f6-4f1a-fd35-c0b22fe3b700',
    homepage: 'http://www.harmoniebauma.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir sind ein aktiver Verein mit ca. 20 Mitgliedern und spielen in der 3. Stärkeklasse. Wir proben 1x pro Woche am Donnerstag. Gemeinsam zu Musizieren, die Gesellschaft und den Zuhörer*Innen mit Musik Freude zu verbreiten, steht an oberster Stelle.  ',
    timetableEntries: [
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 21,
          identifier: 'festzelt-schlieren',
          name: 'Festzelt Schlieren',
          address: 'Badenerstrasse 12, 8952 Schlieren',
          latitude: 47.397439543225,
          longitude: 8.446011061969,
          googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 9,
          mapId: 'FS',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.397439543225,
            longitude: 8.446011061969,
          },
        },
        dateTime: 'So., 23.06.2024, 14:25 - 15:05',
        titel: null,
        description: null,
        programm: [],
      },
    ],
    rankings: [],
  }
})
