export default defineEventHandler(() => {
  return {
    id: 31,
    name: 'Musikverein Stammheim',
    direktionName: 'Fabio Rutz',
    logoImgId: '7b225547-2353-4ae8-a2c9-9cf7d3b21c00',
    bildImgId: '22fab279-45a3-40ab-211c-a9a62980b800',
    homepage: 'https://www.musikverein-stammheim.ch',
    facebook: 'https://www.facebook.com/mvstammheim',
    instagram: 'https://www.instagram.com/musikverein_stammheim',
    websiteText: null,
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:40 - 16:05',
        titel: 'Töne der Veränderung: Ein musikalischer Einblick in Natur und Kultur',
        description:
          '• 25 Anys de Unió Musical\n\nDer Konzert-Pasodoble "25 Anys de Unió " von Juan Bta Meseguer Llopis repräsentiert das 25. Jubiläum der Banda Unió Musical de Tarragona. Die Komposition ist mehr als nur eine Feierlichkeit; sie ist eine Würdigung an die tiefe Verbundenheit zur Blasmusik und ein Tribut an die unermüdliche Arbeit der Banda Unió Musical de Tarragona. Es verkörpert die feierliche Atmosphäre, die einem bedeutenden Meilenstein wie einem Jubiläum gerecht wird. Die Auswahl der Stücke, sowie ihre Interpretation sind geprägt von der spanischen Ausbildung des Dirigenten. Für den Musikverein Stammheim ist diese Komposition ein Spiegelbild der eigenen Verbundenheit zur musikalischen Tradition und der Bedeutung von Jubiläen in der Geschichte. Sie vertritt die Wertschätzung, für die Kontinuität und Hingabe, zur Bewahrung musikalischer Erbschaften, welche der Musikverein Stammheim selbst seit über 150 Jahren pflegt.\n\n• MAY THE FORESTS BLOOM AGAIN\n\n"MAY THE FORESTS BLOOM AGAIN" von Theo Schmitt ist eine musikalische Reise, die die erschütternden Auswirkungen von Waldbränden auf unsere Umwelt einfühlsam widerspiegelt. Das Stück beginnt mit einer idyllischen Darstellung eines unberührten Waldes, dargestellt durch sanfte Melodien von Soloflöte und Solo-Euphonium. Diese friedliche Atmosphäre wird unterbrochen, wenn die Musik die furchtbaren Auswirkungen eines Waldbrandes aufzeigt. Die Komposition vermittelt den intensiven Kampf zwischen den Elementen in den dramatischen Passagen, in denen das tiefe Blech das Geschehen wiedergibt. Doch inmitten dieser Zerstörung gibt es einen Hoffnungsschimmer und die Musik leitet eine langsame Regeneration ein. Die Einsamkeit und Trostlosigkeit der verbrannten Landschaft werden durch einsame Oboen- und Klarinettenklänge dargestellt. Diese führen zu einem langsamen Wiederaufleben des Waldes und einer musikalischen Hymne, die die unermüdliche Fähigkeit der Natur zur Regeneration ausdrückt. Für den Musikverein Stammheim ist dieses Stück mehr als nur eine Komposition; es ist eine Botschaft. Es erinnert daran, wie wichtig es ist, unsere Natur zu schützen und zu bewahren. Durch die Aufführung dieses Stücks setzt der Musikverein Stammheim ein Zeichen für den Respekt und die Verantwortung gegenüber unserer Umwelt.\n\n• Abu Simbel\n\n"Abu Simbel" von Ferrer Ferran ist eine Reise in die majestätische Welt des legendären ägyptischen Ortes Abu Simbel. Diese Komposition würdigt einen Ort auf eine einzigartige Weise, die für ihre monumental, in den Felsen gemeisselten, Tempel und Statuen weltweit bekannt ist. Die Musik spiegelt nicht nur die imposante Grösse wider, sondern auch die geheimnisvolle Atmosphäre dieses historischen Ortes. Durch melodische Motive werden die imposante Architektur und die tiefgreifende historische Bedeutung der Stätte wiedergegeben. Gleichzeitig fangen die rhythmischen Elemente die feierliche Stimmung der antiken Rituale ein, die einst an diesem Ort zelebriert wurden. Genau wie die kolossalen Statuen von Abu Simbel, die über die Jahrhunderte hinweg die Zeit überdauert haben, verleiht diese Komposition eine zeitlose Kraft. Sie erinnert an die Grossartigkeit vergangener Zivilisationen und bringt diese Pracht durch die kraftvolle Sprache der Musik wieder zum Leben. Für den Musikverein Stammheim ist die Interpretation von "Abu Simbel" eine Verbeugung vor der kulturellen Vielfalt und dem faszinierenden historischen Erbe, das durch die Musik lebendig wird. Ähnlich wie Abu Simbel, Geschichte und Architektur vereint, verbindet der Musikverein Stammheim verschiedene musikalische Facetten und Stile zu einem beeindruckenden und vielseitigen Gesamtkunstwerk.\n\nDiese Stücke, jedes auf seine eigene Art und Weise, verkörpern die Werte und Identität des Musikvereins Stammheim. Sie sind nicht nur musikalische Darbietungen, sondern auch Ausdruck einer tiefen Verbindung zu Musikgeschichte, der Hingabe zur Natur und kultureller Vielfalt. Sie erzählen Geschichten, die die Essenz des Vereins widerspiegeln und gleichzeitig das Publikum auf eine klangliche Reise mitnehmen, die weit über die Grenzen des Konzertsaals hinausreicht.\n',
        programm: [
          {
            id: 309,
            modul: 'A',
            titelName: '25 Anys de Unió Musical',
            composer: 'Juan Bta Meseguer Llopis',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              'Der Konzert-Pasodoble "25 Anys de Unió " von Juan Bta Meseguer Llopis repräsentiert das 25. Jubiläum der Banda Unió Musical de Tarragona. Die Komposition ist mehr als nur eine Feierlichkeit; sie ist eine Würdigung an die tiefe Verbundenheit zur Blasmusik und ein Tribut an die unermüdliche Arbeit der Banda Unió Musical de Tarragona. Es verkörpert die feierliche Atmosphäre, die einem bedeutenden Meilenstein wie einem Jubiläum gerecht wird. Die Auswahl der Stücke, sowie ihre Interpretation sind geprägt von der spanischen Ausbildung des Dirigenten. Für den Musikverein Stammheim ist diese Komposition ein Spiegelbild der eigenen Verbundenheit zur musikalischen Tradition und der Bedeutung von Jubiläen in der Geschichte. Sie vertritt die Wertschätzung, für die Kontinuität und Hingabe, zur Bewahrung musikalischer Erbschaften, welche der Musikverein Stammheim selbst seit über 150 Jahren pflegt.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 264,
            modul: 'A',
            titelName: 'Abu Simbel',
            composer: 'Ferrer Ferran',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 593,
            pflichtStueck: false,
            infoModeration:
              '"Abu Simbel" von Ferrer Ferran ist eine Reise in die majestätische Welt des legendären ägyptischen Ortes Abu Simbel. Diese Komposition würdigt einen Ort auf eine einzigartige Weise, die für ihre monumental, in den Felsen gemeisselten, Tempel und Statuen weltweit bekannt ist. Die Musik spiegelt nicht nur die imposante Grösse wider, sondern auch die geheimnisvolle Atmosphäre dieses historischen Ortes. Durch melodische Motive werden die imposante Architektur und die tiefgreifende historische Bedeutung der Stätte wiedergegeben. Gleichzeitig fangen die rhythmischen Elemente die feierliche Stimmung der antiken Rituale ein, die einst an diesem Ort zelebriert wurden. Genau wie die kolossalen Statuen von Abu Simbel, die über die Jahrhunderte hinweg die Zeit überdauert haben, verleiht diese Komposition eine zeitlose Kraft. Sie erinnert an die Grossartigkeit vergangener Zivilisationen und bringt diese Pracht durch die kraftvolle Sprache der Musik wieder zum Leben. Für den Musikverein Stammheim ist die Interpretation von "Abu Simbel" eine Verbeugung vor der kulturellen Vielfalt und dem faszinierenden historischen Erbe, das durch die Musik lebendig wird. Ähnlich wie Abu Simbel, Geschichte und Architektur vereint, verbindet der Musikverein Stammheim verschiedene musikalische Facetten und Stile zu einem beeindruckenden und vielseitigen Gesamtkunstwerk.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
