export default defineEventHandler(() => {
  return {
    id: 79,
    name: 'Musikverein Bäretswil',
    direktionName: 'Ralf Gübeli',
    logoImgId: '378b7532-006f-4033-2687-2220fdb85f00',
    bildImgId: '36abcce6-a465-45f9-a025-8c72934df300',
    homepage: 'https://www.mvbaeretswil.ch',
    facebook: 'https://www.facebook.com/mvbaeretswil',
    instagram: null,
    websiteText:
      'Gegründet wurde der Musikverein Bäretswil 1935, damals noch unter dem Namen "Musikgesellschaft Adetswil". Wir spielen heute in Harmoniebesetzung in der 4. Klasse und bestehen aus 17 Mitgliedern. Die Pflege des kulturellen Lebens in unserem Dorf liegt uns dabei besonders am Herzen. Unser Probetag ist der Donnerstag. ',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Unterstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'So., 23.06.2024, 10:45 - 11:05',
        titel: 'Let Us Entertain You',
        description:
          'Das Motto "Let Us Entertain You" bestimmt in diesem Jahr die künstlerische Ausrichtung des Musikvereins Bäretswil, welcher sich den vielschichtigen Rhythmen verschrieben hat. Die musikalische Reise führt durch Jazz- und Rockkompositionen, wobei die Off Beats den zentralen roten Faden darstellen und ein mitreißendes Erlebnis garantieren. Eine präzise Artikulation bildet einen fundamentalen Schwerpunkt unserer Arbeit, da sie es ermöglicht, die Musik mit höchstem Maß an Leidenschaft und Hingabe zu präsentieren und somit aus einem Programm eine wahre Show zu gestalten.',
        programm: [
          {
            id: 72,
            modul: 'B',
            titelName: "Means That You're Grand",
            composer: 'Jacob Jacobs, Sholom Secunda',
            arrangeur: 'Dennis Armitage',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 135,
            pflichtStueck: false,
            infoModeration:
              "Bei mir bistu shein/Means That You're Grand ist ein Swingstück, das 1938 durch die Andrews Sisters bekannt gemacht wurde. Das Original wurde 1932 für ein jiddisches Musical geschrieben.",
            valid: true,
          },
          {
            id: 73,
            modul: 'B',
            titelName: 'My Dream',
            composer: 'Peter Leitner',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 220,
            pflichtStueck: false,
            infoModeration:
              'Zum Repertoire der populären österreichischen Blasorchester-Big-Band gehören zahlreiche Eigenkompositionen von Peter Leitner, so auch My Dream. Die wunderschöne Melodie ist zunächst beim Improvisieren mit Flügelhorn und Klavier entstanden und wurde später zu einer berührenden Blasmusik-Pop-Ballade für Solo-Flügelhorn ausgearbeitet. Die Solistin am Flügelhorn: Diana Sauter',
            valid: true,
          },
          {
            id: 13,
            modul: 'B',
            titelName: 'On a Roll',
            composer: 'Oliver Waespi',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 74,
            modul: 'B',
            titelName: 'Let Me Entertain You',
            composer: 'Guy Chambers, Robbie Williams',
            arrangeur: 'Marcel Saurer',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Let Me Entertain You wurde vom Interpreten selbst, gemeinsam mit Guy Chambers, geschrieben beziehungsweise komponiert. Die Erstveröffentlichung von Let Me Entertain You erfolgte als Teil von Williams’ Debütalbum Life Thru a Lens am 29. September 1997. Der Solist am Schlagzeug: Malte Winter',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 15,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'UNTERSTUFE',
        klasseDescription: 'Unterstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Unterstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
