export default defineEventHandler(() => {
  return {
    id: 75,
    name: 'Musikverein Gossau ZH',
    direktionName: 'Fredi Olbrecht',
    logoImgId: '88ed499c-9f65-4624-fc28-11de7e77f400',
    bildImgId: '1e8be700-d98a-4b64-d0e7-06ba0d284800',
    homepage: 'http://www.mv-gossau.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Gossau ist ein typischer Dorfverein, der im kulturellen Leben der Gemeinde Gossau einen wichtigen Platz einnimmt. Unser musikalisches Spektrum reicht von Märschen und Polkas über Unterhaltungsmusik bis zu klassischen Kompositionen und Originalblasmusik.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:40 - 10:05',
        titel: 'Elegien des Lebens: Tod, Trauer und die Sehnsucht nach Neuem',
        description:
          'Der Auftritt des Musikverein Gossau ZH verbindet drei Kompositionen, deren narratives Zentrum ein grosses Menschheitsthema bildet: Tod und Zerstörung. Denn stets handelt es sich um gewaltsame Abbrüche: einem Ableben aus Einsamkeit oder Verzweiflung, Zerstörung aus Unachtsamkeit. Dem Tod folgen Schmerz und Trauer auf dem Fuss, aber auch der drängende Wunsch nach Überdauern oder Wiedergeburt. Die Themen des menschlichen Ausdrucks und der emotionalen Tiefe, der Gefühle von Einsamkeit und Konflikt, aber auch Selbstvertrauen, Entschlossenheit, Hoffnung und Veränderung werden in musikalischen Werken, jeweils auf unterschiedlichen Geschichten und Ereignissen basierend, interpretiert. \n\n1. My Soul A Canvas\nEin Stück, das die Gefühle von Einsamkeit, Verlassenheit, Selbstvertrauen, Entschlossenheit und unlösbarem Konflikt darstellt. Es hebt die persönliche Verbindung zu einem bestimmten Individuum hervor, das den Freitod gewählt hat.  Es betont auch den Schmerz und die Trauer derjenigen, die zurückbleiben. Ausdrucksstarke und leicht strukturierte Klänge stehen für die ruhigen Gefühle der Einsamkeit und des Alleinseins, während kühnere und nachdrücklichere Passagen von Zuversicht, Entschlossenheit und Konflikt geprägt sind.\n\n2. May The Forest Bloom Again\nHier wird eine weiter musikalische Komposition beschrieben, die von der dramatischen Waldbränden in den Jahren 2021 und 2022 inspiriert ist. Das Stück handelt von der Hoffnung auf die Wiederherstellung von Lebensräumen, die durch menschliche Aktivitäten zerstört wurden. Es beschreibt die Veränderung in der Natur, von der friedlichen Atmosphäre eines uralten Waldes bis hin zu den wilden Bränden und schliesslich zur Wiedergeburt der Natur.\n\n3. Of Castles And Legends\nEine programmatische Komposition, die auf der deutschen Legende der Weissen Jungfrau von der Kugelsburg basiert. Die weisse Jungfrau war ein Edelfräulein, das im Mittelalter auf der Kugelsburg lebte. Verfolgt von Raubrittern, die ihre Unschuld nehmen wollten, floh sie auf den höchsten Turm und stürzte in den Tod, um ihre Jungfräulichkeit zu bewahren. Die weisse Jungfrau soll den Menschen die unter der Burg vergrabenen Schätze der Raubritter wiederbringen, aber erst, wenn das Böse aus der Welt geschaffen ist.',
        programm: [
          {
            id: 29,
            modul: 'A',
            titelName: 'My Soul a Canvas',
            composer: 'Todd Stalder',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 315,
            pflichtStueck: false,
            infoModeration:
              'Ein Stück, das die Gefühle von Einsamkeit, Verlassenheit, Selbstvertrauen, Entschlossenheit und unlösbarem Konflikt darstellt. Es hebt die persönliche Verbindung zu einem bestimmten Individuum hervor, das den Freitod gewählt hat.  Es betont auch den Schmerz und die Trauer derjenigen, die zurückbleiben. Ausdrucksstarke und leicht strukturierte Klänge stehen für die ruhigen Gefühle der Einsamkeit und des Alleinseins, während kühnere und nachdrücklichere Passagen von Zuversicht, Entschlossenheit und Konflikt geprägt sind.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 30,
            modul: 'A',
            titelName: 'Of Castles and Legends',
            composer: 'Thomas Doss',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 600,
            pflichtStueck: false,
            infoModeration:
              'Eine programmatische Komposition, die auf der deutschen Legende der Weissen Jungfrau von der Kugelsburg basiert. Die weisse Jungfrau war ein Edelfräulein, das im Mittelalter auf der Kugelsburg lebte. Verfolgt von Raubrittern, die ihre Unschuld nehmen wollten, floh sie auf den höchsten Turm und stürzte in den Tod, um ihre Jungfräulichkeit zu bewahren. Die weisse Jungfrau soll den Menschen die unter der Burg vergrabenen Schätze der Raubritter wiederbringen, aber erst, wenn das Böse aus der Welt geschaffen ist.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:00 - 15:05',
        titel: null,
        description: null,
        programm: [
          {
            id: 31,
            modul: 'D',
            titelName: 'Gossauer Marsch',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 32,
            modul: 'D',
            titelName: 'San Carlo',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 160,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
