export default defineEventHandler(() => {
  return {
    id: 39,
    name: 'Musikverein Schönenberg',
    direktionName: 'Luciano Bizzozero',
    logoImgId: null,
    bildImgId: '02e9d339-e495-428d-f0d9-3e54a6bcf800',
    homepage: 'https://www.mvschonenberg.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir sind ein aktiver Dorfverein mit aufgestellten Mitgliedern, welche die Liebe zur Blasmusik und die Kameradschaft verbindet.\nMit unseren rund 35 Mitglieder im Alter von 17 bis 89 Jahren proben wir einmal die Woche.\nDas Jahreshighlight ist unser Chränzli. Auch unter dem Jahr sind wir an diversen Auftritten anzutreffen.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Unterstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'So., 23.06.2024, 11:20 - 11:40',
        titel: 'Classic meets Entertainment',
        description:
          'Es beginnt mit einer Klassiknummer, die Jeder kennt: "Also Sprach Zarathustra" von Richard Strauss. Anschliessend wird mit dem Rock Opening die Stimmung aufgeheizt. Danach wird das Pflichtstück als Höhepunkt zum besten gegeben. Der Abschluss macht dann ein Welthit von Steve Wonder: Sir Duke! Eine bekannte und mitreisende Nummer, welche mit Schlagzeug und Instrumental-Solos einen gelungenen Abschluss unseres Können bietet. Geplant ist ein komplettes Gesamtwerk ohne Unterbrüche, welches das gesamte Publikum und Jury, mit coolen und mitreisenden Rhythmen sowie bekannten und neuen Melodien, in den Bann ziehen soll. ',
        programm: [
          {
            id: 175,
            modul: 'B',
            titelName: 'Also sprach Zarathustra',
            composer: 'Richard Strauss',
            arrangeur: 'Robert Longfield',
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 90,
            pflichtStueck: false,
            infoModeration:
              'Eines der bekanntesten Klassik-Werke von Richard Strauss. Komponiert 1896, inspiriert von Friedrich Nietzsches philosophischem Roman: Also sprach Zarathustra, nimmt uns dieses Werk mit auf eine Reise durch die Entwicklung der Menschheit, von den Uranfängen bis zu den Höhen der Menschheit menschliche Leistung. Die ikonische Eröffnungsfanfare, bekannt aus Stanley Kubricks Film „2001: A Space Odyssey“, bereitet die Bühne für ein monumentales Musikerlebnis',
            valid: true,
          },
          {
            id: 176,
            modul: 'B',
            titelName: 'Rock Opening',
            composer: 'Manfred Schneider',
            arrangeur: 'Manfred Schneider',
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 165,
            pflichtStueck: false,
            infoModeration:
              'Mit den elektrisierenden Klängen von Manfred Schneiders Rock Opening, lassen wir die Entwicklung unseres Programmes weiter gehen. Dieses vielseitige Stück ist ein Kraftpaket voller Energie und Spannung, das Ihr Herz garantiert höher schlagen lässt. Treibenden Rhythmen und stolze Trompetenfanfaren kreieren zusammen mit dem swingenden Holzregister eine musikalische Mischung, die jeden mitreisen kann.',
            valid: true,
          },
          {
            id: 13,
            modul: 'B',
            titelName: 'On a Roll',
            composer: 'Oliver Waespi',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 177,
            modul: 'B',
            titelName: 'Sir Duke',
            composer: 'Steve Wonder',
            arrangeur: 'Naohiro Iwai',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              'Steve Wonders Welthit von 1976 " Sir Duke". Diese ansteckende und freudige Hommage an den grossen Duke Ellington ist ein wahres Meisterwerk aus Funk und Soul. Dieser Zeitlose Klassiker überzeugt durch seine groovigen Rhythmen und der eingehenden Melodie. Der Arrangeur, Naohiro Iwai verstand es genau diesen Groove aufnehmen und zusätzlich die ikonischen Melodien perfekt durch das Orchester in Szene zusetzen. Als besonders Highlight kommen noch diverse Solisten zum Zug, welche das Werk zu einem perfekten Gesamtpaket machen. ',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 14:20 - 14:25',
        titel: null,
        description: null,
        programm: [
          {
            id: 178,
            modul: 'D',
            titelName: 'Albula',
            composer: 'Oscar Tschuor',
            arrangeur: 'Oscar Tschuor',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 179,
            modul: 'D',
            titelName: 'General Lee',
            composer: 'Karl L. King',
            arrangeur: 'Karl L. King',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 15,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'UNTERSTUFE',
        klasseDescription: 'Unterstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Unterstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
