export default defineEventHandler(() => {
  return {
    id: 86,
    name: 'Musikverein Richterswil Samstagern',
    direktionName: 'Christian Bachmann',
    logoImgId: 'ac993059-ec50-4498-74b7-5395f996f500',
    bildImgId: '15b26f2a-51cc-4e39-b40f-02f617a00000',
    homepage: 'https://www.mrs-online.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir sind ein Dorfverein in der 3. Stärkeklasse in Harmoniebesetzung. Unser Repertoire umfasst Musikstücke verschiedener Musikstile, um bei jedem Anlass etwas Passendes dabei zu haben. Wenn Sie Freude an moderner und tradtioneller Blasmusik haben, sind Sie bei uns an der richtigen Adresse. Von jungen bis erfahrenen Musikanten ist bei uns alles vertreten. Wir geniessen das gemeinsame Musizieren und freuen uns auf das kantonale Musikfest. ',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 14:25 - 14:50',
        titel: 'Klangwelten der Natur. Von Leben, Zerstörung und Hoffnung',
        description:
          'In Anlehnung an das Aufgabenstück nehmen wir den Faden der globalen Erwärmung auf und möchten mit dem Stück «Schmelzende Riesen» auf das Abschmelzen unserer Gletscher aufmerksam machen. Diese sind mit ihrem Wasser der Quell allen Lebens und ohne sie wird irgendwann ein Dasein auf unserem Planeten nicht mehr möglich sein.\nDas Stück empfängt uns mit einem majestätischen Anfang, geht über in einen spannenden und rasanten Mittelteil um dann in einem leisen und nachdenklich stimmenden Schluss zu verklingen.\nMit dem Abschmelzen der Gletscher steigt der Meeresspiegel und wird zunehmend auch zur Gefahr für die Seefahrt. «Waterkant» von Markus Götz erzählt die Geschichte der Seefahrer, welche mit den Tücken des Meeres und damit auch mit immer heftigeren Stürmen zu kämpfen haben. Es erzählt aber auch von Lebensfreude, Heimweh und Heimkommen.\n',
        programm: [
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 228,
            modul: 'A',
            titelName: 'Schmelzende Riesen',
            composer: 'Armin Kofler',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 450,
            pflichtStueck: false,
            infoModeration:
              'Schmelzend Riesen ist ein Werk von Armin Kofler, mit dem Gedanken der Klimaerwärmung hinter Titel und Komposition. Es beginnt mit einem majestätischen Teil, der die Erhabenheit der Gletscher widerspiegelt. Nach dem Übergang in einen schnellen und spannenden Mittelteil folgt eine Art Klagelied der Gletscher, um am Schluss des Stücks in leisen Tönen mit der Hoffnung auf eine bessere Zukunft zu verklingen.\nViel Vergnügen\n',
            valid: true,
          },
          {
            id: 229,
            modul: 'A',
            titelName: 'Waterkant',
            composer: 'Markus Götz',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 410,
            pflichtStueck: false,
            infoModeration:
              'Waterkant von Markus ist eine musikalische Geschichte über Matrosen auf der Nordsee. Die verschiedenen Szenen der Geschichte vermitteln ganz unterschiedliche Stimmungen, die Markus Götz geschickt dafür nutzt, um das spannende Matrosen-Dasein darzustellen. Er wechselt zwischen fröhlicher Leichtigkeit, melancholischer Bedrücktheit und feierlicher Freude. \nWir wünschen viel Vergnügen!\n\n',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
