export default defineEventHandler(() => {
  return {
    id: 78,
    name: 'Musikverein Harmonie Altstetten',
    direktionName: 'Jürg Wehrli',
    logoImgId: null,
    bildImgId: '933a79c4-d1e1-445d-f400-46d5cde9c600',
    homepage: 'https://www.mha.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Verein mit seinen bald 125 Jahren Vereinsgeschichte weist gut 50 Mitglieder auf. Fixpunkte im Jahresprogramm sind das Frühlingskonzert im Mai mit eher populärer Ausrichtung und die Kirchenkonzerte im Advent, bei denen symphonisch-konzertante Werke zur Aufführung gelangen. Daneben tritt der Verein am Sechseläuten sowie an Sommer- und Platzkonzerten in der Innenstadt und im Quartier auf.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 2. Klasse, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'Sa., 22.06.2024, 12:00 - 12:30',
        titel: 'aktuell – nachdenklich – optimistisch',
        description:
          'Der Musikverein Harmonie Altstetten stellt dem Pflichtstück «QuaranTime» von Stephan Hodel ein Werk eines weiteren einheimischen Zeitgenossen gegenüber: «Deliverance» von Etienne Crausaz. Auf die «Pflicht» (QuaranTime) folgt die Reflexion «Dusk» (ebenfalls bewusst ein Werk eines aktuellen Komponisten gewählt) und schliesslich die «Kür» als Befreiung (Deliverance) mit Witz, Charme und Spielfreude.',
        programm: [
          {
            id: 3,
            modul: 'A',
            titelName: 'QuaranTime',
            composer: 'Stephan Hodel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 459,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 127,
            modul: 'A',
            titelName: 'Dusk',
            composer: 'Steven Bryant',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 320,
            pflichtStueck: false,
            infoModeration:
              'Das schlichte, choralartige Werk «Dusk» aus dem Jahre 2004 des amerikanischen Komponisten Steven Bryant vertont die Zeit der Abenddämmerung und die feurigen Farben des Sonnenuntergangs. Bryant ist fasziniert von dem vermeintlichen Widerspruch zwischen der Ruhe des Einnachtens und den zunehmend intensiver leuchtenden Farben am Himmel.',
            valid: true,
          },
          {
            id: 126,
            modul: 'A',
            titelName: 'Deliverance',
            composer: 'Etienne Crausaz',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 690,
            pflichtStueck: false,
            infoModeration:
              'Der Freiburger Etienne Crausaz komponierte die Musik für das Freiluftspektakel «Délivrance» (Erlösung, Befreiung), welches 2010 im historischen Städtchen von Gruyères aufgeführt wurde. Mit Motiven aus dieser Theatermusik schuf er anschliessend die viersätzige Suite «Deliverance». Auf die «Overture», dem Eröffnungssatz im Stile eines Sicilianos geschrieben, folgt das farbenfrohe und humorvolle Scherzo. Im dritten, lebhaften Satz «Vivace» treten die verschiedenen Register des Orchesters in einen Dialog. Im abschliessenden brillanten «Finale» lässt Crausaz das Motiv des ersten Satzes nochmals als Reminiszenz ertönen.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 3,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_2',
        klasseDescription: '2. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'A - Konzertmusik, 2. Klasse, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
