export default defineEventHandler(() => {
  return {
    id: 88,
    name: 'Musikverein Kempttal',
    direktionName: 'Stephan Burkhalter',
    logoImgId: '62792df7-089c-4c10-5f94-0750a81a3600',
    bildImgId: 'c72ff89e-39ca-46ad-c32a-4a73e58f4d00',
    homepage: 'https://www.mv-kempttal.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Gegründet wurde unser Verein 1897, damals noch unter dem Namen Musikgesellschaft Winterberg-Grafstal und als reine Blech-Formation. Stark geprägt von den Arbeitern der Firma Maggi in Kemptthal, nahm der Verein 1907 dann seinen jetzigen Namen an. Unter der Leitung von Stephan Burkhalter unterhält das 27 Mitglieder umfassende Orchester sein Publikum regelmässig am Frühlingskonzert, an der Abendunterhaltung und mit diversen Platzkonzerten in der Gemeinde Lindau.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 4. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'Sa., 22.06.2024, 11:00 - 11:25',
        titel: 'Legenden und Mythen',
        description:
          'Um die Samurai, dem Titel des Pflichtstückes, ranken sich viele Legenden und Mythen. Mit unseren ausgewählten Stücken probieren wir das aufzunehmen.   \n',
        programm: [
          {
            id: 216,
            modul: 'A',
            titelName: 'Ride the Wind',
            composer: 'Douglas Court',
            arrangeur: '-',
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 220,
            pflichtStueck: false,
            infoModeration:
              'Die Seefahrt und auch die Seefahrer brachten unzählige Legenden hervor, auch liegt da eine Große Portion Mythos dabei. Ride the Wind beschreibt die lebendige Fahrt eines Segelschiffes vor der Küste von Rhode Island.',
            valid: true,
          },
          {
            id: 5,
            modul: 'A',
            titelName: 'Samurai',
            composer: 'Mathias Wehr',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 218,
            modul: 'A',
            titelName: 'The last ride of the Pony Express',
            composer: 'David Shaffer',
            arrangeur: '-',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Der Pony Express im Wilden Westen des 19.Jh. war sowohl öffentliches Verkehrsmittel wie auch die Postkutsche der damaligen Zeit. Und somit für viele auch der schnellste Weg Nachrichten durch die westliche Hälfte der USA. Banditen die auf die Transportierte Ware oder die Habseligkeiten der Passagiere aus waren überfielen den Pony Express nach wilder Verfolgungsjagd spektakulär und lieferten viele Legend und Mythen über diese bekannte Postkutsche.    ',
            valid: true,
          },
          {
            id: 217,
            modul: 'A',
            titelName: 'Telemark Fantasy',
            composer: 'Kees Vlak',
            arrangeur: '-',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 380,
            pflichtStueck: false,
            infoModeration:
              'Das legendäre Volk der Wikinger hatte seine Heimat in der Telemark, dem Gebiet im Süden Norwegens. Obwohl sie als Krieger und Seefahrer berühmt wurden, hatten sie Zuhause meist auch einen Hof auf dem sie Vieh- und Landwirtschaft betrieben. Das Stück beschreibt die schöne Landschaft der Region und hört die verspielten Melodien der fröhlichen Volkstänze. ',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 5,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_4',
        klasseDescription: '4. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 4. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
