export default defineEventHandler(() => {
  return {
    id: 50,
    name: 'Musikverein Dietlikon',
    direktionName: 'Daniel Zeiter',
    logoImgId: '002352a8-9312-4d14-f512-942a2ade0400',
    bildImgId: '0d349708-65f9-482a-ac4d-f505c91b3600',
    homepage: 'https://www.mvd.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der 1970 gegründete Musikverein Dietlikon ist eine Gruppe von mittlerweile über 50 Musikbegeisterten aus Dietlikon und Umgebung. Wir haben nicht nur die grossen Konzerte, das Sommerkonzert oder Frühlingskonzert. und die beiden Jahreskonzerte, im Blick, sondern auch das gediegene und friedliche Zusammenleben im Verein.  ',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 2. Klasse, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'Sa., 22.06.2024, 11:15 - 11:45',
        titel: 'Like a Phoenix',
        description:
          'Der Phönix ist ein mythischer Vogel, der am Ende seines Lebenszyklus verbrennt, um aus seiner Asche wieder neu zu erstehen. Noch heute kennen wir die Redewendung «Wie ein Phönix aus der Asche» für etwas, das schon verloren geglaubt war, aber in neuem Glanz wieder erscheint. Auch als Reinigung von Altlasten, die ein Wiedererstarken ermöglicht, wird die Redewendung verstanden.\n\nIm Programm des Musikvereins Dietlikon möchten wir den Aspekt der Erneuerung und des in einer Krisenzeit entstehenden Optimismus ins Zentrum stellen und von verschiedenen Seiten beleuchten. \n\nGleichsam als Metapher für unser Motto beginnen wir mit der Fanfare RISE OF THE FIREBIRD, welche sich direkt auf den Mythos des Phoenix bezieht. Der Phoenix ist auch ein Symbol der Hoffnung, des Triumphes und der Unsterblichkeit und ist das Maskottchen der Lakota West High School, welche dieses Werk bei Steven Reineke in Auftrag gegeben hat. Eine positiv vibrierende Eröffnung, welche den Aufbruch und die Kraft dieses Mythos thematisiert und nicht den vorher eingehenden Niedergang.\n\nSo beschreibt es auch Stephan Hodel in QUARANTIME. Entstanden im ersten Lockdown 2020 möchte er mit dieser Komposition nicht die schlechte Erfahrung der Pandemie thematisieren, zumal die Komposition gar nicht programmatisch verstanden werden will, sondern Optimismus versprühen. Wenn wir etwas Positives aus der Coronazeit nehmen wollen, ist es doch die Erkenntnis, dass in Krisenzeiten auch Gutes entstehen kann. Ein füreinander Dasein, ein Wiederentdecken von vergessen geglaubten Werten und Tugenden, ein Rückbesinnen auf Dinge, die in unserem Leben wichtiger sind als Hektik, Globalisierung und Arbeit.\n\nMit JERICHO werden wir im Programm etwas ernster und thematisieren auch den Tiefpunkt und die Krise, welche dem Neubeginn im Phoenix-Mythos unweigerlich vorausgehen muss. JERICHO setzt die bekannte Geschichte aus dem Buch Josua musikalisch um, das die Eroberung der Stadt Jericho durch die Israeliten beschreibt. Der erste Teil schildert den Zug durch die unwirtliche Wüste nach Kanaan, das gelobte Land in einem melancholischen Klagelied, welches das Heimweh, die Suche nach einem Zuhause, nach einem Ende des Herumziehens, besingt. Die Eroberung von Jericho bildet den Hauptteil des Werkes inklusive Kriegslärm und der durch die schmetternden Posaunen einstürzenden Mauern. Aus dieser grossen Katastrophe erwächst schliesslich der Neubeginn der Stadt durch die Besiedlung der Israeliten. Dies äussert sich musikalisch in einem grossen jüdischen Volksfest. Hier zeigt sich wieder der erstarkende Optimus nach Zeiten von Exil, Diaspora und Krieg. Im Finale wiederholen sich alle Themen in verschiedener Form, häufig auch gleichzeitig und führt somit zum Höhepunkt unseres ganzen Programmes. Das Stück endet mit einigen Fragmenten des Klageliedes aus dem ersten Satz, doch dieses Mal in Dur: Die Ruhe ist gefunden.\n\nDieses Gefühl vertiefen wir mit unserem letzten Beitrag: REDEMPTION – Erlösung. Das Stück ist eine lyrische, üppige, romantische Komposition, die die Euphorie einfängt, die man erlebt, nachdem man aus einer emotionalen Krise gerettet wurde. Der ewige Kreislauf aus Niedergang und Neubeginn, welcher uns im Symbol des Phoenix vor Augen geführt wird, kann zur inneren Ruhe, zur Erlösung führen, wenn wir ihn erkennen, aus der Krise Chancen ergreifen und mit Optimismus in die Zukunft blicken.',
        programm: [
          {
            id: 181,
            modul: 'A',
            titelName: 'Rise of the Firebird',
            composer: 'Steven Reineke',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration:
              'Gleichsam als Metapher für unser Motto beginnen wir mit der Fanfare RISE OF THE FIREBIRD, welche sich direkt auf den Mythos des Phoenix bezieht. Der Phoenix ist auch ein Symbol der Hoffnung, des Triumphes und der Unsterblichkeit und ist das Maskottchen der Lakota West High School, welche dieses Werk bei Steven Reineke in Auftrag gegeben hat. Eine positiv vibrierende Eröffnung, welche den Aufbruch und die Kraft dieses Mythos thematisiert und nicht den vorher eingehenden Niedergang.',
            valid: true,
          },
          {
            id: 3,
            modul: 'A',
            titelName: 'QuaranTime',
            composer: 'Stephan Hodel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 459,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 182,
            modul: 'A',
            titelName: 'Jericho',
            composer: 'Bert Appermont',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 660,
            pflichtStueck: false,
            infoModeration:
              'Mit JERICHO werden wir im Programm etwas ernster und thematisieren auch den Tiefpunkt und die Krise, welche dem Neubeginn des Phoenix-Mythos unweigerlich vorausgehen muss. JERICHO setzt die bekannte Geschichte aus dem Buch Josua musikalisch um, das die Eroberung der Stadt Jericho durch die Israeliten beschreibt. Der erste Teil schildert den Zug durch die unwirtliche Wüste nach Kanaan, das gelobte Land in einem melancholischen Klagelied, welches das Heimweh, die Suche nach einem Zuhause, nach einem Ende des Herumziehens, besingt. Die Eroberung von Jericho bildet den Hauptteil des Werkes. Weil die Stadt nicht so einfach einzunehmen ist, ziehen auf Befehl von Jahwe an sechs Tagen die israelitischen Soldaten je ein Mal um die Stadt. Am siebten Tag machen sie diese Runde sieben Mal. Dabei blasen die Priester so laut wie möglich auf ihren Posaunen, das Volk schreit mit aller Kraft, wodurch die Mauern von Jericho schließlich einstürzen. Musikalisch sind deutlich die marschierenden Soldaten zu erkennen und auch die Mauern hören wir mit ohrenbetäubendem Lärm einstürzen. Eine majestätische, großartige Melodie drückt daraufhin das Siegesgefühl aus, das nach der Eroberung der ummauerten Stadt herrscht. Diese mündet in ein grosses typisch jüdisches Volksfest. Hier zeigt sich wieder der erstarkende Optimus nach Zeiten von Exil, Diaspora und Krieg. Im Finale wiederholen sich alle Themen in verschiedener Form – häufig auch gleichzeitig. Das Stück endet mit einigen Fragmenten des Klageliedes aus dem ersten Satz, doch dieses Mal in Dur: Die Ruhe ist gefunden.',
            valid: true,
          },
          {
            id: 183,
            modul: 'A',
            titelName: 'Redemption',
            composer: 'Rossano Galante',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 210,
            pflichtStueck: false,
            infoModeration:
              'Das Gefühl der Ruhe am Ende von JERICHO vertiefen wir mit unserem letzten Beitrag: REDEMPTION – Erlösung. Das Stück ist eine lyrische, üppige, romantische Komposition, die die Euphorie einfängt, die man erlebt, nachdem man aus einer emotionalen Krise gerettet wurde. Der ewige Kreislauf aus Niedergang und Neubeginn, welcher uns im Symbol des Phoenix vor Augen geführt wird, kann zur inneren Ruhe, zur Erlösung führen, wenn wir ihn erkennen, aus der Krise Chancen ergreifen und mit Optimismus in die Zukunft blicken.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 16:30 - 16:35',
        titel: null,
        description: null,
        programm: [
          {
            id: 360,
            modul: 'D',
            titelName: 'Muoler Marsch',
            composer: 'Daniel Zeiter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 361,
            modul: 'D',
            titelName: 'Bundesrat Gnägi-Marsch',
            composer: 'Albert Benz',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 3,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_2',
        klasseDescription: '2. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'A - Konzertmusik, 2. Klasse, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
