export default defineEventHandler(() => {
  return {
    id: 91,
    name: 'Musikverein Weisslingen',
    direktionName: 'Martin Graf',
    logoImgId: 'fb20463e-8481-44d4-1da4-10e7c10c6300',
    bildImgId: '7247147d-5f1e-47b7-7cba-46d93a7d8100',
    homepage: 'https://www.mv-weisslingen.ch',
    facebook: 'https://www.facebook.com/profile.php?id=100085123252190',
    instagram: null,
    websiteText: 'mv-weisslingen.ch',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 4. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:00 - 09:25',
        titel: 'Die Träne im verzauberten Schloss',
        description:
          'Wir wollten das Stück «Lagrima» eigentlich am EMF 2021 spielen, das aber bekanntlich nicht stattfinden konnte. Nun haben wir es an unserem letzten Frühlingskonzert aufgeführt, und es kam gut an - beim Publikum wie auch bei uns Musikanten. \nEs ist abwechslungsreich und interessant, also mussten wir nicht lange suchen, was wir am Kantonalen Musikfest 2024 bringen möchten.\n\nIn diesem Zusammenhang suchten wir etwas Vergleichbares, das wir ebenso gut spielen können, und sind auf das Stück «The enchanted Castle» gestossen.\nAuch dieses gefällt den Mitgliedern sehr. Wir sind überzeugt, beide Stücke gut vorzutragen können. \nZudem ist uns ein Anliegen, Schweizer Komponisten zu berücksichtigen.\n\nDer «Rote Faden»:\nDer Zufall will es, dass mit «Samurai» und «The enchanted Castle» zwei Geschichten zusammenkommen, die man gut in die Kategorie Legenden einordnen könnte.\n',
        programm: [
          {
            id: 98,
            modul: 'A',
            titelName: 'The enchanted Castle',
            composer: 'Mario Bürki',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 360,
            pflichtStueck: false,
            infoModeration:
              '«The enchanted Castle»\nzu Deutsch «Das verwunschene Schloss»:\n-Am Hauensee oberhalb von Arosa liegt ein merkwürdiges Steingewirr. Da soll einst ein Schloss gestanden haben.\nDie zwei Junker die dort wohnten waren der Schrecken der Gegend, keine Frau war sicher vor ihnen.\nEines Tages verschleppten sie ein junges Bauern-Mädchen auf dieses Schloss. \nDer Grossvater dieses Mädchen musste ohnmächtig zuschauen und er rief ihnen diesen Fluch nach: «Oh, wenn nur der Blitz in Euer Schloss einschlagen würde, so dass kein einziger Stein mehr auf dem anderen bleibt !!» \nIn der folgenden Nacht zog ein riesiges Gewitter mit Hagel auf, und am anderen Morgen war\nstatt dem Schloss nur noch ein wirrer, grosser Haufen Steine zu sehen - so die Legende.\n',
            valid: true,
          },
          {
            id: 5,
            modul: 'A',
            titelName: 'Samurai',
            composer: 'Mathias Wehr',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 99,
            modul: 'A',
            titelName: 'Lagrima',
            composer: 'Jean-Claude Kolly',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: false,
            infoModeration:
              '«Lagrima» \nLagrima – zu Deutsch «Träne». \nLegenden bewegten seit jeher die Menschen, bewegten ihre Herzen und rührten zu Tränen des Leides wie auch der Freude. \nDiese Legenden sind so interessant, dass man wirklich eine kleine Träne verdrücken könnte!\nDoch unsere Tränen sollen Freudentränen sein. Freudentränen, dass wir wagen und die Herausforderung angenommen haben, an diesem Wettspiel teilzunehmen.\nUnd mit diesen Tränen der Freude werden wir uns sicher noch Jahre an diesen Tag erinnern.\n',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 5,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_4',
        klasseDescription: '4. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 4. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
