export default defineEventHandler(() => {
  return {
    id: 93,
    name: 'Musikverein Bonstetten',
    direktionName: 'Rhea Paschen',
    logoImgId: '22ee5593-c18c-4047-7193-e03eca56ca00',
    bildImgId: 'bc859fd8-cbb0-4b95-b7e7-26547b0ea000',
    homepage: 'https://www.mv-bonstetten.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Bonstetten wurde im Jahr 1888 gegründet, im 2013 durften wir unser 125-jähriges Bestehen feiern. Unter der Leitung von Rhea Paschen spielen 29 motivierte Aktivmitglieder im Verein mit. Wir treffen uns wöchentlich am Mittwochabend im Gemeindesaal Bonstetten zur Probe. In unserem Repertoire findet man klassische Konzertstücke, Märsche, Polkas und Evergreens - aber auch moderne, poppige Stücke sind vorhanden.\n\nUnsere Zuhörer erfreuen wir das ganze Jahr hindurch bei Auftritten im Dorf, ob an verschiedenen kirchlichen Anlässen oder der 1.Augustfeier  - es gibt immer eine guten Grund, Musik zu machen.\n\nAls Höhepunkt findet das traditionelle Jahreskonzert im März statt:\n\nBei bis anhin immer vollem Haus spielen wir am Samstagabend mit Nachtessen, Tombola und Bar und am Sonntagnachmittag bei Kaffee und selbstgemachtem Kuchen.\n\nAuch die Geselligkeit kommt bei uns nicht zu kurz: Beim gemütlichen Zusammensein nach der Probe, dem Grillabend oder der Musikreise\n\nVielleicht wohnen Sie in der Nähe, spielen ein Blas- oder Schlaginstrument, dann zögern Sie nicht, schauen Sie vorbei, wir würden uns freuen !',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 11:40 - 12:05',
        titel: 'Greed and Conservation',
        description:
          'In einem Wimpernschlag der Natur begann der Mensch ihre Wunder und Schätze zu entdecken und zu nutzen. Mehr denn je ringen im Nutzen dieser Schätze unsere Gier und das Wissen um die Notwendigkeit der Erhaltung von dem, was uns die Natur schenkt und letztendlich am Leben erhält, miteinander. \n"Greed and Conservation" zeigt die Reise dieses "Wimpernschlages" auf.\n"A Western Suite" beschreibt die Abenteuerlust und Begeisterung in der "Entdeckung Amerikas" und den damit verbundenen Schatzsuchen und Volksfesten.\n"Cry of the Last Unicorn" zeigt in schonungsloser Hinsicht auf, wie Jäger in ihrer Gier das letzte Einhorn für sein Horn jagen und töten und dennoch im Nachhinein von der Natur überwältigt werden.\nDas Pflichtstück "May the Forest Bloom Again" führt diese Reise weiter indem es die Zerstörungsgewalt der Menschen in der Natur aufzeigt und die Hoffnung weckt, dass unsere Einsicht zur Notwendigkeit der Erhaltung unserer Natur überwiegt und "unsere Wälder wieder blühen werden".\n',
        programm: [
          {
            id: 189,
            modul: 'A',
            titelName: 'A Western Suite',
            composer: 'Andreas Ludwig Schulte ',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 420,
            pflichtStueck: false,
            infoModeration:
              '"A Western Suite" beschreibt die Abenteuerlust und Begeisterung in der "Entdeckung Amerikas" und den damit verbundenen Schatzsuchen und Volksfesten.',
            valid: true,
          },
          {
            id: 190,
            modul: 'A',
            titelName: 'Cry of the Last Unicorn',
            composer: 'Rossano Galante ',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 510,
            pflichtStueck: false,
            infoModeration:
              '"Cry of the Last Unicorn" zeigt in schonungsloser Hinsicht auf, wie Jäger in ihrer Gier das letzte Einhorn für sein Horn jagen und töten und dennoch im Nachhinein von der Natur überwältigt werden.\n',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 16:00 - 16:05',
        titel: null,
        description: null,
        programm: [
          {
            id: 191,
            modul: 'D',
            titelName: 'Menzberg Marsch (Concert Band/Harmonie)',
            composer: 'Mario Bürki',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 192,
            modul: 'D',
            titelName: 'Schwyzer-Soldaten',
            composer: 'Ernst Lüthold',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 190,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
