export default defineEventHandler(() => {
  return {
    id: 64,
    name: 'Musikverein Harmonie Zürich-Oberstrass',
    direktionName: 'Marcel  Stöckli',
    logoImgId: 'd9f16fd2-3395-43cf-1f9a-e63c75e09200',
    bildImgId: 'a62bffbf-92b7-46c9-92e9-115eda7e2800',
    homepage: 'https://www.mhz-oberstrass.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir sind ein im Zürcher Oberstrass Quartier beheimateter Musikverein, welcher auf eine 124 jährige Geschichte zurückblicken kann. Nebst traditioneller Blasmusik, findet sich in unserem Repertoire vor allem zeitgemässe Unterhaltungsmusik. So erfreuen wir unser Publikum an unserem Unterhaltungskonzert, unserem Konzert in der Kirche oder Sommerkonzerten in und ausserhalb von unserem Quartier mit Rock-, Filmmusik bis hin zu modernen Pop Songs. \n',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:40 - 14:05',
        titel: 'Die Wunder der Natur',
        description:
          'Der "rote Faden" in unserem Konzertprogramm ist die Natur und ihre Bedeutung für die Menschheit. Jedes Stück reflektiert auf unterschiedliche Weisen die Beziehung zwischen Mensch und Natur sowie die Wunder und Herausforderungen, die die Natur mit sich bringt:\n\nWir starten mit dem Wind. Wind steht für Kraft und Energie, die sowohl zur Stromerzeugung genutzt werden, aber auch zerstören kann. Zudem sind Luftströme das entscheidende Element in der Blasmusik. Damit ist es unserer Meinung nach ein ideales Eröffnungsstück, welches Kraft symbolisiert. \n\nUnser Wind entfacht gleich zwei Feuer. Einerseits brennen wir mit viel Leidenschaft für die Musik, im Programm folgt auf den Wind das Pflichtstück mit dem Thema Waldbrand. Einem grossen Waldbrand ist man fast hilflos ausgeliefert und er lässt sich auch mit grossen Anstrengungen in der Regel nicht einfach löschen. Immerhin endet das Pflichtstück nach den Schrecken des Feuers mit Regeneration und Hoffnung. \n\nBei aller Gewalt und Kraft ist der Mensch aber nicht nur der Natur ausgeliefert, sondern kann auch Hand in Hand mit den Jahreszeiten von der Natur profitieren, indem beispielsweise Nutzpflanzen angebaut werden.  Das geschäftige Treiben vom Anbau bis zur Ernte von Kohl beschäftigt uns im nächsten mehrheitlich fröhlichen Stück als starker Kontrast zum Waldbrand.\n\nNachdem der Wind ein Feuer entzündet hat und wir mit einer unscheinbaren, aber wichtigen Pflanze die Symbiose zwischen Mensch und Natur gefeiert haben, wird es Zeit uns mit einem weiteren Naturelement auseinanderzusetzen und ein Fazit zu ziehen ob die Natur gegenüber den Menschen nun eher freundlich oder feindlich gesinnt ist.\n\nWasser ist sozusagen der Gegensatz zum Feuer und der Fluss des Lebens das Gegenteil zur Zerstörung eines Brandes. Wasser braucht es um die Natur zu nutzen aber auch ganz allgemein zum Leben. Auf einer tieferen Ebene spürt man beim Anblick eines Flusses bzw. beim Hören unseres Schlussstückes, dass es trotz zahlreichen Herausforderungen viele Gründe gibt optimistisch zu bleiben und die Natur zu wertzuschätzen. Dieser Grundsatz gilt unserer Meinung nach in Bezug auf die Natur, aber auf für die Blasmusik. Beides muss sorgfältig gepflegt werden, damit wir es noch lange geniessen können.',
        programm: [
          {
            id: 135,
            modul: 'A',
            titelName: 'Wind Power',
            composer: 'Thierry Deleruyelle',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 215,
            pflichtStueck: false,
            infoModeration:
              'Wind Power zeigt diverse Aspekte des Windes. So kann dieser kraftvoll oder sanft daherkommen. Hören Sie selbst wie unser Wind dem Orchester Leben einhaucht und ein Feuer entfacht.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 137,
            modul: 'A',
            titelName: 'Brassica',
            composer: 'Mario Bürki',
            arrangeur: '',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 457,
            pflichtStueck: false,
            infoModeration:
              'Kohl, oder eben "Chabis" ist eine unscheinbare, aber wichtige Nutzpflanze. Nach Wind und Feuer, Kraft und Zerstörung zeigen wir mit diesem Stück der Mensch mit der Natur zusammenarbeiten kann.',
            valid: true,
          },
          {
            id: 136,
            modul: 'A',
            titelName: 'River of Life',
            composer: 'Steven Reineke',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 290,
            pflichtStueck: false,
            infoModeration:
              'Die Natur, aber auch die Menschen brauchen Wasser. Flüsse sind Lebensadern und damit ein weiterer Kontrast zum Feuer. Das letzte Stück in unserem Programm markiert den endgültigen Sieg des Lebens und der Regeneration über die Zerstörung. Unserer Meinung nach gibt es in der Natur trotz aller Herausforderungen mehr Schönheit als Gewalt. Geniessen Sie die Hymne auf das Leben und feiern mit uns noch einmal die Wunder der Natur.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 16:10 - 16:15',
        titel: null,
        description: null,
        programm: [
          {
            id: 211,
            modul: 'D',
            titelName: 'Zunft Oberstrass',
            composer: 'Jakob Bichsel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 216,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 212,
            modul: 'D',
            titelName: 'Züri-Marsch',
            composer: 'Ernst Lüthold',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
