export default defineEventHandler(() => {
  return {
    id: 32,
    name: 'Musikverein Harmonie Affoltern am Albis',
    direktionName: 'Martin Schiesser',
    logoImgId: '8065e576-8de1-4a92-6e4a-4dc4be557d00',
    bildImgId: 'd149d391-4553-4615-ff22-094ae785df00',
    homepage: 'https://www.harmonie-affoltern.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Harmonie Affoltern a/A ist eine gesellige Gruppe von Frauen und Männern, die eine gemeinsame Leidenschaft haben: Sie musizieren alle unheimlich gerne. \n1920 wurde die Harmonie Affoltern a/A gegründet. Zurzeit treffen sich ca. 40 junge und jung gebliebene Mitglieder jeden Dienstag zur Probe. Die Harmonie nimmt auch gerne an Musikfesten teil. Zu den jährlichen musikalischen Höhepunkten zählen das Frühlingskonzert sowie auch die Jahreskonzerte im November. Auch das gemütliche Beisammensein (Skitag, Grillabend, Familientag, Musikreise, Jahresschlusshöck, etc.) darf nicht fehlen.\n\nDie Harmonie Affoltern a/A freut sich auf das Zürcher Kantonalmusikfest in Urdorf + Schlieren und bedankt sich ganz herzlich für die Gastfreundschaft!',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:10 - 10:30',
        titel: 'smoke in a bar',
        description:
          'Mit diesen Stücken werden zeitlose Musikstücke zusammengefasst. Eingängige Melodien mit\nverschiedenen Rhythmen werden gespielt. Nach den Klassikern von Frank Sinatra –New\nYork, New York, welches die lebhafte Atmosphäre der Stadt umschreibt; Somethin’Stupid,\ndas wunderschöne Duett als zärtliche Liebesballade; Fly me to the moon, ein sanfter Swing;\nMy way, der wohl bekannteste Hit Sinatras –folgt ein weiteres Unterhaltungsstück, das unter-\nschiedliche Rhythmen und Stilrichtungen kombiniert. Vor allem die Moderne wird abgebildet\nmit Dancefloor, einem schönen Largo, dem Hip Hop und dem abschliessenden Electro Swing.\nAn diese swingige Melodie schliesst das letzte Stück an.',
        programm: [
          {
            id: 114,
            modul: 'B',
            titelName: 'Frank Sinatra Classics',
            composer: 'div.',
            arrangeur: 'Stefan Schwalgin',
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 444,
            pflichtStueck: false,
            infoModeration:
              'Frank Sinatra, auch bekannt als "The Voice" oder "Ol\' Blue Eyes", war einer der größten Sänger des 20. Jahrhunderts und eine Ikone der Unterhaltungsmusik. Seine einzigartige Stimme, sein charismatisches Auftreten und seine unverwechselbare Interpretation machten ihn zu einer Legende.\n\n- "New York, New York" ist ein Song, der untrennbar mit Frank Sinatra verbunden ist und zu einem der bekanntesten Lieder seiner Karriere wurde. Die eingängige Melodie und die eindringlichen Texte feiern die pulsierende Energie der Metropole New York City. Sobald die ersten Takte erklingen, spürt man förmlich die lebhafte Atmosphäre und den Stolz auf diese Stadt. "New York, New York" wurde zu einer Art Hymne für New York und ist ein zeitloses Meisterwerk, das Sinatra unsterblich machte.\n- "Somethin\' Stupid" ist ein wunderschönes Duett, das Frank Sinatra zusammen mit seiner Tochter Nancy aufgenommen hat. Die zärtliche Liebesballade wurde ursprünglich von C. Carson Parks geschrieben, aber die Version von Frank und Nancy Sinatra wurde zu einem weltweiten Hit. Die harmonische Chemie zwischen Vater und Tochter verleiht dem Lied eine besondere Note, und ihre Stimmen verschmelzen zu einer herzerwärmenden Darbietung.\n- "Fly Me to the Moon" ist ein weiterer Klassiker von Frank Sinatra, der seine Fans mit seinem sanften Swing und seiner romantischen Stimmung verzauberte. Geschrieben von Bart Howard, wurde dieses Lied zu einem Sinnbild für das Streben nach Liebe und Abenteuer. Sinatras Interpretation verleiht dem Song eine unwiderstehliche Leichtigkeit und Eleganz, die ihn zu einem zeitlosen Favoriten gemacht hat.\n- "My Way" ist ohne Zweifel einer der bekanntesten Hits von Frank Sinatra und wird oft als sein "Signature Song" bezeichnet. Geschrieben von Paul Anka und basierend auf dem französischen Lied "Comme d\'habitude", erzählt "My Way" von Selbstbestimmung und der Unabhängigkeit, sein Leben auf eigene Weise zu leben. Sinatras Interpretation vermittelt eine kraftvolle Botschaft der Selbstreflexion und hat unzählige Menschen inspiriert.\n\nIn "Frank Sinatra Classics" sind zeitlose Musikstücke zusammengefasst, die die Essenz der goldenen Ära des Showbusiness einfangen und bis heute eine breite Fangemeinde haben. Sinatras unvergessliche Stimme und die tiefgreifenden Emotionen seiner Darbietungen haben dazu beigetragen, dass diese Lieder zu zeitlosen Schätzen geworden sind. Sie werden auch weiterhin Generationen von Musikliebhabern begeistern und inspirieren.',
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 115,
            modul: 'B',
            titelName: 'The Big Squid',
            composer: 'Marco Martoia',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 210,
            pflichtStueck: false,
            infoModeration:
              '"Der grosse Tintenfisch", eine tolle, süffige Komposition des Italieners Marco Martoia. Mit jazzigen Rhythmen und einer eingängigen Melodie wird das Publikum in den Bann gezogen.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:50 - 13:55',
        titel: null,
        description: null,
        programm: [
          {
            id: 116,
            modul: 'D',
            titelName: 'Gruss an Bern',
            composer: 'Carl Friedemann',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 117,
            modul: 'D',
            titelName: 'Papstein Marsch',
            composer: 'Fritz Hanusch',
            arrangeur: 'Johann Heinrich Müller',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
