export default defineEventHandler(() => {
  return {
    id: 24,
    name: 'Musikgesellschaft Andelfingen',
    direktionName: 'Philippe Coradi',
    logoImgId: '7d303e0c-e7ea-4651-f49e-e78cdeb65200',
    bildImgId: '4161350d-019c-4d90-9df9-cd29f692c900',
    homepage: 'https://www.mgandelfingen.ch',
    facebook: null,
    instagram: null,
    websiteText:
      '\nwww.mgandelfingen.ch\nMG Andelfingen | Facebook\nMusikgesellschaft Andelfingen (@mgandelfingen) • Instagram-Fotos und -Videos\n\n\nDie Musikgesellschaft Andelfingen ist ein Verein mit 34 motivierten Musikantinnen und Musikanten, die durch die Liebe zur Blasmusik miteinander verbunden sind. Unsere Leidenschaft für die Musik schafft eine einzigartige Verbindung zwischen den Mitgliedern. Wir teilen nicht nur Noten, sondern auch Emotionen, Ziele und Erinnerungen. \nWir proben engagiert und fleissig um unsere musikalischen Fähigkeiten zu verbessern und als Ensemble zu wachsen. \nAuf unsere Erfolge bei Wettbewerben und die vielen positiven Rückmeldungen unseres Publikums sind wir stolz. Auftritte sind Chancen unsere Freude zu teilen.\nWir spielen in Harmoniebesetzung und sind glücklich darüber, dass wir eine solide Besetzung haben, die es uns ermöglicht, konstante musikalische Leistungen zu erbringen. Selbstverständlich träumen wir von der Erweiterung unserer Register und würden uns über Zuwachs freuen. Mit viel Engagement und Durchhaltewillen ist es uns glücklicherweise in den letzten Jahren gelungen, unsere Nachwuchsförderung solide zu gestalten und junge Talente zu fördern. \nHilfsbereitschaft, Teamwork und Pünktlichkeit sind weitere Grundpfeiler unserer Gemeinschaft. Wir unterstützen uns gegenseitig und achten darauf, dass jede und jeder seinen Platz im Orchester findet. Gemeinsam geniessen wir auch das gesellige Zusammensein an Vereinsabenden, Ausflügen und Feiern. Es sind auch Freundschaften, die über die Bühne hinausgehen. \nWenn wir unsere Instrumente in die Hand nehmen, entstehen Klänge, die uns und hoffentlich alle unsere Zuhörerinnen und Zuhörer im Herzen berühren, inspirieren und verbinden. \n',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 09:00 - 09:25',
        titel: 'force of nature',
        description:
          'Wir präsentieren mit Golden Peaks (Vulkane) und May the forest bloom again zwei Werke, die in unterschiedlicher Weise gewaltige Naturereignisse wiederspiegeln.\nPassend zu den eindrücklichen Werken eröffnen wir unseren Konzertteil mit der Fanfare Exuberante, welche abwechslungsreich ist – so wie die Natur in unseren beiden anderen Werken auch.',
        programm: [
          {
            id: 241,
            modul: 'A',
            titelName: 'Fanfare Exuberante',
            composer: 'Satoshi Yagisawa',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration:
              'Satoshi Yagisawa verwendete für die Komposition "Fanfare Exuberante" eine ganze Palette der Klangmöglichkeiten für sinfonisches Blasorchester. Das Resultat ist eine sehr abwechslungsreich gestaltete, kurze Fanfare. ',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 242,
            modul: 'A',
            titelName: 'Golden Peak',
            composer: 'Deleruyelle Thierry',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 630,
            pflichtStueck: false,
            infoModeration:
              'Golden Peak ist ein Konzertstück, das uns tief in die Welt der Vulkane in der Auvergne in Mittelfrankreich entführt. Es handelt sich um erloschene Vulkane, deren Ursprünge zwischen 7.000 bis 65 Millionen Jahren vor unserer Zeit liegen. Zu den bekanntesten gehören die 80 Vulkane der Chaîne des Puys, eine spektakuläre Gegend, die zu den faszinierendsten Landschaften der Welt zählt. Der Titel dieses dynamischen und rhythmischen Stücks, in dem alle Instrumentengruppen des Orchesters verwendet werden, bezieht sich auf die Kurstadt Mont-Dore. Das zentrale Thema ist sehr sanft und voller Emotionen und die Musik beschreibt sowohl die Betriebsamkeit als auch die Ruhe dieser Region.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 14:50 - 14:55',
        titel: null,
        description: null,
        programm: [
          {
            id: 243,
            modul: 'D',
            titelName: 'Menzberg',
            composer: 'Mario Bürki',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 244,
            modul: 'D',
            titelName: 'Frei wie der Adler',
            composer: 'Heinrich Steinbeck',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 140,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
