export default defineEventHandler(() => {
  return {
    id: 70,
    name: 'Musikverein Grüningen',
    direktionName: 'Raphael Honegger',
    logoImgId: '4a6a9670-b536-41c6-86d2-b09e9c48b000',
    bildImgId: 'f9fcaebb-037c-4f7e-e72d-836de7aa6e00',
    homepage: 'https://www.mvgrueningen.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Herzlich willkommen beim Musikverein Grüningen im Zürcher Oberland.\n \nWir spielen in der 3. Klasse Harmoniebesetzung und treffen uns jeden Mittwochabend von 20.00 Uhr bis 22.00 Uhr im Werkhof Grüningen zu unseren Gesamtproben. Unser Repertoire umfasst die ganze Palette der heutigen Blasmusik. Diese reicht von konzertanter bis hin zur modernen Unterhaltungsliteratur. Fehlen dürfen jedoch auch die traditionellen Märsche, Polkas und Walzer nicht.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'So., 23.06.2024, 14:25 - 14:50',
        titel: 'Durch Jahreszeiten und Alpen',
        description:
          'Wir nehmen Sie in unserem Konzertblock mit auf eine abwechslungsreiche Reise in die Berge. Fliegen Sie mit uns wie ein Adler über die verschneiten Gipfel, die tiefblauen Seen und die urchigen Täler und lassen Sie den Alltag hinter sich. Zusammen machen wir eine Wanderung durch den Bergfrühling und erhören Sie die ersten Frühlingsblüten in den letzten Schneefeldern. Auch im Herbst reisen wir noch einmal in die Berge und staunen Sie über die leuchtend gelben Wälder unter dem stahlblauen Himmel. Zum krönenden Abschluss nehmen wir an der epischsten Zugfahrt der Schweiz teil und schlängeln uns im Glacier Express vom Engadin über den Albula, durch die Rheinschlucht bis vors Matterhorn. Lauschen Sie dem Musikverein Grüningen und lassen Sie sich in die Berge entführen.',
        programm: [
          {
            id: 75,
            modul: 'A',
            titelName: 'Where Eagles Soar',
            composer: 'Steven Reineke',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: false,
            infoModeration:
              'Die Konzertouvertüre "Where Eagles Soar" (Wo Adler fliegen) stellt die Schönheit, Weite und Freiheit des US-Staates Main musikalisch dar. Gleichzeitig steht es auch als Sinnbild dafür, welche mentale Kraft es in einem Menschen auslösen kann, wenn er realisiert, welches Potenzial er in sich trägt. Der Adlerflug über den US-Bundesstaat lässt sich jedoch genauso für andere Regionen der Erde übertragen.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 76,
            modul: 'A',
            titelName: 'Yellow Mountains',
            composer: 'Jacob de Haan',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 200,
            pflichtStueck: false,
            infoModeration:
              'Oktober 1997. Jacob de Haan besucht St. Moritz in der Schweiz, wo er als Dirigent mit einem Symphonischen Blasorchester arbeitet. Die Berge rings um die Stadt, die Rhätischen Alpen, leuchten in kräftigen Herbstfarben. Die Berggipfel nahe der italienischen Grenze scheinen noch einmal tief Atem zu holen, bevor der erste Schnee fällt und Horden von Touristen das Gebiet wieder bevölkern. „Die Farben, die Gerüche, die Ruhe und die Natur inspirierten mich.“',
            valid: true,
          },
          {
            id: 77,
            modul: 'A',
            titelName: 'The Glacier Express',
            composer: 'Larry Neeck',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 409,
            pflichtStueck: false,
            infoModeration:
              'Die Komposition von Larry Neeck beschreibt musikalisch den Weg des Glacier Express, der berühmtesten Schweizer Gebirgsbahn, welche St. Moritz mit Zermatt verbindet. Die Einleitung des Stückes schildert die Grösse der Bergwelt bei der Ausgangsstation, der Zug setzt sich in Bewegung, die Reise beginnt. Der Allegro-Teil in Moll zeigt die Fahrt während des Winters durch Schneetreiben und Eis. Im langsamen Mittelabschnitt streift die Bahn durch sommerliche Bergweiden und Täler. Das erneute Aufgreifen des Allegros - diesmal in Dur - ruft den ersten Streckenteil in Erinnerung, allerdings bei weit besseren Wetterbedingungen. Der Schluss zeigt noch einmal die majestätische Bergwelt, während die Bahn ihre Reise beendet.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 17,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
