export default defineEventHandler(() => {
  return {
    id: 51,
    name: 'Musikverein Neerach',
    direktionName: 'Reto Bärtsch',
    logoImgId: 'e3e17443-8cb3-4d55-3e47-a734206b7100',
    bildImgId: '6574eac4-f4b7-4a63-2b5d-8830cdd4aa00',
    homepage: 'https://www.mvneerach.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Neerach zählt aktuell 45 Aktivmitglieder und ein paar weitere Musikfreunde, die tatkräftig und regelmässig bei uns mitwirken. Von jung bis jung geblieben sind Frauen und Männer sehr ausgeglichen vertreten.\nUnser abwechslungsreiches Repertoire hat nicht nur für unser Publikum einiges zu bieten, sondern begeistert die Musikantinnen und Musikanten von 12 bis 73 Jahren gleichermassen. ',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'So., 23.06.2024, 10:20 - 10:45',
        titel: 'Natur',
        description:
          'Beide Stücke unseres Selbstwahlprogramms haben, wie das Aufgabenstück,  mit dem Thema Natur zu tun. Alpine Inspiration beschreibt die Schönheit der Berge. Arethusa bezieht sich auf einen alten Mythos um die Nymphe gleichen Namens. Die Geschichte spielt sich im Wasser des Alpheios ab.',
        programm: [
          {
            id: 18,
            modul: 'A',
            titelName: 'Alpine Inspiration',
            composer: 'Martin Scharnagl',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 480,
            pflichtStueck: false,
            infoModeration:
              'Die Ouvertüre „Alpine Inspirations“ beschreibt die vielfältige Schönheit der Berge. Man kann sich anhand der eindrucksvollen Musik eine schöne Wanderung durch die Berglandschaft vorstellen, bei der man die traumhafte Kulisse inspirierend auf sich einwirken lässt. Der junge Tiroler Komponist Martin Scharnagl hat hierfür ein eigenes “Bergmotiv” komponiert, das sich durch die ganze Ouvertüre zieht. Dieses Motiv, bestehend aus vier Sechzehntelnoten und einer Viertelnote, wird gleich zu Beginn von Trompeten, Flügelhörnern und Tenorhörnern in Dur vorgestellt. Der erste Teil stellt den Sonnenaufgang dar, der die noch ruhende Bergwelt in ein wunderschönes, warmes Licht taucht. Man hört die Bäche rauschen und die Vögel beginnen zu zwitschern…die Natur erwacht. Nun beginnt unsere Wanderung auf den Berg, die rhythmische Begleitung im tiefen Blech symbolisiert den zu Beginn noch fröhlichen Aufstieg. Darüber erklingt ein Thema im Holz und im hohen Blech, das in abgewandelter Form auch das “Bergmotiv” in Dur beinhaltet. Es folgt ein Wechsel des Motivs nach Moll, gespielt von den Trompeten und Flügelhörnern. Die dunklere Tonart steht für den nun immer schwieriger und mühsamer werdenden Anstieg, der zum Teil auch einige Gefahren birgt. Mit filmmusikähnlichen Elementen, z.B. im Schlagwerk, verstärkt Martin Scharnagl hier die ausdrucksstarken musikalischen Bilder. Nachdem der anspruchsvolle Aufstieg endlich geschafft ist, kehrt mit „Tranquillo“ Ruhe ein. Hier atmen wir zum ersten Mal richtig durch und genießen bei einer Pause den atemberaubenden Ausblick auf das vor uns liegende Panorama, dargestellt durch eine einfache lyrische Melodie. Mit der Reprise, als wir uns wieder auf den Abstieg begeben, kehren fast identische Rhythmen und Klänge des Anfangs zurück. Zum Abschluss erklingt erneut das „Bergmotiv“ in Dur. Wir lassen die Wanderung und ihre Eindrücke noch einmal Revue passieren, bevor wir schließlich ins Tal zurückkehren.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 19,
            modul: 'A',
            titelName: 'Arethusa',
            composer: 'Johan Nijs',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: false,
            infoModeration:
              'Der Titel des Werkes bezieht sich auf einen alten Mythos um die Nymphe Arethusa. Diese will die Liebe des Flussgottes Alpheios nicht erwidern und wird daraufhin von ihm gejagt. Auf der Flucht fleht die Nymphe ihre Herrin Diana um Hilfe an und wird zu ihrem eigenen Schutz in eine Quelle verwandelt und nach Sizilien versetzt. Die Wasser des Alpheios hingegen suchen weiterhin im Meer nach der Angebeteten. Johan Nijs’ Komposition ist zwar keine programmatische Vertonung der mystischen Geschichte, jedoch birgt die Musik ebenso viel mitreißende Dramatik und aufregendes Wechselspiel.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 15:00 - 15:05',
        titel: null,
        description: null,
        programm: [
          {
            id: 20,
            modul: 'D',
            titelName: 'Marsch des Infanterie Regiments 27',
            composer: 'Eduard Bodmer',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 165,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 21,
            modul: 'D',
            titelName: 'Bündnergruss',
            composer: 'Paul Nold',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 171,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 17,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
