export default defineEventHandler(() => {
  return {
    id: 102,
    name: 'Musikgesellschaft Seuzach',
    direktionName: 'Valeriya Bernikova',
    logoImgId: 'd504aad3-0e99-479c-a69b-f01130389400',
    bildImgId: 'ab5e94ed-f0d2-41ff-0c07-4d3f2e7d0000',
    homepage: 'https://www.mgseuzach.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Anfang März 1897 fanden sich gleichgesinnte Musikfreunde zusammen und gründeten die Musikgesellschaft Seuzach. Unser Verein zählt rund 40 Aktivmitglieder und besteht aus dem Musikkorps, dem Drumkorps und unserem Nachwuchs. Unser Leitsatz seit der Gründung des Vereins heisst: "Sich selber und anderen Menschen mit Musik Freude bereiten".',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:35 - 13:55',
        titel: 'We make rock work',
        description: 'Das Pfilchtstück von Christoph Walter betten wir ein in Musik der Rock-Legenden Queen und Bon Jovi.',
        programm: [
          {
            id: 219,
            modul: 'B',
            titelName: 'Queen Will Rock You',
            composer: 'Queen',
            arrangeur: 'Tom Stanford',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 415,
            pflichtStueck: false,
            infoModeration:
              'Als eine der wenigen Bands in der Geschichte der Popmusik hat Queen seinen Bekanntheitsgrad auf einem gleichbleibend hohen Niveau gehalten. We Will Rock You, The Show Must Go On, Fat Bottomed Girls und I Want It All gehören zu den rockigen Songs aus ihrem breiten Repertoire. Tom Stanford hat all diese Rock-Songs in einem Medley mit dem passenden Titel QUEEN WILL ROCK YOU verwendet.',
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 220,
            modul: 'B',
            titelName: 'Bon Jovi Rock Mix',
            composer: 'Bon Jovi',
            arrangeur: 'Wolfgang Wössner',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 375,
            pflichtStueck: false,
            infoModeration:
              'Für das Stück Bon Jovi Rock Mix nahm sich Wolfgang Wössner vier Hits der amerikanischen Rockband vor. Das Medley beginnt mit Runaway von 1983. Dem folgen die Songs It’s My Life aus dem Jahr 1999 sowie Livin’ on a Prayer von 1986. You Give Love a Bad Name, ebenfalls von 1986, vervollständigt dieses starke Medley.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:30 - 15:35',
        titel: null,
        description: null,
        programm: [
          {
            id: 256,
            modul: 'D',
            titelName: 'Eidgenossen',
            composer: 'Kurt Weber',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 140,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 257,
            modul: 'D',
            titelName: 'Flott im Schritt',
            composer: 'Josef Nagel',
            arrangeur: 'Franz Königshofer',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
