export default defineEventHandler(() => {
  return {
    id: 108,
    name: 'Musikverein Wil ZH',
    direktionName: 'Paul Baur',
    logoImgId: null,
    bildImgId: 'd1a76b6d-c560-4aad-b6ee-9ee34c06db00',
    homepage: 'https://www.mvwil.ch',
    facebook: null,
    instagram: null,
    websiteText: null,
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Unterstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'So., 23.06.2024, 14:15 - 14:35',
        titel: ' Musikverein Wil jubiliert!',
        description:
          'In diesem Jahr (2024) feiert der Musikverein Wil sein 75 Jahr Jubiläum. Wir präsentieren ein Programm (ausser dem Plichtstück), dass wir zusammen mit zahlreichen ehemaligen Musikanten des MVW an unserem Jubiläumsanlass im März 24 aufgeführt haben. Wir freuen uns auf viele weitere Jahre mit Musik und guter Kameradschaft.',
        programm: [
          {
            id: 225,
            modul: 'B',
            titelName: 'Anniversarium 2024  (Marsch)',
            composer: 'Paul Baur',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration:
              'Neukomposition unseres Dirigenten Paul Baur für das Vereinsjubiläum 2024, 75 Jahre Musikverein Wil, uraufgeführt am 23.März 2024 vom Jubiläumsorchester Wil (MV Wil zusammen mit über 30 ehemaligen Vereinsmitgliedern)',
            valid: true,
          },
          {
            id: 13,
            modul: 'B',
            titelName: 'On a Roll',
            composer: 'Oliver Waespi',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 227,
            modul: 'B',
            titelName: 'Über sieben Brücken',
            composer: 'Ulrich Swillms/Helmut Richter',
            arrangeur: 'Manfred Schneider',
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 190,
            pflichtStueck: false,
            infoModeration:
              'Einer der bekanntesten Hits des deutschen Musikers Peter Maffay (stammt aber eigentlich von der DDR Rockgruppe Karat). Wir haben dieses  Stück als Brückenschlag der verschiedenen Generationen ins Programm unseres Jubiläumsorchesters aufgenommen.',
            valid: true,
          },
          {
            id: 226,
            modul: 'B',
            titelName: 'Waterloo',
            composer: 'ABBA',
            arrangeur: 'Roland Kernen',
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration:
              'Zum Abschluss unseres Jubiläumsprogramms spielen wir den ersten grossen Hit der Popgruppe ABBA, mit dem sie am 6. April 1974 den ESC gewonnen haben. Also vor genau 50 Jahren,  auch ein Jubiläum!',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 15:40 - 15:45',
        titel: null,
        description: null,
        programm: [
          {
            id: 239,
            modul: 'D',
            titelName: 'Feurig Blut',
            composer: 'Hans Heusser',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 240,
            modul: 'D',
            titelName: 'Slaidburn',
            composer: 'William Rimmer',
            arrangeur: 'K.v.d. Woude',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 230,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 15,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'UNTERSTUFE',
        klasseDescription: 'Unterstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Unterstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
