export default defineEventHandler(() => {
  return {
    id: 41,
    name: 'Musikverein Hedingen',
    direktionName: 'Röhrig Jürgen',
    logoImgId: '77c92194-8d34-46a0-4c96-b1f729775600',
    bildImgId: 'ebcfe3ae-07e0-4551-bb34-0e3213908000',
    homepage: 'https://mv-hedingen.jimdofree.com',
    facebook: null,
    instagram: null,
    websiteText:
      'Der 1937 gegründete Musikverein Hedingen ist ein Harmonie-Blasorchester und umfasst heute etwa 30 Musikerinnen und Musiker.\n\nSeither fördert der Verein das Musizieren als aktive Freizeitgestaltung und kulturelle Betätigung. Er gestaltet aktiv das Dorfleben mit, indem er jährlich verschiedene Konzerte organisiert oder an anderen Anlässen im Dorf teilnimmt. In unserem Repertoire finden sich fast alle Stilrichtungen, von der klassischen Musik über traditionelle Märsche bis zu moderner Unterhaltungsmusik.\n\nMit Freude und Spass wollen wir Musik für uns und unser Publikum machen. Der Schwierigkeitsgrad der Musikstücke wird unseren Fähigkeiten und unseren Möglichkeiten angepasst und bewegt sich zwischen der 2. und der 3. Stärkeklasse. Einmal im Jahr spielen wir ein zweiteiliges grosses Konzert. Dieses beinhaltet einen konzertanten Teil sowie einen Teil mit Unterhaltungsmusik. Mit unterhaltsamer und zielgerichteter Literatur wollen wir die Herzen des Publikums gewinnen.',
    timetableEntries: [
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 21,
          identifier: 'festzelt-schlieren',
          name: 'Festzelt Schlieren',
          address: 'Badenerstrasse 12, 8952 Schlieren',
          latitude: 47.397439543225,
          longitude: 8.446011061969,
          googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 9,
          mapId: 'FS',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.397439543225,
            longitude: 8.446011061969,
          },
        },
        dateTime: 'So., 23.06.2024, 09:05 - 09:45',
        titel: null,
        description: null,
        programm: [],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 15:10 - 15:15',
        titel: null,
        description: null,
        programm: [],
      },
    ],
    rankings: [
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
