export default defineEventHandler(() => {
  return {
    id: 103,
    name: 'Musikverein Brass Band Henggart',
    direktionName: 'Roger  Wellauer',
    logoImgId: '99af1fc4-b5b5-4288-1ef1-fdb60adbc600',
    bildImgId: '55f46e6f-315b-4c22-6ec4-368fe2bc4700',
    homepage: 'https://www.mvbbh.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Brass Band Henggart spielt in der 2. Stärkeklasse und ist im schönen zürcher Weinland daheim. Wir begeistern unser Publikum mit einem zeitgemässen Repertoire an unseren Unterhaltungskonzeren im Januar oder an unserer sommerlichen Serenade. Weiter nehmen wir auch regelmässig an Wettbewerben teil.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 2. Klasse, Brass Band',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:30 - 11:00',
        titel: 'Citius, Altius, Fortius',
        description:
          'Die Brass Band Henggart eröffnet ihr Programm mit „Olympus“ von Philip Harper, welches auf griechischen Sagen rund um Olympia basiert. Das olympische Motto „Citius, Altius, Fortius“ (Schneller, Höher, Stärker) wird ebenso musikalisch dargestellt und dieser olympische Gedanke wird auch in der Brass Band Szene hochgehalten. Die Brass Band Szene ist bekannt für nationale und internationale Wettbewerbe in diversen Ländern und auch die Brass Band Henggart nimmt regelmässig an solchen teil. Ein Wettstreit an einem Brass Band Wettbewerb kann also durchaus mit dem olympischen Gedanken gleichgesetzt werden. \nWährend der Ursprung der olympischen Spiele in Griechenland liegt, ist Grossbritannien das Geburtsland der Brass Bands. Traditionelle Volkslieder wurden schon immer gerne von bekannten Brass Band Komponisten verarbeitet. So wurde in unserem 2. Werk „David of the white Rock“ die Melodie eines walisischen Barden aus dem Jahre 1740 vom bekannten Komponisten Phillip Sparke in Szene gesetzt. Rund 100 Jahre später entstanden die schottischen Geigenmelodien, die Alan Fernie in „ Airs and Dances“ verwoben hat. In diesen beiden Werken zeigt sich die Tradition, dass Brass Band Komponisten diese alten Volkslieder immer wieder gerne neu aufleben lassen. DIe Brass Band Henggart schliesst ihr Programm mit einem der bekanntesten Brass Band Märsche „Viva Birkinshaw“ von William Rimmer, welcher eine der legendärsten Brass Bands, die Black Dyke Band, hochleben lässt.\nEin zweiter roter Faden, der diese Werke verbindet, zeigt sich in der Vielfalt der Emotionen und Stimmungen, die sie hervorrufen. Jedes Stück hat einen einzigartige Atmosphäre und erzeugt unterschiedliche Gefühle beim Zuhörer.',
        programm: [
          {
            id: 78,
            modul: 'A',
            titelName: 'Olympus',
            composer: 'Philip Harper',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 690,
            pflichtStueck: false,
            infoModeration:
              'Das Werk Olympus basiert auf drei griechischen Sagen rund um das Thema Olympia, verarbeitet in den Sätzen „The Temple of Zeus at Olympia“, „The Olympic Flame“ und „The Olympic Truce“, sowie das olympische Motto "Citius, Altius, Fortius", lateinisch für "Schneller, Höher, Stärker".\nDie Musik beginnt mit der aufregenden Eröffnungszeremonie der Olympischen Spiele im antiken Griechenland. Mit lauten Fanfaren und immer wieder ansteigender Lautstärke werden die Athleten begrüsst und sogleich beginnen die Wagenrennen, welche in dieser Zeitepoche einen hohen Stellenwert hatten. Es folgt eine langsame, mystische Beschreibung des Zeustempels in Olympia. Die Statue des Zeus befand sich darin und galt als eines der 7 Weltwunder der Antike Zeit. Viele Solo-Passagen runden diesen Satz ab.\nIm nächsten Satz, „Die olympische Flamme“ erkennt man zwei der drei Leitmotive der olympischen Spiele „Altius“ (Höher) und „Citius“ (Schneller). Das „Höher“ wird dargestellt indem die Hauptmelodie von den tiefen Instrumenten zu den hohen weitergegeben wird. Das „Schneller“ wird durch ein Accelerando am Ende dieses Satzes gezeigt. Der finale Satz heisst „olympischer Waffenstillstand“ und symbolisiert den alten Brauch, die herrschenden Kriege während der Spiele zu beenden. Das letzte Leitmotiv „Stärker“ zeigt sich in diesem 3.Satz des Werkes mit einer hymnischen Melodie. Das Werk endet, wie es angefangen hat: mit einer Farbenpracht, Optimismus und einer globalen Feier.\n',
            valid: true,
          },
          {
            id: 80,
            modul: 'A',
            titelName: 'David of the white rock',
            composer: 'Phillip Sparke',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 165,
            pflichtStueck: false,
            infoModeration:
              'Dafydd Owain war ein berühmter walisischer Barde, der auf einem Bauernhof namens Gareg Wen, was so viel wie „weißer Felsen" bedeutet, lebte; daher der Name „David vom weißen Felsen“. Es wird erzählt, dass Dafydd auf seinem Sterbebett nach seiner Harfe verlangte und dort diese Melodie komponierte, mit der Bitte, man möge sie zu seiner Beerdigung spielen.',
            valid: true,
          },
          {
            id: 8,
            modul: 'A',
            titelName: 'Airs and Dances',
            composer: 'Alan Fernie',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 446,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 79,
            modul: 'A',
            titelName: 'Viva Birkinshaw',
            composer: 'William Rimmer',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 256,
            pflichtStueck: false,
            infoModeration:
              'Populärer Marsch, komponiert von William Rimmer\nWilliam Rimmer (1862–1936), Brass Band Komponist und Dirigent aus Lancashire, welcher für die Komposition von Märschen sehr bekannt ist.\n„Viva Birkinshaw“ wurde von Rimmer für George Birkinshaw jr. geschrieben, einen führenden Solo Cornetisten der damaligen Black Dyke Mills Band.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 16:20 - 16:25',
        titel: null,
        description: null,
        programm: [
          {
            id: 94,
            modul: 'D',
            titelName: 'La Berra',
            composer: 'Fritz Rickli',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 160,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 95,
            modul: 'D',
            titelName: 'Schwyzer Soldaten',
            composer: 'Ernst Lüthold',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 190,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 4,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_2',
        klasseDescription: '2. Klasse',
        besetzung: 'BRASS_BAND',
        besetzungDescription: 'Brass Band',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'A - Konzertmusik, 2. Klasse, Brass Band (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
