export default defineEventHandler(() => {
  return {
    id: 52,
    name: 'Musikverein Meilen',
    direktionName: 'Roman Brogli',
    logoImgId: 'bb838ec7-5833-467c-fb4b-284c1bc78600',
    bildImgId: '6dd8b58b-05a8-4592-dede-32f176c5df00',
    homepage: 'https://www.mv-meilen.com',
    facebook: 'https://www.facebook.com/mvmeilen',
    instagram: 'https://instagram.com/mvmeilen',
    websiteText:
      'Der Musikverein Meilen ist ein dynamisches und modernes Blasorchester der 1. Stärkeklasse, welches sich aus einer guten Mischung aus jungen sowie erfahreneren Mitgliedern zusammensetzt. Aktuell dürfen wir auf rund 35 Mitglieder zählen, mit deren Puste wir unsere Musik an den verschiedensten Anlässen im Jahr präsentieren. Unser breites und anspruchsvolles Repertoire umfasst für die Jahreskonzerte Ende Januar ein eher sinfonisches Programm, sowohl mit Originalwerken für Blasorchester, wie auch mit Transkriptionen aus der klassischen Musik. Für die meisten Anlässe unter dem Jahr präsentieren wir ein breites Spektrum von bekannten Film- und Popklassikern über mitreissende Arrangements aus verschiedenen Volksmusikformen und traditionellen Blasmusikmärschen.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'So., 23.06.2024, 09:00 - 09:45',
        titel: 'Tänze',
        description:
          'Der Musikverein Meilen hat es zur Tradition gemacht, seine Jahreskonzerte im Januar mit hochwertiger, sinfonisch-konzertanter Blasmusikliteratur zu gestalten. Um diese Charakteristik des Orchesters herauszustreichen und zu präsentieren, haben wir eines der Hauptwerke der Jahreskonzerte 2024 für das Selbstwahlprogramm für das kantonale Musikfest 2024 ausgewählt. Zusammen mit dem Pflichtstück «La Mezquita de Córdoba» präsentiert wir ein Programm unter dem Motto «Tänze».\n\nDas dreisätzige Werk «Tales and Legends» des Schweizers Etienne Crausaz hat seine Wurzeln in den Geschichten und Legenden von Gruyère. Der erste Satz erzählt die Geschichte von Katharina «la Catillon» Repond (1662–1731), die als letzte Frau in der Westschweiz wegen Hexerei zum Tod auf dem Scheiterhaufen verurteilt wurde. Der zweite Satz ist dem letzten Hofnarren von Gruyère gewidmet, dem unverschämten und gerissenen Possenreisser Chalamala, der im 14. Jahrhundert lebte. Der letzte Satz zeigt ein Porträt von Michel, dem letzten Grafen von Gruyère, der diesen Titel von 1539 bis 1544 innehatte. Er beginnt mit einem Mittelalter-Tanz und geht dann in einen Walzer über. Das Stück überzeugt durch seine Vielfältigkeit und gekonnt eingesetzten Klangfarben von dramatisch bis fröhlich, hebt dabei die Facetten eines guten Blasorchesters hervor und fordert dieses auch technisch heraus.\n\nAls drittes Stück präsentieren wir das Stück «Balkan Dance», welches ebenfalls von Etienne Crausaz stammt. Diese Komposition ist ein dynamisches und mitreissendes musikalisches Werk, das die pulsierenden Rhythmen und die lebendige Energie der Balkanregion einfängt und sie mit Elementen der Rockmusik kombiniert. Die Fusion dieser beiden musikalischen Stile erzeugt eine aufregende und fesselnde Klanglandschaft, die die Zuhörer in Bewegung bringt und eine lebendige Atmosphäre schafft. Das Werk ist stark von rhythmischen Elementen geprägt und die charakteristischen Merkmale der Balkanregion sind deutlich hörbar. All dies verleiht dem Stück viel Energie und Kraft und schafft so einen fulminanten Schlusspunkt in unserem Programm.',
        programm: [
          {
            id: 2,
            modul: 'A',
            titelName: 'La Mezquita de Cordoba',
            composer: 'Julie Giroux',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 701,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 374,
            modul: 'A',
            titelName: 'Tales & Legends ',
            composer: 'Etienne Crausaz',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 1320,
            pflichtStueck: false,
            infoModeration:
              'Dieses dreiteilige Werk des Schweizer Komponisten Etienne Crausaz handelt von wahren Geschichten und faszinierenden Legenden aus dem Mittelalter. Der erste Satz erzählt die dramatische Geschichte der Hexe Catherine Catillon Repond (1662-1731) nach. Sie war die letzte Frau, die als Hexe hingerichtet wurde. Im zweiten Satz steht der berühmte Hofnarr Girard Chalamala im Mittelpunkt, der wirklich jeden zum Lachen zu bringen vermochte. Er war der letzte Narr im Schloss von Graf Greyerz. Der dritte Teil handelt von Graf Michael, der als spielsüchtiger Lebenskünstler in die Geschichte einging. Sein Schuldenberg wuchs so hoch, dass er das Weite suchte und nie wieder zurückkehrte. ',
            valid: true,
          },
          {
            id: 375,
            modul: 'A',
            titelName: 'Balkan Dance',
            composer: 'Etienne Crausaz',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: false,
            infoModeration:
              'Die Balkanregion diente im Laufe der Jahrhunderte schon immer als musikalische Inspirationsquelle. Starke Rhythmen und oftmals große musikalische Höhepunkte sind typisch für den großartigen und abwechslungsreichen Musikstil. Etienne Crausaz hat einige dieser Elemente verwendet und sie mit Elementen aus der Rockmusik vermischt. Mit Balkan Dance hat er ein schwungvolles und fantastisches Stück geschaffen, bei dem niemand still sitzen kann! ',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 13,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
