export default defineEventHandler(() => {
  return {
    id: 22,
    name: 'Musikverein Harmonie Hausen am Albis',
    direktionName: 'Rägle Brawand',
    logoImgId: 'f3bc8548-e124-4e76-101d-3d3b46439400',
    bildImgId: '3cd422a5-a893-4c58-f7c5-3fa0bc618f00',
    homepage: 'https://mvhausen.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Harmonie Hausen am Albis wurde am 18. Juli 1894 gegründet und ist somit schon über 125 Jahre alt. Zurzeit zählt unser Verein ca. 50 Aktivmitglieder zwischen 20 und 80 Jahren. So verschieden unsere Mitglieder sind, so vielseitig ist auch unser musikalisches Repertoire. Es reicht von Klassik über Märsche bis hin zu Musical-, Film- und Popmusik. Neben der musikalischen Weiterentwicklung und neuen musikalischen Projekten und Herausforderungen wird auch die Kameradschaft sehr gross geschrieben. Weitere Informationen finden Sie auf unserer Homepage unter www.mvhausen.ch.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:00 - 15:25',
        titel: 'Klänge der Hoffnung',
        description:
          'Diese drei musikalischen Erzählungen thematisieren die Elemente Waldbrand und -erholung, Kolonialismus mit Sklaverei und Bürgerkrieg sowie die Air Force One-Entführung und betonen die transformierende Kraft der Musik. Sie verbinden unsere Geschichte und Erfahrungen und lassen uns erkennen, dass in den verschiedensten Momenten des Lebens die Melodie der Hoffnung niemals verstummt.',
        programm: [
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 33,
            modul: 'A',
            titelName: 'Virginia',
            composer: 'Jacob de Haan',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 553,
            pflichtStueck: false,
            infoModeration:
              'Das Musikstück "Virginia" von Jacob de Haan ist eine eindrucksvolle Komposition, die eine musikalische Reise durch die Geschichte und Landschaft des US-Bundesstaates Virginia darstellt. Die Komposition fängt die Essenz von Virginias Vergangenheit, Gegenwart und Zukunft ein. Durch verschiedene musikalische Abschnitte und Stimmungen spiegelt das Stück die historischen Ereignisse, kulturellen Einflüsse und die Schönheit der Landschaft wider. Von majestätischen Fanfaren bis hin zu zarten Melodien vermittelt "Virginia" eine Atmosphäre von Ehrfurcht und Wertschätzung für diesen vielfältigen Staat.',
            valid: true,
          },
          {
            id: 34,
            modul: 'A',
            titelName: 'Air Force One',
            composer: 'Jerry Goldsmith',
            arrangeur: 'Michal Worek',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 335,
            pflichtStueck: false,
            infoModeration:
              'Die von Jerry Goldsmith komponierte Musik für den Film "Air Force One" unterstreicht auf eindrucksvolle Weise die Spannung, den Druck und die Dramatik des Films. Die Filmmusik begleitet die Geschichte eines entführten Präsidenten an Bord der Air Force One und betont die Intensität der Handlung. Goldsmith nutzt kraftvolle Orchestrierungen, um die Bedrohung und den Kampf um die Freiheit hervorzuheben. Die Musik wechselt zwischen heroischen Themen für den Präsidenten und bedrohlichen Klängen für die Entführer. Insgesamt trägt die Musik von Jerry Goldsmith maßgeblich dazu bei, die emotionale Tiefe und den Adrenalinschub des Films zu verstärken.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
