export default defineEventHandler(() => {
  return {
    id: 80,
    name: 'Musikverein Uetikon am See',
    direktionName: 'Isam Shéhade',
    logoImgId: 'fe5639a2-0b1e-4a2f-5dc9-150cb8e67300',
    bildImgId: '48c51cdc-632c-457d-01a4-eb2b3d00d900',
    homepage: 'https://www.mv-uetikon.ch',
    facebook: null,
    instagram: null,
    websiteText: 'Mit viel Hingabe unterstützen wir seit 1965 aktiv das Dorfleben in Uetikon am See mit vielfältiger Musik. ',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Unterstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'So., 23.06.2024, 13:40 - 14:00',
        titel: 'Flying high',
        description:
          'Das Pflichtstück on a roll ist ein schwungvolles, vorwärts gerichtetes Stück mit Soul-Beats und Blues Parts das ein positives Gefühl und Lust auf mehr vermittelt.\nMit dem Medley Rocky on Broadway möchten wir den positiven aufgebauten Soul-Groove drive weiter führen. Es fängt mit dem unverkennbaren Rocky Beat «Gonna Fly Now» an. Der Mittelteil «Fight From The Heart» wird ruhiger und einzelne Instrumente kommen klangvoll zur Geltung. Im Schlussteil mit «Eye Of The Tiger» zieht der unverwechselbare Beat uns wie Rocky selbst, kraftvoll die Treppe rauf. \nMit Venus geht die Musikrichtung im Rock und Soul-groove weiter und setzt noch eine Schippe drauf. Die positive Stimmung wird weiter angefacht und wir möchten den Zuhörern eine unvergessliche musikalische Unterhaltung bieten.\nViel Vergnügen und Unterhaltung wünscht ihnen der Musikverein Uetikon. \n',
        programm: [
          {
            id: 13,
            modul: 'B',
            titelName: 'On a Roll',
            composer: 'Oliver Waespi',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 159,
            modul: 'B',
            titelName: 'Rocky on Broadway',
            composer: 'Diverse',
            arrangeur: 'Roszell',
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: false,
            infoModeration:
              'Das Medley Rocky on Broadway fängt mit dem unverkennbaren Rocky Beat «Gonna Fly Now» an. Der Mittelteil «Fight From The Heart» wird ruhiger und einzelne Instrumente kommen klangvoll zur Geltung. Im Schlussteil mit «Eye Of The Tiger» zieht der unverwechselbare Beat uns wie Rocky selbst, kraftvoll die Treppe rauf. ',
            valid: true,
          },
          {
            id: 160,
            modul: 'B',
            titelName: 'Venus',
            composer: 'Leeuwen, Robbie van',
            arrangeur: 'Sauerer Marcel',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 200,
            pflichtStueck: false,
            infoModeration:
              'Mit «Venus» geschrieben von der niederländischen Band Shocking Blue aus dem Jahr 1969, geht die Musikrichtung im Rock und Soul-groove weiter und setzt noch eine Schippe drauf. Die positive Stimmung wird weiter angefacht und wir möchten euch eine unvergessliche musikalische Unterhaltung bieten.\nViel Vergnügen und Unterhaltung wünscht ihnen der Musikverein Uetikon \n',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 15,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'UNTERSTUFE',
        klasseDescription: 'Unterstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Unterstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
