export default defineEventHandler(() => {
  return {
    id: 89,
    name: 'Musikverein Harmonie Thalwil',
    direktionName: 'Katarzyna Bolardt',
    logoImgId: null,
    bildImgId: '543c099b-cdc0-4217-76af-f53c50df0f00',
    homepage: 'https://www.harmonie-thalwil.ch',
    facebook: 'https://www.facebook.com/harmoniethalwil',
    instagram: null,
    websiteText:
      'Der Musikverein Harmonie Thalwil ist die Adresse für Blasmusik in Thalwil. Mit gegenwärtig etwa 30 Aktivmitgliedern führen wir zweimal jährlich ein grösseres Konzertprogramm durch, die Abendunterhaltung im Mai sowie das konzertante Blasmusikkonzert im Dezember. Das musikalische Jahresprogramm ergänzt sich durch Auftritte an Anlässen der Gemeinde sowie durch kleinere Konzerte in Quartieren des Dorfes und auswärts.\n\nNeben all der Musik darf natürlich das Gesellschaftliche nicht zu kurz kommen. Angefangen beim gemütlichen Zusammensein nach der Probe in der Beiz über Ausflüge, Samichlausabend hin zu Musikreise und Skiweekend gibt es Anlässe, an denen wir Mitglieder und nicht die Musiknoten im Mittelpunkt stehen.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 2. Klasse, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:30 - 15:00',
        titel: 'Zauber der Fantasie',
        description:
          'Leitgedanke ist die Auszeit während der Quarantäne. Eine Zeit, in der der Alltag verlangsamt ist und man Zeit für Fantasie und Kreativität finden kann. Eine Zeit, in der der magische Zauber der Fantasie eine Reise in eine andere Welt ermöglicht und von der jeder seine eigenen Erlebnisse und Vorstellungen mitnehmen kann.  ',
        programm: [
          {
            id: 3,
            modul: 'A',
            titelName: 'QuaranTime',
            composer: 'Stephan Hodel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 459,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 207,
            modul: 'A',
            titelName: 'Cry of the Last Unicorn',
            composer: 'Rossano Galante',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 462,
            pflichtStueck: false,
            infoModeration:
              'Mit Cry of the Last Unicorn, komponiert von Rossano Galante wird das schicksalhafte Zusammentreffen des letzten Einhorns und dessen Jäger beschrieben - eine dramatische Verfolgung, mal stürmisch, mal melancholisch. ',
            valid: true,
          },
          {
            id: 208,
            modul: 'A',
            titelName: 'Imagasy',
            composer: 'Thiemo Kraas',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 555,
            pflichtStueck: false,
            infoModeration:
              'Aus den Wörtern Imagination und Fantasy ist Imagasy von Thiemo Kraas zusammengesetzt. Eine Komposition, die einen auf eine eigene Reise mitnimmt. \nDie Anregung zu seiner Komposition erhielt Kraas durch die Beobachtung eines kleinen Kindes, das sich, völlig versunken, malend in eine Traumwelt versetzte. "Mit seiner grenzenlosen Phantasie malte es mir eine Geschichte“, beschreibt er dieses Erlebnis.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 3,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_2',
        klasseDescription: '2. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'A - Konzertmusik, 2. Klasse, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
