export default defineEventHandler(() => {
  return {
    id: 55,
    name: 'Musikverein Helvetia Marthalen',
    direktionName: 'Ruth  Suppiger',
    logoImgId: '1111f051-b0a2-4789-4062-b0090fa99700',
    bildImgId: 'd8796110-0ac2-4271-bb3f-8be11ebcfc00',
    homepage: 'https://www.musikverein-marthalen.ch',
    facebook: 'https://www.facebook.com/MusikvereinHelvetiaMarthalen',
    instagram: 'https://instagram.com/musikverein_marthalen?igshid=MXNkeHI1aXBiOXVudg%3D%3D&utm_source=qr',
    websiteText:
      '\nWillkommen in Marthalen, dem Dorf mit einem intakten Vereinsleben. Unser Verein ist Teil der Vielfalt und trägt aktiv und mit Freude zu einem lebendigen Dorf bei. Wir sind in Marthalen und der näheren Umgebung bestens verankert und mit diversen Anlässen das ganze Jahr unterwegs. Nähere Informationen findest du auf unserer Homepage.\n\nHaben wir dein Interesse als Zuhörer oder Musikant geweckt? Dann besuche uns am nächsten Anlass oder komme doch einfach bei der nächsten Probe am Dienstag vorbei.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Unterstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'So., 23.06.2024, 10:10 - 10:30',
        titel: 'In Harmonie zum Höhenflug',
        description:
          'Die im Titel des Pflichtstücks enthaltene Redewendung "On a Roll" - zu deutsch "einen Lauf oder einen Höhenflug haben" - dient als Inspiration für unser Selbstwahlprogramm. Wenn alles harmoniert und passt (Straight Fit), können wir zum Höhenflug (How to train your dragon) ansetzen; wir sind "on a roll".\n\nDer Zusammenhang zwischen dem Ausdruck "in a roll" und dem Film "How to Train Your Dragon" besteht in der Entwicklung des Hauptcharakters, Hicks. Hicks ist zu Beginn der Geschichte unsicher und unglücklich und stellt sich oft ungeschickt an. Doch im Verlauf der Geschichte entwickelt er sich zu einem selbstbewussten und erfolgreichen Drachenreiter, der auf seinem Drachen "Ohnezahn" fliegt. Hicks ist also "on a roll", da er eine beeindruckende Veränderung durchmacht und in vielerlei Hinsicht erfolgreich wird.',
        programm: [
          {
            id: 92,
            modul: 'B',
            titelName: 'Straight fit',
            composer: 'Thiemo Kraas',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 160,
            pflichtStueck: false,
            infoModeration:
              'Das englische Wort „fit“ bezeichnet die Passform eines Kleidungsstückes. Unter „Straight Fit“ versteht man zum Beispiel eine gerade geschnittene Jeanshose. Diese Hose ist ausgesprochen bequem zu tragen und für viele verschiedene Anlässe geeignet. Thiemo Kraas hat die Idee des „geraden Schnittes“ auf kreative Weise in seiner Rockkomposition für Blasorchester übernommen. Die lässige Musik mit ihrem vorwärtstreibenden, geradlinigen Groove ist ganz bewusst im Tutti-Sound angelegt, sodass sie auch in kleinerer Blasorchester-Besetzung gut zu spielen und in ihrer kompakten Anlage universell einsetzbar ist.\n"Straight fit" gehört in unser Programm "In Harmonie zum Höhenflug", denn: Wenn alles harmoniert und passt (Straight Fit), können wir zum Höhenflug ansetzen.',
            valid: true,
          },
          {
            id: 13,
            modul: 'B',
            titelName: 'On a Roll',
            composer: 'Oliver Waespi',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 93,
            modul: 'B',
            titelName: 'How to Train Your Dragon',
            composer: 'John Powell',
            arrangeur: "Sean O'Loughlin",
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 290,
            pflichtStueck: false,
            infoModeration:
              'Das Wikingerdorf Berk wird seit 300 Jahren von Drachen angegriffen, die das Dorf verwüsten und Nahrung stehlen. Um in Berk angesehen  zu werden, ist es deshalb wichtig, ein guter Drachentöter zu sein. Hicks, der Sohn des Stammesoberhaupts, ist jedoch nicht fürs Kämpfen gemacht und versucht vergeblich, sich zu beweisen. Selbst als es ihm gelingt, einen Drachen vom Himmel zu schießen, glaubt ihm niemand. So sucht er nach dem Drachen, um ihn zu töten und einen Beweis für seinen Erfolg zu bringen. Doch als er den Drachen findet, kommt alles anders als ursprünglich geplant. Die beiden werden Freunde und Hicks zu einem selbstbewussten und erfolgreichen Drachenreiter. Hicks ist also "on a roll"; er macht eine beeindruckende Veränderung durch und wird dadurch erfolgreich.',
            valid: true,
          },
        ],
      },
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 21,
          identifier: 'festzelt-schlieren',
          name: 'Festzelt Schlieren',
          address: 'Badenerstrasse 12, 8952 Schlieren',
          latitude: 47.397439543225,
          longitude: 8.446011061969,
          googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 9,
          mapId: 'FS',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.397439543225,
            longitude: 8.446011061969,
          },
        },
        dateTime: 'So., 23.06.2024, 13:30 - 14:10',
        titel: null,
        description: '',
        programm: [],
      },
    ],
    rankings: [
      {
        id: 15,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'UNTERSTUFE',
        klasseDescription: 'Unterstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Unterstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
