export default defineEventHandler(() => {
  return {
    id: 30,
    name: 'Musikgesellschaft Fehraltorf',
    direktionName: 'Marcel Ingold',
    logoImgId: '0be6f7bb-057b-4620-d3d8-543956726d00',
    bildImgId: 'e86e8d51-aede-4772-0e2a-93c13cb47b00',
    homepage: 'https://mg-fehraltorf.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Musikgesellschaft Fehraltorf ist seit ihrer Gründung im Jahre 1892 ein Blasorchester in Harmoniebesetzung, in welchem Holz- und Blechblasinstrumente gleichermaßen vertreten sind. Das Orchester umfasst ca. 35-40 Aktivmitglieder, die zwischen 16 und 65 Jahre alt sind.\n\nUnser vielseitiges Repertoire, welches von moderner Unterhaltungsmusik (Film, Musical, Swing, Rock, Pop etc.) über konzertante Klassik bis hin zur traditionellen Blasmusik reicht, begeistert nebst unserem Publikum vor allem auch unsere große Zahl von jungen Musikantinnen und Musikanten.\n\nWir treffen uns wöchentlich am Donnerstagabend zur Probe und falls notwendig, vor anspruchsvollen Auftritten, auch zu Gesamt- oder Registerproben am Montag - stets bestrebt, unser musikalisches Niveau innerhalb der zweiten Stärkeklasse Harmonie weiter zu steigern. Wir beteiligen uns u. a. an Gemeindeanlässen, geben Quartierständchen im Dorf und nehmen regelmäßig an musikalischen Wettspielen wie kantonale oder eidgenössische Musikfeste oder an Kreismusiktagen teil. Als Höhepunkt jedes Jahres findet jeweils am letzten Wochenende im Januar unsere Abendunterhaltung in der Mehrzweckhalle Heiget statt. Das inzwischen zur Tradition gewordene Konzert in der Kirche, welches ca. jedes zweite Jahr im Herbst aufgeführt wird, ist ebenfalls kaum mehr aus unserem Spielprogramm wegzudenken. Selbstverständlich kommt dabei die Kameradschaft nicht zu kurz: Sommernachtsfeste, Minigolf- oder Kegelabende, Go-Kart Rennen, Skitage oder Musikreisen sind nur einige der Aktivitäten, die wir dank der ausgezeichneten Stimmung im Verein immer wieder miteinander unternehmen.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 2. Klasse, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:45 - 10:15',
        titel: 'Wechselbad der Gefühle',
        description:
          'Inspiriert durch das Pflichtstück „QuaranTime“, haben wir ein Programm zusammengestellt, welches uns auf eine Zeitreise vor und nach der Pandemie mitnimmt. Die damit verbundenen, sehr gegensätzlichen Gefühle wie Freude, Angst, Hoffnung und Sehnsucht sollen durch unsere ausgesuchten Selbstwahlstücke repräsentiert werden.',
        programm: [
          {
            id: 35,
            modul: 'A',
            titelName: 'A Golden Jubilation',
            composer: 'Yagisawa, Satoshi',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 140,
            pflichtStueck: false,
            infoModeration:
              'Freude - Diese festliche Komposition entführt das Publikum in eine Welt der unbeschwerten Freude und Feierlichkeit, wie sie vor der Pandemie häufig an einem Fest zu erleben war. Der Glanz und die Euphorie sind durch die strahlenden Melodien und Rhythmen spürbar.',
            valid: true,
          },
          {
            id: 3,
            modul: 'A',
            titelName: 'QuaranTime',
            composer: 'Stephan Hodel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 459,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 36,
            modul: 'A',
            titelName: 'Resurgences',
            composer: 'Sheldon, Robert',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: false,
            infoModeration:
              'Hoffnung – Entsprechend dem Titel „Resurgences“ (Wiederaufleben) drückt dieses fröhliche Stück die Freude und Begeisterung über einen Neuanfang, ein Wiederaufleben des täglichen Lebens ohne Einschränkungen aus.',
            valid: true,
          },
          {
            id: 37,
            modul: 'A',
            titelName: 'Voice of the Vikings',
            composer: 'Geisler, Michael',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 471,
            pflichtStueck: false,
            infoModeration:
              'Sehnsucht – Nachdem sich der Alltag wieder normalisiert hatte, flammte bei vielen die Sehnsucht nach Reisen und ferne Länder wieder auf. \nDie Wikinger, und damit das Stück „Voice of the Vikings“, stehen für uns symbolisch für lange Reisen und Entdeckerlust, um neue Länder weit über die bekannten Grenzen hinaus zu erkunden. ',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:10 - 15:15',
        titel: null,
        description: null,
        programm: [
          {
            id: 38,
            modul: 'D',
            titelName: 'Rumisberger Marsch',
            composer: 'Joseph, Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 143,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 39,
            modul: 'D',
            titelName: 'Jugend voran',
            composer: 'Jaeggi Stephan',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 145,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 3,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_2',
        klasseDescription: '2. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'A - Konzertmusik, 2. Klasse, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
