export default defineEventHandler(() => {
  return {
    id: 42,
    name: 'Musikverein Zürich-Höngg',
    direktionName: 'Enrico Calzaferri',
    logoImgId: '1cd63cd1-ea11-4668-df63-5c0102a24e00',
    bildImgId: '012cdbe2-506c-4799-c4a1-f07de322df00',
    homepage: 'https://hoenggermusik.ch',
    facebook: 'https://www.facebook.com/Hoenggermusik',
    instagram: 'https://www.instagram.com/mv_hoengg/',
    websiteText:
      'Der Musikverein Zürich-Höngg, ein voll ausgebautes symphonisches Blasorchester der Stadt Zürich, steht seit Januar 2023 unter der Leitung von Enrico Calzaferri. Zu den Höhepunkten im Jahresprogramm gehören das Konzert im Toni-Areal im Frühling, die Konzerte in der Kirche im Dezember sowie die Openair-Sommerkonzerte an den schönsten Plätzen in der Stadt Zürich. Die rund 80 Musiker*innen erarbeiten unter der professionellen Leitung ihres Dirigenten Blasorchesterliteratur aus verschiedensten Sparten und bereiten dem Publikum eine vielfältiges Konzerterlebnis.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'So., 23.06.2024, 13:50 - 14:35',
        titel: 'Out of Dark',
        description:
          'Die Mezquita de Cordoba hat sich im Verlaufe ihrer erlebnisreichen Geschichte von einem römischen Tempel über eine christliche Kirche zu einer Moschee gewandelt. Letztlich wurde diese wieder geweiht und wird bis heute als Kirche genutzt. Trotz allen formellen Änderungen wohnte die Spiritualität dem Ort stets inne und ebendiese Spiritualität steht auch im Fokus des Programms.\n\n"Out of Dark", vom Musikverein Zürich-Höngg im Jahr 2023 bei Benedikt Hayoz in Auftrag gegeben, beschäftigt sich musikalisch mit dem Aufstieg aus der Dunkelheit ins Licht.  Düstere und helle Klänge werden einander gegenübergestellt, dabei verwischt der Komponist Dur, Moll und Politonalität. Als Inspirationsquelle diente "Versa est in luctum" des Komponisten Alonso Lobo, welcher den Kontrast vom Tod (Dunkelheit) und dem ewigen Leben (Licht) meisterlicht umsetzte. \n\nIm Werk "Give Us This Day" steht die Idee der Achtsamkeit, Selbstverbindung und bewussten Lebendigkeit im Mittelpunkt, wie es der buddhistische Mönch Thich Nhat Hanh niedergeschrieben hat. Der Komponist David Maslanka verbindet diese spirituellen Grundsätze mit dem christlichen Glauben. Dies widerspiegelt sich einerseits im Titel, welcher aus der traditionellen, englischen Version des Vaterunsers stammt und andererseits in der Tatsache, dass am Ende des Werks "Vater unser im Himmelreich" von J.S. Bach zitiert wird. In der kurzen, zweisätzigen Sinfonie werden, genau wie in der Mezquita de Cordoba, unterschiedliche Religionen verbunden, welche dieselben Grundsätze haben. So deutet am Ende vieles darauf hin, dass das Einende das Trennende überwiegt. \n\n\n(Der Text soll den Entstehungsprozess des Programms aufzeigen und widerspiegelt nicht die musikalische Reihenfolge des Programms - diese orientiert sich am Spannungsverlauf der Stücke und berücksichtigt unter anderem auch die Ideen der Komponisten (Maslanka sieht sein Werk als Schlusswerk eines Programms vor))',
        programm: [
          {
            id: 314,
            modul: 'A',
            titelName: 'Out of Dark',
            composer: 'Benedikt Hayoz',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 600,
            pflichtStueck: false,
            infoModeration:
              'Das Werk wurde vom Musikverein Zürich-Höngg beim Komponisten Benedikt Hayoz in Auftrag gegeben und im Dezember 2023 uraufgeführt. \n\nWerknotizen des Komponisten: \nVor einiger Zeit stieß ich auf das Werk Versa est in luctum von Alonso Lobo. Das Werk des spanischen Komponisten der Renaissance wurde entsprechend der liturgischen Tradition in Spanien als Musikstück nach einem Requiem komponiert. Es ist ein Meisterwerk, das die Trauer über den Tod und die Hoffnung auf eine herrliche Zukunft im Licht zum Ausdruck bringt. Davon ausgehend habe ich mich mit tiefen, dunklen und manchmal auch harten Klängen beschäftigt. Eine stets pulsierende Rhythmik treibt die dissonanten Klänge immer weiter hinauf zum Licht. Dabei spiele ich mit Verwischungen von Dur und Moll und polytonalen Klängen, um den Grundgedanken von der Dunkelheit zum Licht musikalisch aufzugreifen.',
            valid: true,
          },
          {
            id: 2,
            modul: 'A',
            titelName: 'La Mezquita de Cordoba',
            composer: 'Julie Giroux',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 701,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 315,
            modul: 'A',
            titelName: 'Give Us This Day',
            composer: 'David Maslanka',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 990,
            pflichtStueck: false,
            infoModeration:
              '"Give Us This Day" ist eine eindrucksvolle musikalische Komposition von David Maslanka, die auf den ersten Blick durch ihre tiefe emotionale Resonanz und ihre reiche symphonische Textur beeindruckt. Die Musik wurde im Kontext einer inspirierenden Quelle geschaffen und verkörpert eine tiefgreifende Botschaft, die sowohl spirituell als auch existenziell ist.\n\nDie Komposition wurde von Eric Weirather, dem Direktor der Rancho Buena Vista High School in Kalifornien, in Auftrag gegeben. Unterstützt durch ein Konsortium wurde das Werk im Oktober 2005 fertiggestellt und erfuhr im Frühjahr 2006 an Weirathers Schule seine Uraufführung. Seitdem hat "Give Us This Day" eine bemerkenswerte Reise angetreten, mit zahlreichen Aufführungen in den USA und vielen anderen Teilen der Welt.\n\nDie Inspirationsquelle für "Give Us This Day" ist interessanterweise buddhistischer Natur, obwohl der Titel aus traditionellen, englischen Version des christlichen Gebets "Vaterunser" stammt. Die Verbindung zwischen den beiden religiösen Traditionen betont die universelle Bedeutung der Botschaft. Die Idee der Achtsamkeit, Selbstverbindung und bewussten Lebendigkeit, die der vietnamesische buddhistische Mönch Thich Nhat Hanh betont, findet hier in der Musik ihren Ausdruck.\n\nObwohl "Give Us This Day" aus nur zwei Sätzen besteht, besitzt es den Charakter einer kurzen Symphonie für Bläserensemble. Der erste Satz, mit seinem langsamen und suchenden Charakter, vermittelt eine tiefe Reflexion und Innigkeit. Der zweite Satz kontrastiert mit energetischer und lebhafter Musik, die sowohl Freude als auch nüchterne Ernsthaftigkeit ausdrückt. Dieser Wechsel zwischen den Sätzen spiegelt die Dualität des menschlichen Erlebens wider, während das Stück als Ganzes eine breite Palette von Emotionen und Stimmungen enthält. Ein bemerkenswertes Merkmal von "Give Us This Day" ist die Verwendung der Choralmelodie "Vater Unser im Himmelreich" von J.S. Bach am Ende des Stücks. Dies fügt eine zusätzliche religiöse und spirituelle Dimension hinzu und schafft eine Verbindung zwischen verschiedenen musikalischen Traditionen.\n\nDie Komposition "Give Us This Day" lädt den Hörer ein, sich auf eine musikalische Reise der Selbstreflexion, Achtsamkeit und bewussten Präsenz einzulassen. In einer Welt, die von Herausforderungen und Unsicherheit geprägt ist, spricht die Musik zu einem tieferen Wunsch nach Frieden, Sinnhaftigkeit und Verbindung. Durch die Macht der Musik ermutigt "Give Us This Day" den Hörer dazu, den gegenwärtigen Moment bewusst zu leben und eine Zukunft der Hoffnung und Harmonie aufzubauen.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 13,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
