export default defineEventHandler(() => {
  return {
    id: 53,
    name: 'Musikgesellschaft Glattfelden',
    direktionName: 'Roger Loeliger',
    logoImgId: '5bdcef6a-5fe1-4546-51bd-c095a4172b00',
    bildImgId: 'cce0b539-c89f-4b9e-e5c2-7ee806189b00',
    homepage: 'https://musik-glattfelden.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir, die Musikgesellschaft Glattfelden, sind ein über 100 Jahre alter Traditionsverein. Derzeit bestehen wir aus 28 aktiven MitgliederInnen. Über das ganze Jahr verteilt finden diverse Akti-vitäten statt. Wir spielen an öffentlichen Anlässen in Glattfelden und Umgebung, gestalten eigene Unterhaltungskonzerte und nehmen regelmässig an Musiktagen teil.\nBeim Musizieren steht die Freude am Zusammenspiel, Teamgeist und das Abtauchen in eine andere Welt an erster Stelle. Das wollen wir MusikantInnen nicht nur selber erleben, sondern auch unserer Jugend vermitteln. Wir bieten Kindern die Möglichkeit, Blasinstrumente und Schlagwerke kennen zu lernen und in Zusammenarbeit mit der Musikschule Zürcher Unterland ein Instrument zu erlernen. Wir freuen uns sehr über jedes Kind, welches diese sinnvolle Frei-zeitbeschäftigung wählt und so bald als möglich bei uns im Verein mitspielen kann! Zurzeit zählt unsere Junior-Rock-Band 10 Mitglieder im Alter zwischen 10 und 15 Jahren.\nWir möchten generationenübergreifend die Freude am Musizieren vermitteln und fördern. In unserer offenen, kameradschaftlichen Vereinskultur ist uns jedes Mitglied wichtig.\n',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:45 - 11:05',
        titel: 'MGG-ein musikalisches Portrait',
        description:
          '\nGeschichte und Tradition prägen unseren über 100 Jahre alten Verein bis heute. Veränderungen brauchen Zeit und müssen reifen. Nicht immer gelingt es alle Mitglieder ins Boot zu holen. Wir freuen uns jedoch sehr, dass der Zeitpunkt jetzt stimmt, Neues zu wagen. \nDie letzten zwei Jahre hat uns ein grosses Projekt begleitet - die Anschaffung einer neuen Uniform. Ein teures Unterfangen - trotzdem haben wir uns wie Christoph Walter gesagt "We\'ll make it work" und haben es auch geschafft. Am 8 11.2024 findet die Neuuniformierung statt.\n\nWir wünschen Ihnen viel Vergnügen mit der Musikgesellschaft Glattfelden\n',
        programm: [
          {
            id: 130,
            modul: 'B',
            titelName: 'Break the Wave!',
            composer: 'Zeiter, Daniel',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 230,
            pflichtStueck: false,
            infoModeration:
              'Wie unser Name schon sagt kommen wir aus Glattfelden. Ein hübsches Dorf im Züri Unterland an der Glatt und am Rhein gelegen. Seit vielen, sehr vielen Jahren schwimmen wir auf der Welle der Meinung, dass die MGG nie an ein kantonales Musikfest geht! Es gibt kein Mitglied bei uns, dass mit Glattfelden an einem Kantonalen war! Warum das so ist, ist eine längere Geschichte. Nun brechen wir diese Welle und freuen uns an dieser ersten Teilnahme bei euch in Urdorf-Schlieren mit unserem Eröffnungsstück «Break the Wave von Daniel Zeiter»',
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 131,
            modul: 'B',
            titelName: 'Night in Havana',
            composer: 'Ericsen,Lars',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 207,
            pflichtStueck: false,
            infoModeration:
              'Die Neuuniformierung feiern wir an unserer Abendunterhaltung. Das Musikchränzli im November ist seit x Jahren fester Bestandteil im Jahresprogramm der MGG und im Glattfelder Kulturprogramm. Dieses Konzert steht ganz im Fokus der Unterhaltung für jedermann. Da ist Abwechslung in den Stilrichtungen gefragt und es macht Spass einen Cha-cha-cha wie "Night in Havanna" von Lars Ericsen im Programm zu haben.  ',
            valid: true,
          },
          {
            id: 132,
            modul: 'B',
            titelName: 'Perger Polka',
            composer: 'Gäble, Kurt',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 275,
            pflichtStueck: false,
            infoModeration:
              'Unser kleines Konzert beenden wir mit der "Perger Polka von Kurt Gäble" - Wir spielen dieses Stück zu "ehren" von unserem dienstältesten Musikanten Rolf "B"erger. Er ist ein grosser Polka-Fan und hat dieses Stück ins Repertoire gebracht.  ',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:40 - 14:45',
        titel: null,
        description: null,
        programm: [
          {
            id: 133,
            modul: 'D',
            titelName: 'Seldwyla (Gottfried Keller-Marsch)',
            composer: 'David, Franz',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 220,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 134,
            modul: 'D',
            titelName: 'Schönes Prag',
            composer: 'Tuschla, Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 160,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
