export default defineEventHandler(() => {
  return {
    id: 38,
    name: 'Musikgesellschaft Fällanden',
    direktionName: 'Cyrill Oberholzer',
    logoImgId: 'd9e920a9-845e-439e-8f22-3f9e1df37000',
    bildImgId: 'f3e98277-78fc-4060-41fc-94a0cfceec00',
    homepage: 'https://mgfaellanden.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Uns gibt es schon seit über 110 Jahren. 1907 wurde die Musikgesellschaft Fällanden gegründet – und sie hat seither einiges erlebt. Als konfessionell und politisch unabhängiger Musikverein spielen wir sowohl aktuelle wie auch traditionelle Blasmusik. Neben dem Erreichen der musikalischen Zielsetzung ist uns auch der gesellschaftliche Kontakt untereinander wichtig.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:10 - 14:30',
        titel: 'Eighties Icons On Stage',
        description:
          'Mit dem ikonischen Werk "We\'ll Make It Work" wurden bei der MGF Erinnerungen an die 80er-Jahre wach. Die Selbstwahlstücke umrahmen das Pflichtstück von Christoph Walter und setzen dieses in den Kontext einer Reminiszenz an die Sternstunden von Disco und Pop. Ein gewaltiger Urschrei ("Tarzan Boy") eröffnet das Konzert der MGF und versetzt die Zuhörer unmittelbar in die 80er zurück. Danach folgt "We\'ll Make It Work", welches mit seinen Sätzen stilistisch die Welthits aus jener Zeit andeutet und auf den krönenden Abschluss überleitet - einen Zusammenschnitt der grössten Hits der Dekade ("Eighties Flashback").',
        programm: [
          {
            id: 96,
            modul: 'B',
            titelName: 'Tarzan Boy',
            composer: 'Maurizio Bassi',
            arrangeur: 'Jirka Kadlec',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 255,
            pflichtStueck: false,
            infoModeration:
              'Starten wird die MGF mit dem Stück Tarzan Boy in einem Arrangement von Jirka Kadlec. Geschrieben wurde dieser Song im Jahr 1985 von Jimmy McShane und Maurizio Bassi. Tarzan Boy wurde im selben Jahr in vielen Europäischen Ländern zu einem Nummer-Eins Hit. In den USA gelangte der Durchbruch als der Song zu einer Werbung von Listerin Mundwasser verwendet wurde. \n',
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 97,
            modul: 'B',
            titelName: 'Eighties Flashback',
            composer: 'diverse',
            arrangeur: 'Paul Murtha',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 495,
            pflichtStueck: false,
            infoModeration:
              'Zum Schluss spielt die MGF ein Medley aus diversen grossen Hits aus den 80ern. So zum Beispiel Time after Time von Cyndi Lauper, Eye of the Tiger von Survivor, aber auch Hits von Micheal Jackson Joe Cocker oder Bon Jovi sind dabei die Sie garantiert kennen. Arrangiert wurde dieses Medley von Paul Murtha. Die MGF wünscht gute Unterhaltung!!!',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
