export default defineEventHandler(() => {
  return {
    id: 57,
    name: 'Musikgesellschaft Niederhasli',
    direktionName: 'Roberto Cereghetti',
    logoImgId: 'cb2cfe8c-38c0-4576-968f-3fcd40e02a00',
    bildImgId: 'ae587a82-7d12-436c-ad34-31d123952800',
    homepage: 'https://mgniederhasli.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Musikgesellschaft Niederhasli gibt es schon seit über 100 Jahren, gegründet wurde sie im Jahr 1913. Wir sind ein junger\nund engagierter, im Dorf sehr gut verankerter, Verein. Wir widmen uns vor allem der modernen Unterhaltungsmusik sowie der\nklassischen Blasorchesterliteratur. Und natürlich kommt bei uns auch das Vereinsleben nicht\nzu kurz. ',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Oberstufe, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'So., 23.06.2024, 10:30 - 10:55',
        titel: 'In Other Words',
        description:
          '«In Other Words» – «in anderen Worten» oder «in einer anderen Sprache». Die Musikgesellschaft Niederhasli präsentiert ein Programm, zu dem dieser Titel gleich aus mehreren Gründen passt: Lateinamerikanische Rhythmen, Lieder eines norwegischen Songwriters, ein Stück einer japanischen Jazz-Fusion Band und ein amerikanischer Jazz-Standard, der ursprünglich «In Other Words» hiess – unser Programm ist international und multikulturell. Das gemeinsame Element ist die Sprache der Musik. Sie verbindet die Menschen über alle Sprachgrenzen und Kontinente hinweg. «In Other Words» - denn die Blasmusik ist mir ihrer stilistischen Flexibilität ein perfekter Botschafter für alle Kulturen.',
        programm: [
          {
            id: 170,
            modul: 'B',
            titelName: 'Latin Pop Special',
            composer: 'Mark Taylor, Desmond Child',
            arrangeur: 'Masato Myokoin',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 333,
            pflichtStueck: false,
            infoModeration:
              'Popmusik und lateinamerikanische Rhythmen – das sind die Merkmale des Latin Pop, der in den 1990er-Jahren so richtig aufkam. Zwei der Protagonisten dieser Stilrichtung sind Enrique Iglesias und Ricky Martin. Sie hatten im Jahr 1999 grosse Erfolge mit zwei ihrer grössten Hits. «Bailamos – let the rhythm take you over» sang Enrique Iglesias. Und Ricky Martin lebte sein verrücktes Leben – “Livin’ La Vida Loca”. Der japanische Arrangeur Masato Myokoin verarbeitete diese beiden Nummern in «Latin Pop Special». ',
            valid: true,
          },
          {
            id: 11,
            modul: 'B',
            titelName: 'Halvdan Sivertsen Medley',
            composer: 'Lars Erik Gudim',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 390,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 171,
            modul: 'B',
            titelName: 'Omens of Love',
            composer: 'Hirotaka Izumi',
            arrangeur: 'Toshio Mashima',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 260,
            pflichtStueck: false,
            infoModeration:
              'T-Square – das ist eine japanische Jazz-Fusion-Band, die es schon seit 1976 gibt und die ihre grössten Erfolge in den 1970ern und 1980ern feierte. Damals entstand auch «Omens Of Love» - eine eingängige Melodie unterlegt mit poppigem Rhythmus. Die Besonderheit daran war: Die Hauptstimme wurde zwar von einem Blasinstrument gespielt – aber von einem elektronischen. Ein unvergleichlicher 80er-Jahre-Sound. Von Toshio Mashima wurde «Omens Of Love» für Blasorchester arrangiert – ohne Elektronik, aber mit ebenfalls unvergleichlichem Sound, und genauso eingängig.',
            valid: true,
          },
          {
            id: 172,
            modul: 'B',
            titelName: 'Fly me to the Moon',
            composer: 'Bart Howard',
            arrangeur: 'Hoshide Takashi',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 333,
            pflichtStueck: false,
            infoModeration:
              'Frank Sinatra machte diesen Jazz-Standard mit seiner von Quincy Jones arrangierten Version 1964 zwar berühmt – aber die Nummer gab es da schon seit 10 Jahren. 1954 hatte Bart Howard das Lied geschrieben und unter dem Titel «In Other Words» veröffentlicht. Und er dürfte nicht damit gerechnet haben, dass sein Stück 1969 tatsächlich auf dem Mond gespielt würde. Die Astronauten von Apollo 11 nahmen nämlich eine Aufnahme der Sinatra-Version mit und übermittelten nach der erfolgreichen Mondlandung die musikalischen Grüsse auf die Erde. Da hiess der Titel zwar «Fly Me To The Moon» - im Liedtext ist aber “In Other Words” weiterhin enthalten.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 13:40 - 13:45',
        titel: null,
        description: null,
        programm: [
          {
            id: 173,
            modul: 'D',
            titelName: 'Albula ',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 174,
            modul: 'D',
            titelName: 'Belgano',
            composer: 'Max Leemann',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 155,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 16,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'OBERSTUFE',
        klasseDescription: 'Oberstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'B - Unterhaltungsmusik, Oberstufe, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
