export default defineEventHandler(() => {
  return {
    id: 69,
    name: 'Musikverein Neftenbach',
    direktionName: 'Vitalij Vosnjak',
    logoImgId: 'f1b1a155-1db7-4622-7e8d-e963970abd00',
    bildImgId: 'd1c2c1db-6b48-463d-82dd-63677a26b700',
    homepage: 'https://mv-neftenbach.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der MV Neftenbach existiert seit 1897 – ursprünglich unter dem Namen Musikgesellschaft «Alpenrösli» Neftenbach. Nach mehr als einem Jahrhundert Vereinsgeschichte sind wir etwa 40 Musikerinnen und Musiker vom Teenager bis zur Rentnerin, die vor allem eines verbindet. Die Liebe zur Musik.\n\nWir treffen uns jeweils Donnerstags (wenn nötig auch Dienstags) um 19:45 Uhr in der alten Turnhalle Drei Linden zur Probe und bestreiten das ganze Jahr hindurch grössere und kleinere Auftritte. Wir verstehen uns als typischen Dorfverein, haben aber den Anspruch, innerhalb der 3. Stärkeklasse Harmonie auf hohem Niveau zu spielen. Dementsprechend nehmen wir auch regelmässig an regionalen, kantonalen und eidgenössischen Musikfesten teil.\n\nDa nicht alle dieselben musikalischen Vorlieben haben, spielen wir auch ganz verschiedene Programme: an der Abendunterhaltung ist vor allem anspruchsvolle Unterhaltungsmusik gefragt, an Wettspielen klassische Blasmusikkompositionen und bei Ständchen auch traditionelle Märsche und Walzer. So kommen alle zum Zug.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'So., 23.06.2024, 09:40 - 10:05',
        titel: 'Zuversicht',
        description:
          'Dieses Konzertprogramm richtet den Blick auf die Kinder und bietet eine vielschichtige musikalische Erfahrung: die emotionale Tiefe, Naturbetrachtung, Märchenzauber und die dringende Notwendigkeit, gegen den Klimawandel anzukämpfen und den Wald zu schützen, miteinander verwebt. So spüren auch wir, wie zerbrechlich unser persönliches Glück und wie ungewiss ein Blick in die Zukunft ist. Um diese Zukunft einmal gestalten zu können, brauchen Kinder aber vor allem eins: Zuversicht. Zum Schluss lässt die Musik die Zuversicht auf die Erfüllung der Träume der kommenden Generationen wachsen.',
        programm: [
          {
            id: 81,
            modul: 'A',
            titelName: 'On the Shoulders of Giants',
            composer: 'Eduardo M. Brito',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 210,
            pflichtStueck: false,
            infoModeration:
              'Dieses Konzertprogramm nimmt die Zuhörer mit auf eine emotionale Reise. Es beginnt mit der kindlichen Perspektive auf den Schultern der Eltern und vermittelt ein Gefühl von Nähe und Zuversicht - bereit, jede Herausforderung anzunehmen.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 82,
            modul: 'A',
            titelName: 'A fairy Tale',
            composer: 'Ferrer Ferran',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 420,
            pflichtStueck: false,
            infoModeration:
              'So spüren auch wir, wie zerbrechlich unser persönliches Glück und wie ungewiss ein Blick in die Zukunft ist. Um diese Zukunft einmal gestalten zu können, brauchen Kinder aber vor allem eins: Zuversicht.\nDas Programm geht dann über zu einer heiteren und zauberhaften Darstellung von den Hütern des Waldes, den Feen aus Märchen und Legenden, die die Verbindung zwischen Realität und Märchenwelt symbolisieren. Lassen wir die Musik die Märchen erzählen, in denen das Gute gewinnt. Lassen wir so die Zuversicht wachsen, schwierige Bedingungen bewältigen zu können.\n',
            valid: true,
          },
          {
            id: 83,
            modul: 'A',
            titelName: 'My Dream',
            composer: 'Peter Leitner',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 225,
            pflichtStueck: false,
            infoModeration:
              'Schliesslich wird die Bedeutung von Träumen und Lebenszielen in unserer Lebensreise hervorgehoben. Die Musik erinnert uns daran, dass es unsere Verantwortung ist, den Lebensraum Wald zu schützen. Sie ermutigt uns, für die Erhaltung der Natur und die Erfüllung der Träume der kommenden Generationen aktiv einzutreten.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 15:20 - 15:25',
        titel: null,
        description: null,
        programm: [
          {
            id: 84,
            modul: 'D',
            titelName: 'Ravanello',
            composer: 'Joseph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 165,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 85,
            modul: 'D',
            titelName: '60 Jahre Musikant',
            composer: 'Jean-Pierre Fleury',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 17,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
