export default defineEventHandler(() => {
  return {
    id: 58,
    name: 'Musikgesellschaft Harmonie Turbenthal',
    direktionName: 'Pascal Zenklusen',
    logoImgId: '8b82e30a-4d49-4981-af7d-e0c0d76e2200',
    bildImgId: '73cab507-4cc6-44ec-0445-b8c8a89c3800',
    homepage: 'https://www.mght.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Wir sind ein bunt gemischter Dorfverein, dem es am Herzen liegt, gemeinsam zu musizieren und dabei Spass zu haben. Wir sind auch gewillt, uns neuen Herausforderungen zu stellen und wollen uns musikalisch weiterentwickeln.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 10:20 - 10:45',
        titel: 'Naturphänomene',
        description:
          'Das Programm soll einerseits die natürliche Schönheit als auch die ungeheure Kraft der Natur musikalisch umrahmen. Während wir als Menschen immer wieder Einfluss auf die Natur haben, sind wir doch letzten Endes machtlos, wenn die Natur zurückschlägt. So soll unser musikalisches Programm die Schönheit und Gewalt der Natur, sowie die Wiederkehr des Lebens unter einen runden Bogen fassen.',
        programm: [
          {
            id: 310,
            modul: 'A',
            titelName: 'Where eagles soar',
            composer: 'Steven Reinecke',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 250,
            pflichtStueck: false,
            infoModeration:
              'Die Konzertouvertüre "Where Eagles Soar" (Wo Adler fliegen) stellt die Schönheit, Weite und Freiheit des US-Staates Main musikalisch dar. Gleichzeitig steht sie auch als Sinnbild dafür, welche mentale Kraft es in einem Menschen auslösen kann, wenn er realisiert, welches Potenzial er in sich trägt. Während sich jeder von uns weiterentwickelt und immer mehr dazu lernt, verstehen wir irgendwann, dass wir ganz individuelle und besondere Talente haben. Wenn wir das vollumfassend begriffen haben, dann befreit sich unser innerer Geist und steigt hinauf - dorthin, wo Adler fliegen.',
            valid: true,
          },
          {
            id: 311,
            modul: 'A',
            titelName: 'Pompeji',
            composer: 'Mario Bürki',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 560,
            pflichtStueck: false,
            infoModeration:
              'Es ist eine Geschichte, die vor mehr als 2000 Jahren begann: Am 24. August 79 n. Chr. brach der Vesuv, ein aktiver Vulkan in der italienischen Region Kampanien, aus und überzog Pompeji in einer dicken Ascheschicht. Der Vulkanausbruch beendete das Leben von etwa 2.000 Menschen und zwang die Bewohner zur Flucht aus dem antiken römischen Gebiet. Doch das Leben geht weiter.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 14:40 - 14:45',
        titel: null,
        description: null,
        programm: [
          {
            id: 312,
            modul: 'D',
            titelName: 'San Carlo',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 313,
            modul: 'D',
            titelName: 'Schwyzer Soldate',
            composer: 'Ernst Lüthold',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
