export default defineEventHandler(() => {
  return {
    id: 48,
    name: 'Musikgesellschaft Häggenschwil',
    direktionName: 'Stefan Herzig',
    logoImgId: '233ddb4a-6f04-4edd-d311-279b53e14a00',
    bildImgId: 'bfde1c4b-bb67-43d7-656a-2a1e27777100',
    homepage: 'https://mg-haeggenschwil.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Musikgesellschaft Häggenschwil ist ein dynamischer Verein, der sich gerne von neuen und kreativen Ideen begeistern lässt und offen für Neues ist. Unsere Musig-Show mit diversen läuferischen Einlagen auf der Bühne ist bereits zur Tradition geworden. Wir verbringen aber auch gerne gemütliche Stunden miteinander, was unseren Zusammenhalt ebenso stärkt.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 11:20 - 11:40',
        titel: 'Rock meets Blasmusik',
        description: 'Programm aus Rock-Klassikern mit einem eigenen Arrangement der Schweizer Band Hecht.',
        programm: [
          {
            id: 163,
            modul: 'B',
            titelName: 'Welcome To The Jungle',
            composer: "Guns N' Roses",
            arrangeur: 'Paul Murtha ',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 160,
            pflichtStueck: false,
            infoModeration:
              "Als Startstück für unseren zweiten Teil der Musig-Show 2024 hat das Stück so richtig 'gfeget'. Mit Show- und Tanzeinlagen auf der Bühne schaffen wir es, unser Publikum (wieder) für die Blasmusik zu begeistern. Auch den Mitgliedern macht es Spass, eine abwechslungsreiche Show einzustudieren. Überzeugen Sie sich auf unserem Facebook-Kanal selbst von unseren Shows.",
            valid: true,
          },
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 164,
            modul: 'B',
            titelName: 'Heicho',
            composer: 'Hecht',
            arrangeur: 'Stefan Herzig',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration:
              "Während Corona hat eine kleine Formation der MGH an einem Gallus Brass Wettbewerb teilgenommen. Da unser Dirigent immer verstanden hat 'und denn isch än Hai cho' anstelle von 'bi dir will i hei cho' trägt das Stück, welches von Stefan Herzig arrangiert wurde, nun auch diesen Titel. Zudem singen wir auch den 'falschen' Titel.",
            valid: true,
          },
          {
            id: 165,
            modul: 'B',
            titelName: 'Coldplay on Stage',
            composer: 'Coldplay',
            arrangeur: 'Michel Brown',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 330,
            pflichtStueck: false,
            infoModeration:
              'Medley aus Clocks, Lost! und Viva La Vida.\nAuch dieses Stück haben wir an der Musig-Show präsentiert. Die abwechslungsreichen Melodien und diversen Soli fordern uns auf eine angenehme Art und Weise heraus. ',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:20 - 15:25',
        titel: null,
        description: null,
        programm: [
          {
            id: 22,
            modul: 'D',
            titelName: 'Herzig-Marsch',
            composer: 'Stefan Herzig',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 178,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 23,
            modul: 'D',
            titelName: 'Montreux',
            composer: 'Raymond Pasche',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 255,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
