export default defineEventHandler(() => {
  return {
    id: 37,
    name: 'Musikverein Langnau am Albis',
    direktionName: 'Fabio Ryser',
    logoImgId: '0960619b-3726-47aa-57a3-fc5f5f369b00',
    bildImgId: '67d48d84-f624-4993-1574-70524258f100',
    homepage: 'https://www.musikverein-langnau.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der im Jahre 2009 gegründete Musikverein Langnau am Albis setzt sich mit Hingabe dafür ein, gute Musik zu pflegen und das öffentliche, kulturelle sowie gesellschaftliche Leben in Langnau am Albis zu bereichern. Durch regelmäßige Proben und öffentliche Auftritte tragen wir aktiv zum Dorfleben bei und hoffen, viele Menschen zu begeistern.\nUnser Repertoire ist vielfältig und umfasst sowohl Originalwerke für Blasorchester als auch zeitgenössische Arrangements. Wir möchten ein breites Publikum ansprechen und wagen uns gerne an verschiedene musikalische Stilrichtungen heran. \nBesonders wichtig ist uns die enge Zusammenarbeit mit der Jugendmusik Sihltal (ehemals Jugendspiel Langnau am Albis). Viele unserer Mitglieder haben bereits in der Jugendmusik Sihltal musiziert oder tun dies immer noch. Wir unterstützen mit Registerproben und helfen beim Jahreskonzert mit. \nWir freuen uns auf musikalische Stunden im Rahmen des ZKMF 2024 !',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 09:00 - 09:25',
        titel: 'Die Kraft des Augenblicks',
        description:
          'In seiner noch jungen Geschichte seit seiner Gründung im Jahre 2009 hat der Musikverein Langnau stets Wert darauf gelegt sowohl für die Musiker als auch fürs Publikum möglichst viele Stilrichtungen zu bedienen. Dabei wurde immer ein Fokus gelegt auf konzertante und wenn möglich auch originale Blasmusik. So ist auch das heute vorgetragene Selbstwahlprogramm entstanden.\nDas lateinische Wort «Momentum» hat verschiedene Bedeutungen: Augenblick, aber auch Bewegung, Schwung und Bewegungskraft. Emotionale Augenblicke kreieren und gleichzeitig Schwung und Dynamik aufbauen, das will der Musikverein Langnau mit seinem Programm bewirken. Dem lyrischen Eingangsstück mit bewegenden harmonischen Momenten folgt das Pflichtstück «May The Forest Bloom Again» mit seinem schwungvollen 7/8-Takt. Noch mehr Bewegungskraft bringt schliesslich die abschliessende Komposition «A Filvar Story» - ein perfekter und schwungvoller Programmaufbau für einen einmaligen musikalischen Augenblick.',
        programm: [
          {
            id: 118,
            modul: 'A',
            titelName: 'Momentum',
            composer: 'Thomas Doss',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 368,
            pflichtStueck: false,
            infoModeration:
              '«Momentum» stammt aus der Feder von Thomas Doss, österreichischer Komponist und Dirigent und wurde am 06.Juni 1966 in Linz geboren.\nDie Eltern von Thomas Doss, beide Berufsmusiker, unterrichteten ihn ab dem Alter von 7 Jahren auf dem Tenorhorn und auf der Posaune. Thomas Doss schrieb mit 11 Jahren erste Kompositionen.\nEr studierte ab 1980 am Brucknerkonservatorium in seiner Heimatstadt Linz und schloss sein Studium in den Fächern Instrumentalpädagogik, Posaune, Komposition und klassisches Dirigieren ab.\nDas lateinische Wort „Momentum“ hat viele Bedeutungen: Augenblick, Bewegung oder bewegende Kraft.\nIn einer Zeit der Schnelligkeit und Raserei soll dieses meditative Musikstück eine kleine Auszeit von Hast und Unruhe sein: ein Verharren und sich Fallenlassen im Moment. \nIn diesem Sinne, geniessen sie diesen kleinen Augenblick mit dem Musikverein Langnau.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 119,
            modul: 'A',
            titelName: 'A Filvar Story',
            composer: 'Vitor Resende',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 510,
            pflichtStueck: false,
            infoModeration:
              'Vitor Resende, mit ganzem Namen Vitor Manuel Resende Silva ist ein portugiesischer Komponist. Neben seinen Tätigkeiten als Komponist zeichnet er sich auch seit 15 Jahren verantwortlich als Professor an der Academia de Resende. \n«A Filvar Story» ist ein Porträt der Geschichte der Philharmonic Varzeense Filvar. Ein Beweis dafür, dass mit harter Arbeit alle Ziele erreicht werden können. \nVitor Resende hat ein inspirierendes Werk komponiert, um sich der Herausforderung einer Eigenkomposition zu stellen und das Repertoire des Orchesters um portugiesische Komponisten zu erweitern.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:30 - 14:35',
        titel: null,
        description: null,
        programm: [
          {
            id: 122,
            modul: 'D',
            titelName: 'Rumisberger Marsch ',
            composer: 'W.Joseph',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 123,
            modul: 'D',
            titelName: 'For Ever',
            composer: 'E.Röthlisberger',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
