export default defineEventHandler(() => {
  return {
    id: 29,
    name: 'Musikverein Eintracht Wallisellen',
    direktionName: 'Reto Aeppli',
    logoImgId: '2c95999a-86a4-41a5-bf39-9281f6007300',
    bildImgId: 'a9f53bb8-d383-448a-de4c-efd74cf57700',
    homepage: 'https://www.musik-wallisellen.ch',
    facebook: null,
    instagram: null,
    websiteText: 'www.musik-wallisellen.ch',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 11:40 - 12:05',
        titel: 'Waldbrand bei Bitsch VS ',
        description:
          'Arctic Fire entführt das Publikum in eine sternenklare Nacht in die Walliser Alpen. Das Stück Swiss Mountain Village beschreibt eigentlich die Walliser Gemeinde Törbel, wir spielen es als Symbol für das Leben in einem Walliser Bergdorf. Das aufkommende Feuer und den Waldbrand stellt das Stück May the Forest Bloom Again dar. Und das Stück After the Battle vermittelt ein Gefühl von Aufatmen und neuer Hoffnung für die Bewohner und die Fachkräfte, die gegen das Feuer gekämpft haben.\n__\nModerationsinfo zum Stück "May the Forest Bloom Again":\nMit dem nächsten Stück «May the Forest Bloom Again» wird es ganz aktuell. Théo \nSchmitt thematisiert darin die weltweiten katastrophalen Waldbrände in den Jahren 2021 \nund 2022. Im Sommer 2023 wurde Bitsch und seine Umgebung Opfer einer solchen \nstarken, langanhaltenden Feuersbrunst. Die anfängliche Idylle eines dichten, alten \nWaldes weicht der zerstörerischen Kraft des Feuers und zeigt die verheerende \nAuswirkungen einer solchen Tragödie. Schmitt zeichnet gegen Ende des Stückes aber \nauch das langsame Wiedererwachen der Natur nach einem solchen tragischen Ereignis, \nsowie die erstaunliche Eigenschaft der Natur, wie ein Phönix aus der Asche \nwiederzuerstehen. Nach und nach regeneriert sich der Wald und die Natur holt sich die \nzerstörten Flächen langsam aber stetig wieder zurück.\nErleben Sie dieses turbulente Ereignis zusammen mit uns und «May the Forest Bloom \nAgain».',
        programm: [
          {
            id: 52,
            modul: 'A',
            titelName: 'Arctic Fire',
            composer: 'Robert (Bob) Buckley',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 315,
            pflichtStueck: false,
            infoModeration:
              'Herzlich willkommen zu unserem Konzert. Es freut uns sehr, dass Sie uns auf unserer \nmusikalischen Reise begleiten werden. Wir möchten Sie mit «Arctic Fire» von Robert \nBuckley in die Walliser Alpen entführen. Mit ihren weissen, verschneiten – fast arktischen \n- Gipfeln thronen sie majestätisch über dem Tal. Der Sonnenuntergang lässt sie in einem \nstrahlenden Rot erglühen und weithin strahlen, bevor die sternenklare Nacht hereinbricht \nund der Mond die Berge in ein fahles, geheimnisvolles Licht hüllt.\nGeniessen Sie mit uns diese musikalische Wanderung durch dieses imposante «Feuer aus \ndem Eis» mit «Arctic Fire». Viel Vergnügen!',
            valid: true,
          },
          {
            id: 53,
            modul: 'A',
            titelName: 'Swiss Mountain Village',
            composer: 'Mario Bürki',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 360,
            pflichtStueck: false,
            infoModeration:
              'Hier inmitten der Walliser Alpen liegt das malerische Dorf Bitsch. Nach unserer\nWanderung durch die strahlenden, verschneiten Gipfel der Walliser Alpen besuchen wir \nnun dieses «Swiss Mountain Village». Mario Bürki zeichnet in seinem gleichnamige Werk \nmusikalisch die Idylle von Törbel, einem ähnlichen, kleinen, verträumten Bergdorf nach. Die Kühe \nweiden auf den Wiesen, weithin klingen ihre Glocken und im Hintergrund hört man das \nrhythmische «klack-klack» der alten Mühlen.\nVerweilen Sie mit uns in dem "Schweizer Bergdorf" und geniessen Sie den Aufenthalt mit «Swiss Mountain \nVillage».',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 54,
            modul: 'A',
            titelName: 'After the Battle',
            composer: 'Rob Romeyn',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 169,
            pflichtStueck: false,
            infoModeration:
              'Mit unserem letzten Stück «After the Battle» von Rob Romeyn denken wir an die Helden \nvon Bitsch. Es sind dies die vielen unermüdlichen Helfer der Feuerwehr, der \nFluglöschdienste, des Militärs und sämtlicher anderen Hilfsorganisationen welche an der \nBekämpfung dieses Brandes beteiligt waren.\nDie Mühen und Belastungen für die Helfer im Kampf gegen das Feuer sind enorm. Umso \nmehr haben sie sich nach der Schlacht Ruhe verdient. Sie dürfen stolz auf sich sein, Ihre \nMitmenschen vor den verheerenden Schäden durch diese Naturgewalt - mitunter unter \nEinsatz ihres eigenen Lebens - beschützt zu haben.\nZollen wir nach dieser Schlacht gegen die Naturgewalten den unermüdlichen Helfern und \nRettern unseren Respekt mit «After the Battle».',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
