export default defineEventHandler(() => {
  return {
    id: 66,
    name: 'Musikverein Rümlang',
    direktionName: 'Roland Schiesser',
    logoImgId: 'e9f3fd95-7e2e-4795-d1fc-589ae2c52200',
    bildImgId: '500f5ebb-44db-4865-bc93-485d00427100',
    homepage: 'https://www.mvruemlang.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Rümlang besteht seit 1959. Die Vereinsgeschichte ist also schon alt, sicherlich bewegt aber keinesfalls verstaubt. Im Gegenteil, dank aktiven Mitgliedern hat der Verein allen Strömungen Stand gehalten und wir sind stolz darauf, dass wir als Dorfverein mit unseren engagierten Aktivmitgliedern das ganze Jahr hindurch  musizieren und an lokalen Veranstaltungen teilnehmen. \nNicht nur musikalisch sind wir aktiv, auch das gemütliche Beisammensein bei einem Grillend oder Fondueplausch sowie diverse Ausflüge gehören bei uns zum Programm.',
    timetableEntries: [
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:30 - 13:35',
        titel: null,
        description: null,
        programm: [
          {
            id: 274,
            modul: 'D',
            titelName: 'Musketier-Marsch',
            composer: 'Ernst Lüthold',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 275,
            modul: 'D',
            titelName: 'Pioneers March',
            composer: 'Harm Evers',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Mittelstufe, Harmonie',
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:45 - 15:05',
        titel: 'Musikverein Rümlang at its best! Dance/Techno mit sweet Jazz und the best of Jackson Five!',
        description:
          'Das Programm soll die Vielfältigkeit des Musikvereins Rümlang aufzeigen. Von Dance und neuesten Kompositionen über swingigen Jazz bis hin zum King of Pop beherrscht der MVR nicht nur die Harmonie und Intonation, sondern insbesondere auch die abwechslungsreichen Rhythmen in den verschiedenen Sparten. ',
        programm: [
          {
            id: 12,
            modul: 'B',
            titelName: "We'll Make It Work",
            composer: 'Christoph Walter',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 300,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 272,
            modul: 'B',
            titelName: 'Jitterbug!',
            composer: 'Robert Buckley',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              "Jitterbug! ist ein jazziger Mix zum Mitwippen! Zur Blütezeit des Jazz hatte jede der großen Swing-Bands ihren eigenen 'signature'-Sound, der für ihre begeisterten Fans sofort erkennbar war. Diese Komposition stellt diese verschiedenen Klänge und Rhythmen zu einer Hommage an eine lebendige und innovative Zeit in der amerikanischen Musik zusammen. ",
            valid: true,
          },
          {
            id: 273,
            modul: 'B',
            titelName: 'Jackson 5 Medley',
            composer: 'Jackson Five',
            arrangeur: 'Takashi Hoshide',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 460,
            pflichtStueck: false,
            infoModeration:
              'The best of... Von Michael Jackson und den Jackson Five könnte man locker 20 Songs oder mehr spielen. Wir durften uns an diesem tollen Arrangement austoben.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 9,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 17,
          identifier: 'turnhalle-weihermatt-urdorf',
          name: 'Turnhalle Weihermatt Urdorf',
          address: 'Weihermattstrasse 50, 8902 Urdorf',
          latitude: 47.379936044763,
          longitude: 8.427330468337,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
          sortOrder: 4,
          mapId: '6W',
          cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
          kuulaId: '5ZfzW',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.379936044763,
            longitude: 8.427330468337,
          },
        },
        description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
