export default defineEventHandler(() => {
  return {
    id: 81,
    name: 'Musikverein Harmonie Adliswil',
    direktionName: 'Marc Bühler',
    logoImgId: '5fd2817d-2d40-47e2-95ac-715a206d0200',
    bildImgId: 'f4099c42-3afe-4e38-bec1-d4ad1c6cf300',
    homepage: 'https://www.harmonie-adliswil.ch',
    facebook: 'https://www.facebook.com/mvhadliswil',
    instagram: 'https://www.instagram.com/mvhadliswil/',
    websiteText:
      'Obwohl wir den Jahrgang 1891 haben, spielen wir keineswegs nur altbewährte Blasmusik, sondern fühlen uns fast wohler in der modernen Unterhaltungsmusik. Neben unserer alljährlichen Abendunterhaltung im Februar spielen wir jeweils im April als Zunftmusik der Schmiden am Sechseläuten mit oder unterhalten die Menschen in und um Adliswil.',
    timetableEntries: [
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 21,
          identifier: 'festzelt-schlieren',
          name: 'Festzelt Schlieren',
          address: 'Badenerstrasse 12, 8952 Schlieren',
          latitude: 47.397439543225,
          longitude: 8.446011061969,
          googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 9,
          mapId: 'FS',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.397439543225,
            longitude: 8.446011061969,
          },
        },
        dateTime: 'So., 23.06.2024, 12:15 - 13:00',
        titel: null,
        description: null,
        programm: [],
      },
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 22,
          identifier: 'festzelt-urdorf',
          name: 'Festzelt Urdorf',
          address: 'Bahnhofstrasse 52, 8902 Urdorf',
          latitude: 47.386092494172,
          longitude: 8.424727317603,
          googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 8,
          mapId: 'FU',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 8,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.386092494172,
            longitude: 8.424727317603,
          },
        },
        dateTime: 'So., 23.06.2024, 16:00 - 16:45',
        titel: null,
        description: null,
        programm: [],
      },
    ],
    rankings: [],
  }
})
