export default defineEventHandler(() => {
  return {
    id: 25,
    name: 'Musikverein Harmonie Birmensdorf',
    direktionName: 'Cäcilia Gebhardt',
    logoImgId: '68114baf-a26c-4b46-f04b-7e256ebb4c00',
    bildImgId: 'ac903a33-a6a5-426a-f2e7-a2ec9c84ce00',
    homepage: 'https://mhbirmensdorf.ch',
    facebook: 'https://www.facebook.com/profile.php?id=100063672812286',
    instagram: null,
    websiteText:
      'Der Musikverein Harmonie Birmensdorf wurde bereits im Jahr 1904 gegründet. Trotz seines hohen Alters strahlt er mit seinen gut 40 Aktivmitgliedern in jugendlicher Frische. \nWir sind ein Dorfverein, welcher die Gemeinden Birmensdorf, Aesch und Uitikon an diversen Auftritten repräsentiert. So sind uns Ständli im Dorf genauso wichtig wie die Teilnahme an Musikfesten.\n\nJeweils am letzten Novembersamstag und am ersten Dezembersamstag finden unsere traditionellen Jahreskonzerte statt. Wir bieten ein abwechslungsreiches Programm mit Unterhaltungsmusik vom Marsch über Dixie, Pop, Rock bis zu Klassik, Musicals und Filmmusik.\n\nDas alljährlich Kirchenkonzert in der reformierten Kirche in Birmensdorf fordert uns in klassischer und konzertanter Blasmusikliteratur.\n\nAls Zunftspiel der Zunft zur Meisen sind wir schon viele Jahre am traditionsreichen Zürcher Sechseläuten mitten in der Innenstadt mit dabei.\n\nWir wagen uns immer wieder an spezielle Musikprojekte wie zum Beispiel das Konzert mit den vereinigten Chören von Birmensdorf oder das Gemeinschaftskonzert mit dem Musikverein Harmonie Wollishofen.\n\nAuch die Geselligkeit kommt bei uns nicht zu kurz. Wir legen viel Wert auf gute Kameradschaft und eine gesellige Vereinskultur.\n\nWir proben jeweils am Montag im Gemeindezentrum Brüelmatt von 20:00-22:00 Uhr (Zusatzproben sind am Donnerstag) und freuen uns über jeden Besuch.\n',
    timetableEntries: [
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 21,
          identifier: 'festzelt-schlieren',
          name: 'Festzelt Schlieren',
          address: 'Badenerstrasse 12, 8952 Schlieren',
          latitude: 47.397439543225,
          longitude: 8.446011061969,
          googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 9,
          mapId: 'FS',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.397439543225,
            longitude: 8.446011061969,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:50 - 11:30',
        titel: null,
        description: 'Die Stücke 10-12 sind Zugaben. Kurzfristige Programmänderungen vorbehalten.',
        programm: [],
      },
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:20 - 14:45',
        titel: 'Eine musikalische Reise',
        description:
          'An einem sonnigen, warmen Tag packen wir morgens früh unsere Sachen und fahren mit dem Auto in Richtung Süden. Durch die heruntergelassenen Scheiben hören wir eine fröhliche Fanfare, wahrscheinlich ein Volksfest. Wir sind gut gelaunt und bereits gespannt, was wir noch alles erleben werden.\n \nAls wir durch duftende, unberührte Pinienwälder schweifen und die frische Luft geniessen, sehen wir von weitem plötzlich eine bedrohliche, schwarze Rauchsäule – ein Waldbrand! Um der Gefahr zu entkommen, biegen wir ab und fahren so schnell wie möglich weiter. An einer anderen Stelle hat es bereits vor einer Weile gebrannt: Wir sehen, wie aus der tristen, grauen Landschaft wieder einzelne Pflänzchen zu spriessen beginnen. Betroffen hoffen wir, dass die Natur sich bald wieder erholt.\n \nNach einer Weile sehen wir das tiefblaue Meer, wo sich die Wellen sanft am Strand kräuseln. Dort angekommen, geniessen wir es, wie unsere Füsse vom Meerwasser umspült werden und bestaunen die Seevögel, die am Horizont vorüberziehen. Ausgeruht und voller Tatendrang rennen wir dem Strand entlang, den Wind in den Haaren, den feinen Sand unter den Füssen. Zwischendurch setzen wir uns auf die Terrasse eines Restaurants und lassen die Gedanken kreisen, welch prächtige Aussicht! Wir lassen die beeindruckende Weite des Meeres eine Weile auf uns wirken. Frisch gestärkt ziehen wir voller Energie weiter durch die Dünen.\n \nAm Abend geniessen wir ein Konzert auf dem Platz des Fischerdorfes unter freiem Himmel. Engagiert spielen die jungen und älteren Musiker ein abwechslungsreiches Programm. Das Publikum klatscht begeistert und das Orchester spielt eine mitreissende Zugabe. Zurück im Hotel fallen wir glücklich, aber auch nachdenklich ins Bett – was für ein aufregender Tag!',
        programm: [
          {
            id: 111,
            modul: 'A',
            titelName: 'A Little Opening - Fanfare for Concert Band',
            composer: 'Thiemo Kraas',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration:
              'Diese Komposition des jungen deutschen Komponisten Thiemo Kraas erzeut unmittelbar die aufregende Atmosphäre eines Konzertbeginns, der das Publikum in den Bann zieht. Die Spannung liegt förmlich in der Luft und zieht sich in Form einer Fanfare wie ein roter Faden durch das ganze Werk. Das Stück endet über ein spannungsvolles, großes Ritardando in einem funkelnden Presto.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 112,
            modul: 'A',
            titelName: 'Seagate Overture',
            composer: 'James Swearingen',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 457,
            pflichtStueck: false,
            infoModeration:
              'Dieses bedeutende Blasorchesterwerk stammt aus der Feder des bekannten US-amerikanischen Komponisten James Swearingen, wurde 1988 uraufgeführt und sofort mit Begeisterung von den Musikern und dem Publikum aufgenommen. Die spannende Konzertouvertüre mit langsamer Einleitung und zwei schnellen rhythmischen Teilen, die den getragenen mittleren Abschnitt umschliessen, ist ein schönes Beispiel für die herausragenden musikalischen Qualitäten des Komponisten, der bisher über 400 Werke geschrieben hat. Der Dialog zwischen Holz- und Blechbläsern sowie der Perkussion bringt alle Nuancen des modernen Blasorchesters zum Vorschein.',
            valid: true,
          },
          {
            id: 113,
            modul: 'A',
            titelName: 'Salute to a Hero – Fanfare for Billy',
            composer: 'Philip Sparke',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 135,
            pflichtStueck: false,
            infoModeration:
              '„Salute to a Hero“ wurde 2009 beim bekannten englischen Komponisten Philip Sparke für das Frühlingskonzert der Marlow High School Band in Oklahoma zu Ehren des musikalischen Direktors Billy Daniel in Auftrag gegeben. Das Stück beginnt mit einer Blechbläserfanfare, die von den Holzbläsern umschmückt wird. Nach einer kurzen Überleitung kehrt die Fanfare zurück, diesmal gespielt vom gesamten Blasorchester. Ein lyrischer Mittelteil erzeugt Ruhe und Kontraste zwischen den Blech- und Holzbläserregistern, bevor das Werk wiederum durch die Fanfare majestätisch beendet wird. ',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
