export default defineEventHandler(() => {
  return {
    id: 21,
    name: 'Musikverein Harmonie Zürich Schwamendingen',
    direktionName: 'Matteo Genini',
    logoImgId: '9a60f7af-fc0e-4a27-d4cd-6f2ed6d81300',
    bildImgId: '60f9cc22-a346-4edb-d915-770b24effd00',
    homepage: 'https://www.mvschwamendingen.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der MVS ist ein lebhafter und engagierter Verein im Quartier Schwamendingen mit rund 30 Musizierenden.\nWir heissen Neulinge und Wiedereinsteigende genauso herzlich willkommen wie Fortgeschrittene. Mit offenen Armen empfangen wir alle Interessierten und sind stets auf der Suche nach musikalischer Verstärkung. Egal welches Niveau alle haben die Möglichkeit, sich dem Verein anzuschliessen und gemeinsam mit Gleichgesinnten Musik zu machen. Die Gemeinschaft steht im Mittelpunkt, und alle tragen zum klangvollen Zusammenspiel bei.\nWir proben jeden Mittwoch und begeistern an unseren Konzerten mit Stücken der 4. Stärkeklasse aus einem breiten Spektrum an musikalischen Genres. Darüber hinaus ist der Verein stolz darauf, als Zunftmusik der Zunft Schwamendingen jedes Jahr beim Zürcher Sechseläuten mitzulaufen.\nWir danken für die Organisation und freuen uns auf das kantonale Musikfest.\n',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 4. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:20 - 10:45',
        titel: 'Von der Schlacht zum Fest',
        description:
          'Die Eröffnung des Programms wird mit "Hymnus Pastorale" von Bert Appermont gemacht. Es erzählt von einem unbeschwerten und Tugendhaftem Leben auf dem Land.\n"Samurai" von Mathias Wehr führt die Zuhörer in eine kraftvolle Klangwelt. Die musikalische Darstellung der Samurai-Ära spiegelt sich in diesem Stück wieder. \n"Lay Down Your Arms" von Florian Moitzi bildet das emotionale Herzstück des Programms. Es thematisiert den Kontrast zwischen Krieg und Frieden und träumt von einer waffenlosen Gesellschaft.\nDas Finale mit "Ein Fest der Musik" von Thomas Rüedi bietet einen fulminanten musikalischen Abschluss des Programms, das den Kreis schliesst und wieder zu einer unbeschwerten, fröhlichen Stimmung zurückkehrt.',
        programm: [
          {
            id: 198,
            modul: 'A',
            titelName: 'Hymnus Pastorale',
            composer: 'Bert Appermont',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration:
              'Wir Eröffnen das Programm mit "Hymnus Pastorale" von Bert Appermont. Es erzählt von einem unbeschwerten und tugendhaften Leben auf dem Land.',
            valid: true,
          },
          {
            id: 5,
            modul: 'A',
            titelName: 'Samurai',
            composer: 'Mathias Wehr',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 200,
            modul: 'A',
            titelName: 'Lay Down Your Arms',
            composer: 'Florian Moitzi',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 295,
            pflichtStueck: false,
            infoModeration:
              'Mit "Lay down your arms" beschreibt der Komponis Florian Moitzi das Leben und Werk von Bertha von Suttner, einer österreichischen Pazifistin die 1905 als erste Frau den Friedensnobelpreis erhielt. Das Stück thematisiert den Kontrast zwischen Krieg und Frieden und träumt von einer waffenlosen Gesellschaft.',
            valid: true,
          },
          {
            id: 202,
            modul: 'A',
            titelName: 'Ein Fest der Musik',
            composer: 'Thomas Rüedi',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 225,
            pflichtStueck: false,
            infoModeration: '"Ein Fest der Musik" von Thomas Rüedi bietet ein fulminanten musikalischen Abschluss unseres Programmes.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 5,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_4',
        klasseDescription: '4. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 4. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
