export default defineEventHandler(() => {
  return {
    id: 98,
    name: 'Musikgesellschaft Rafz',
    direktionName: 'Nadine Brennwald',
    logoImgId: 'e98c3f25-51e7-43d4-729c-d66ee824fe00',
    bildImgId: 'f1b9ba28-8e2f-439a-85cc-aa5415dbdf00',
    homepage: 'https://www.mg-rafz.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der 1917 gegründete Verein zählt immer gute 35 Aktivmitglieder.\n \nDer Verein hat eine gute Mischung von "Alt und Jung".\n \nWir spielen in der 3. Stärkeklasse, Harmonie.\n \nUnser Repetoir hat Stücke von leichter klassischer Musik über traditionelle Märsche bis zur modernen Unterhaltungsmusik.\n \nEine Hautpaufgabe ist das Umrahmen von Dorfanlässen. Wir spielen zu goldenen und diamantenen Hochzeiten, sowie bei 80, 90 und ab 95 Jahren jährlich unseren Mitbürgern.\n \nDer Verein fördert auch das kameradschaftliche Miteinander und unternimmt dazu Vereinsreisen oder andere Freizeitaktivitäten.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 11:00 - 11:25',
        titel: 'MG Rafz im Zyklus des Lebens',
        description: 'Das Programm beschreibt das Entstehen und Vergehen als zentrale Konstante im Leben.',
        programm: [
          {
            id: 26,
            modul: 'A',
            titelName: 'Orion',
            composer: 'Jan van der Roost',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Die Reise beginnt am Himmel im Sternbild Orion. Orion ist in der griechischen Mythologie der grosse Jäger und als guter Jäger weiss er auch, dass in der Natur stets ein Entstehen und Vergehen gibt, Leben und Tod, Blühen und Verwelken. Dieses Thema wird durch das anschliessende Stück "May the forrest bloom again" aufgenommen, welches einen Waldbrand und die anschliessende Rückkehr des Lebens beschreibt.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 27,
            modul: 'A',
            titelName: 'Towards a new Horizon',
            composer: 'Steven Reinecke',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 368,
            pflichtStueck: false,
            infoModeration: 'Aufbruch zu einem neuen Horizont und einem neuen Anfang. Nach einem Ende folgt der Aufbruch zu neuen Ufern um neu zu beginnen.',
            valid: true,
          },
          {
            id: 28,
            modul: 'A',
            titelName: 'El Ladronzuelo',
            composer: 'Emilio Esteban Rojo de Broma',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'El Landronzuelo ist die Verkleinerungsform von Taschendieb auf Spanisch. Und auch für die gestohlenen Gegenstände Beginnt ein neues in den Händen des neuen Besitzers.',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 15:40 - 15:45',
        titel: null,
        description: null,
        programm: [
          {
            id: 24,
            modul: 'D',
            titelName: 'Feurig Blut',
            composer: 'Hans Heusser',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 25,
            modul: 'D',
            titelName: 'Slaidburn',
            composer: 'William Rimmer',
            arrangeur: 'K. v. d. Woude',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 230,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
