export default defineEventHandler(() => {
  return {
    id: 97,
    name: 'Musikverein Harmonie Wädenswil',
    direktionName: 'Roger Rütti',
    logoImgId: 'b7747d47-a48e-4c67-697d-df9e05f09200',
    bildImgId: 'fee6e586-708f-4319-3ed9-888e01605a00',
    homepage: 'http://www.harmonie-waedenswil.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Der Musikverein Harmonie Wädenswil wurde 1883 aus einer Initiative des Männergesangvereins heraus gegründet. Heute umfasst das Orchester ca. 55 MusikerInnen aller Altersklassen. Als Stadtmusik der grössten Gemeinde am Zürichsee sind wir fester Bestandteil des kulturellen Lebens in Wädenswil. Darüber hinaus sind wir mit Stolz seit über 50 Jahren die Zunftmusik der "Zunft zu den drei Königen" aus Zürich.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Oberstufe, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'So., 23.06.2024, 09:45 - 10:10',
        titel: 'Tribute to Naohiro Iwai',
        description:
          'Das Pflichtstück enthält viele verschiedene Musikstile aber keinen Jazz. Deshalb schlagen wir eine Brücke zwischen dem norwegischen Komponisten/Posaunisten und den USA. Die beiden ausgewählten Jazzarrangements ergänzen und umhüllen das Pflichtstück mit ihrem Swing sehr gut. Wir haben uns für zwei Arrangements von Naohiro Iwai entschieden, da sich 2024 sein Todestag zum zehnten Mal jährt und er mit seinen ca. 5000 Arrangements zu den bedeutendsten Arrangeuren im Bereich der Unterhaltungsmusik zählt.',
        programm: [
          {
            id: 153,
            modul: 'B',
            titelName: 'American Beauties',
            composer: 'Diverse',
            arrangeur: 'Naohiro Iwai',
            grad: 4.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 445,
            pflichtStueck: false,
            infoModeration:
              'In diesem Medley hat Naohiro Iwai sechs der schönsten amerikanischen Hits vereint, die in den vierziger und fünfziger Jahren erstmals veröffentlicht wurden, aber auch heute noch in aller Munde und Herzen sind: wahre musikalische American Beauties eben!',
            valid: true,
          },
          {
            id: 11,
            modul: 'B',
            titelName: 'Halvdan Sivertsen Medley',
            composer: 'Lars Erik Gudim',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 390,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 154,
            modul: 'B',
            titelName: "There's No Business Like Show Business",
            composer: 'Irving Berlin',
            arrangeur: 'Naohiro Iwai',
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 320,
            pflichtStueck: false,
            infoModeration:
              'Der beliebte Show-Klassiker von Irving Berlin präsentiert sich im modernen Gewand des japanischen "Top-Schneiders" für Blasorchester-Arrangements Naohiro Iwai. ',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 14:00 - 14:05',
        titel: null,
        description: null,
        programm: [
          {
            id: 144,
            modul: 'D',
            titelName: 'Albula',
            composer: 'Oscar Tschuor',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 145,
            modul: 'D',
            titelName: 'Gruss an Bern!',
            composer: 'Carl Friedemann',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 16,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'OBERSTUFE',
        klasseDescription: 'Oberstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'B - Unterhaltungsmusik, Oberstufe, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
