export default defineEventHandler(() => {
  return {
    id: 111,
    name: 'Perkussionsensemble Winterthur',
    direktionName: 'Willi Forster',
    logoImgId: '3cf839ab-545e-47ce-d79c-1b28bc424200',
    bildImgId: null,
    homepage: null,
    facebook: null,
    instagram: null,
    websiteText:
      'Die Formation setzt sich vor allem aus jetzigen und ehemaligen Schülerinnen und Schülern der Musikschule „Eulach-Perkussion“ Winterthur und Gästen zusammen. Wir wollen den Anlass des ZKMF 24 in Urdorf nutzen, um um das Werk von David Maslanka aufzuführen.',
    timetableEntries: [
      {
        modul: 'H',
        competition: 'Perkussionsensembles, Oberstufe',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:55 - 16:15',
        titel: null,
        description: null,
        programm: [
          {
            id: 432,
            modul: 'H',
            titelName: 'Ogun Badagris',
            composer: 'Christopher Rouse',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: 'Schwer',
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              'Ogun Badagris ist inspiriert von haitianischen Trommelrhythmen. Die verschiedenen Instrumente übernehmen abwechselnd führende Funktionen. Christopher Rouse hat in vielen seiner Werke ethnische Trommelrhythmen verarbeitet.',
            valid: true,
          },
          {
            id: 433,
            modul: 'H',
            titelName: 'Quintett für Marimbas',
            composer: 'Michael H. Lang',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: 'Schwer',
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              'Das Quintett für Marimbas von Michael H. Lang bringt auf virtuose Weise die vielfältigen Möglichkeiten der Instrumente zur Geltung.\nMichael H. Lang, selbst Marimbaspieler, Pädagoge und Komponist vermittelt in einer eigenen Tonsprache seine Freude an Musik und am Instrument.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 12,
        modul: 'H',
        modulDescription: 'H - Perkussionsensembles',
        klasse: 'OBERSTUFE',
        klasseDescription: 'Oberstufe',
        besetzung: 'PERKUSSIONSENSEMBLE',
        besetzungDescription: 'Perkussionsensemble',
        category: null,
        categoryDescription: null,
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'H - Perkussionsensembles, Oberstufe, Perkussionsensemble (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
