export default defineEventHandler(() => {
  return {
    id: 72,
    name: 'Schlagzeugensemble Florhof',
    direktionName: 'Luca Borioli',
    logoImgId: '01bea775-073f-4e7d-6c99-2ee97506f500',
    bildImgId: null,
    homepage: null,
    facebook: null,
    instagram: null,
    websiteText:
      'Das Ensemble Florhof ist eine bunte ZUsammenstellung von Anfänger und fortgeschrittene Schüler. Gemeinsam haben sie die Neugier neue Instrumente auszuprobieren, und die Freude am Zusammenspiel.',
    timetableEntries: [
      {
        modul: 'H',
        competition: 'Perkussionsensembles, Mittelstufe',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:10 - 14:30',
        titel: null,
        description: null,
        programm: [
          {
            id: 370,
            modul: 'H',
            titelName: 'Metheny Medley',
            composer: 'Pat Metheny - Lyle Mays',
            arrangeur: 'Luca Borioli',
            grad: null,
            schwierigkeitsgrad: 'Mittel',
            durationInSeconds: 405,
            pflichtStueck: false,
            infoModeration: 'Das Medley besteht aus drei Stücken gespielt von der "Pat Metheny Group": Minuano, Last Train Home, First Circle',
            valid: true,
          },
          {
            id: 371,
            modul: 'H',
            titelName: 'Peach Fuzz',
            composer: "Peter O'Gorman",
            arrangeur: '-',
            grad: null,
            schwierigkeitsgrad: 'Mittel',
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration:
              'Da unser Ensemble unbedingt ein Rudimental Stück in der "klassischen " Besetzung Snare Drum, Tenor Drum und Bass Drum spielen wollte, aber kaum Oktette für diese Besetzung gibt, haben wir ein Trio einstudiert, und die Stimmen jeweils verdoppelt. ',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 11,
        modul: 'H',
        modulDescription: 'H - Perkussionsensembles',
        klasse: 'MITTELSTUFE',
        klasseDescription: 'Mittelstufe',
        besetzung: 'PERKUSSIONSENSEMBLE',
        besetzungDescription: 'Perkussionsensemble',
        category: null,
        categoryDescription: null,
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'H - Perkussionsensembles, Mittelstufe, Perkussionsensemble (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
