export default defineEventHandler(() => {
  return {
    id: 59,
    name: 'SJMUZ Percussion Ensemble',
    direktionName: 'Christoph von Bergen',
    logoImgId: 'f88352ed-f2e4-4f39-6192-12c04632eb00',
    bildImgId: '71147c24-4d4b-435c-1725-987a13f5ca00',
    homepage: 'https://www.sjmuz.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Das SJMUZ Percussion Ensemble bietet den Aspi- und Blasorchester-Schlagzeugern die Möglichkeit, als Ergänzung zu ihrer Formation zusätzlich in einem Schlagzeugensemble zu spielen. Je nach Projekt bestehen wir aus 6 - 12 Schlagzeugerinnen und Schlagzeugern.\nDer Höhepunkt des Jahres ist jeweils der Auftritt am Jahresschlusskonzert am ersten Wochenende im Dezember. Aber wir nehmen auch regelmässig an Wettbewerben teil. So konnten wir am Eidgenössischen Jugendmusikfest in Zug 2013 den Schweizermeister Titel in der Kategorie Schlagzeugensembles gewinnen. Ausserdem dürfen wir jeweils das Blasorchester auf seinen Auslandreisen begleiten.\nWir decken die ganze Bandbreite der Perkussionsliteratur ab: neben anspruchsvollen Wettbewerbsstücken spielen wir viel Grooviges, aber auch effektvolle Show-Stücke fehlen nicht in unserem Repertoire. Bei Umzügen führt das SJMUZ Percussion Ensemble als Drumline das Blasorchester an und bildet so die akustische Visitenkarte der SJMUZ.',
    timetableEntries: [
      {
        modul: 'H',
        competition: 'Perkussionsensembles, Oberstufe',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:20 - 15:40',
        titel: null,
        description: null,
        programm: [
          {
            id: 365,
            modul: 'H',
            titelName: 'Symphonie Nr. 10; II. Allegro',
            composer: 'Dmitri Schostakovich',
            arrangeur: 'Christoph von Bergen',
            grad: null,
            schwierigkeitsgrad: 'Schwer',
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              'Dimitri Schostakovitsch lebte im kommunistischen Russland und litt sehr unter der Diktatur von Josef Stalin. Sich dagegen zu wehren, war lebensgefährlich. Schostakovitsch tat es trotzdem: Und zwar mit seiner Musik. Diese ist oft mit einem doppelten Boden versehen: Auf den ersten Blick vielleicht fröhlich, harmlos, offenbaren sich bei genauerem Hinhören Abgründe und beissende Kritik.\nIn seiner 10. Symphonie komponierte Schostakovitsch im zweiten Satz (Allegro) ein musikalisches Portrait von Stalin. Dessen gefürchteten Wutausbrüche, sein irrationaler Charakter, sein unmenschlicher, gnadenloser Machtapparat, werden hier musikalisch erlebbar gemacht.\nDas düstere Weltgeschehen lässt einem als einzelnes Individuum oft machtlos zurück. Mit diesem Werk wollen wir ein Statement gegen Totalitarismus und Diktatur abgeben.',
            valid: true,
          },
          {
            id: 366,
            modul: 'H',
            titelName: 'Starlight',
            composer: 'Peter Meechan',
            arrangeur: 'Christoph von Bergen',
            grad: null,
            schwierigkeitsgrad: 'Schwer',
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Als ruhiger Gegenpol zum dramatischen und wilden Schostakovitsch haben wir Startlight gewählt. Dieses ursprünglich für Brass Band komponierte Werk beginnt mit leisen, schwebenden Klängen und einer friedlichen Melodie. Quasi ein musikalischer Blick in den Sternenhimmel.\nDie anfangs leise, zerbrechliche Melodie steigert sich immer mehr zu einem klanggewaltigen Höhepunkt, das Licht der Sterne überstrahlt am Ende alles…',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 12,
        modul: 'H',
        modulDescription: 'H - Perkussionsensembles',
        klasse: 'OBERSTUFE',
        klasseDescription: 'Oberstufe',
        besetzung: 'PERKUSSIONSENSEMBLE',
        besetzungDescription: 'Perkussionsensemble',
        category: null,
        categoryDescription: null,
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'H - Perkussionsensembles, Oberstufe, Perkussionsensemble (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
