export default defineEventHandler(() => {
  return {
    id: 94,
    name: 'SJMUZ Schlagzeugensemble',
    direktionName: 'Christoph von Bergen',
    logoImgId: '74515138-d025-4cc0-774e-9cad2dcbe000',
    bildImgId: 'ca0cafe8-a83b-40dc-6ec9-ad217905f500',
    homepage: 'https://www.sjmuz.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Das SJMUZ-Schlagzeugensemble bietet jungen Schlagzeugerinnen und Schlagzeugern ab ca. einem Jahr Unterricht eine erste Möglichkeit für das Zusammenspiel. Die Gruppe besteht aus 4 – 8 Kindern. Zweimal im Jahr präsentieren wir die geübten Stücke an einem Konzert.\nDas Spielen in der Gruppe mit Gleichaltrigen macht grossen Spass, ist ein enormer Motivationsfaktor und eine unverzichtbare Ergänzung zur Einzelstunde. Im Ensemble lernen wir wichtige musikalische Grundlagen wie das Zusammenspiel und das Spielen unter einem Dirigenten. Zusätzlich lernen wir die vielen verschiedenen Instrumente aus der Welt der Perkussion kennen, was grosse Abwechslung bietet.',
    timetableEntries: [
      {
        modul: 'H',
        competition: 'Perkussionsensembles, Unterstufe',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:35 - 13:55',
        titel: null,
        description: null,
        programm: [
          {
            id: 367,
            modul: 'H',
            titelName: 'Italodisco',
            composer: 'The Kolors',
            arrangeur: 'Christoph von Bergen',
            grad: null,
            schwierigkeitsgrad: 'Einfach',
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'ItaloDisco ist eine Stilrichtung innerhalb der elektronischen Tanzmusik, deren Produzenten, Komponisten und Interpreten vorwiegend aus Italien stammen. Seine Blütezeit hatte dieser Stil in den 1980er-Jahren. Der gleichnamige Song der italienischen Band The Kolors ist eine Hommage an diese Musikart: Die Klangfarben, die Bass-Linie und auch der Songtext huldigen den grossen Interpreten dieser Zeit.',
            valid: true,
          },
          {
            id: 368,
            modul: 'H',
            titelName: 'Freed from Desire',
            composer: 'Gala',
            arrangeur: 'Christoph von Bergen',
            grad: null,
            schwierigkeitsgrad: 'Einfach',
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Der Song "Freed from Desire" ist einer der bekanntesten Titel der Stilrichtung "Eurodance", welche in den 90er-Jahren enorm populär war. Geschrieben und gesungen wurde er von der italienischen Sängerin Gala und wurde 1996 ein Hit in ganz Europa. Doch seine eingängigen Melodien und Harmonien machen den Song zu einem zeitlosen Klassiker, der auch heute in keiner Playlist fehlen darf.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 10,
        modul: 'H',
        modulDescription: 'H - Perkussionsensembles',
        klasse: 'UNTERSTUFE',
        klasseDescription: 'Unterstufe',
        besetzung: 'PERKUSSIONSENSEMBLE',
        besetzungDescription: 'Perkussionsensemble',
        category: null,
        categoryDescription: null,
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'H - Perkussionsensembles, Unterstufe, Perkussionsensemble (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
