export default defineEventHandler(() => {
  return {
    id: 83,
    name: 'Spielgemeinschaft Mettmenstetten/Ottenbach',
    direktionName: 'Tobias Loew',
    logoImgId: null,
    bildImgId: '9079dba1-5bd1-444c-6c50-f66eed4dcc00',
    homepage: 'https://www.mvmettmenstetten.ch',
    facebook: null,
    instagram: null,
    websiteText: 'Siehe: mvmettmenstetten.ch',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 4. Klasse, Harmonie',
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:20 - 14:45',
        titel: 'Erste Teilnahme an einem Musikfest',
        description:
          'Die Spielgemeinschaft Mettmenstetten - Ottenbach existiert nun seit dem Jahr 2020. Dies ist die erste Teilnahme an einem Musikfest. Die Spielgemeinschaft ist seit ihrem Zusammenschluss stetig am wachsen, denn das Gemeinsame Musizieren ist uns allen wichtig! Trotz einigen Verbiegungen steht heute ein Konzertprogramm auf dem Spielplan, welches alle Mitspielerinnen und Mitspieler fordert und bei den Musikantinnen und Musikanten und dem Publikums hoffen wir, gut ankommt. Denn unsere Leidenschaft ist es, das Publikum mit unserer Begeisterung zu Packen! Mit den drei Wettbewerbsstücken aus unserer und der 3. Klasse, wünschen wir uns, der Jury und Ihnen, verehrtes Publikum, viel vergnügen.',
        programm: [
          {
            id: 5,
            modul: 'A',
            titelName: 'Samurai',
            composer: 'Mathias Wehr',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 345,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 321,
            modul: 'C',
            titelName: 'Ratafia',
            composer: 'Willy Fransen',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 500,
            pflichtStueck: false,
            infoModeration:
              'Diese Komposition wurde anlässlich des 75-jährigen Jubiläums der Königlichen Harmonie De Vriendenkring -Oostham (Belgien) geschrieben und ist dem Dirigenten, den Musikern und dem Vorstand gewidmet. Das Wort Ratafia geht auf das 17. Jahrhundert zurück und bedeutete damals in etwa "möge es Ihnen wohl ergehen". Heute ist Ratafia als Name eines Likörs bekannt.',
            valid: true,
          },
          {
            id: 236,
            modul: 'A',
            titelName: 'Song and Dance',
            composer: 'André Waignein',
            arrangeur: null,
            grad: 2.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 410,
            pflichtStueck: false,
            infoModeration:
              'Song and Dance - zu Deutsch: Lied und Tanz - ist ein Werk in zwei sehr unterschiedlichen Sätzen. Der erste Satz entwickelt eine leichte, bezaubernde Melodielinie, die den Zuhörer in eine kleine Träumerei entführt, während der zweite Satz etwas temperamentvoller, sprudelnder im Charakter ist und zum Tanzen einlädt. Die Rhythmen sind einfach, aber mitreißend.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 5,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_4',
        klasseDescription: '4. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 19,
          identifier: 'grosse-ref-kirche-schlieren',
          name: 'Grosse Ref. Kirche Schlieren',
          address: 'Kirchgasse 7, 8952 Schlieren',
          latitude: 47.396801014533,
          longitude: 8.44573297815,
          googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
          sortOrder: 1,
          mapId: '2W',
          cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
          kuulaId: '5c8Mp',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.396801014533,
            longitude: 8.44573297815,
          },
        },
        description: 'A - Konzertmusik, 4. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
