export default defineEventHandler(() => {
  return {
    id: 76,
    name: 'Stadtharmonie Winterthur-Töss',
    direktionName: 'Helmut Hubov',
    logoImgId: '7f7a52c3-5df6-4b8e-facc-a197bea02200',
    bildImgId: 'e49126ae-28f2-45d1-2553-c6e05e1de600',
    homepage: 'https://www.stadtharmonie-winterthur.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Stadtharmonie Winterthur-Töss wurde 1879 , vor beinahe 150-Jahren gegründet. Im Jahr 2005 übernahm Helmut Hubov die musikalische Leitung und prägt und fördert seither unsere musikalischen Fähigkeiten.\nDas Vereinsjahr ist geprägt vom Familienkonzert im Frühling (Familienprogramm, Märchen und Einbezug der Jugendensembles) dem Winterkonzert mit konzertanter Blasorchesterliteratur und im Dezember ein Adventskonzert in der Kirche. Sommerkonzerte mit Unterhaltungsmusik in und um Winterthur vervollständigen das abwechslungsreiche Jahresprogramm. Zur Standortbestimmung gehören auch die Teilnahme an Kantonalen, Nationalen oder Europäischen Musikwettbewerben. Immer wieder sind auch vielbeachtete Grossprojekte wie  "The Queen Symphony" von Tolga Kashif (2010), "Stabat Mater" von Karl Jenkins (2014) oder "Carmina Burana" von Carl Orff (2018) mit jeweils total über 200 Mitwirkenden Teil der Vereinsaktivitäten. \nDer nächste Grossanlass ist bereits programmiert. Im Herbst 2024 möchten wir nochmals das beeindruckende Werk «Stabat Mater» von Karl Jenkins zusammen mit der Stadtmusik Stockach (D) und einem grossen Chor aus Winterthur aufführen. \nwww.stadtharmonie-winterthur.ch \n',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'So., 23.06.2024, 10:05 - 10:50',
        titel: 'Castillos y tradiciones de España.',
        description:
          'Eine Reise zu verschiedenen Burgen und Orten mit grossen Geschichten und Traditionen. Dies aber in den unterschiedlichsten musikalischen Stilrichtungen, vielfarbig wie dieses Land.',
        programm: [
          {
            id: 249,
            modul: 'A',
            titelName: 'Alcazar',
            composer: 'Llano',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 420,
            pflichtStueck: false,
            infoModeration:
              'Die Ouvertüre „Alcázar“ wird durch dieses spanische Flair in unverkennbarer Weise geprägt und das sollte auch nicht verwundern, denn die wesentliche Inspiration zu diesem Werk hatte der Komponist während eines Besuches in Sevilla, der Hauptstadt Andalusiens am Fluß Guadalquivir. Der romantische Mittelteil geht auf einen Spaziergang im Palastgarten in sternenklarer Nacht zurück. Mittags dagegen besuchte der Komponist den Stadtteil Santa Cruz, in dem auch die Handlung des weltberühmten „Barbier von Sevilla“ angesiedelt ist. Hier begeisterte ihn ein junger Spanier, den er Gitarre spielend unter einem Zitronenbaum antraf. In den schnellen Passagen der Ouvertüre hat der Komponist daher den Flamenco, das Stampfen mit den Haken und den Klang der Kastagnetten eingefangen, und die von ihm gewählten Akkorde orientieren sich an den Barrégriffen der Gitarre.\nEin Werk also voller andalusischer Lebensfreude.',
            valid: true,
          },
          {
            id: 2,
            modul: 'A',
            titelName: 'La Mezquita de Cordoba',
            composer: 'Julie Giroux',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 701,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 250,
            modul: 'A',
            titelName: 'El Sorior y la Orden de Ucles',
            composer: 'Theodoro Apiricio',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 735,
            pflichtStueck: false,
            infoModeration:
              'Dieses Werk wurde zum Gedenken an den Einzug der Truppen von König Jaume I., dem Eroberer, in Enguera (Valencia) geschrieben. „Sorior“ ist der Name des ersten städtischen Zentrums dieser kleinen Stadt und der Orden von Uclés ist der kastilische Orden, der bereits zum Zeitpunkt des Einmarsches der Truppen von Jaume I. in Enguera ansässig war.\n\nDas Werk wurde 1995 von der Unión Musical Santa Cecilia de Enguera uraufgeführt. „Sorior y la Orden de Ucless“ ist das erste symphonische Werk dieses Komponisten und wurde mehr als ein Dutzend Mal aufgenommen.',
            valid: true,
          },
          {
            id: 251,
            modul: 'A',
            titelName: 'Gallito',
            composer: 'Santiago Lope',
            arrangeur: 'Frank de Vyuyst',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Die valencianische Presse bat Santiago Lope für einen Stierkampf, der am 29.07.1905 in der örtlichen Plaza de Toros stattfinden sollte, einen Pasodoble zu Ehren de berühmten Toreros José „Joselito“ Gómez Ortegazu zu komponieren. Lope übertraf sich selbst mit seiner Komposition "Gallito+ ( der kleine Hahn). Unter den Toreros Spaniens nimmt „Joselito“ Gómez Ortega insofern eine Sonderstellung ein, als er nach spanischer Ansicht „… es comúnmente aceptado como mejor torero de todos los tiempos“ angesehen wird, also als „der berühmteste Torero aller Zeiten“.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 13,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
