export default defineEventHandler(() => {
  return {
    id: 46,
    name: 'Stadtmusik Winterthur',
    direktionName: 'Ruth Suppiger',
    logoImgId: 'a4cf3a9b-8ab3-4cd2-4377-d5270e511300',
    bildImgId: '3dbecf25-eac8-4019-8b6e-33492afa7500',
    homepage: 'https://www.stadtmusik-winterthur.ch',
    facebook: 'https://www.facebook.com/StadtmusikWinterthur',
    instagram: 'https://www.instagram.com/stadtmusikwinterthur',
    websiteText:
      'Die Stadtmusik Winterthur besteht aus zirka 60 Aktivmitgliedern von durchschnittlich 37 Jahren. Das breite Repertoire des Erstklass-Vereins umfasst neben Bearbeitungen eine grosse Anzahl zeitgenössischer Originalwerke.  \n\nDie Wurzel der Stadtmusik Winterthur reichen über viele Generationen zurück bis ins Jahr 1872. Damals trafen sich 20 engagierte Bläser und gründeten einen Verein, der mittlerweile seit über 140 Jahren erfolgreich musiziert. Dabei hat sich in den letzten 40 Jahren die Geschlechterverteilung stark verändert: Während noch am Anfang der siebziger Jahre des letzten Jahrhunderts nur eine einzige Frau im Verein mitspielte, ist heute die Hälfte der Musizierenden weiblichen Geschlechts.\n\nWenn die Stadtmusik heute den Heinrich-Menet-Marsch vorträgt, gedenkt sie damit auch ihres ehemaligen Dirigenten und ausgebildeten Trompeters Heinrich Menet, der von 1960-1988 den Stab führte. Er wurde 1986 am Eidgenössischen Musikfest mit dem Stephan-Jaeggi-Preis für seine Verdienste um die Blasmusik in der Schweiz ausgezeichnet. Langjährige Dirigenten waren auch Solo-Oboist Gunhard Mattes und der Klarinettist Urs Bamert. Von 2006 bis 2020 stand der Verein unter der musikalischen Leitung des ausgebildeten Dirigenten und Perkussionisten Fredi Olbrecht. Im Sommer 2006 erreichte die Stadtmusik unter seiner Leitung am Eidgenössischen Musikfest in Luzern den 10. Rang in der ersten Stärkeklasse.\n\nDie wichtigsten musikalischen Anlässe sind das Jahreskonzert Ende März und das Herbstkonzert im November. Das Jahreskonzert steht jedes Jahr unter einem anderen Motto, zu welchem Transkriptionen und Originalwerken gespielt werden. Das Herbstkonzert stellt einen musikalischen Gegensatz zum Jahreskonzert dar, wobei Musikstücke aus anderen Stilrichtungen gespielt werden.\n\nDie Stadtmusik nimmt regelmässig an nationalen und internationalen Wettbewerben teil und tritt an diesen in der ersten Klasse an. Erfolge sind der 7. Platz am Eidgenössischen Musikfest in St. Gallen 2011, sowie 2012 die Titelverteidigung des Wallbergcontests in Volketswil und der Sieg am Musikwettbewerb in Malgart de Mar (Spanien) 2014.\n\nAls Verein organisierten wir das Eidgenössische Musikfest 1986 und das Zürcher Kantonalmusikfest 2013.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'Sa., 22.06.2024, 13:45 - 14:30',
        titel: 'Yesterday is history. Tomorrow is a mystery. Today is the gift.',
        description:
          'Roter Faden:\nDass das Zusammenleben von Menschen mit unterschiedlichen Backgrounds schwierig sein kann, zeigt uns die Geschichte immer wieder. Und doch lernen wir nicht daraus. Unser Konzertprogramm steht im Zeichen der Freundschaft, der Toleranz, des Friedens, der Mahnung und der Hoffnung.\nFreundschaft: Der Pasadoble La Lira de Pozuelo ist für uns ein Symbol der Freundschaft. Zwei unserer Mitglieder sind durch ein Auslandsemester mit dem spanischen symphonischen Blasorchester aus Pozuelo, einem Madrider Vorort, verbunden. Trotz unterschiedlicher Herkunft und Kulturen verbindet sie die Leidenschaft zur Musik. Sie pflegen den Kontakt bis heute. \nToleranz: Die frühe Periode der arabischen-maurischen Herrschaft über al-Andalus, in welcher mit dem Bau der Mezquita de Cordoba begonnen wurde, ist bekannt für die gegenseitige Toleranz und Akzeptanz, die Christen, Juden und Muslime einander entgegenbrachten. Dass dieser Frieden nicht ewig währte, zeigt uns Julie Giroux mit ihrem Werk. Gleichzeitig widerspiegelt aber die Mezquita und Giroux‘ Werk die eindrückliche Schönheit, die entsteht, wenn diverse Kulturen zusammenarbeiten. \nFrieden: Pacem steht für das Ringen um den individuellen und universellen Frieden.\nMahnung: Die Hommage an Rosa Parks, Teil der schwarzen Bürgerrechtsbewegung, verstehen wir als Mahnung an uns selbst, allen Menschen mit Toleranz und Respekt zu begegnen. \nHoffnung: „Yesterday is history. Tomorrow is a mystery. Today is the gift.“ – Afrikanisches Sprichwort. Was kommen mag, wissen wir nicht. Aber heute haben wir die Möglichkeit, für die Gerechtigkeit, die Toleranz und den Frieden einzustehen.\n',
        programm: [
          {
            id: 230,
            modul: 'A',
            titelName: 'La Lira de Pozuelo',
            composer: 'Luis Serrano Alarcón',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 330,
            pflichtStueck: false,
            infoModeration:
              'Freundschaft: Der Pasadoble La Lira de Pozuelo ist für uns ein Symbol der Freundschaft. Zwei unserer Mitglieder sind durch ein Auslandsemester mit dem spanischen symphonischen Blasorchester aus Pozuelo, einem Madrider Vorort, verbunden. Trotz unterschiedlicher Herkunft und Kulturen verbindet sie die Leidenschaft zur Musik. Sie pflegen den Kontakt bis heute. ',
            valid: true,
          },
          {
            id: 2,
            modul: 'A',
            titelName: 'La Mezquita de Cordoba',
            composer: 'Julie Giroux',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 701,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 231,
            modul: 'A',
            titelName: 'Pacem - A Hymn for Peace',
            composer: 'Robert Spittal',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Pacem (dt.: Frieden) widerspiegelt das Ausmaß des anhaltenden, hoffnungsvollen und oft schwierigen Kampfes der Menschheit um die Verwirklichung des persönlichen und universellen Friedens.',
            valid: true,
          },
          {
            id: 232,
            modul: 'A',
            titelName: 'A Movement for Rosa',
            composer: 'Mark Camphouse',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 660,
            pflichtStueck: false,
            infoModeration:
              'Dieses Tongedicht enthält drei kontrastierende Abschnitte. Der erste Abschnitt beschreibt Rosas frühe Jahre, von ihrer Geburt im Februar 1913 in Alabama, bis zu ihrer Heirat im Jahr 1932. Der zweite Abschnitt schildert die Jahre der Rassenkonflikte in Montgomery und das Streben nach sozialer Gleichheit. Der dritte Abschnitt ist von Stärke und Gelassenheit geprägt. Die letzten Takte des Werks sind eine bedrohliche Erinnerung an die anhaltende Präsenz des Rassismus in der modernen amerikanischen Gesellschaft.\nMahnung: Die Hommage an Rosa Parks, Teil der schwarzen Bürgerrechtsbewegung, verstehen wir als Mahnung an uns selbst, allen Menschen mit Toleranz und Respekt zu begegnen. \n',
            valid: true,
          },
          {
            id: 233,
            modul: 'A',
            titelName: 'Today is the Gift',
            composer: 'Samuel Robert Hazo',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Diese Komposition ist eine Hommage an Rosa Parks und ihren Kampf für die Bürgerrechte vor rund 70 Jahren.\nHoffnung: „Yesterday is history. Tomorrow is a mystery. Today is the gift.“ – Afrikanisches Sprichwort. Was kommen mag, wissen wir nicht. Aber heute haben wir die Möglichkeit, für die Gerechtigkeit, die Toleranz und den Frieden einzustehen.\n',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 13,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
