export default defineEventHandler(() => {
  return {
    id: 71,
    name: 'Stadtmusik Bülach',
    direktionName: 'Aliaksei Shablyka',
    logoImgId: '05b451a9-da62-48db-f512-ef11999e1900',
    bildImgId: '87942338-02e4-4b6d-098c-38f47e021200',
    homepage: 'https://smbuelach.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Stadtmusik, über 100jährig, bringt beim Musizieren Jung und Alt zusammen. Zwei Konzerte pro Jahr sind unsere Highlights. Das Repertoire umfasst von Traditionell über Film, Pop, Rock, Musicalmelodien und klassischer Musik bis zu originaler Blasmusik-Literatur. Neben der Musik pflegen wir auch ein fröhliches Miteinander.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:20 - 10:45',
        titel: 'Mitreis(s)end',
        description:
          'Wir stellen die Stadtmusik Bülach vor - eine Harmoniemusik, die kunstvoll musikalische Landschaften durchquert und durch ihre Darbietungen von "Pasadena", "May The Forest Bloom Again" und "Robinson Crusoe" einen reichen Klangteppich bietet.\n\nAuf ihrer Reise nach "Pasadena" entführt die Stadtmusik Bülach in das Herz dieser pulsierenden Stadt und lässt Sie in ihre lebendigen Rhythmen und fesselnden Melodien eintauchen. "May The Forest Bloom Again" erwacht mit üppigen Harmonien und einer Symphonie der Stimmen der Natur zum Leben und zeichnet ein lebendiges Bild von Erneuerung und Wachstum. In ihrer musikalischen Erzählung entfaltet sich "Robinson Crusoe" als eine fesselnde Geschichte über Einsamkeit und Überleben, unterstrichen von Melodien, die die Ebbe und Flut des Lebens als Schiffbrüchiger widerspiegeln.\n\nDie Stadtmusik Bülach lädt Sie ein, sie auf einer unvergesslichen musikalischen Reise zu begleiten, bei der jede Komposition ein einzigartiges Kapitel darstellt und verspricht, Ihre Sinne zu entzünden und Sie an die lebhaften Straßen von Pasadena , verwunschene Wälder und an ferne Küsten zu entführen.',
        programm: [
          {
            id: 245,
            modul: 'A',
            titelName: 'Pasadena',
            composer: 'De Haan, Jacob',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 360,
            pflichtStueck: false,
            infoModeration:
              'Pasadena ist eine am Fuß der San Gabriel Mountains gelegene Stadt im US-Bundesstaat Kalifornien. Das Gebiet des heutigen Pasadena gehörte früher zur Mission San Gabriel Arcángel (1771). Bauern aus Indiana gründeten hier 1873 eine Kolonie. Der Name Pasadena kam erstmals 1875 auf, die übliche Herkunftsableitung deutet auf ein Wort der Chippewa-Indianer, in deren Sprache Pasadena „des Tals“ bedeutet – Teil des Ausdrucks „Weo-quan pa-sa-de-na“ für „Krone des Tals“. \n\nDie Rose Parade, auch bekannt als Tournament of Roses Parade (oder einfach Tournament of Roses), ist eine jährliche Parade, die im Anschluss an das Rose Bowl Game stattfindet. Sie findet meist am Colorado Boulevard in Pasadena im Großraum Los Angeles statt, und zwar am Neujahrstag (oder am Montag, dem 2. Januar, wenn der Neujahrstag auf einen Sonntag fällt). Die Parade, die von der gemeinnützigen Pasadena Tournament of Roses Association veranstaltet wird, beginnt in der Regel um 8:00 Uhr pazifischer Zeit (UTC-8) und umfasst blumengeschmückte Festwagen, Marschkapellen und Reitertruppen. Auf die Parade folgt am Nachmittag die Rose Bowl, eines der wichtigsten Bowl-Spiele im College-Football. Mit Ausnahme der Jahre 1942, 1943 und 1945 während des Zweiten Weltkriegs und 2021 wegen der COVID-19-Pandemie wurde die Parade nie unterbrochen. Die Rose Parade, die erstmals am 1. Januar 1890 stattfand, wird von Hunderttausenden von Zuschauern verfolgt. Das College-Football-Spiel Rose Bowl wurde 1902 eingeführt, um die Kosten für die Durchführung der Parade zu finanzieren.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 246,
            modul: 'A',
            titelName: 'Robinson Crusoe',
            composer: 'Appermont, Bert',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 454,
            pflichtStueck: false,
            infoModeration:
              "Dieses Werk lehnt sich an Daniel Defoe's weltberühmten Roman Robinson Crusoe aus dem Jahr 1719 an, und umreißt das Leben des Helden in groben Zügen in vier Teilen. Im ersten Teil erfahren wir über sein Leben als Seefahrer. Der zweite Teil beschreibt die stürmischen Eindrücke eines Schiffwracks, dessen er zum Opfer fällt. Der nächste Teil handelt von seinem glücklichen Leben zusammen mit seinem Freund Freitag, welcher durch einen melodischen Hymnus dargestellt wird. Schließlich beschreibt der vierte Teil die angespannte Begegnung mit den Kannibalen und seine Rückkehr nach Hause.",
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:40 - 15:45',
        titel: null,
        description: null,
        programm: [
          {
            id: 247,
            modul: 'D',
            titelName: 'Jubilate',
            composer: 'Fleury, Jean-Pierre',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 248,
            modul: 'D',
            titelName: '\tArc en Ciel',
            composer: 'Fleury, Jean-Pierre',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 170,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
