export default defineEventHandler(() => {
  return {
    id: 47,
    name: 'Stadtmusik Dietikon',
    direktionName: 'Marco Nussbaumer',
    logoImgId: '1ab7755b-70f2-4c9a-16ff-503d2bc25600',
    bildImgId: 'f9417e39-4dec-4e50-b4db-c665175dbd00',
    homepage: 'https://www.stadtmusik-dietikon.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die Stadtmusik Dietikon...\n- ist ein Blasorchester mit rund 70 Mitgliedern.\n- musiziert unter der Leitung von Marco Nussbaumer.\n- gibt es bereits seit 1891. Damals hiess der Verein noch Eintracht.\n- ist bereits seit 60 Jahren Zunftmusik der Zunft zum Kämbel.\n- ist durchschnittlich 44 Jahre alt. Das jüngste Mitglied ist 22, das älteste 80.\n- probt im Schnitt etwa 100 Stunden pro Jahr.\n- besteht zu mehr als 60% aus Mitgliedern, die auch in Dietikon wohnen.\n- probt immer Mittwochs von 20 - 22 Uhr im eigenen Probelokal.\n- nimmt an Wettbewerben in der ersten Stärkeklasse teil.\n- bestreitet rund 14 musikalische Auftritte pro Jahr.',
    timetableEntries: [
      {
        modul: 'B',
        competition: 'Unterhaltungsmusik, Oberstufe, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'So., 23.06.2024, 09:00 - 09:25',
        titel: 'Groove around the World',
        description:
          'Mit dem Programm möchte die Stadtmusik Dietikon eine kleine Weltreise durch verschiedene Länder und Stilrichtungen machen. Aus dem Norden kommend mit dem Pflichtstück reisen wir über den Ozean zur Swing Musik Amerikas, die für viele unserer Mitglieder Erinnerungen aus Jugendmusikzeiten weckt. Mit Zwischenstationen über Südamerika zurück nach Europa auf die Balkanhalbsinsel und schliesslich in die Stadthalle Dietikon, um mit dem Siegerstück des Gesangswettbewerbs "Limmattaler Singtalent 2019" nochmals Swingmusik und Erinnerungen zu zelebrieren.  Als Abschluss fliegen wir dann mit Sky High in die Wolken für einen fulminanten Schlusspunkt.',
        programm: [
          {
            id: 11,
            modul: 'B',
            titelName: 'Halvdan Sivertsen Medley',
            composer: 'Lars Erik Gudim',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 390,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 40,
            modul: 'B',
            titelName: 'Sing, Sing, Sing',
            composer: 'Louis Prima',
            arrangeur: 'Naohiro Iwai',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 135,
            pflichtStueck: false,
            infoModeration:
              'Sing, Sing, Sing (With a Swing) ist eine Komposition von Louis Prima aus dem Jahr 1936, die insbesondere in der Coverversion von Benny Goodman zum Jazzstandard wurde. Das Stück wurde auch in zahlreichen Filmen verwendet.',
            valid: true,
          },
          {
            id: 41,
            modul: 'B',
            titelName: 'Baker Street',
            composer: 'Gerry Rafferty',
            arrangeur: 'Ted Parson',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 105,
            pflichtStueck: false,
            infoModeration:
              'Baker Street ist ein Pop-Rock-Song von Gerry Rafferty aus dem Jahr 1978. Als Single erreichte das Musikstück hohe Chartpositionen. Es wurde seither mehr als fünf Millionen Mal im Radio gespielt und vielfach von anderen Musikern gecovert und ist wohl eines der markantesten Saxophon-Solos überhaupt.',
            valid: true,
          },
          {
            id: 42,
            modul: 'B',
            titelName: 'Copacabana',
            composer: 'B. Manilow, B. Sussman, J. Feldman',
            arrangeur: 'Naohiro Iwai',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 155,
            pflichtStueck: false,
            infoModeration:
              'Copacabana aus dem Jahr 1978 ist neben Songs wie Mandy oder Looks Like We Made It einer der größten, bis heute unvergessenen Hits von Barry Manilow, der seine Karriere einst als Komponist von Erkennungsmelodien in Radio und Fernsehen begann. ',
            valid: true,
          },
          {
            id: 43,
            modul: 'B',
            titelName: 'Balkan Dance',
            composer: 'Etienne Crausaz',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 100,
            pflichtStueck: false,
            infoModeration:
              'Die Balkanregion diente im Laufe der Jahrhunderte schon immer als musikalische Inspirationsquelle. Starke Rhythmen und oftmals große musikalische Höhepunkte sind typisch für den großartigen und abwechslungsreichen Musikstil. Etienne Crausaz hat einige dieser Elemente verwendet und sie mit Elementen aus der Rockmusik vermischt. Mit Balkan Dance hat er ein schwungvolles und fantastisches Stück geschaffen, bei dem niemand still sitzen kann!',
            valid: true,
          },
          {
            id: 44,
            modul: 'B',
            titelName: 'Hallelujah I Love Her So',
            composer: 'Ray Charles',
            arrangeur: 'Lars Erik Gudim',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 180,
            pflichtStueck: false,
            infoModeration:
              '"Hallelujah I Love Her So" ist eine single de armikanischen Muisikers Ray Charles aus dem Jahre 1956. 2019 gewann Martina Meier mit diesem Song den von der Stadtmusik Dietikon veranstalteten Gesangswettbewerb "Limmattaler Singtalent". ',
            valid: true,
          },
          {
            id: 45,
            modul: 'B',
            titelName: 'Sky High',
            composer: 'Desmond Dyer, Clive Scott',
            arrangeur: 'Tomohiro Tabete',
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration:
              'Desmond Dyer und Clive Scott gründeten 1966 in Australien die Popgruppe Jigsaw. Der große Erfolg stellte sich aber erst neun Jahre später ein - dann aber gewaltig: Mit dem Hit Sky High landeten sie weltweit in den Top 20 der Hitparaden. Seither wurde das Lied von verschiedenen Bands und Künstlern neu interpretiert. Tomohiro Tanabe sorgte nun dafür, dass auch Blasorchester ihr Repertoire um diesen Pophit erweitern können.',
            valid: true,
          },
        ],
      },
      {
        modul: 'C',
        competition: 'Platzkonzerte',
        location: {
          id: 22,
          identifier: 'festzelt-urdorf',
          name: 'Festzelt Urdorf',
          address: 'Bahnhofstrasse 52, 8902 Urdorf',
          latitude: 47.386092494172,
          longitude: 8.424727317603,
          googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
          type: 'FESTZELT',
          capacity: null,
          modules: null,
          sortOrder: 8,
          mapId: 'FU',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 8,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.386092494172,
            longitude: 8.424727317603,
          },
        },
        dateTime: 'So., 23.06.2024, 15:00 - 15:45',
        titel: null,
        description: null,
        programm: [],
      },
    ],
    rankings: [
      {
        id: 16,
        modul: 'B',
        modulDescription: 'B - Unterhaltungsmusik',
        klasse: 'OBERSTUFE',
        klasseDescription: 'Oberstufe',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'B - Unterhaltungsmusik, Oberstufe, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
