export default defineEventHandler(() => {
  return {
    id: 28,
    name: 'Stadtmusik Illnau-Effretikon',
    direktionName: 'Monika Schütz',
    logoImgId: '8af16efa-e81e-4570-da68-10f30e823600',
    bildImgId: '77db9dfd-80bd-4876-abed-fff6c74cd300',
    homepage: 'https://smie.ch',
    facebook: 'https://www.facebook.com/StadtmusikIllnauEffretikon',
    instagram: 'https://www.instagram.com/stadtmusikillnaueffretikon',
    websiteText:
      'Die SMIE ist ein Amateur-Orchester der 1. Stärkeklasse, unter professioneller musikalischer Leitung. Rund 50 Aktivmitglieder aus Stadt und Region zwischen 18 und 85 Jahren pflegen vielfältige Blasorchesterliteratur.\n\nHauptanlässe sind das Konzert in der Kirche im Januar und das Unterhaltungskonzert im September.\n\nDer Verein trägt zur kulturellen Vielfalt in der Region bei und wird von der Stadt und von seiner Gönnervereinigung unterstützt. Mit der Stadtjugendmusik besteht eine enge Zusammenarbeit.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'So., 23.06.2024, 11:10 - 11:55',
        titel: 'La Mezquita - multikulturelles Wunder',
        description:
          'Die Mezquita von Cordoba, weltgrösste Moschee, zählt zum UNESCO Weltkulturerbe. Sie vereint Baustile des Frühbarocks, der Renaissance, aber auch griechisch-römische, westgotische und byzantinische Kunst. Muslimische, christliche und jüdische Glaubensrichtungen wurden innerhalb der Mauern gleichermassen praktiziert, was damals ein Novum war und heute buchstäblich unbekannt ist. Aus dem Geist des "multikulturellen und religiösen Miteinanders" ist ein Programm entstanden, das ganz im Zeichen der musikalischen und kulturellen Vielfalt steht, welches Kontrast und Abwechslung verspricht. Wir loten die klanglichen Möglichkeiten des Blasorchesters aus und widmen uns dabei unterschiedlichen Musikstilen. \nRossano Galantes emotionale, westlich geprägte Musiksprache (Lexicon of the Gods) trifft auf die spanisch - orientalischen Klänge des Pflichtstücks La Mezquita de Cordoba. Mit sich entwickelnden Akkorden lässt Eric Whitacre in Lux aurumque eine goldene Lichtwolke entstehen. Seine hymnische Musik ist ein zutiefst bewegendes Erlebnis für Musiker und Publikum. Es versprüht Hoffnung und Wärme, Licht und Gold. Kontrastreich erklingt in der Folge Volksmusik, Johan de Meij\'s Werk Klezmer Classics. Er bearbeitete fünf jiddische "Traditionals" aus dem Klezmer-Repertoire und schuf daraus ein farbenreiches und spektakuläres Stück. Der Bogen schliesst sich mit Mercury, einem wuchtigen Konzertmarsch, "very british" konzipiert. ',
        programm: [
          {
            id: 138,
            modul: 'A',
            titelName: 'Lexicon of the Gods',
            composer: 'Rossano Galante',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 585,
            pflichtStueck: false,
            infoModeration:
              'Dieses programmatische Werk stellt drei große mythologische Götter dar: Perseus, den griechischen Helden und legendären Gründer von Mykene, Penthos, den Geist der Trauer und Klage, und schließlich Zeus, der als König der Götter auf dem Olymp regierte.\n\nI: Perseus: Slayer of Medusa, ist ein mitreißendes, dramatisches Stück mit einem heroischen Trompeten-Thema. Das Stück entwickelt sich zu einem fließenden, melodischen Abschnitt, der von einem rhythmischen Puls in den unteren Holz- und Blechinstrumenten begleitet wird. Das Hauptthema kehrt mit einem großartigen, stattlichen Tempo zurück, welches das gesamte Ensemble einbezieht. Der Satz endet mit einer Coda, die wie das Schwert, das Perseus beherrscht, schnell, aufregend und rhythmisch ist.\n\nII: Penthos: der Geist des Kummers ist eine lyrische, klagende Meditation über die menschliche Auflösung in eine kontemplative Stimmung.\n\nIII: Zeus: Gott des Himmels und des Donners. Um die Stärke und Kraft des Dyaus Pita oder Himmelsvaters zu repräsentieren, beginnt dieser Abschnitt mit einem kraftvollen Bläserthema und unerschütterlichen Orchestrierungen. Das zweite Thema verwendet warmes, reiches thematisches Material, bevor es in eine Reprise der ersten melodischen Idee übergeht. Die Coda setzt akkordische Bläser ein, um dieses epische Werk zu seiner berührenden Schlussfolgerung zu bringen.',
            valid: true,
          },
          {
            id: 2,
            modul: 'A',
            titelName: 'La Mezquita de Cordoba',
            composer: 'Julie Giroux',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 701,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 139,
            modul: 'A',
            titelName: 'Lux aurumque',
            composer: 'Eric Whitacre',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 240,
            pflichtStueck: false,
            infoModeration:
              'Lux Aurumque (Licht und Gold) ist eine Komposition in einem Satz von Eric Whitacre. Er schrieb das Werk 2000 auf ein lateinisches Gedicht für gemischten Chor a cappella. 2005 bearbeitete er es zu einer Komposition für Blasorchester. Es gibt auch eine Fassung für Männerchor. Die Version für gemischten Chor wurde bekannt durch sein Projekt Virtual Choir.\n\nDer Komponist wurde angeregt durch ein kurzes Gedicht in englischer Sprache, „Light and Gold“, von Edward Esch (*1970), das mit dem Wort „Light“ beginnt und den Gesang von Engeln für das Neugeborene anspricht („... angels sing softly to the new-born baby“, „... Engel singen sanft für das neugeborene Baby“). Charles Anthony Silvestri schrieb auf Whitacres Wunsch eine Übersetzung in Latein. \n\nIm Auftrag der Texas Music Educators Association für ihre 2005 All-State Band ist Lux Aurumque eine außerordentlich üppige und ergreifende Adaption eines der beliebtesten Chorwerke von Eric Whitacre. Wunderschöne, einfache Dreiklänge verschmelzen von einem schönen Akkord zum nächsten und erzeugen eine sich langsam entwickelnde Farb- und Lichtwolke. Elegant inszeniert vom Komponisten, ist Lux Aurumque ein zutiefst bewegendes Erlebnis für Musikanten und Publikum. ',
            valid: true,
          },
          {
            id: 140,
            modul: 'A',
            titelName: 'Klezmer Classics',
            composer: 'Johan de Meij',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 480,
            pflichtStueck: false,
            infoModeration:
              "Klezmer ist die traditionelle Instrumentalmusik bei Hochzeiten und Festen der jiddisch sprechenden Juden Osteuropas. Ihr Ursprung geht auf das 16. Jahrhundert zurück. Die jiddische Kultur erlebte ihren Höhepunkt in den Ländern, in denen damals viele Juden lebten: Polen, Ukraine, Weiß-Russland, Lettland, Litauen, Moldawien, Rumänien, Slowakei und Ungarn.\n\nDas jiddische Wort Klezmer (Mehrzahl: Klezmorim) bedeutet ursprünglich 'Musikant' (aus dem hebräischen kele zemer – 'Instrument des Liedes'). Dies war die Bezeichnung für die jüdischen Berufsmusiker osteuropäischer Herkunft, die diese Musik spielten. Seit den 70er-Jahren des 20. Jahrhunderts, als diese Musik von Amerika aus ein wahres Revival erlebte, wird das Wort für den Musikstil selbst gebraucht. Johan de Meij bearbeitete fünf Klassiker aus dem Klezmer-Repertoire und schuf daraus eine farbenreiche Auswahl:\n\n1. Mazltov\nDiese Melodie diente früher beim Abschied als sogenanntes Dobranots ('Gute Nacht-Lied') dazu, die Hochzeitsgäste hinaus zu geleiten.\n\n2. Dem Trisker rebn's nign (Melodie des Rabbis von Trisk)\nDiese Melodie wurde erstmalig anno 1925 in New York vom Klarinettisten Dave Tarras aufgenommen. Der Titel (Trisk ist ein kleiner Ort in der ukrainischen Provinz Wolhynien) spielt auf die Gefühle der zahlreichen jüdischen Immigranten, die sich in Amerika niederließen, an. Sie bildeten einen potentiellen Absatzmarkt für die aufkeimende Plattenindustrie.\n\n3. Lomir zich iberbetn (Jiddisch: Lassen wir uns miteinander versöhnen)\nDies ist ein traditioneller Hochzeitstanz. Er wurde auf dem Fest von den ledigen Mädchen und Jungen getanzt, die – um Körperkontakt zu vermeiden – lediglich durch ein Taschentuch verbunden waren.\n\n4. Chosidl\nChosidl ist ein chassidischer Tanz von getragenem Charakter. Die Melodie basiert auf einem Nigun (chassidische textlose Melodie). Der Chassidismus ist eine orthodoxe Strömung innerhalb des religiösen Judentums, in welchem Mystizismus eine wichtige Rolle spielt.\n\n5. Ma jofus (Hebräisch: Wie prächtig...)\nDie Melodie basiert auf einem Loblied auf den Schabbat. Ein echter Klassiker aus dem Klezmer-Repertoire, auch bekannt unter dem Titel Tants, tants, Jidelech. Das Lied war früher in Osteuropa ebenso bekannt wie heute Hava Nagila.",
            valid: true,
          },
          {
            id: 141,
            modul: 'A',
            titelName: 'Mercury',
            composer: 'Jan van der Roost',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 190,
            pflichtStueck: false,
            infoModeration:
              '1990 schrieb Jan Van der Roost diesen Contest-March anlässlich des 15-jährigen Bestehens seiner eigenen Band: Brass Band Midden Brabant. Wie bei vielen britischen Märschen ist das Hauptthema in einer Molltonart geschrieben. In der griechischen Mythologie entspricht Merkur Hermes. Er ist ein Vermittler, der die Botschaft der Götter den Sterblichen überbringt und sie dabei auch übersetzt. Als Götterbote kann er sich schneller bewegen als das Licht. Dies ermöglichen ihm geflügelte Schuhe, ein Flügelhelm und einen Stab mit zwei Flügeln.\n',
            valid: true,
          },
        ],
      },
      {
        modul: 'D',
        competition: 'Parademusik traditionell',
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        dateTime: 'So., 23.06.2024, 13:30 - 13:35',
        titel: null,
        description: null,
        programm: [
          {
            id: 142,
            modul: 'D',
            titelName: 'Marsch der Grenadiere',
            composer: 'Hans Honegger',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 150,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 143,
            modul: 'D',
            titelName: 'Welcome to the Jungle',
            composer: "Guns'n'Roses",
            arrangeur: 'Paul Murtha',
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 160,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 13,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 14,
        modul: 'D',
        modulDescription: 'D - Parademusik traditionell',
        klasse: null,
        klasseDescription: null,
        besetzung: null,
        besetzungDescription: null,
        category: null,
        categoryDescription: null,
        location: {
          id: 20,
          identifier: 'marschmusikstrecke-urdorf',
          name: 'Parademusikstrecke Urdorf',
          address: 'Im Moos 3, 8902 Urdorf',
          latitude: 47.390412605741,
          longitude: 8.427050647289,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
          type: 'PARADEMUSIK',
          capacity: null,
          modules: null,
          sortOrder: 7,
          mapId: '7W',
          cloudflareId: null,
          kuulaId: null,
          einspiellokal: null,
          instrumentendepotId: null,
          instrumentendepotParademusikId: null,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: null,
          coordinates: {
            latitude: 47.390412605741,
            longitude: 8.427050647289,
          },
        },
        description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
