export default defineEventHandler(() => {
  return {
    id: 23,
    name: 'Stadtharmonie Zürich Oerlikon-Seebach',
    direktionName: 'Carlo Balmelli',
    logoImgId: '069bfa0e-b6e6-475c-3e85-2d9fdeb2a400',
    bildImgId: 'd2b215f4-7255-4b23-4a2a-37a0aeed7500',
    homepage: 'https://stadtharmonie.ch',
    facebook: 'https://www.facebook.com/stadtharmonie.ch',
    instagram: 'https://www.instagram.com/stadtharmonie.ch',
    websiteText:
      'Die Stadtharmonie Zürich Oerlikon-Seebach ist ein ausgebautes sinfonisches Blasorchester der Höchstklasse mit rund 80 Amateurmusikerinnen und -musikern. Sie steht seit 2005 unter der Leitung des Tessiner Dirigenten Carlo Balmelli. Bekannt ist die Stadtharmonie für ihren warmen, ausgewogenen Klang und ihren musikalischen Ausdruck. Die Stadtharmonie hat es sich zum Ziel gesetzt, möglichst alle Instrumente mit eigenen Musikanten zu besetzen, so z.B. auch Spezialinstrumente wie Englischhorn oder Bassflöte. Auch die Solisten stammen bei Konzerten der Stadtharmonie regelmässig aus den eigenen Reihen. Nur wenn die Instrumentierung über den Bestand des Orchesters hinausgeht, werden externe Musiker hinzugezogen.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, Höchstklasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'Sa., 22.06.2024, 20:30 - 21:30',
        titel: '«überirdisch»',
        description:
          '«Traveler» und «Bachseits» bilden den Rahmen des Programms der Stadtharmonie Zürich Oerlikon-Seebach. David Maslanka und Johannes Stert fanden für diese Werke Inspiration in der Musik Johann Sebastian Bachs. Obwohl sie musikalisch-inhaltlich und in der Klangsprache sehr verschieden sind, ist in beiden Werken die Musik Bachs allgegenwärtig und doch irgendwie auch „nicht von dieser (heutigen) Welt“. Und ebenfalls nicht von dieser Welt, sondern von nordischen Göttern, handelt die Symphonie Nr. 1 «Asgard» von Teo Aparicio-Barberán in der Mitte des Programms.',
        programm: [
          {
            id: 1,
            modul: 'A',
            titelName: 'Traveler',
            composer: 'David Maslanka',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 796,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 120,
            modul: 'A',
            titelName: 'Symphony No. 1 «Asgard»',
            composer: 'Teo Aparicio-Barberán',
            arrangeur: null,
            grad: 5.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 1320,
            pflichtStueck: false,
            infoModeration:
              'Diese Symphonie ist das bisher bedeutendste Werk des spanischen Komponisten Teo Aparicio-Barberán (*1967). Die Uraufführung fand beim internationalen Wettbewerb für Blasorchester Ciudad de Valencia im Jahr 2002 statt, einem der bedeutendsten Wettbewerbe seiner Art in Europa. Der Komponist benutzt in dem aus drei Sätzen bestehenden Stück eine moderne Sprache und kombiniert eine wohlklingende Instrumentierung mit beeindruckenden rhythmischen Teilen. Asgard beruht auf einer mythischen skandinavischen Geschichte vor dem Hintergrund der alten germanischen Göttersagen.',
            valid: true,
          },
          {
            id: 121,
            modul: 'A',
            titelName: 'Bachseits',
            composer: 'Johannes Stert',
            arrangeur: null,
            grad: 6.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 825,
            pflichtStueck: false,
            infoModeration:
              'Johannes Stert (*1963) möchte mit seinen Kompositionen eine Brücke zwischen moderner Blasorchester- und klassischer Musik schlagen. Das Werk „Bachseits“ entstand als Wettbewerbsbeitrag des Symphonischen Blasorchesters Hilgen zum Deutschen Blasorchesterwettbewerb im Jahr 2012. Die Inspiration für die Fantasie in drei Sätzen stammt von der Ciaccona in d-Moll für Solovioline von Johann Sebastian Bach. Mit seinem Werk Bachseits möchte Stert „alle Farben des Blasorchesters hervorheben“. Seit seiner Uraufführung hat das Stück große internationale Anerkennung gefunden.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 19,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'HOECHSTKLASSE',
        klasseDescription: 'Höchstklasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, Höchstklasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
