export default defineEventHandler(() => {
  return {
    id: 49,
    name: 'Stadtmusik Zürich',
    direktionName: 'Niki Wüthrich',
    logoImgId: 'e09b204b-ce21-4444-78a0-ab497c6f9200',
    bildImgId: '722f6c10-6e92-4e36-5a0c-7208fa9ec200',
    homepage: 'https://www.stadtmusik.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die 1846 gegründete Stadtmusik Zürich, repräsentatives Musikkorps der grössten Schweizer Stadt, ist ein voll ausgebautes Harmonie-Blasorchester und umfasst heute rund 80 Musikerinnen und Musiker. Gemäss ihren Weisungen bezweckt sie die Pflege guter Blasmusik und ist bestrebt, das kulturelle Leben der Stadt Zürich und deren Ansehen im In- und Ausland zu fördern.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 1. Klasse, Harmonie',
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        dateTime: 'Sa., 22.06.2024, 14:50 - 15:35',
        titel: 'Una mañana, una tarde, una noche en Córdoba –  Ein Morgen, ein Abend, eine Nacht in Córdoba',
        description:
          "In Analogie an Suppés berühmte Operette «Ein Morgen, ein Mittag, ein Abend in Wien», die als Skizze über das Wiener Leben komponiert wurde, begeben wir uns auf einen musikalischen Tagesausflug nach Córdoba im südspanischen Andalusien. Wir betrachten die Stadt dabei aus den Augen dreier Nicht-Spanischer-Komponisten, die ihre Reiseeindrücke von Land und Leuten musikalisch festgehalten haben.\n\nDass Musik im «Spanischen Stil» von Nicht-Spaniern geschrieben wird, ist sicherlich nichts Neues: «Capriccio Espagnole» von Rimski-Korsakow, «Rapsodie Espagnole» von Maurice Ravel, «Der Troubadour» von Giuseppe Verdi, «Iberia» von Claude Debussy, «Don Quixote» von Richard Strauss oder die Oper «Carmen» von George Bizet sind berühmte Beispiele dafür, dass Musik in diesem Stil in den letzten 150 Jahren eine internationale Angelegenheit geworden ist. Auch wichtige und anspruchsvolle Werke für Sinfonische Blasorchester wie Roger Nixons «Fiesta del Pacifico», Clifton Williams «Symphonic Dance No.3, Fiesta» und «El Camino Real» von Alfred Reed sind im charakteristischen spanischen Kolorit gehalten. Die heute zur Aufführung gelangenden Werke der Amerikaner Julie Giroux und James Barnes sowie des Belgiers Dirk Brossé setzen diese Tradition gekonnt fort.\n\n\nEin Morgen in Córdoba – Julie Giroux: La Mezquita de Córdoba\n\nCórdoba war ab 169 v.Chr. eine wichtige römische Stadt und ein bedeutendes Zentrum des Islams im Mittelalter. Unter den Mauren erreichte die Stadt im 10. Jahrhundert eine Einwohnerzahl von 500'000, was verglichen mit 38'000 in Paris sehr beachtlich war. Die Machthaber Córdobas regierten mit Weisheit und Gerechtigkeit und behandelten Christen und Juden mit religiöser Toleranz. Sie verbesserten den Handel, die Landwirtschaft, unterstützten die Künste und Wissenschaften. Unter Ihnen wurde Córdoba eine der fortschrittlichsten Städte Europas.\n\nGestärkt durch einen belebenden Carajillo (Espresso mit einem Schuss Brandy, der in Andalusien zu jeder Tageszeit getrunken wird) besuchen wir das berühmteste Bauwerk der Stadt: Die Mezquita, eine riesige Moschee (ab 784 in rund 40-jähriger Bauzeit erstellt) mit über 500 Säulen aus Marmor und Alabaster sowie wunderschönen Mosaiken aus byzantinischer Zeit. Als die Christen Córdoba im Jahr 1236 zurückeroberten, waren die neuen christlichen Herrscher so beeindruckt von der Schönheit des Bauwerks, dass sie es erhielten und ihre Kathedrale inmitten seiner Bögen und Säulen errichteten. In den Mauern wurde muslimischer, christlicher und jüdischer Glaube praktiziert - eine beispiellose und seither nie wieder erlebte Besonderheit. Verschiedene Einflüsse der Geschichte zeigen sich in der Architektur des eindrucksvollen Gebäudes und auch seine bemerkenswerte politische und historische Entwicklung macht es zu einem ganz besonderen Ort. Das geschichtsträchtige Monument wird in Spanien oft ehrfurchtsvoll als «La Gran Mezquita» bezeichnet. Seit 1984 gehört sie zum UNESCO-Weltkulturerbe. \n\nJulie Giroux, eine der wenigen weiblichen Komponistinnen für Blasorchester, widmet ihre Komposition der Moschee/Kathedrale von Córdoba und erzählt die Geschichte des einzigartigen Schmelztigels verschiedener Kulturen auf musikalische Weise.\n\n\nEin Abend in Córdoba – Dirk Brossé: El Golpe Fatal\n\nNach ausgiebiger Siesta schleppen wir uns durch die gleissende Hitze in den engen Gassen zur Plaza de toros Los Califas. Die Stierkampfarena bietet Platz für knapp 17‘000 Zuschauer und gilt als Arena bester Kategorie. Weil auch um 19 Uhr die Sonne noch hoch über dem Horizont steht, leisten wir uns die teureren Karten im Schatten, um dem traditionellen Spektakel beizuwohnen. \n\nDas sinfonische Gedicht «El Golpe Fatal» zeichnet in musikalisch sehr eindrücklichen Bildern einen Stierkampf nach. Unterstützt von kräftigen Akkorden eröffnen Trommelwirbel und Trompeten-Fanfaren die sogenannte «corrida». Der Stier erscheint unter lautem Jubel vor der begeisterten Menge. Verschiedene musikalische Themen symbolisieren den Heldenmut und die Entschlossenheit des Matadors. Der Kampf beginnt und die Menge applaudiert. In wagemutigen Angriffen versucht der Matador den Stier zu bezwingen. Der Kampf wird heftiger. Der Stier wird schwächer und kämpft mit letzter Kraft. Doch sein Schicksal ist besiegelt. Ein kurzes Signal der Blechbläser, von einer dumpfen «Todestrommel» gefolgt, gibt die Entscheidung der Kampfrichter bekannt: Der Matador hat den Zweikampf gewonnen, der Stier darf getötet werden. Es folgt der verhängnisvolle Schlag: «El Golpe Fatal»! Der Stier schwankt. Erschöpft und kraftlos sinkt er hernieder. Tausendfacher Jubel bricht aus. Die kräftigen Schlussakkorde unterstreichen den Triumph des Matadors und den freudigen Jubel der Menge. Der letzte Ton jedoch klingt leise und melancholisch nach, als Symbol für den für den Stier fatalen Ausgang des Kampfes.\n\nDie besten Matadores Córdobas werden als «Califa» bezeichnet, wiederum eine Referenz an die arabischen Vergangenheit Córdobas.\n\n\nEine Nacht in Córdoba – James Barnes: Danza Sinfonica\n\nViele Stunden nach Sonnenuntergang werden die Temperaturen endlich angenehm und die Stadt erwacht in buntem Treiben. Auch wir machen die Nacht zum Tag und gönnen uns in einem der zahlreichen «Tablaos Flamencos» andalusische Köstlichkeiten wie eine Gazpacho und eine erlesene Auswahl von Tapas, bei der der luftgetrockneten Jamón Ibérico nicht fehlen darf. Andalusien gilt ab Mitte des 19. Jahrhunderts als Geburtsort des Kunstgenres «Flamenco». \n\nJames Barnes nimmt uns in seinen «Danza Sinfonica» mit auf eine Reise auf die Iberische Halbinsel und eröffnet uns die Welt des klassischen Flamencos.\n\nIm «Tablao» wird uns eine eindrückliche Flamenco-Show geboten: Tänzerinnen in den typischen engen, mit kontrastreichen Punkten oder Blumenmuster versehenen Kleidern klappern wie wild mit den Kastagnetten und stampfen energiegeladene Rhythmen auf den Parkett während uns die Gitarristen mit ihren Liedern in längst vergangen scheinende Zeiten entführen. Erfüllt von all den Eindrücken Córdobas entschwinden wir kurz vor der Morgenröte ins Reich der Träume.",
        programm: [
          {
            id: 2,
            modul: 'A',
            titelName: 'La Mezquita de Cordoba',
            composer: 'Julie Giroux',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 701,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 161,
            modul: 'A',
            titelName: 'El Golpe Fatal',
            composer: 'Dirk Brossé',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 840,
            pflichtStueck: false,
            infoModeration:
              'Das sinfonische Gedicht «El Golpe Fatal» zeichnet in musikalisch sehr eindrücklichen Bildern einen Stierkampf nach. Unterstützt von kräftigen Akkorden eröffnen Trommelwirbel und Trompeten-Fanfaren die sogenannte «corrida». Der Stier erscheint unter lautem Jubel vor der begeisterten Menge. Verschiedene musikalische Themen symbolisieren den Heldenmut und die Entschlossenheit des Matadors. Der Kampf beginnt und die Menge applaudiert. In wagemutigen Angriffen versucht der Matador den Stier zu bezwingen. Der Kampf wird heftiger. Der Stier wird schwächer und kämpft mit letzter Kraft. Doch sein Schicksal ist besiegelt. Ein kurzes Signal der Blechbläser, von einer dumpfen «Todestrommel» gefolgt, gibt die Entscheidung der Kampfrichter bekannt: Der Matador hat den Zweikampf gewonnen, der Stier darf getötet werden. Es folgt der verhängnisvolle Schlag: «El Golpe Fatal»! Der Stier schwankt. Erschöpft und kraftlos sinkt er hernieder. Tausendfacher Jubel bricht aus. Die kräftigen Schlussakkorde unterstreichen den Triumph des Matadors und den freudigen Jubel der Menge. Der letzte Ton jedoch klingt leise und melancholisch nach, als Symbol für den für den Stier fatalen Ausgang des Kampfes.',
            valid: true,
          },
          {
            id: 162,
            modul: 'A',
            titelName: 'Danza Sinfonica',
            composer: 'James Barnes',
            arrangeur: null,
            grad: 5.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 720,
            pflichtStueck: false,
            infoModeration:
              'James Barnes nimmt uns in seinen «Danza Sinfonica» mit auf eine Reise auf die Iberische Halbinsel und eröffnet uns die Welt des klassischen Flamencos.\n\nIm «Tablao» wird uns eine eindrückliche Flamenco-Show geboten: Tänzerinnen in den typischen engen, mit kontrastreichen Punkten oder Blumenmuster versehenen Kleidern klappern wie wild mit den Kastagnetten und stampfen energiegeladene Rhythmen auf den Parkett während uns die Gitarristen mit ihren Liedern in längst vergangen scheinende Zeiten entführen.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 13,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_1',
        klasseDescription: '1. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 15,
          identifier: 'zentrumshalle-urdorf',
          name: 'Zentrumshalle Urdorf',
          address: 'Birmensdorferstrasse 77, 8902 Urdorf',
          latitude: 47.385636902376,
          longitude: 8.422329961061,
          googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
          type: 'WETTSPIELLOKAL',
          capacity: '80 Personen',
          modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
          sortOrder: 5,
          mapId: '4W',
          cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
          kuulaId: '5Msg1',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.385636902376,
            longitude: 8.422329961061,
          },
        },
        description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
