export default defineEventHandler(() => {
  return {
    id: 74,
    name: 'Stadtmusik Dübendorf',
    direktionName: 'Karin Wäfler',
    logoImgId: 'd8d78f86-a0a7-4479-53a3-29ad9e136600',
    bildImgId: 'ba5b168d-7e0e-4759-904d-f9ad7ffcf000',
    homepage: 'http://www.stadtmusik-duebendorf.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Willkommen bei der Stadtmusik Dübendorf!\nWir sind ein aufgestelltes und dynamisches Blasorchester und haben uns für den Vortrag in der zweiten Stärkeklasse angemeldet. Dreiundvierzig Bläser:innen und Schlagzeuger:innen treffen sich ein- bis zweimal pro Woche zur Probe. Neben einem weiten Spektrum an Musikstilen pflegen wir die Geselligkeit. Wir freuen uns darauf, wenn Ihr an unserem Vortrag am ZKMF vorbei schaut.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 2. Klasse, Harmonie',
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        dateTime: 'Sa., 22.06.2024, 15:15 - 15:45',
        titel: 'Initium novum',
        description:
          'Nach der Pandemie, in der die Klänge der Musik vorübergehend verstummt waren, präsentieren wir stolz ein Programm, das die Sehnsucht nach einem Neubeginn verkörpert. In unserem Programm "Initium novum" nutzen wir die Kraft der Melodien, um die wiedergefundene Schönheit des Lebens nach der Stille zu feiern.\n\n"Winds on Fire" von Bert Appermont eröffnet mit seinem glühenden Charakter unser Konzert und symbolisiert die Energie und Begeisterung, die durch den Zusammenschluss zweier Orchester entstanden ist. Dieses Stück wurde von zwei belgischen Fanfaren in Auftrag gegeben, welche zu einem gemeinsamen Ensemble verschmolzen sind.\n\nDer Choral "The Last Night of Fall" von Etienne Crausaz illustriert die Wintersonnenwende, die längste Nacht des Jahres und damit den Wendepunkt in Richtung Frühling und Neubeginn. Dieses besinnliche Werk schafft einen Moment der Stille und lebt zugleich von der in ihm steckenden Kraft.\n\nDie choralartigen Melodien im zweiten Stück "QuaranTime" von Stephan Hodel laden dazu ein, innezuhalten und über die vergangene Quarantäne nachzudenken. Die Motive in den schnellen Passagen des Stückes, welche auf einer 5-tönigen Leiter basieren, ermutigen uns, die Zeit der Pandemie als Chance zu sehen, uns mit unseren Gedanken, Träumen und innersten Wünschen zu verbinden.\n\nUnsere musikalische Reise erreicht ihren letzten Höhepunkt mit "A Legend from Yao". Das Stück basiert auf einem traditionellen chinesischen Lied und der Legende von Yao: einem chinesischen Kaiser. Das Stück geleitet durch das lange Leben Yaos, das Höhen, Tiefen aber auch Willen durchzuhalten in sich birgt.\n\nDie vier Stücke verschmelzen zu einer emotionalen Reise, die uns daran erinnert, dass Musik selbst in den schwierigsten Zeiten als verbindendes Element wirkt und uns hilft uns neu zu entfalten.\n',
        programm: [
          {
            id: 124,
            modul: 'A',
            titelName: 'Winds on Fire',
            composer: 'Bert Appermont',
            arrangeur: null,
            grad: 3.5,
            schwierigkeitsgrad: null,
            durationInSeconds: 490,
            pflichtStueck: false,
            infoModeration:
              'Winds on Fire wurde von den Fanfaren in Loksbergen und Kortenaken in Auftrag gegeben, die zu einem gemeinsamen Ensemble verschmolzen sind. Dieses festliche Werk besteht deshalb aus zwei gegensätzlichen Elementen: einem schnellen, rhythmischen und charaktervollen Thema sowie einem melodischen, einfühlsamen und langsamen Thema.',
            valid: true,
          },
          {
            id: 325,
            modul: 'A',
            titelName: 'The Last Night of Fall',
            composer: 'Etienne Crausaz',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 290,
            pflichtStueck: false,
            infoModeration:
              'Der Choral "The Last Night of Fall" wurde von Etienne Crausaz komponiert und illustriert die Wintersonnenwende, die längste Nacht des Jahres und damit den Wendepunkt in Richtung Frühling und Neubeginn.',
            valid: true,
          },
          {
            id: 3,
            modul: 'A',
            titelName: 'QuaranTime',
            composer: 'Stephan Hodel',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 459,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 326,
            modul: 'A',
            titelName: 'A Legend from Yao',
            composer: 'Mao Yuan',
            arrangeur: 'Yeh Shu-Han',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 420,
            pflichtStueck: false,
            infoModeration:
              '"A Legend from Yao" entstand aus einem traditionellen chinesischen Lied, das von Mao Yuan komponiert und von Yeh-Shu Han arrangiert wurde. Das Stück basiert auf einer Legende von Yao, welcher im Alter von 20 Jahren zum Herrscher wurde und erst mit 119 Jahren verstarb.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 3,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_2',
        klasseDescription: '2. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 18,
          identifier: 'salmensaal-schlieren',
          name: 'Salmensaal Schlieren',
          address: 'Uitikonerstrasse 17, 8952 Schlieren',
          latitude: 47.396055051974,
          longitude: 8.448625196597,
          googleMapsAddress: 'https://www.google.ch/maps/place/Uitikonerstrasse+17%2C+8952+Schlieren',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.396055051974,8.448625196597',
          type: 'WETTSPIELLOKAL',
          capacity: '70 Personen',
          modules: 'A (Konzertmusik) 2. Klasse, Harmonie und Brass Band und B (Unterhaltungsmusik) Oberstufe, Harmonie',
          sortOrder: 2,
          mapId: '1W',
          cloudflareId: '68f436aa-a3cf-42c2-fce8-e355110daf00',
          kuulaId: '5ZfQq',
          einspiellokal: null,
          instrumentendepotId: 8,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.396055051974,
            longitude: 8.448625196597,
          },
        },
        description: 'A - Konzertmusik, 2. Klasse, Harmonie (Salmensaal Schlieren)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
