export default defineEventHandler(() => {
  return {
    id: 56,
    name: 'Tambourenverein der Stadt Winterthur',
    direktionName: 'Daniel Rogger',
    logoImgId: 'f7574c11-9038-4861-6a19-a0a0ac443200',
    bildImgId: '7e09f898-3541-4e01-82b4-82f59a743800',
    homepage: 'https://www.tambourenwinterthur.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Mit Freude stellen wir uns als grössten Tambourenverein der Umgebung Winterthur vor. Neuzeit paart sich nirgends so gut mit Tradition wie bei uns!\nAn verschiedenartigen Engagements dürfen wir unser Können unter Beweis stellen. Grosse Saalkonzerte im Theater Winterthur, das Begleiten von feierlichen Festakten und private Anlässe gehören dazu. Erlebnisse wie Räbeliechtli-Umzüge in der kalten Jahreszeit, Wettspiele in der ganzen Schweiz, Geburtstage und Hochzeiten runden das Vereinsjahr auf abwechslungsreiche Weise ab. \nTolle Erfolge zieren unsere Vereinsgeschichte. Wir sind amtierender Vize-Schweizermeister in der Kategorie Percussion. \n\nWeitere Infos zu uns findet ihr hier: https://www.tambourenwinterthur.ch/ueber-uns',
    timetableEntries: [
      {
        modul: 'G',
        competition: 'Tambouren',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:45 - 11:05',
        titel: null,
        description: null,
        programm: [
          {
            id: 327,
            modul: 'G',
            titelName: 'Jackpot',
            composer: 'Daniel Rogger',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 328,
            modul: 'G',
            titelName: "L'Echo",
            composer: 'Philippe Leuzinger',
            arrangeur: null,
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 363,
            modul: 'G',
            titelName: 'Zic Zac',
            composer: 'Fabian Egger',
            arrangeur: null,
            grad: 2.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 364,
            modul: 'G',
            titelName: 'Hot & Spicy',
            composer: 'Daniel Rogger',
            arrangeur: null,
            grad: 1.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 8,
        modul: 'G',
        modulDescription: 'G - Tambouren',
        klasse: null,
        klasseDescription: null,
        besetzung: 'TAMBOUREN',
        besetzungDescription: 'Tambouren',
        category: 'MODUL_G_KAT_C',
        categoryDescription: 'Kat. C',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'G - Tambouren (Kat. C), Tambouren (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 6,
        modul: 'G',
        modulDescription: 'G - Tambouren',
        klasse: null,
        klasseDescription: null,
        besetzung: 'TAMBOUREN',
        besetzungDescription: 'Tambouren',
        category: 'MODUL_G_KAT_A',
        categoryDescription: 'Kat. A',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'G - Tambouren (Kat. A), Tambouren (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 7,
        modul: 'G',
        modulDescription: 'G - Tambouren',
        klasse: null,
        klasseDescription: null,
        besetzung: 'TAMBOUREN',
        besetzungDescription: 'Tambouren',
        category: 'MODUL_G_KAT_B',
        categoryDescription: 'Kat. B',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'G - Tambouren (Kat. B), Tambouren (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
