export default defineEventHandler(() => {
  return {
    id: 99,
    name: 'Tambouren der Polizeimusik Zürich-Stadt',
    direktionName: 'André Flückiger',
    logoImgId: 'bc632145-a664-4f43-d056-99681a6d5d00',
    bildImgId: 'b306b21c-d2af-4a79-12a0-2be63de7cf00',
    homepage: 'https://www.polizeimusik.ch',
    facebook: 'https://www.facebook.com/polizeimusik',
    instagram: 'https://www.instagram.com/polizeimusikzurichstadt/',
    websiteText:
      'Am 31. Kantonalmusikfest in Urdorf und Schlieren sind wir mit unserer Tambourengruppe zu Gast.\nDie Polizeimusik Zürich-Stadt wurde 1902, analog der ältesten Korpsmusik der Schweiz, der Korpsmusik der Kantonspolizei Zürich, gegründet. Wir sind ein wichtiges Bindeglied zwischen Polizei und Bevölkerung und musikalische Botschafterin für die Stadtpolizei Zürich, die Stadt Zürich und die Schweiz mit Auftritten im In- und Ausland. Musikalisch sind wir auf konzertante Unterhaltungsmusik, Hallen- und Rasenshows ausgerichtet.\nAls reine Amateurband mit aktuell 74 Mitgliedern, davon 52 Musikern, 9 Tambouren und 13 Funktionären wollen wir mit unserer Musik unseren Mitmenschen Freude bereiten.',
    timetableEntries: [
      {
        modul: 'G',
        competition: 'Tambouren',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 10:10 - 10:30',
        titel: null,
        description: null,
        programm: [
          {
            id: 362,
            modul: 'G',
            titelName: 'Double Fantasy',
            composer: 'Roman Lombriser',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 8,
        modul: 'G',
        modulDescription: 'G - Tambouren',
        klasse: null,
        klasseDescription: null,
        besetzung: 'TAMBOUREN',
        besetzungDescription: 'Tambouren',
        category: 'MODUL_G_KAT_C',
        categoryDescription: 'Kat. C',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'G - Tambouren (Kat. C), Tambouren (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
