export default defineEventHandler(() => {
  return {
    id: 73,
    name: 'Tambourenverein Weinland Andelfingen',
    direktionName: 'Peter Schwarzer',
    logoImgId: null,
    bildImgId: 'ffa5efd7-5d96-44e4-c044-8e37d06d0900',
    homepage: 'https://tvwa.ch',
    facebook: null,
    instagram: null,
    websiteText: 'Tambourenverein Weinland Andelfingen www.tvwa.ch',
    timetableEntries: [
      {
        modul: 'G',
        competition: 'Tambouren',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        dateTime: 'Sa., 22.06.2024, 11:20 - 11:40',
        titel: null,
        description: null,
        programm: [
          {
            id: 377,
            modul: 'G',
            titelName: 'Siidefiin',
            composer: 'Moritz von Allmen',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 378,
            modul: 'G',
            titelName: 'Powerplay',
            composer: 'Reto Käser/Roger Meier',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
          {
            id: 379,
            modul: 'G',
            titelName: 'Black & White 2000',
            composer: 'Roman Lombriser',
            arrangeur: null,
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 0,
            pflichtStueck: false,
            infoModeration: null,
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 8,
        modul: 'G',
        modulDescription: 'G - Tambouren',
        klasse: null,
        klasseDescription: null,
        besetzung: 'TAMBOUREN',
        besetzungDescription: 'Tambouren',
        category: 'MODUL_G_KAT_C',
        categoryDescription: 'Kat. C',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'G - Tambouren (Kat. C), Tambouren (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
      {
        id: 6,
        modul: 'G',
        modulDescription: 'G - Tambouren',
        klasse: null,
        klasseDescription: null,
        besetzung: 'TAMBOUREN',
        besetzungDescription: 'Tambouren',
        category: 'MODUL_G_KAT_A',
        categoryDescription: 'Kat. A',
        location: {
          id: 14,
          identifier: 'embrisaal-urdorf',
          name: 'Embrisaal Urdorf',
          address: 'Im Embri 8, 8902 Urdorf',
          latitude: 47.387068997702,
          longitude: 8.425614397929,
          googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
          type: 'WETTSPIELLOKAL',
          capacity: '10 Personen',
          modules: 'G (Tambouren) und H (Perkussionsensembles)',
          sortOrder: 6,
          mapId: '3W',
          cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
          kuulaId: '5ZfQh',
          einspiellokal: null,
          instrumentendepotId: 6,
          instrumentendepotParademusikId: 6,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'FULL',
          coordinates: {
            latitude: 47.387068997702,
            longitude: 8.425614397929,
          },
        },
        description: 'G - Tambouren (Kat. A), Tambouren (Embrisaal Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
