export default defineEventHandler(() => {
  return {
    id: 101,
    name: 'VBZ Musik',
    direktionName: 'Walter Brühlmann',
    logoImgId: '6a4264d3-2feb-48de-6f1e-eb5ab7ac0300',
    bildImgId: '2da917b9-8a68-4c29-a337-748174a15d00',
    homepage: 'https://vbz-musik.ch',
    facebook: null,
    instagram: null,
    websiteText:
      'Die VBZ-Musik ist ein Blasmusikverein mit einer stattlichen Anzahl Mitglieder und hat sich in erster Linie der Unterhaltungsmusik verschrieben. Wir wollen mit unserer Musik die Zuhörer unterhalten und Lebensfreude vermitteln. Und was genauso wichtig ist, wir wollen Spass haben an dem, was wir machen!\n\nEs ist kein Geheimnis, dass wir in unserem Verein die Geselligkeit genauso pflegen wie unsere musikalische Ausrichtung. Wir haben das grosse Glück, unseren Sitz im Musikzentrum Albisgütli zu haben, fernab des städtischen Rummels und mit traumhafter Sicht auf Uetliberg und Zürichsee.\n\nBei uns ist jeder willkommen, der unsere Freude an gepflegter Unterhaltungsmusik teilen will, eine musikalische Grundausbildung hat und bereit ist, mit einem Blasmusikverein der etwas anderen Art selbst die Probearbeit zu geniessen.',
    timetableEntries: [
      {
        modul: 'A',
        competition: 'Konzertmusik, 3. Klasse, Harmonie',
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        dateTime: 'So., 23.06.2024, 15:05 - 15:30',
        titel: 'Olympic Spirit',
        description:
          'Nach einer längeren Zeit nehmen wir uns wieder einmal eine Herausforderung an und nehmen am Musikwettbewerb teil. Entsprechend unserem Vereinsmotto ‘Jede / jeder kann mitmachen!’ haben wir unser Konzertprogramm dem Theme ‘Olympia’ gewidmet. Wir starten deshalb mit der Eröffnungshymne der Olympischen Spiele aus dem Jahre 1988. Wir hoffen, dass wir wie bei einer Olympiade, nach dem Pflichtstück ‘May the Forest Bloom Again’ mit unserem weiteren Selbstwahlstück ins Land der Legenden gehen können und die selbstauferlegte Herausforderung erfolgreich meistern.',
        programm: [
          {
            id: 223,
            modul: 'A',
            titelName: 'The Olympic Spirit',
            composer: 'John Willisams',
            arrangeur: 'Roland Smeets',
            grad: 3.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 270,
            pflichtStueck: false,
            infoModeration:
              '1988 bat die NBC Sports Division John Williams, ein neues Werk für ihre Berichterstattung über die Sommerspiele in Seoul zu schaffen. James Curnows Nachbildung des ursprünglichen Orchestersatzes fängt die Kraft und den Geist der Olympischen Spiele vollständig ein.',
            valid: true,
          },
          {
            id: 4,
            modul: 'A',
            titelName: 'May the Forest Bloom Again',
            composer: 'Théo Schmitt',
            arrangeur: null,
            grad: null,
            schwierigkeitsgrad: null,
            durationInSeconds: 398,
            pflichtStueck: true,
            infoModeration: null,
            valid: true,
          },
          {
            id: 224,
            modul: 'A',
            titelName: 'Land of Legends',
            composer: 'Andreas Ludwig Schulte',
            arrangeur: '/',
            grad: 4.0,
            schwierigkeitsgrad: null,
            durationInSeconds: 660,
            pflichtStueck: false,
            infoModeration:
              'In „Land of Legends“ entführt Sie der deutsche Komponist Andreas Ludwig Schulte in die fiktive Welt der Sagen, Mythen und Märchen. Die Einleitung zum ersten Teil (Das Schloss) beschreibt die majestätischen Konturen des Handlungsortes. Seine Instrumentierung (Hörner) versetzt einen sofort in mittelalterliche Sphären.\n\nDas Hinzufügen prägnanter Blechinstrumente verleiht dem Teil sogar eine heroische Note. Nach dem Eintreten durch das Tor herrscht im Hof ​​offenbar reges Treiben. Pagen, Knappen und Soldaten sind damit beschäftigt, sich um ihre Waffen zu kümmern. Es wird Bier gebraut, Flachs gesponnen, das Vieh gehütet und einige Handwerker aus den umliegenden Dörfern sind fleißig am Werk. In der oberen Kammer des runden Turms lebt ein alter Mann (The Old Wizard). Er lässt sich nur selten blicken und niemand weiß genau, was er tut. Es wird gesagt, dass er sich mit Zauberei und Magie beschäftigt. Es ist alles sehr mysteriös.\n\nEs gibt auch Feste, manche davon nüchtern, andere ausgelassen.\n\nDie Hochzeit im dritten Teil wird im großen Stil gefeiert. Mit Trompetenklang tritt die Braut an der Hand ihres Vaters ein. Anschließend wird auf der Party zur Musik der Minnesänger getanzt und natürlich folgt ein ausgiebiges Bankett.',
            valid: true,
          },
        ],
      },
    ],
    rankings: [
      {
        id: 2,
        modul: 'A',
        modulDescription: 'A - Konzertmusik',
        klasse: 'KLASSE_3',
        klasseDescription: '3. Klasse',
        besetzung: 'HARMONIE',
        besetzungDescription: 'Harmonie',
        category: null,
        categoryDescription: null,
        location: {
          id: 16,
          identifier: 'reformierte-kirche-urdorf',
          name: 'Reformierte Kirche Urdorf',
          address: 'Weihermattstrasse 40, 8902 Urdorf',
          latitude: 47.381879850735,
          longitude: 8.424846238635,
          googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
          googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
          type: 'WETTSPIELLOKAL',
          capacity: '50 Personen',
          modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
          sortOrder: 3,
          mapId: '5W',
          cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
          kuulaId: '5gJVm',
          einspiellokal: null,
          instrumentendepotId: 7,
          instrumentendepotParademusikId: 7,
          instrumentendepot: null,
          juryfeedback: null,
          percussionEquipmentType: 'STANDARD',
          coordinates: {
            latitude: 47.381879850735,
            longitude: 8.424846238635,
          },
        },
        description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
        status: 'FINAL',
        entries: [],
        final: true,
        notPending: true,
      },
    ],
  }
})
