export default defineEventHandler(() => {
  return {
    id: 2,
    modul: 'A',
    modulDescription: 'A - Konzertmusik',
    klasse: 'KLASSE_3',
    klasseDescription: '3. Klasse',
    besetzung: 'HARMONIE',
    besetzungDescription: 'Harmonie',
    category: null,
    categoryDescription: null,
    location: {
      id: 16,
      identifier: 'reformierte-kirche-urdorf',
      name: 'Reformierte Kirche Urdorf',
      address: 'Weihermattstrasse 40, 8902 Urdorf',
      latitude: 47.381879850735,
      longitude: 8.424846238635,
      googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+40%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.381879850735,8.424846238635',
      type: 'WETTSPIELLOKAL',
      capacity: '50 Personen',
      modules: 'A (Konzertmusik) 3. Klasse, Harmonie',
      sortOrder: 3,
      mapId: '5W',
      cloudflareId: 'ab20757a-c9b7-49c1-90bb-3d842a190600',
      kuulaId: '5gJVm',
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 7,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'STANDARD',
      coordinates: {
        latitude: 47.381879850735,
        longitude: 8.424846238635,
      },
    },
    description: 'A - Konzertmusik, 3. Klasse, Harmonie (Reformierte Kirche Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'musikgesellschaft-andelfingen',
        vereinsName: 'Musikgesellschaft Andelfingen',
        score: 95.33,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'musikgesellschaft-harmonie-turbenthal',
        vereinsName: 'Musikgesellschaft Harmonie Turbenthal',
        score: 92,
        additionalInfo: null,
      },
      {
        rank: 3,
        vereinIdentifier: 'musikverein-gossau-zh',
        vereinsName: 'Musikverein Gossau ZH',
        score: 91,
        additionalInfo: null,
      },
      {
        rank: 4,
        vereinIdentifier: 'harmonie-eintracht-maennedorf',
        vereinsName: 'Harmonie Eintracht Männedorf',
        score: 90,
        additionalInfo: null,
      },
      {
        rank: 5,
        vereinIdentifier: 'jugendmusik-bezirk-affoltern',
        vereinsName: 'Jugendmusik Bezirk Affoltern',
        score: 86.67,
        additionalInfo: null,
      },
      {
        rank: 6,
        vereinIdentifier: 'musikverein-langnau-am-albis',
        vereinsName: 'Musikverein Langnau am Albis',
        score: 86,
        additionalInfo: null,
      },
      {
        rank: 7,
        vereinIdentifier: 'vbz-musik',
        vereinsName: 'VBZ Musik',
        score: 85.33,
        additionalInfo: null,
      },
      {
        rank: 8,
        vereinIdentifier: 'musikverein-harmonie-zuerich-oberstrass',
        vereinsName: 'Musikverein Harmonie Zürich-Oberstrass',
        score: 84.67,
        additionalInfo: null,
      },
      {
        rank: 9,
        vereinIdentifier: 'musikverein-bonstetten',
        vereinsName: 'Musikverein Bonstetten',
        score: 84,
        additionalInfo: null,
      },
      {
        rank: 10,
        vereinIdentifier: 'musikgesellschaft-rafz',
        vereinsName: 'Musikgesellschaft Rafz',
        score: 83,
        additionalInfo: null,
      },
      {
        rank: 11,
        vereinIdentifier: 'musikverein-harmonie-birmensdorf',
        vereinsName: 'Musikverein Harmonie Birmensdorf',
        score: 82.33,
        additionalInfo: null,
      },
      {
        rank: 12,
        vereinIdentifier: 'musikverein-harmonie-hausen-am-albis',
        vereinsName: 'Musikverein Harmonie Hausen am Albis',
        score: 81,
        additionalInfo: null,
      },
      {
        rank: 13,
        vereinIdentifier: 'musikverein-stammheim',
        vereinsName: 'Musikverein Stammheim',
        score: 80.67,
        additionalInfo: null,
      },
      {
        rank: 14,
        vereinIdentifier: 'stadtmusik-buelach',
        vereinsName: 'Stadtmusik Bülach',
        score: 80,
        additionalInfo: null,
      },
      {
        rank: 15,
        vereinIdentifier: 'musikverein-eintracht-wallisellen',
        vereinsName: 'Musikverein Eintracht Wallisellen',
        score: 79,
        additionalInfo: null,
      },
      {
        rank: 16,
        vereinIdentifier: 'musikverein-richterswil-samstagern',
        vereinsName: 'Musikverein Richterswil Samstagern',
        score: 76.67,
        additionalInfo: null,
      },
      {
        rank: 17,
        vereinIdentifier: 'harmonie-eintracht-kuesnacht',
        vereinsName: 'Harmonie Eintracht Küsnacht',
        score: 76.33,
        additionalInfo: null,
      },
    ],
    final: true,
    notPending: true,
  }
})
