export default defineEventHandler(() => {
  return {
    id: 12,
    modul: 'H',
    modulDescription: 'H - Perkussionsensembles',
    klasse: 'OBERSTUFE',
    klasseDescription: 'Oberstufe',
    besetzung: 'PERKUSSIONSENSEMBLE',
    besetzungDescription: 'Perkussionsensemble',
    category: null,
    categoryDescription: null,
    location: {
      id: 14,
      identifier: 'embrisaal-urdorf',
      name: 'Embrisaal Urdorf',
      address: 'Im Embri 8, 8902 Urdorf',
      latitude: 47.387068997702,
      longitude: 8.425614397929,
      googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
      type: 'WETTSPIELLOKAL',
      capacity: '10 Personen',
      modules: 'G (Tambouren) und H (Perkussionsensembles)',
      sortOrder: 6,
      mapId: '3W',
      cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
      kuulaId: '5ZfQh',
      einspiellokal: null,
      instrumentendepotId: 6,
      instrumentendepotParademusikId: 6,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'FULL',
      coordinates: {
        latitude: 47.387068997702,
        longitude: 8.425614397929,
      },
    },
    description: 'H - Perkussionsensembles, Oberstufe, Perkussionsensemble (Embrisaal Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'sjmuz-percussion-ensemble',
        vereinsName: 'SJMUZ Percussion Ensemble',
        score: 97,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'perkussionsensemble-winterthur',
        vereinsName: 'Perkussionsensemble Winterthur',
        score: 84.67,
        additionalInfo: '2 Punkte Abzug (Zeitunter- oder überschreitung)',
      },
    ],
    final: true,
    notPending: true,
  }
})
