export default defineEventHandler(() => {
  return {
    id: 13,
    modul: 'A',
    modulDescription: 'A - Konzertmusik',
    klasse: 'KLASSE_1',
    klasseDescription: '1. Klasse',
    besetzung: 'HARMONIE',
    besetzungDescription: 'Harmonie',
    category: null,
    categoryDescription: null,
    location: {
      id: 15,
      identifier: 'zentrumshalle-urdorf',
      name: 'Zentrumshalle Urdorf',
      address: 'Birmensdorferstrasse 77, 8902 Urdorf',
      latitude: 47.385636902376,
      longitude: 8.422329961061,
      googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
      type: 'WETTSPIELLOKAL',
      capacity: '80 Personen',
      modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
      sortOrder: 5,
      mapId: '4W',
      cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
      kuulaId: '5Msg1',
      einspiellokal: null,
      instrumentendepotId: 6,
      instrumentendepotParademusikId: 6,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'FULL',
      coordinates: {
        latitude: 47.385636902376,
        longitude: 8.422329961061,
      },
    },
    description: 'A - Konzertmusik, 1. Klasse, Harmonie (Zentrumshalle Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'musikverein-zuerich-hoengg',
        vereinsName: 'Musikverein Zürich-Höngg',
        score: 96.67,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'stadtmusik-zuerich',
        vereinsName: 'Stadtmusik Zürich',
        score: 94.67,
        additionalInfo: null,
      },
      {
        rank: 3,
        vereinIdentifier: 'musikverein-meilen',
        vereinsName: 'Musikverein Meilen',
        score: 91.33,
        additionalInfo: null,
      },
      {
        rank: 4,
        vereinIdentifier: 'stadtmusik-winterthur',
        vereinsName: 'Stadtmusik Winterthur',
        score: 91,
        additionalInfo: null,
      },
      {
        rank: 5,
        vereinIdentifier: 'harmoniemusik-helvetia-horgen',
        vereinsName: 'Harmoniemusik Helvetia Horgen',
        score: 84.67,
        additionalInfo: null,
      },
      {
        rank: 6,
        vereinIdentifier: 'stadtmusik-illnau-effretikon',
        vereinsName: 'Stadtmusik Illnau-Effretikon',
        score: 83.67,
        additionalInfo: null,
      },
      {
        rank: 7,
        vereinIdentifier: 'stadtharmonie-winterthur-toess',
        vereinsName: 'Stadtharmonie Winterthur-Töss',
        score: 82.33,
        additionalInfo: '2 Punkte Abzug (Zeitunter- oder überschreitung)',
      },
    ],
    final: true,
    notPending: true,
  }
})
