export default defineEventHandler(() => {
  return {
    id: 14,
    modul: 'D',
    modulDescription: 'D - Parademusik traditionell',
    klasse: null,
    klasseDescription: null,
    besetzung: null,
    besetzungDescription: null,
    category: null,
    categoryDescription: null,
    location: {
      id: 20,
      identifier: 'marschmusikstrecke-urdorf',
      name: 'Parademusikstrecke Urdorf',
      address: 'Im Moos 3, 8902 Urdorf',
      latitude: 47.390412605741,
      longitude: 8.427050647289,
      googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+3%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.390412605741,8.427050647289',
      type: 'PARADEMUSIK',
      capacity: null,
      modules: null,
      sortOrder: 7,
      mapId: '7W',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: null,
      instrumentendepotParademusikId: null,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: {
        latitude: 47.390412605741,
        longitude: 8.427050647289,
      },
    },
    description: 'D - Parademusik traditionell (Parademusikstrecke Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'musikverein-neerach',
        vereinsName: 'Musikverein Neerach',
        score: 87.25,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'musikverein-harmonie-waedenswil',
        vereinsName: 'Musikverein Harmonie Wädenswil',
        score: 87,
        additionalInfo: null,
      },
      {
        rank: 3,
        vereinIdentifier: 'stadtmusik-illnau-effretikon',
        vereinsName: 'Stadtmusik Illnau-Effretikon',
        score: 86.75,
        additionalInfo: null,
      },
      {
        rank: 4,
        vereinIdentifier: 'musikverein-schoenenberg',
        vereinsName: 'Musikverein Schönenberg',
        score: 86,
        additionalInfo: null,
      },
      {
        rank: 5,
        vereinIdentifier: 'musikverein-wil-zh',
        vereinsName: 'Musikverein Wil ZH',
        score: 85.5,
        additionalInfo: null,
      },
      {
        rank: 5,
        vereinIdentifier: 'musikgesellschaft-rafz',
        vereinsName: 'Musikgesellschaft Rafz',
        score: 85.5,
        additionalInfo: null,
      },
      {
        rank: 7,
        vereinIdentifier: 'jugendmusik-bezirk-affoltern',
        vereinsName: 'Jugendmusik Bezirk Affoltern',
        score: 83.75,
        additionalInfo: null,
      },
      {
        rank: 8,
        vereinIdentifier: 'musikverein-hedingen',
        vereinsName: 'Musikverein Hedingen',
        score: 83.5,
        additionalInfo: null,
      },
      {
        rank: 9,
        vereinIdentifier: 'musikgesellschaft-andelfingen',
        vereinsName: 'Musikgesellschaft Andelfingen',
        score: 83,
        additionalInfo: null,
      },
      {
        rank: 10,
        vereinIdentifier: 'brass-band-musig-hittnau',
        vereinsName: 'Brass Band Musig Hittnau',
        score: 82.75,
        additionalInfo: null,
      },
      {
        rank: 11,
        vereinIdentifier: 'musikverein-neftenbach',
        vereinsName: 'Musikverein Neftenbach',
        score: 80.5,
        additionalInfo: null,
      },
      {
        rank: 11,
        vereinIdentifier: 'musikgesellschaft-niederhasli',
        vereinsName: 'Musikgesellschaft Niederhasli',
        score: 80.5,
        additionalInfo: null,
      },
      {
        rank: 13,
        vereinIdentifier: 'harmonie-pfaeffikon',
        vereinsName: 'Harmonie Pfäffikon',
        score: 80.25,
        additionalInfo: null,
      },
      {
        rank: 14,
        vereinIdentifier: 'musikgesellschaft-harmonie-turbenthal',
        vereinsName: 'Musikgesellschaft Harmonie Turbenthal',
        score: 79.25,
        additionalInfo: null,
      },
    ],
    final: true,
    notPending: true,
  }
})
