export default defineEventHandler(() => {
  return {
    id: 15,
    modul: 'B',
    modulDescription: 'B - Unterhaltungsmusik',
    klasse: 'UNTERSTUFE',
    klasseDescription: 'Unterstufe',
    besetzung: 'HARMONIE',
    besetzungDescription: 'Harmonie',
    category: null,
    categoryDescription: null,
    location: {
      id: 17,
      identifier: 'turnhalle-weihermatt-urdorf',
      name: 'Turnhalle Weihermatt Urdorf',
      address: 'Weihermattstrasse 50, 8902 Urdorf',
      latitude: 47.379936044763,
      longitude: 8.427330468337,
      googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
      type: 'WETTSPIELLOKAL',
      capacity: '70 Personen',
      modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
      sortOrder: 4,
      mapId: '6W',
      cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
      kuulaId: '5ZfzW',
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 7,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'STANDARD',
      coordinates: {
        latitude: 47.379936044763,
        longitude: 8.427330468337,
      },
    },
    description: 'B - Unterhaltungsmusik, Unterstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'musikverein-helvetia-marthalen',
        vereinsName: 'Musikverein Helvetia Marthalen',
        score: 96,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'musikverein-schoenenberg',
        vereinsName: 'Musikverein Schönenberg',
        score: 89,
        additionalInfo: null,
      },
      {
        rank: 3,
        vereinIdentifier: 'musikverein-wil-zh',
        vereinsName: 'Musikverein Wil ZH',
        score: 85,
        additionalInfo: null,
      },
      {
        rank: 4,
        vereinIdentifier: 'musikverein-uetikon-am-see',
        vereinsName: 'Musikverein Uetikon am See',
        score: 84,
        additionalInfo: null,
      },
      {
        rank: 5,
        vereinIdentifier: 'musikverein-baeretswil',
        vereinsName: 'Musikverein Bäretswil',
        score: 83,
        additionalInfo: null,
      },
    ],
    final: true,
    notPending: true,
  }
})
