export default defineEventHandler(() => {
  return {
    id: 18,
    modul: 'A',
    modulDescription: 'A - Konzertmusik',
    klasse: 'KLASSE_1',
    klasseDescription: '1. Klasse',
    besetzung: 'BRASS_BAND',
    besetzungDescription: 'Brass Band',
    category: null,
    categoryDescription: null,
    location: {
      id: 15,
      identifier: 'zentrumshalle-urdorf',
      name: 'Zentrumshalle Urdorf',
      address: 'Birmensdorferstrasse 77, 8902 Urdorf',
      latitude: 47.385636902376,
      longitude: 8.422329961061,
      googleMapsAddress: 'https://www.google.ch/maps/place/Birmensdorferstrasse+77%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.385636902376,8.422329961061',
      type: 'WETTSPIELLOKAL',
      capacity: '80 Personen',
      modules: 'A (Konzertmusik) Höchstklasse und 1. Klasse, Harmonie und Brass Band',
      sortOrder: 5,
      mapId: '4W',
      cloudflareId: '7a0f8db8-c84c-46c2-d1e0-682aae49e500',
      kuulaId: '5Msg1',
      einspiellokal: null,
      instrumentendepotId: 6,
      instrumentendepotParademusikId: 6,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'FULL',
      coordinates: {
        latitude: 47.385636902376,
        longitude: 8.422329961061,
      },
    },
    description: 'A - Konzertmusik, 1. Klasse, Brass Band (Zentrumshalle Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'brass-band-eglisau',
        vereinsName: 'Brass Band Eglisau',
        score: 97.0,
        additionalInfo: null,
      },
    ],
    final: true,
    notPending: true,
  }
})
