export default defineEventHandler(() => {
  return {
    id: 5,
    modul: 'A',
    modulDescription: 'A - Konzertmusik',
    klasse: 'KLASSE_4',
    klasseDescription: '4. Klasse',
    besetzung: 'HARMONIE',
    besetzungDescription: 'Harmonie',
    category: null,
    categoryDescription: null,
    location: {
      id: 19,
      identifier: 'grosse-ref-kirche-schlieren',
      name: 'Grosse Ref. Kirche Schlieren',
      address: 'Kirchgasse 7, 8952 Schlieren',
      latitude: 47.396801014533,
      longitude: 8.44573297815,
      googleMapsAddress: 'https://www.google.ch/maps/place/Kirchgasse+7%2C+8952+Schlieren',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.396801014533,8.445732978150',
      type: 'WETTSPIELLOKAL',
      capacity: '50 Personen',
      modules: 'A (Konzertmusik) 3. und 4. Klasse, Harmonie und Brass Band',
      sortOrder: 1,
      mapId: '2W',
      cloudflareId: '6458b379-2a58-41ce-8f58-abbc73b98700',
      kuulaId: '5c8Mp',
      einspiellokal: null,
      instrumentendepotId: 8,
      instrumentendepotParademusikId: 7,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'STANDARD',
      coordinates: {
        latitude: 47.396801014533,
        longitude: 8.44573297815,
      },
    },
    description: 'A - Konzertmusik, 4. Klasse, Harmonie (Grosse Ref. Kirche Schlieren)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'spielgemeinschaft-mettmenstetten-ottenbach',
        vereinsName: 'Spielgemeinschaft Mettmenstetten/Ottenbach',
        score: 93,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'musikverein-kempttal',
        vereinsName: 'Musikverein Kempttal',
        score: 91,
        additionalInfo: null,
      },
      {
        rank: 3,
        vereinIdentifier: 'musikverein-harmonie-zuerich-schwamendingen',
        vereinsName: 'Musikverein Harmonie Zürich Schwamendingen',
        score: 90,
        additionalInfo: null,
      },
      {
        rank: 4,
        vereinIdentifier: 'musikverein-weisslingen',
        vereinsName: 'Musikverein Weisslingen',
        score: 84,
        additionalInfo: null,
      },
      {
        rank: 5,
        vereinIdentifier: 'kreismusik-limmattal',
        vereinsName: 'Kreismusik Limmattal',
        score: 82.33,
        additionalInfo: null,
      },
    ],
    final: true,
    notPending: true,
  }
})
