export default defineEventHandler(() => {
  return {
    id: 8,
    modul: 'G',
    modulDescription: 'G - Tambouren',
    klasse: null,
    klasseDescription: null,
    besetzung: 'TAMBOUREN',
    besetzungDescription: 'Tambouren',
    category: 'MODUL_G_KAT_C',
    categoryDescription: 'Kat. C',
    location: {
      id: 14,
      identifier: 'embrisaal-urdorf',
      name: 'Embrisaal Urdorf',
      address: 'Im Embri 8, 8902 Urdorf',
      latitude: 47.387068997702,
      longitude: 8.425614397929,
      googleMapsAddress: 'https://www.google.ch/maps/place/Im+Embri+8%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.387068997702,8.425614397929',
      type: 'WETTSPIELLOKAL',
      capacity: '10 Personen',
      modules: 'G (Tambouren) und H (Perkussionsensembles)',
      sortOrder: 6,
      mapId: '3W',
      cloudflareId: '0e6455f2-ec9a-45cc-79fe-ad062b0dbd00',
      kuulaId: '5ZfQh',
      einspiellokal: null,
      instrumentendepotId: 6,
      instrumentendepotParademusikId: 6,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'FULL',
      coordinates: {
        latitude: 47.387068997702,
        longitude: 8.425614397929,
      },
    },
    description: 'G - Tambouren (Kat. C), Tambouren (Embrisaal Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'tambourenverein-stadt-winterthur',
        vereinsName: 'Tambourenverein der Stadt Winterthur',
        score: 57.2,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'kreismusik-limmattal-tambouren',
        vereinsName: 'Tambourengruppe der Kreismusik Limmattal',
        score: 54.1,
        additionalInfo: null,
      },
      {
        rank: 3,
        vereinIdentifier: 'tambouren-polizeimusik-zuerich-stadt',
        vereinsName: 'Tambouren der Polizeimusik Zürich-Stadt',
        score: 53.2,
        additionalInfo: null,
      },
      {
        rank: 4,
        vereinIdentifier: 'tambourenverein-weinland-andelfingen',
        vereinsName: 'Tambourenverein Weinland Andelfingen',
        score: 52.9,
        additionalInfo: null,
      },
    ],
    final: true,
    notPending: true,
  }
})
