export default defineEventHandler(() => {
  return {
    id: 9,
    modul: 'B',
    modulDescription: 'B - Unterhaltungsmusik',
    klasse: 'MITTELSTUFE',
    klasseDescription: 'Mittelstufe',
    besetzung: 'HARMONIE',
    besetzungDescription: 'Harmonie',
    category: null,
    categoryDescription: null,
    location: {
      id: 17,
      identifier: 'turnhalle-weihermatt-urdorf',
      name: 'Turnhalle Weihermatt Urdorf',
      address: 'Weihermattstrasse 50, 8902 Urdorf',
      latitude: 47.379936044763,
      longitude: 8.427330468337,
      googleMapsAddress: 'https://www.google.ch/maps/place/Weihermattstrasse+50%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.379936044763,8.427330468337',
      type: 'WETTSPIELLOKAL',
      capacity: '70 Personen',
      modules: 'B (Unterhaltungsmusik) Mittel- und Unterstufe, Harmonie und Brass Band',
      sortOrder: 4,
      mapId: '6W',
      cloudflareId: '82172b4e-af46-4b34-0a67-30494b161c00',
      kuulaId: '5ZfzW',
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 7,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: 'STANDARD',
      coordinates: {
        latitude: 47.379936044763,
        longitude: 8.427330468337,
      },
    },
    description: 'B - Unterhaltungsmusik, Mittelstufe, Harmonie (Turnhalle Weihermatt Urdorf)',
    status: 'FINAL',
    entries: [
      {
        rank: 1,
        vereinIdentifier: 'harmonie-wetzikon',
        vereinsName: 'Harmonie Wetzikon',
        score: 91.33,
        additionalInfo: null,
      },
      {
        rank: 2,
        vereinIdentifier: 'musikverein-ruemlang',
        vereinsName: 'Musikverein Rümlang',
        score: 90.67,
        additionalInfo: null,
      },
      {
        rank: 3,
        vereinIdentifier: 'musikgesellschaft-seuzach',
        vereinsName: 'Musikgesellschaft Seuzach',
        score: 90,
        additionalInfo: null,
      },
      {
        rank: 4,
        vereinIdentifier: 'musikverein-harmonie-affoltern-am-albis',
        vereinsName: 'Musikverein Harmonie Affoltern am Albis',
        score: 88,
        additionalInfo: null,
      },
      {
        rank: 5,
        vereinIdentifier: 'musikgesellschaft-faellanden',
        vereinsName: 'Musikgesellschaft Fällanden',
        score: 87.33,
        additionalInfo: null,
      },
      {
        rank: 6,
        vereinIdentifier: 'harmoniemusik-wald',
        vereinsName: 'Harmoniemusik-Wald',
        score: 87,
        additionalInfo: null,
      },
      {
        rank: 7,
        vereinIdentifier: 'musikgesellschaft-haeggenschwil',
        vereinsName: 'Musikgesellschaft Häggenschwil',
        score: 86.33,
        additionalInfo: null,
      },
      {
        rank: 8,
        vereinIdentifier: 'harmonie-zumikon',
        vereinsName: 'Harmonie Zumikon',
        score: 85.33,
        additionalInfo: null,
      },
      {
        rank: 9,
        vereinIdentifier: 'musikgesellschaft-glattfelden',
        vereinsName: 'Musikgesellschaft Glattfelden',
        score: 84.67,
        additionalInfo: null,
      },
    ],
    final: true,
    notPending: true,
  }
})
