export default defineEventHandler(() => {
  return {
    type: 'SONNTAG',
    date: '2024-06-23',
    start: '14:00:00',
    end: '14:45:00',
    title: 'Blaskapelle aus Altheim und Sigmaringendorf (DE)',
    subtitle: null,
    text: 'Ehrwürdiger Besuch von den Nachbarn aus Süddeutschland! Der Musikverein Altheim und der Musikverein Sigmaringendorf planten eine Reise nach Zürich. Nachdem sie erfahren hatten, dass das Kantonalmusikfest just am vorgesehenen Wochenende stattfindet, beschlossen sie sogleich, den Event im Rahmen ihres Aufenthalts mit einer musikalischen Darbietung zu bereichern. Herzlichen Dank und willkommen im Limmattal!',
    location: {
      id: 22,
      identifier: 'festzelt-urdorf',
      name: 'Festzelt Urdorf',
      address: 'Bahnhofstrasse 52, 8902 Urdorf',
      latitude: 47.386092494172,
      longitude: 8.424727317603,
      googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 8,
      mapId: 'FU',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 8,
      instrumentendepot: {
        id: 7,
        identifier: 'turnhalle-bahnhofstrasse',
        name: 'Turnhalle Bahnhofstrasse',
        address: 'Bahnhofstrasse 50, 8902 Urdorf',
        latitude: 47.3865713534,
        longitude: 8.425189176428,
        googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '5/6D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: {
          latitude: 47.3865713534,
          longitude: 8.425189176428,
        },
      },
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: {
        latitude: 47.386092494172,
        longitude: 8.424727317603,
      },
    },
    cloudflareId: null,
    vereinIdentifier: null,
    unterhaltungIdentifier: 'altheim-und-sigmaringendorf',
    inPast: false,
  }
})
