export default defineEventHandler(() => {
  return {
    type: 'SAMSTAG_TAG',
    date: '2024-06-22',
    start: '12:00:00',
    end: '14:00:00',
    title: 'Zmittag mit Brässkalation',
    subtitle: null,
    text: 'Fette Brass-Power ohne Kompromisse! Nach diesem Motto gründeten zehn Jungs vor neun Jahren eine Band, um auf eigene Faust die weite Welt der Blasmusik zu erkunden. Mit ihrem einzigartigen Sound, der quer durch Pop, Hip-Hop und Funk geht, reizt die Band die Grenzen dessen aus, was Blasmusik heute sein kann.',
    location: {
      id: 22,
      identifier: 'festzelt-urdorf',
      name: 'Festzelt Urdorf',
      address: 'Bahnhofstrasse 52, 8902 Urdorf',
      latitude: 47.386092494172,
      longitude: 8.424727317603,
      googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 8,
      mapId: 'FU',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 8,
      instrumentendepot: {
        id: 7,
        identifier: 'turnhalle-bahnhofstrasse',
        name: 'Turnhalle Bahnhofstrasse',
        address: 'Bahnhofstrasse 50, 8902 Urdorf',
        latitude: 47.3865713534,
        longitude: 8.425189176428,
        googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '5/6D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: { latitude: 47.3865713534, longitude: 8.425189176428 },
      },
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: { latitude: 47.386092494172, longitude: 8.424727317603 },
    },
    cloudflareId: '996f1c4f-5cdc-470b-e212-61221748fd00',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'braesskalation',
    inPast: false,
  }
})
