export default defineEventHandler(() => {
  return {
    type: 'SAMSTAG_ABEND',
    date: '2024-06-22',
    start: '22:30:00',
    end: '23:59:00',
    title: 'Feiern mit der Compass Party Band',
    subtitle: null,
    text: 'Compass ist die neue Partyband der Schweiz. Als perfekt eingespieltes Team treten die sechs Musiker bei verschiedensten Events in der Schweiz und im benachbarten Ausland auf. Sie wissen genau, was es für eine richtige Party braucht, und können auf eine langjährige Bühnenerfahrung in verschiedenen Stilrichtungen zurückblicken.',
    location: {
      id: 22,
      identifier: 'festzelt-urdorf',
      name: 'Festzelt Urdorf',
      address: 'Bahnhofstrasse 52, 8902 Urdorf',
      latitude: 47.386092494172,
      longitude: 8.424727317603,
      googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 8,
      mapId: 'FU',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 8,
      instrumentendepot: {
        id: 7,
        identifier: 'turnhalle-bahnhofstrasse',
        name: 'Turnhalle Bahnhofstrasse',
        address: 'Bahnhofstrasse 50, 8902 Urdorf',
        latitude: 47.3865713534,
        longitude: 8.425189176428,
        googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '5/6D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: {
          latitude: 47.3865713534,
          longitude: 8.425189176428,
        },
      },
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: {
        latitude: 47.386092494172,
        longitude: 8.424727317603,
      },
    },
    cloudflareId: 'ea75cb30-69c0-4a19-6ee7-0e79ab4cf900',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'compass',
    inPast: false,
  }
})
