export default defineEventHandler(() => {
  return {
    type: 'SAMSTAG_ABEND',
    date: '2024-06-23',
    start: '01:00:00',
    end: '04:00:00',
    title: 'Ausklang mit DJ Outside',
    subtitle: null,
    text: 'DJ Outside ist «Diskjockey, Moderator und Veranstalter von musikalischen Mega-Events – ein aufgestellter und auf dem Boden gebliebener Schweizer Bub». Das musikalische Menü wird mit viel Schwung serviert. Durch jahrelange Erfahrung hat DJ Outside immer die richtige Musik parat, so dass sich alle wohlfühlen können.',
    location: {
      id: 22,
      identifier: 'festzelt-urdorf',
      name: 'Festzelt Urdorf',
      address: 'Bahnhofstrasse 52, 8902 Urdorf',
      latitude: 47.386092494172,
      longitude: 8.424727317603,
      googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 8,
      mapId: 'FU',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 8,
      instrumentendepot: {
        id: 7,
        identifier: 'turnhalle-bahnhofstrasse',
        name: 'Turnhalle Bahnhofstrasse',
        address: 'Bahnhofstrasse 50, 8902 Urdorf',
        latitude: 47.3865713534,
        longitude: 8.425189176428,
        googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '5/6D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: {
          latitude: 47.3865713534,
          longitude: 8.425189176428,
        },
      },
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: {
        latitude: 47.386092494172,
        longitude: 8.424727317603,
      },
    },
    cloudflareId: '96b8667c-d26d-43da-6b02-9305e1284300',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'dj-outside',
    inPast: false,
  }
})
