export default defineEventHandler(() => {
  return {
    type: 'SAMSTAG_TAG',
    date: '2024-06-22',
    start: '09:00:00',
    end: '10:00:00',
    title: 'Jugend und Blasmusik',
    subtitle: null,
    text: 'Mitmachen in einer Bläserklasse – etwas für Dich? Das Erlernen eines Instruments macht Spass und lässt Dich in die wunderbare Welt der Musik eintauchen. Die Schule Urdorf hat vor einigen Monaten ein Pilotprojekt gestartet. Jan Wyss, musikalischer Leiter, zeigt, was die Schülerinnen und Schüler in dieser Zeit erreicht haben und wie Du mitmachen kannst.',
    location: {
      id: 1,
      identifier: 'singsaal-moosmatt',
      name: 'Singsaal Moosmatt',
      address: 'Im Moos 24, 8902 Urdorf',
      latitude: 47.388554561192,
      longitude: 8.425192408359,
      googleMapsAddress: 'https://www.google.ch/maps/place/Im+Moos+24%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.388554561192,8.425192408359',
      type: 'EINSPIELLOKAL',
      capacity: null,
      modules: null,
      sortOrder: 0,
      mapId: '4E',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: null,
      instrumentendepotParademusikId: null,
      instrumentendepot: null,
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: {
        latitude: 47.388554561192,
        longitude: 8.425192408359,
      },
    },
    cloudflareId: '8757a3f7-653d-44e5-6b5a-7a8b1a151800',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'jugend-und-blasmusik',
    inPast: false,
  }
})
