export default defineEventHandler(() => {
  return {
    type: 'SONNTAG',
    date: '2024-06-23',
    start: '12:00:00',
    end: '13:45:00',
    title: 'Zmittag mit Schäbyschigg',
    subtitle: null,
    text: 'Schäbyschigg sind fünf weltoffene und unerschrockene Musiker: Mit Klarinette, Trompeten, Tuba und Akkordeon sowie Käse, Brot und «Tiggets» im Gepäck sind sie unterwegs, um mit ihrer Musik die Herzen von Nah und Fern zu erfreuen. Mal groovig, mal lüpfig, mal melancholisch, mal urchig – immer authentisch und frisch tragen sie ihre Melodien in die Welt hinaus.',
    location: {
      id: 22,
      identifier: 'festzelt-urdorf',
      name: 'Festzelt Urdorf',
      address: 'Bahnhofstrasse 52, 8902 Urdorf',
      latitude: 47.386092494172,
      longitude: 8.424727317603,
      googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 8,
      mapId: 'FU',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 8,
      instrumentendepot: {
        id: 7,
        identifier: 'turnhalle-bahnhofstrasse',
        name: 'Turnhalle Bahnhofstrasse',
        address: 'Bahnhofstrasse 50, 8902 Urdorf',
        latitude: 47.3865713534,
        longitude: 8.425189176428,
        googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '5/6D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: {
          latitude: 47.3865713534,
          longitude: 8.425189176428,
        },
      },
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: {
        latitude: 47.386092494172,
        longitude: 8.424727317603,
      },
    },
    cloudflareId: '537e6324-ebdd-46ee-759c-059cceceaf00',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'schaebyschigg',
    inPast: false,
  }
})
