export default defineEventHandler(() => {
  return {
    type: 'SAMSTAG_TAG',
    date: '2024-06-22',
    start: '14:25:00',
    end: '15:00:00',
    title: 'Schwyzerörgeli Gruppe Schlieren',
    subtitle: null,
    text: 'Die 1990 gegründete Schwyzerörgeli-Gruppe besteht heute aus 21 Musizierenden und spielt unter der Leitung von Dominik Heller vorwiegend traditionelle schweizerische Volkmusik, wie Länder, Marsch, Schottisch und Walzer.',
    location: {
      id: 21,
      identifier: 'festzelt-schlieren',
      name: 'Festzelt Schlieren',
      address: 'Badenerstrasse 12, 8952 Schlieren',
      latitude: 47.397439543225,
      longitude: 8.446011061969,
      googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 9,
      mapId: 'FS',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 8,
      instrumentendepotParademusikId: 7,
      instrumentendepot: {
        id: 8,
        identifier: 'schulhaus-hofacker-turnhalle',
        name: 'Schulhaus Hofacker Turnhalle',
        address: 'Hofackerstrasse 2, 8952 Schlieren',
        latitude: 47.39453952852,
        longitude: 8.444151354002,
        googleMapsAddress: 'https://www.google.ch/maps/place/Hofackerstrasse+2%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.394539528520,8.444151354002',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '1/2D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: {
          latitude: 47.39453952852,
          longitude: 8.444151354002,
        },
      },
      juryfeedback: null,
      percussionEquipmentType: 'STANDARD',
      coordinates: {
        latitude: 47.397439543225,
        longitude: 8.446011061969,
      },
    },
    cloudflareId: 'c13c0cf1-638d-4160-8f76-aaee65fefd00',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'schwyzeroergeli-gruppe-schlieren',
    inPast: false,
  }
})
