export default defineEventHandler(() => {
  return {
    type: 'FREITAG_ABEND',
    date: '2024-06-21',
    start: '21:00:00',
    end: '22:30:00',
    title: 'Feiern mit der Stubete Gäng',
    subtitle: null,
    text: 'Aurel und Moritz Hassler, die beiden sympathischen Brüder aus dem Zugerland, haben mit ihrer Stubete Gäng 2019 mal ebenso einen völlig neuen Musikstil erfunden. Ihr «ÖrbnLändlr» eroberte die Schweiz im Sturm. Der Megahit «Petra Sturzenegger» ist längst anerkanntes Schweizer Kulturgut, das landauf, landab von Göschenen bis Airolo mitgesungen wird.',
    location: {
      id: 22,
      identifier: 'festzelt-urdorf',
      name: 'Festzelt Urdorf',
      address: 'Bahnhofstrasse 52, 8902 Urdorf',
      latitude: 47.386092494172,
      longitude: 8.424727317603,
      googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+52%2C+8902+Urdorf',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.386092494172,8.424727317603',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 8,
      mapId: 'FU',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 7,
      instrumentendepotParademusikId: 8,
      instrumentendepot: {
        id: 7,
        identifier: 'turnhalle-bahnhofstrasse',
        name: 'Turnhalle Bahnhofstrasse',
        address: 'Bahnhofstrasse 50, 8902 Urdorf',
        latitude: 47.3865713534,
        longitude: 8.425189176428,
        googleMapsAddress: 'https://www.google.ch/maps/place/Bahnhofstrasse+50%2C+8902+Urdorf',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.386571353400,8.425189176428',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '5/6D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: {
          latitude: 47.3865713534,
          longitude: 8.425189176428,
        },
      },
      juryfeedback: null,
      percussionEquipmentType: null,
      coordinates: {
        latitude: 47.386092494172,
        longitude: 8.424727317603,
      },
    },
    cloudflareId: '687817b1-01a6-42b5-6bfa-8c8e559dda00',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'stubete-gaeng',
    inPast: false,
  }
})
