export default defineEventHandler(() => {
  return {
    type: 'SAMSTAG_TAG',
    date: '2024-06-22',
    start: '11:45:00',
    end: '13:00:00',
    title: 'Swiss Jungle Drummers Steelband',
    subtitle: null,
    text: 'Die 14-köpfige popige Steelband stammt aus dem Musik-und Showunternehmen Art of Rhythm von Roger Küng.\nDie Band wurde 2007 gegründet und begeistert das Publikum mit ihrem karibischen Holiday-Sound. Im repertoir finden sich sowohl typische karibische titel im calypso oder Samba Stil aber auch moderne Unterhaltung aus der Popszene. Lassen sie sich mit diesem einzigartigen Stil verzaubern und geniessen sie dieses Holiday-Feeling!',
    location: {
      id: 21,
      identifier: 'festzelt-schlieren',
      name: 'Festzelt Schlieren',
      address: 'Badenerstrasse 12, 8952 Schlieren',
      latitude: 47.397439543225,
      longitude: 8.446011061969,
      googleMapsAddress: 'https://www.google.ch/maps/place/Badenerstrasse+12%2C+8952+Schlieren',
      googleMapsCoordinates: 'https://www.google.com/maps?q=47.397439543225,8.446011061969',
      type: 'FESTZELT',
      capacity: null,
      modules: null,
      sortOrder: 9,
      mapId: 'FS',
      cloudflareId: null,
      kuulaId: null,
      einspiellokal: null,
      instrumentendepotId: 8,
      instrumentendepotParademusikId: 7,
      instrumentendepot: {
        id: 8,
        identifier: 'schulhaus-hofacker-turnhalle',
        name: 'Schulhaus Hofacker Turnhalle',
        address: 'Hofackerstrasse 2, 8952 Schlieren',
        latitude: 47.39453952852,
        longitude: 8.444151354002,
        googleMapsAddress: 'https://www.google.ch/maps/place/Hofackerstrasse+2%2C+8952+Schlieren',
        googleMapsCoordinates: 'https://www.google.com/maps?q=47.394539528520,8.444151354002',
        type: 'INSTRUMENTENDEPOT',
        capacity: null,
        modules: null,
        sortOrder: 0,
        mapId: '1/2D',
        cloudflareId: null,
        kuulaId: null,
        einspiellokal: null,
        instrumentendepotId: null,
        instrumentendepotParademusikId: null,
        instrumentendepot: null,
        juryfeedback: null,
        percussionEquipmentType: null,
        coordinates: { latitude: 47.39453952852, longitude: 8.444151354002 },
      },
      juryfeedback: null,
      percussionEquipmentType: 'STANDARD',
      coordinates: { latitude: 47.397439543225, longitude: 8.446011061969 },
    },
    cloudflareId: 'eb2d6b58-fe53-4532-23df-ba32f9c6db00',
    vereinIdentifier: null,
    unterhaltungIdentifier: 'swiss-jungle-drummers-steelband',
    inPast: false,
  }
})
